### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by what-the-drew** [jsfiddle/jsfiddle-issues#1000]
I don't know how to contact yall other than through this. 

THANK YOU SO MUCH FOR MAKING A SIMPLE WAY TO VIEW JavaScript on a Mac. I am trying to learn JS from an old Murach Book, and they are only really are helpful for PC users and have OLD software. Seriously thank you so MUCH for making this. I can actually learn other than trying to work on my mac through a remote access, spent hours looking for anything as simple as this. Thank you for making this easy

HAVE A GREAT AND KNOW SOME ONE OUT THERE APPRECIATES THE SHIT OUT OF WHAT YALL DO!

Thanks,
Drew Dugger

**Comment by oskarkrawczyk** [comment]
Thanks a lot @what-the-drew!
