### ISSUE TITLE
fullscreen "results screen" 

### ISSUE THREAD

**Issue by shuttleshooter** [jsfiddle/jsfiddle-issues#1002]
would be nice to see how your page looks fullscreen, could do this by just adding the option to make an extra tab you can reload to see the results of your code.

**Comment by oskarkrawczyk** [comment]
We won't be adding this again, since spammers and scammers used to use JSFiddle in full screen for their missdeeds.

**Comment by shuttleshooter** [comment]
oh really, well that's too bad. I'm using jsfiddle atm to learn html and
css and thought it would be useful for understanding padding and the box
model in general better for full pages, since i get how this works on small
scale but haven't tried it out on full sites. But if you came to that
conclusion i guess that must've been pretty serious.

thanks for your reply,
shuttle

2017-04-18 12:03 GMT+02:00 Oskar Krawczyk <notifications@github.com>:
