### ISSUE TITLE
Choose insert point of external resources

### ISSUE THREAD

**Issue by cheshrkat** [jsfiddle/jsfiddle-issues#1003]
I've had a dig and couldn't find an existing issue, my apologies if this is a duplicate.

The request: the ability to choose the loading point of external resources, same as with frameworks.

My use case: I have a custom library that needs to load at the end of BODY and not in the HEAD. The only way to make this work now is to inject it inline; but then there's an error message on screen at all times, covering the last line of HTML.

**Comment by oskarkrawczyk** [comment]
You already choose the insert point (load type) for frameworks - configuration dropdown.

As for resources, there are no plans on doing this as the codebase is frozen.

Future version of JSFiddle will not have the distinction between framework and resource.
