### ISSUE TITLE
JSFiddle.net causes browser to stop responding with high CPU

### ISSUE THREAD

**Issue by gRoberts84** [jsfiddle/jsfiddle-issues#1004]
When going to https://www.jsfiddle.net or viewing an existing Fiddle, the header/sidebar appears but hangs with a spinning wheel in the tab header and will remain there until the browser decides to kill the tab, or I have to manually kill the task via Chromes task manager (unable to close the tab the usual way.)

Chrome 57.0.2987.133 (64-bit) on OSX

![screen shot 2017-04-20 at 08 40 14](https://cloud.githubusercontent.com/assets/348184/25219240/a30319c8-25a5-11e7-9834-679acd086e24.png)
![screen shot 2017-04-20 at 08 40 29](https://cloud.githubusercontent.com/assets/348184/25219239/a3014bfc-25a5-11e7-8043-147b4f253544.png)
![screen shot 2017-04-20 at 08 45 20](https://cloud.githubusercontent.com/assets/348184/25219275/c15996ea-25a5-11e7-968b-127494e9664f.png)

I've tried to take a profile of the page loading etc but it fails also. 

If there is anything else you need me to provide, please do not hesitate to ask.

**Comment by oskarkrawczyk** [comment]
@gRoberts84 Weird. Same in incognito mode?

**Comment by gRoberts84** [comment]
@oskarkrawczyk Oddly enough, no, however I see where you're going with this, so I disabled all of my extensions and it still happens.

![screen shot 2017-04-20 at 08 53 42](https://cloud.githubusercontent.com/assets/348184/25219608/e74f28f0-25a6-11e7-85d4-f7243e4fcbe4.png)

**Comment by oskarkrawczyk** [comment]
Most likely something cached or wonky Chrome profile (this happens) – I cannot replicate this on the same setup under different conditions.

There's a chance clearning cache + restarting Chrome will fix the issue.

**Comment by gRoberts84** [comment]
@oskarkrawczyk Will give it a go. Oddly, if I kill the process and reload a few times, it does sometime load. Found it happened on my personal machine (OSX) as well as my work (again OSX) so thought I'd report it.

Will report back asap.

Thanks 😄

**Comment by oskarkrawczyk** [comment]
> Found it happened on my personal machine (OSX) as well as my work (again OSX) so thought I'd report it

Synchronizing profile via google? :-)

**Comment by gRoberts84** [comment]
Thankfully no :)

**Comment by oskarkrawczyk** [comment]
I'll leave this open for now, in case more reports come in

**Comment by gRoberts84** [comment]
@oskarkrawczyk As suggested, clearing the cache/restarting worked. 

I probably should have done this before posting an issue, sorry for the hassle!

Thanks again.

**Comment by oskarkrawczyk** [comment]
@gRoberts84 don't worry, I do the same most of the time - how dare someone say that it's MY setup that's broken! 😉
