### ISSUE TITLE
How to do a supported window.fetch() request on a response.html ?

### ISSUE THREAD

**Issue by Lcfvs** [jsfiddle/jsfiddle-issues#1006]
I'm trying to do an AJAX demo for a new library based on `window.fetch()` but when I call a response.html (in a gist) but I got that message :

> Please use only with Ajax requests

**Comment by oskarkrawczyk** [comment]
Example?

**Comment by Lcfvs** [comment]
Sure :)

http://jsfiddle.net/gh/gist/library/pure/3352f1e9abc25fce12d1bef36b07b690/

**Comment by Lcfvs** [comment]
The library source : https://github.com/Lcfvs/globuling.js/blob/master/globuling.js

The gist https://gist.github.com/Lcfvs/3352f1e9abc25fce12d1bef36b07b690

**Comment by oskarkrawczyk** [comment]
You have a `dispatcher is not defined` error.

Generally this is an issue with the code not JSFiddle.
