### ISSUE TITLE
jQuery UI

### ISSUE THREAD

**Issue by Mottie** [jsfiddle/jsfiddle-issues#1008]
Thanks for providing a fantastic service!

Pretty much *all links* to jQuey UI need to be fixed:

https://jsfiddle.net/Mottie/0dpv482o/

In the above demo, jQuery Slim 3.1.0 Slim + jQuery UI 1.12.0 (as described in #886) are being used. The "jQueryUI" url points to https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/external/jquery/jquery.js, which is actually a copy of jQuery v1.12.4 loaded on top of jQuery 3.1.0 Slim. jQuery UI isn't even loaded.

Also, because that demo is being loaded over `https`, switching to use jQuery (Edge), which is the only version beside jQuery 1.9.1 that provides a jQuery UI checkboxes, shows jQuery UI v1.8.5 and jQuery UI v1.8.9 as options. Neither of those versions work because:

1) The URLs are using `http`:

    > Mixed Content: The page at 'https://jsfiddle.net/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.js'. This request has been blocked; the content must be served over HTTPS.

2) jQuery UI v1.8.9 throws errors in the console when combined with jQuery v1.9+ because [jQuery.browser](http://api.jquery.com/jQuery.browser/) was completely removed in those versions of jQuery... It appears that all references to `jQuery.browser` were removed in jQuery UI v1.9.1+. So please provide more up-to-date options.

I use jsFiddle a lot for demos, and when asking users that open issues to submit a demo. I would really appreciate it if jQuery UI got a little lovin' in the menus.

Thanks!

**Comment by oskarkrawczyk** [comment]
@majkelcc if possible, can you replace all DEP & FW URL's in the DB to non-protocol?

**Comment by majkelcc** [comment]
@oskarkrawczyk I changed all external libraries and dependencies urls to protocol relative.

**Comment by oskarkrawczyk** [comment]
jQuery UI 1.12.0 source has been fixed.

Closing.

Next time, please open separate tickets per issue.
