### ISSUE TITLE
reCAPTCHA error on signup page, Cant signup

### ISSUE THREAD

**Issue by cpxPratik** [jsfiddle/jsfiddle-issues#1009]
**Cant signup from `https://fiddle.jshell.net/user/signup/`** since `ERROR for site owner: Invalid domain for site key on a site` is shown on reCAPTCHA block. **Please fix this asap.**

![jsfiddle](https://cloud.githubusercontent.com/assets/6893334/25469955/4b8658e6-2b3f-11e7-9cb3-8eb22a5b7618.png)

**Comment by majkelcc** [comment]
@cpxPratik that is not the right url for signup, please use this one https://jsfiddle.net/user/signup
