### ISSUE TITLE
Trying to comment Javascript code by pressing Ctrl+/ will add HTML comment tags

### ISSUE THREAD

**Issue by hieroglyphic** [jsfiddle/jsfiddle-issues#1011]
### 📄 Description of the problem
Whenever I try to comment codes on Javascript panel(the one in bottom left corner) by pressing Ctrl+/ keyboard shortcut, JSFiddle will add `<!-- ` and ` -->` around selection(or current cursor position if selection is not present).

### 🔢 Step(s) to reproduce
0. Focus on Javascript code panel
0. Press <kbd>Ctrl</kbd>+<kbd>/</kbd>

### ❔ What did I expect
Let's say `|` is where the cursor is at.
`var actual|Variable = 73;` &rarr; `// var actual|Variable = 73;` or `/* var actual|Variable = 73; */`

### ❗️ What happened
Let's say `|` is where the cursor is at.
`var actual|Variable = 73;` &rarr; `var actual<!-- | -->Variable = 73;`

### 💻  Testing environment(s)
- Chrome 58.0.3029.81 (64-bit) with guest profile
- Firefox 53.0 (64-bit)  without add-ons/extensions, private window
Both on Windows 10, Bitdefender Total Security 2017 Installed and Running (Network audit)

**Comment by oskarkrawczyk** [comment]
https://github.com/jsfiddle/jsfiddle-issues/blob/master/README.md
