### ISSUE TITLE
Incompatible jQuery UI versions

### ISSUE THREAD

**Issue by Mottie** [jsfiddle/jsfiddle-issues#1013]
TLDR; Please change jQuery UI to use v1.12.1 with jQuery Edge.

Setting the framework to jQuery (Edge) shows jQuery UI v1.8.5 and jQuery UI v1.8.9 as options. Neither of those versions work. All versions of jQuery UI older than 1.9.1 still use [jQuery.browser](http://api.jquery.com/jQuery.browser/) internally, which was a function that was removed in jQuery v1.9+.

**Comment by oskarkrawczyk** [comment]
It has been done
