### ISSUE TITLE
Add a search bar in JS Fiddle

### ISSUE THREAD

**Issue by nitishgaddam** [jsfiddle/jsfiddle-issues#1014]
# Note on existing issues:

- Known and minor issues will **not be addressed and most likely will be closed**
- More info in README.md

# Library update request

- Be sure your library (in the correct version) exits on cdnjs.org

**Comment by nitishgaddam** [comment]
Add a search bar so that we can go through all the publicly available code. Private code should be private and not accessible through search results

**Comment by oskarkrawczyk** [comment]
We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by greggman** [comment]
I found the issue on trello but I'd personally like to search only my own fiddles, not public fiddles.

I have tons of them and I often want to reference old ones I know are there. As it is I just have to page through them. After 5 or 6 pages I usually give up 😅
