### ISSUE TITLE
Chrome's Find function just doesn't cut it

### ISSUE THREAD

**Issue by krabbypattified** [jsfiddle/jsfiddle-issues#1017]
If I have lots of code, I want to search through it and look for all occurences of the word `foo`. For some reason, it only finds the occurences that are currently visible on-screen. Anything off-screen is ignored.

Is there any way to fix this? Find is an essential feature for any code editor!

**Comment by oskarkrawczyk** [comment]
This is how CodeMirror works. Seems like there's a configuration option to bypass the default behavior. Will look into it on Monday.
