### ISSUE TITLE
Window size bug

### ISSUE THREAD

**Issue by anuragl94** [jsfiddle/jsfiddle-issues#1021]
No idea how it happened, but here's the current window_sizes cookie value:

`%7B%22w%22%3A%5B%22103.226%25%22%2C%2210.1382%25%22%5D%2C%22h%22%3A%5B%2228.7145%25%22%2C%2271.2855%25%22%2C%2216.6945%25%22%2C%2283.3055%25%22%5D%7D`

Unable to revert to original sizes.

![js fiddle window_sizes bug](https://cloud.githubusercontent.com/assets/9764372/26627724/04aa6e72-4619-11e7-96b9-137a3272a735.png)

**Comment by oskarkrawczyk** [comment]
https://github.com/jsfiddle/jsfiddle-issues/issues/493
