### ISSUE TITLE
Add the "secure" attribute to the session_id cookie.

### ISSUE THREAD

**Issue by roseperrone** [jsfiddle/jsfiddle-issues#1025]
Currently, an attacker sniffing the network can see a user's session_id cookie when the user navigates to an unauthenticated part of the app. The attacker can use the session_id to hijack the user's session and impersonate the user.

For more info, see:
https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OTG-SESS-002)

**Comment by majkelcc** [comment]
Hi rosepperrone! Unfortunately your session needs to be available under `http` protocol as well, so we can't add this attribute to the session cookie.

**Comment by roseperrone** [comment]
Why not use only the `https` protocol?

**Comment by majkelcc** [comment]
It's because of the fiddles that need to be accessible by both `http` and `https` protocols.

**Comment by majkelcc** [comment]
We'll think of what can be done in this matter in new version of jsfiddle, thanks for suggesting it 👍
