### ISSUE TITLE
Visual Forking (pg) Feature Request

### ISSUE THREAD

**Issue by jacksonkr** [jsfiddle/jsfiddle-issues#1026]
Can we have an option to see all forks / versions of a fiddle as a visual element? Essentially this would be a small version of the fiddle but to sandbox it, this could be an animated gif (timelapse) of 10-30 seconds of the fiddle's output.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
