### ISSUE TITLE
Add lua syntax highlighting and automatic tabbing when using text/lua script type

### ISSUE THREAD

**Issue by Wunder-Wulfe** [jsfiddle/jsfiddle-issues#1027]
`<script src="https://daurnimator.github.io/lua.vm.js/lua.vm.js"></script>`
support for the module as a window for the scripting language dropdown box or just simply highlighting within the html window, its fine for me to put it with the html
`<script type="text/lua">
--code
</script>
`
lua vm about:
https://daurnimator.github.io/lua.vm.js/lua.vm.js.html

**Comment by oskarkrawczyk** [comment]
@Wunder-Wulfe what is `automatic tabbing`?

**Comment by oskarkrawczyk** [comment]
Closing. Through the years there has only been one request for Lua, this one.
