### ISSUE TITLE
input element syntax highlighting issue

### ISSUE THREAD

**Issue by martinRenou** [jsfiddle/jsfiddle-issues#1028]
In the HTML editor there is an issue of syntax highlighting when closing an input element, it is rendered with a red background.

**Comment by oskarkrawczyk** [comment]
@martinRenou Please provide an example fiddle, otherwise I'll close this issue.

**Comment by martinRenou** [comment]
I thought about doing that, but I also thought that it wasn't that difficult to reproduce
https://jsfiddle.net/martinRenou/oos9wreu/

**Comment by martinRenou** [comment]
It looks like an input element is not recognize as an html element by jsfiddle

**Comment by oskarkrawczyk** [comment]
https://developer.mozilla.org/en/docs/Web/HTML/Element/input

You don't close the input element in HTML.

**Comment by martinRenou** [comment]
My bad! Sorry, and thank you.
