### ISSUE TITLE
Idea: Export as StackOverflow snippet

### ISSUE THREAD

**Issue by beerwin** [jsfiddle/jsfiddle-issues#1031]
Many people have code on JSFiddle (or create it here as a demo) and want to share it on StackOverflow as part of a question or answer. 

It would be great to have an export like:  

- click a button 
- show the generated StackOverflow snippet code in a modal 
- from where the user can copy it

**Comment by oskarkrawczyk** [comment]
As soon as SO adds the ability to export snippet to JSFiddle.

For now there are no plans on a export to SO feature
