### ISSUE TITLE
create anonymous fiddle with out username on url 

### ISSUE THREAD

**Issue by bhvreddy** [jsfiddle/jsfiddle-issues#1032]
to share code on stackoverflow or similar sites .. the url show the username , 

its good to add a feature to share code anonymously .. 

currently i am doing that by open the code in non signed browser and fork it and sharing it ..

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
