### ISSUE TITLE
Update fabricjs to 1.7.15

### ISSUE THREAD

**Issue by asturur** [jsfiddle/jsfiddle-issues#1034]
# Library update request

i think you can remove the oldest of the 1.7 branch if you feel like.

http://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.15/fabric.min.js

**Comment by asturur** [comment]
i bumbed the request to 1.7.15 since i had to release a bugfix

**Comment by oskarkrawczyk** [comment]
Done!

**Comment by asturur** [comment]
Thank you very much
