### ISSUE TITLE
Premium account (no ads) feature request

### ISSUE THREAD

**Issue by Willshaw** [jsfiddle/jsfiddle-issues#1036]
I don't like showing ads, even if they are high quality tech related - would rather pay a subscription or fee on the account to not show them (not an unusual model these days)

I'd rather actually support JSFiddle directly than via ads.

**Comment by Willshaw** [comment]
They are very small an non invasive, and I have disabled my ad blocker - but still, I'd rather give you money

**Comment by oskarkrawczyk** [comment]
We'll have premium accounts in the next version of JSFiddle
