### ISSUE TITLE
Allow adding multiple extension from JavaScript setting

### ISSUE THREAD

**Issue by Jonathan0wh** [jsfiddle/jsfiddle-issues#1037]
Now if people want to add multiple resources, they would usually select a source from JavaScript setting:  
  
![screen shot 2017-07-05 at 2 54 18 pm](https://user-images.githubusercontent.com/13926920/27849628-db840c94-6191-11e7-9c93-1ea11d4a0988.png)
  
and then manually find url for the other resources and add them from the "External Resources" on the left panel:  
  
![screen shot 2017-07-05 at 2 55 35 pm](https://user-images.githubusercontent.com/13926920/27849648-0a5e040c-6192-11e7-830e-27b77a002235.png) . 
  
Is it possible to slightly improve the UI and allow users to select and add multiple resources directly from the JavaScript setting in the first screenshot? Users may usually use multiple common resources like react, lodash and underscore.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap) for JSFiddle v2.0.
