### ISSUE TITLE
Fix text editor so it doesn't get confused by long lines

### ISSUE THREAD

**Issue by BigBadaboom** [jsfiddle/jsfiddle-issues#1041]
The current editor can easily get confused by long lines that wrap.  By confused I mean that the cursor is displayed at a different location to the insertion point.

It would be nice if this frustrating long-standing bug was fixed.

Affects all browsers.

**Comment by oskarkrawczyk** [comment]
Since it's a CodeMirror issue, it would be better to report it on their GH Issues.
