### ISSUE TITLE
Breaking Bug: Can no longer resize output window

### ISSUE THREAD

**Issue by krabbypattified** [jsfiddle/jsfiddle-issues#1043]
My JSFiddle is broken. I accidentally resized the output window to 0 and I can't get it back to normal. I tried logging out, clearing localStorage, and of course resizing the windows, but it just appears to be a horrible UI glitch. Please help!
This screenshot pretty much explains it:
<img width="901" alt="screen shot 2017-07-14 at 11 38 39 am" src="https://user-images.githubusercontent.com/13423815/28221533-4ca6609a-6889-11e7-94a8-53ec47d3ce5b.png">

**Comment by oskarkrawczyk** [comment]
https://github.com/jsfiddle/jsfiddle-issues/issues/493#issuecomment-39214845
