### ISSUE TITLE
Can embeds be made non-editable? (fork only?)

### ISSUE THREAD

**Issue by rcrooks** [jsfiddle/jsfiddle-issues#1045]
Is this possible? If not, can it be added to the roadmap?

**Comment by oskarkrawczyk** [comment]
@rcrooks Do you mean that the fiddle should become read-only if JSFiddle detects the fiddle has been embedded somewhere? If so, there are no plans on that. Fiddles have versions, even anonymous fiddles, there's no way someone else can overwrite a fiddle.

**Comment by rcrooks** [comment]
Got it, thanks
