### ISSUE TITLE
Button to Change Fiddle from "Public" to "Private" and Vice Versa

### ISSUE THREAD

**Issue by ivanlmj** [jsfiddle/jsfiddle-issues#1046]
It would be nice to have a button that could allow the user to change the status of the fiddle, from "Private" to "Public" and vice versa, just like Github does with Gists.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by ivanlmj** [comment]
Thanks, @oskarkrawczyk :)!
