### ISSUE TITLE
Follow Feature

### ISSUE THREAD

**Issue by carlosbocanegra** [jsfiddle/jsfiddle-issues#1049]
# Follow Feature

**Scenario**
Sometimes someone shares a fiddle with you to show you some code, you review it and close the window. If you want to come back to it and review it again you have to the link again if you didnt save it or if you dont know his/her profile id. Or you have to fork the other person fiddle (maybe dont do any modiffication) just to have it on your fiddles.

**Propose Solution**
We could have a follow feature somiliar to GitHug, where you can just tag someone else profile (maybe tag specific fiddles) and it will be linked to your profile, so if you want to see these people's fiddles you can just go to a follow section in your profile and see the poeple you have marked to follow.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
