### ISSUE TITLE
Add "Add Framework" function

### ISSUE THREAD

**Issue by aureole82** [jsfiddle/jsfiddle-issues#1050]
JSFiddle is too clumsy to start from scratch!

Why? Take Bootstrap as an example (let's assume I want to fiddle with http://getbootstrap.com/components/#btn-dropdowns-single):
* My first guest "External Resources": Nothing! Hitting "+" several times: Again, nothing!
* Open new tab → getbootstrap.com/getting-started → Copy "...bootstrap.min.css" → "External Resources" → Paste → Hitting "+": Style ok, function fails
* As a Bootstrap newbie I forgot that Bootstrap has JavaScript as well, so again: Back to getbootstrap.com/getting-started → Copy "...bootstrap.min.js" → "External Resources" → Paste → Hitting "+": Function fails again! F***!!!
* After a dozen senseless roundtrips I opened the console by coincident: _"Error: Bootstrap's JavaScript requires jQuery"_. Sorry, my fault. I just didn't know...
* And again: Open new tab → http://code.jquery.com → Copy "http://code.jquery.com/jquery-3.2.1.min.js" → "External Resources" → Paste → Hitting "+": _"You're loading resources over HTTP not HTTPS, your fiddle will not work. Do you wish to continue?"_ Arrghhhh....
* And again: Open new tab → https://code.jquery.com → Copy "https://code.jquery.com/jquery-3.2.1.min.js" → "External Resources" → Paste → Hitting "+": _"Error: Bootstrap's JavaScript requires jQuery"_ F***!!!!!!!!!
* "External Resources" → Order jquery-3.2.1.min.js above bootstrap.min.js
**Finally it works, but but at what price and pain?**

All I wish to have a "Quick-add" like https://codepen.io offers. BUT: I want to make one selection only, like "Latest Bootstrap 3" which comes with all what's needed. No hassle about what CSS and JS and in which order! Just quick start!

**Comment by oskarkrawczyk** [comment]
Unfortunately the codebase for the current JSFiddle version is frozen and no new features will be added. 

We're all hands on the 2.0 rewrite which will have a new way of adding libraries. 

You can have a look at the potential and approved features on our roadmap: https://trello.com/b/LakLkQBW/jsfiddle-roadmap

**Comment by aureole82** [comment]
Guess where I come from:
![jsfiddle-1050 - forwarded from trello](https://user-images.githubusercontent.com/4819891/28667484-024e9592-72cc-11e7-9b6f-bd3ed0d4e58b.png)
