### ISSUE TITLE
getting splash to whitelist even though I have done it.

### ISSUE THREAD

**Issue by robbiemu** [jsfiddle/jsfiddle-issues#1053]
Please feel free to move this or invite me to post it to a specific, proper location if this is not the right place.

I was getting "like jsFiddle, consider whitelisting us" where there might otehrwise be advertisements, because I use Disconnect on Chrome. So , I did it. However, I notice that I still get that blue background request in the bottom-left, asking me to whitelist the site. I don't run an additional ad-blocker, just Disconnect (actually, I do use AdBlock for Youtube, but that shouldn't affect the site at all). If you feel like addressing this issue, I'm glad to provide any information you might need.

PS> You guys are in Delaware! :) Please consider hiring me if you need an extra front end/full stack dev. 😃

**Comment by oskarkrawczyk** [comment]
No idea why would it be happening. Normally it should just go away. Not a big deal really to spend time and research a fix, since it's something specific to your browser+extensions configuration.

JSFiddle is based in beautiful Warsaw, Poland. Inc in Delaware :)
