### ISSUE TITLE
script type="module"

### ISSUE THREAD

**Issue by nicolasparada** [jsfiddle/jsfiddle-issues#1056]
Allow to set the type of a script to "module". Right now it's overwriten to "text/javascript" even if I set it in the configuration about the script attribute.

**Comment by oskarkrawczyk** [comment]
The script attribute filed adds new attributes, doesn't replace existing.

I personally don't see the reason for using `type="module"` on the whole JS panel, nevertheless added your request to our roadmap, voting is open, will let the community decide.

**Comment by nicolasparada** [comment]
Chrome 61 will support `<script type=module>`. I suspect more and more people using it from now on.

**Comment by nicolasparada** [comment]
Inside the script you can import other libs like so:
```js
import { something } from 'https://somecdn/my-lib.js'
```

**Comment by nicolasparada** [comment]
Currently Safari, Chrome and Edge do support modules. We need this.

**Comment by Link2Twenty** [comment]
This would be very helpful for LitHTML and LitElement examples

**Comment by rocka** [comment]
I think we definitely need this! It's 2019 and Chrome/Firefox/Edge all support this!

**Comment by greggman** [comment]
This needs to be made a priority. Several libraries have gone module format and without this I end up having to put all my javascript in the HTML panel.

Vote here!

https://trello.com/c/r0HnI5vf/73-ability-to-change-js-panel-to-typemodule

**Comment by greggman** [comment]
I thought I'd point out codepen does this automatically based on if there is an `import` statement in the JavaScript. I have no idea if they parse the JS or if they just use a regex but if there is no import statement then it's a normal script tag

![](https://i.imgur.com/UDmWIdg.png)

If there is an `import` statement then it adds `type="module"` automatically

![](https://i.imgur.com/8FsrW2Q.png)

**Comment by oskarkrawczyk** [comment]
@greggman added a test implementation, seems to work, can you double check on your end if it works as you'd expect?

Thanks!

**Comment by greggman** [comment]
was it supposed to do it automatically or is there a check/option somewhere? here's a fiddle

https://jsfiddle.net/greggman/d4f267qk/

**Comment by oskarkrawczyk** [comment]
> was it supposed to do it automatically

Yes. From what I see it does add `type="module"`.

**Comment by greggman** [comment]
Ok, it works!

I just needed to set it to "no wrap" instead the default "onload".  

<img width="326" alt="Screen Shot 2019-09-06 at 10 02 47" src="https://user-images.githubusercontent.com/234804/64393685-8c0ae080-d08d-11e9-9ad0-350700f61113.png">

"no wrap bottom of head" and "no wrap bottom of body" both work

**Comment by greggman** [comment]
I wonder if "No wrap - bottom of <body>" should be the default? I can't think of anywhere that's not going to cover everywhere that "onload" covers. That way, people trying to use `import` it will just work where as with `onload` as the default it won't and they need to dig through the docs to find out how to set things to work.

**Comment by oskarkrawczyk** [comment]
@greggman I was just thinking about this yesterday and I think I agree. Will have to look into that.

**Comment by greggman** [comment]
If there is whitespace before the `import` keyword the check for adding `type="module"` fails

Here's a fiddle

https://jsfiddle.net/greggman/vgzdrxu0/
