### ISSUE TITLE
Copying from textarea - incorrect row selection/range

### ISSUE THREAD

**Issue by ChrisAllinson** [jsfiddle/jsfiddle-issues#1058]
I'm finding the textareas in JSFiddle to not highlight/copy correctly.

I'm noticing it copying the incorrect range of rows (e.g. if I highlight lines 6-10, it was copying lines 4-6 or something similar).

This was found on https://jsfiddle.net/
Here's my situation exactly: https://jsfiddle.net/kimmobrunfeldt/mxjj6jom/

---

Copy:
<img width="624" alt="copy" src="https://user-images.githubusercontent.com/8192008/29593291-7b3bc2e4-8777-11e7-80ef-a287d03139f1.png">

Paste:
<img width="549" alt="paste" src="https://user-images.githubusercontent.com/8192008/29593303-870d8ea4-8777-11e7-8689-863106cf0434.png">

---

Perhaps this is solely related to the "BABEL + JSX" field/option ... :?

**Comment by oskarkrawczyk** [comment]
@ChrisAllinson What browser is this happening on? Can't replicate the issue myself.

**Comment by ChrisAllinson** [comment]
Hi, try it out in Chrome Incognito mode, I just reproduced it.
hmmm, it seems to resolve itself with a reload of the page ... now I can't reproduce it :S

**Comment by oskarkrawczyk** [comment]
Since the codebase for the current version of JSFiddle is frozen, I'll just let this minor issue stay there. We'll update CodeMirror in the next version, so the potential bug might be solved then.

**Comment by dandv** [comment]
This issue is quite annoying.

**Comment by ChrisAllinson** [comment]
Agreed :)
