### ISSUE TITLE
Debug formData

### ISSUE THREAD

**Issue by kaihendry** [jsfiddle/jsfiddle-issues#1062]
Hi, how do I debug/echo formData? I'm stuck here: https://jsfiddle.net/kaihendry/fjgomgpb/

**Comment by oskarkrawczyk** [comment]
@kaihendry `/echo` endpoints are for async requests only, see more here: http://doc.jsfiddle.net/use/echo.html

**Comment by vanillajonathan** [comment]
The echo endpoint only returns the content of the `html` key.

Example:
```html
<form method="post" action="/echo/html">
  <input name="html" value="hello">
  <input type="submit">
</form>
```

I think it would be easier to debug form data if there were an echo endpoint that returned everything that was posted.
