### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by vanillajonathan** [jsfiddle/jsfiddle-issues#1063]
Would be nice to be able switch to a dark theme from the settings menu.

**Comment by oskarkrawczyk** [comment]
Soon, ~1 month

**Comment by farskid** [comment]
is it still in progress?

**Comment by oskarkrawczyk** [comment]
@farskid yes but lots of delay, no ETA

**Comment by farskid** [comment]
@oskarkrawczyk If there is anything I could help with, I'd be happy to help and join. just let me know about it 👍 At the end of the day, JSFiddle is the tool we use everyday and help making it better will benefit all of us :)
