### ISSUE TITLE
abnormal style

### ISSUE THREAD

**Issue by iamwelk** [jsfiddle/jsfiddle-issues#1069]
https://jsfiddle.net/

![image](https://user-images.githubusercontent.com/6983075/31379443-d9a49a10-ade0-11e7-860f-d1266e57e545.png)

**Comment by oskarkrawczyk** [comment]
Most likely an extension is blocking some css files. Cannot replicate.

Please provide more details, until then closing.

**Comment by iamwelk** [comment]
@oskarkrawczyk 
![image](https://user-images.githubusercontent.com/6983075/31379603-4b433b0e-ade1-11e7-97ed-1762930a8096.png)

I cannot find blocked css files

**Comment by oskarkrawczyk** [comment]
@iamwelk same happens after reseting cache? In incognito? Different browser?

What version of Chrome is that?

**Comment by iamwelk** [comment]
@oskarkrawczyk 
chrome
版本 61.0.3163.100（正式版本） （64 位）

In firefox it can work
