### ISSUE TITLE
Missing fiddles

### ISSUE THREAD

**Issue by JohnSatriano** [jsfiddle/jsfiddle-issues#1072]
https://jsfiddle.net/user/jsat/fiddles/
https://jsfiddle.net/jsat/Mb8sQ/
https://jsfiddle.net/jsat/3pzhn23a/

Is there any way to recover them?

**Comment by oskarkrawczyk** [comment]
Please elaborate.

Have you removed them? Are they listed anywhere on your account?

Are these your fiddles:

https://jsfiddle.net/Mb8sQ/
https://jsfiddle.net/3pzhn23a/

**Comment by JohnSatriano** [comment]
It appears the URL normally used for my fiddles has changed. This has broken some of my links, but I can fix it. However, in my dashboard, the links are still incorrect. Maybe a bad routing patch was pushed?

**Comment by JohnSatriano** [comment]
Actually, in the render for the fiddles you linked, there is a 404 nginx error.

**Comment by oskarkrawczyk** [comment]
Nothing in the codebase has changed, so no idea what happened.

If you run the fiddle, render works. Picking one of the later revisions also works, so just set as base one of the latter revisions.

Codebase is frozen, nothing like this has happened before, so I'll categorize this as a freak accident. We're in the midst of rewriting the code, so this sort of things won't be happening.

**Comment by JohnSatriano** [comment]
I can't embed my fiddles any longer. The embed is always 404. I guess I could try to copy them into new fiddles or something?

**Comment by oskarkrawczyk** [comment]
@JohnSatriano fork them

**Comment by JohnSatriano** [comment]
http://jsfiddle.net/mgqdc8Lx/embedded/result/#Result
Still broken.

**Comment by oskarkrawczyk** [comment]
Forked under my account, works fine http://jsfiddle.net/oskar/rsd2d5go/

**Comment by JohnSatriano** [comment]
I guess my account is borked. I'll create another and move forward. Thanks for the help

**Comment by oskarkrawczyk** [comment]
@JohnSatriano turns out there was indeed a bug in the code, apologies for the misdiagnosis. Fiddles under your account work again.
