### ISSUE TITLE
http://jsfiddle.net/api not available anymore?

### ISSUE THREAD

**Issue by KooiInc** [jsfiddle/jsfiddle-issues#1073]
It seems the api page is not available anymore (see screenshot). Can anyone confirm?

![image](https://user-images.githubusercontent.com/836043/31850130-d31a8ebe-b64d-11e7-9caf-66901208b014.png)

**Comment by oskarkrawczyk** [comment]
@KooiInc can you try now?

**Comment by KooiInc** [comment]
Hi Oscar, that was fast! It works, thanks.

![image](https://user-images.githubusercontent.com/836043/31850403-70892bda-b651-11e7-8956-a31a13821076.png)
