### ISSUE TITLE
Dashboard's UI name field

### ISSUE THREAD

**Issue by nhatn1507** [jsfiddle/jsfiddle-issues#1076]
For a better user's reference and interaction, in dashboard, the name field can be used to display the fiddle's name instead of the random url string?
Also, clicking the url directs user to the original draft of the fiddle, while perhaps most people just want to see the latest version of their fiddle which is actually the red url next to the name something like "#2 is the latest revision".

**Comment by oskarkrawczyk** [comment]
1. Name of the fiddle can be changed in the editor.
2. Version can be made the HEAD (no number in the URL) from the editor level (`save as base`)
