### ISSUE TITLE
Reorganize CSS/JS/HTML panels 

### ISSUE THREAD

**Issue by nhatn1507** [jsfiddle/jsfiddle-issues#1077]
A lot of editors allow users to reorganize these panels as needed to suit their codes, for example I personally only want to see HTML and CSS panels stack into one column and the Result panel on another, while hiding away the JS panel, when I just fiddle with HTML and CSS code. This way I can see more of the codes and also more of the result.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
