### ISSUE TITLE
Preadded options for popular libraries

### ISSUE THREAD

**Issue by nhatn1507** [jsfiddle/jsfiddle-issues#1078]
Users should be able to add popular external libraries such as Bootstrap, jQuery from a provided list instead of having to go find their latest CDNs and add them manually

**Comment by oskarkrawczyk** [comment]
<img width="624" alt="screen shot 2017-10-25 at 08 47 53" src="https://user-images.githubusercontent.com/34213/31984285-4968c570-b961-11e7-8d6d-0fec91a31508.png">
