### ISSUE TITLE
https://jsfiddle.net/ brings an http error

### ISSUE THREAD

**Issue by MrGlacier** [jsfiddle/jsfiddle-issues#1080]
If i run an empy fiddle in Chrome (60.0.3112.101 64bit) or FF (56.0.1 (64-Bit)) the console bring an error.

> Laden von gemischten aktiven Inhalten "http://fiddle.jshell.net/_display/" wurde blockiert.[Weitere Informationen]

This means there is an http request from an https site.
The Result brings an "301 Moved Permanently" Message.

Can someone check this. I dont know is it me or the Fiddle Site?

Steps to Produce the Error:
1. Open https://jsfiddle.net/
2. Press F12
3. Run the empty Fiddle by pressing "Run"

Sry, for my bad english :-(

**Comment by oskarkrawczyk** [comment]
@MrGlacier Thanks for letting us know, we're looking into it

**Comment by oskarkrawczyk** [comment]
Fixed
