### ISSUE TITLE
Deal with new restrictions for WebMidi

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#1081]
I wrote a small web midi sample and in Chrome 64 I'm setting this message in the console

> fiddle.jshell.net/:52 [Deprecation] requestMIDIAccess usage in cross-origin iframes is deprecated and will be disabled in M64, around January 2018. To continue to use this feature, it must be enabled by the embedding document using Feature Policy, e.g. <iframe allow="midi" ...>. See https://goo.gl/EuHzyv for more details.

https://jsfiddle.net/greggman/c1r2t134/

**Comment by oskarkrawczyk** [comment]
Done. Will land on production later today.
