### ISSUE TITLE
External resources not loaded before Javascript code runs

### ISSUE THREAD

**Issue by remi-stripe** [jsfiddle/jsfiddle-issues#1082]
A recent change to jsfiddle is causing most of my jsfiddles to fail on load because the external resources are not properly loaded before rendering the JS. Because of this, the console displays an error message and the code does not work.

I work for Stripe and use jsfiddle to show quick examples such as:
- creating a Card token with Stripe.js: http://jsfiddle.net/ch9jtkgb/
- creating a Card token with Elements: https://jsfiddle.net/edz9d5Ln/

In both cases, Stripe.js is included as an external resource and the Javascript panel is configured to wait for the resources to be loaded first but they both show an error in the console indicating that Stripe is undefined.

I've tried a few other setups but the only thing that works now is to explicitly load the resource in the HTML panel.

This has worked for a ling time. The first jsfiddle is at least 2 years old. Not sure if something changed on your end or if it was mostly luck and there's a better approach.

Let me know if I can provide more details to reproduce this!

**Comment by oskarkrawczyk** [comment]
@remi-stripe Thanks for the heads up. We're looking into the issue.

**Comment by majkelcc** [comment]
@remi-stripe Hi, we recently made some changes and it looks like resources were not properly included when the file in url was missing extension (as in `https://js.stripe.com/v2/` case). Can you confirm everything is working properly now?

**Comment by remi-stripe** [comment]
@majkelcc Wow I'm amazed at how quickly you were able to pinpoint the issue and deploy a fix. I can confirm my jsfiddles now work as expected.

Jsfiddle is an awesome product and now I know that the dev team is too :)
