### ISSUE TITLE
Reset layout

### ISSUE THREAD

**Issue by dotnetCarpenter** [jsfiddle/jsfiddle-issues#1083]
I accidentally pulled the vertical splitter all the way to the right and now I can not see the CSS/OUTPUT panes. There is no way to reset the layout and I haven't found a cookie to delete, in order to reset my layout. Could you please provide a reset link so I don't have to change browser every time I need to see a jsfiddle?

**Comment by oskarkrawczyk** [comment]
@dotnetCarpenter See **Known issues** in [README.md](https://github.com/jsfiddle/jsfiddle-issues/blob/master/README.md)
