### ISSUE TITLE
medium.com embed tweak (choose which tab is selected)

### ISSUE THREAD

**Issue by bitbonsai** [jsfiddle/jsfiddle-issues#1084]
When embedding on medium.com, the JS tab is always selected. While it makes sense, sometimes you want to write a post and highlight either the JS, CSS, HTML or result.

So if we could pass a param to select one of the available tags, I'm sure that jsfiddle could supersede GitHub gists as THE code sharing tool on medium.com

If the code is theme able, that would be a huge plus but not necessary. The first most impactful step would be ability to select the selected tab.

**Comment by oskarkrawczyk** [comment]
http://doc.jsfiddle.net/use/embedding.html

See the section **Changing tabs**
