### ISSUE TITLE
Add css via external resource

### ISSUE THREAD

**Issue by CZechBoY** [jsfiddle/jsfiddle-issues#1085]
Hi,
I'm unable to add external css file `https://mydomain.tld/webtemp/cssloader-5fds123f1d2s.css?1509700617`.
How to do it?
I have tried:
1) <link rel=stylesheet href="..."> -> this warns me about external resources and the file is not loaded and is removed from html
2) paste link to `External resources` -> this tries load CSS STYLESHEET via `<script src="..."></script>` which loads the file but immediately crashes with syntax error in js file (really?, it is not js file but css)

Thanks for fixing this.

**Comment by majkelcc** [comment]
Hi @CZechBoY, we just pushed a fix to this. Please confirm it works.

**Comment by CZechBoY** [comment]
looks good
thanks
