### ISSUE TITLE
Fiddles missing form the dashboard if ore than one page

### ISSUE THREAD

**Issue by gusmatlis** [jsfiddle/jsfiddle-issues#1086]
A couple of days ago I noticed that only the first page of fiddles I have saved is showing in my dashboard.  There used to be buttons with page numbers and next/previous to navigate trough the dashboard pages, but now it's all gone?

Anyone knows why the pagination buttons are missing and how can I get to the rest of my fiddles?

**Comment by oskarkrawczyk** [comment]
@gusmatlis can you double check if the issue still exits? There has been a fix to pagination made a day ago.

From what I see the pagination is visible for accounts with many fiddles.

**Comment by gusmatlis** [comment]
All works now. ....thanks! !!!!!!!
