### ISSUE TITLE
CoffeeScript seems to be broken

### ISSUE THREAD

**Issue by Inversion-des** [jsfiddle/jsfiddle-issues#1087]
Simple test — https://jsfiddle.net/Inversion/bqxxtnsd/
It always throws: 
Uncaught SyntaxError: missing indentation

**Comment by oskarkrawczyk** [comment]
Looking into it

**Comment by oskarkrawczyk** [comment]
@majkelcc A simple test shows that some extra indentation is being inserted: https://jsfiddle.net/oskar/hpLhx35t/2/

Input:

```
# first line

if (true)
	console.log this
```

Result:

```
    # first line

if (true)
	console.log this
```

**Comment by oskarkrawczyk** [comment]
Fixed
