### ISSUE TITLE
POST API doesn't load external resources in first load

### ISSUE THREAD

**Issue by jaredp** [jsfiddle/jsfiddle-issues#1088]
**Expected behavior:**

JSFiddle POST API works with external resources.  Using external resources is documented at http://doc.jsfiddle.net/api/post.html#display-a-fiddle-from-post.

**Observed behavior:**

External resources do not work on the first load.  When a POST API request is made, the external resources are not loaded.  However, the external resources are added to the fiddle, and are run if the user manually clicks the `Run` button.

This does not look like the known issue around timing, because the external resources are never loaded the first time around.  They are always loaded correctly if the user manually clicks the `Run` button after the first load.

**Steps to reproduce:**

https://jsfiddle.net/rxsvoz2r/2/ is a fiddle with sample code that should work with the jsfiddle POST API.  When clicked, the button in the fiddle should create and open a new fiddle with React set up.   

It uses the external resources feature to load the React libraries ( `resources="https://unpkg.com/react@16.0.0/umd/react.development.js,https://unpkg.com/react-dom@16.0.0/umd/react-dom.development.js"`).

When the button is clicked, it successfully opens a new fiddle with all the right content.  However, the preview does not load.  There is an error in the console saying `React is not defined`.  When the JS runs, the external resources had not yet been loaded.  It does not appear to be a timing issue, because the external resources are not added to the preview pane at all.  Everything works correctly if the user clicks the `Run` button in the API-created fiddle after the first load.

**Comment by oskarkrawczyk** [comment]
@jaredp Thanks for the lengthy explanation. We're aware of the issue, the app is load balanced between a version that has this issue and one that doesn't (rewrite). Once we iron out all issues on the rewrite the problem will be no more.

Until then, sometimes loading resources via POST API will work and other times it'll not.

I'll leave this ticket open for now.
