### ISSUE TITLE
Wrong output in plain javascript program

### ISSUE THREAD

**Issue by vamshisuram** [jsfiddle/jsfiddle-issues#1089]
Not sure if this is a known issue. Just wanted to bring to your notice. The context is different in the execution.

Please compare the results of the same program in these fiddles
[jsbin](http://jsbin.com/jehureb/edit?js,console)  - outputs "two"  - which i think is right.
[jsfiddle](https://jsfiddle.net/vamshisuram/yusexdnu/3/)  - outputs "one"

**Comment by oskarkrawczyk** [comment]
Generally this code is wrong in my eyes, you're only assuming `this` will be the context of `window`, which it doesn't have to. 

This works:

```
var name = "one";
function printName() {
    name = "two";
    console.log(name);
}```

**Comment by vamshisuram** [comment]
I understand this is not a good practice. But I believe, considering the program i wrote (present in the links), the context should point to window. Please look at JsBin output. It seems jsfiddle program is run with some other context binding.

**Comment by majkelcc** [comment]
@vamshisuram jsfiddle by default wraps code in `onLoad` wrapper. If you select no wrap it will work the same as on jsbin:

<img width="565" alt="screen shot 2017-11-08 at 5 09 08 pm" src="https://user-images.githubusercontent.com/1869402/32540495-d9c7397a-c4a7-11e7-8a69-6cc782a81244.png">

**Comment by vamshisuram** [comment]
@majkelcc thanks a lot for clarifying. 👍
