### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by kud** [jsfiddle/jsfiddle-issues#1090]
It would be great to have collections of fiddles. Like on codepen.

For the moment, we just have a ordered list of elements like:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/655838/32653134-09a3ab46-c607-11e7-8758-249efc3dcda7.png">

I would like to be able to organise my fiddles in collections. :)

**Comment by oskarkrawczyk** [comment]
@kud Agree, we have [grouping on our roadmap](https://trello.com/c/28gPYs4Y/2-grouping-fiddles)

**Comment by kud** [comment]
Haha thanks, I was going to say I've found this card https://trello.com/c/28gPYs4Y/2-grouping-fiddles and asking if it was the same thing.

Thanks!
