### ISSUE TITLE
FabricJS 1.7.20 update request

### ISSUE THREAD

**Issue by asturur** [jsfiddle/jsfiddle-issues#1092]
# Library update request

Kindly request to update fabricJS to 1.7.20 on jsfiddle

http://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.20/fabric.min.js

**Comment by asturur** [comment]
argh i did not tagged it yet. need some minute for the cdn to wakup

**Comment by oskarkrawczyk** [comment]
@majkelcc added, can you deploy the app?

**Comment by majkelcc** [comment]
🏁
