### ISSUE TITLE
Please add viewport meta tag to your header!

### ISSUE THREAD

**Issue by tcurrie** [jsfiddle/jsfiddle-issues#1094]
Please add the viewport meta tag to your embedded view header so they can be shared and previewed properly on mobile devices.
`<meta name="viewport" content="width=device-width, initial-scale=1" />
`

The suggested work around of closing the style and inserting the meta tag does not work, as noted multiple times by myself and others: https://stackoverflow.com/questions/16929613/where-do-i-put-viewport-meta-tag-in-jsfiddle/47293024#47293024

Reproduction: 
1) Open the embedded view of fiddle, https://jsfiddle.net/g91pz43g/1/, using: http://jsfiddle.net/g91pz43g/1/embedded/result/ 
   - In a chrome browser and in the developer tools use the device toolbar to switch to a mobile view.
   - or actually just open it on a mobile device.

Chrome mobile view in developers tools:
![screen shot 2017-11-14 at 10 14 48 am](https://user-images.githubusercontent.com/13125516/32796797-b502c2d6-c924-11e7-87fc-705b5436b6bb.png)

Actual iphone 6 chrome screencap:  (different fiddle showing a set of smart phone wide formatted ads!  Each or those ads should render screen width!):
![screen shot 2017-11-14 at 10 22 02 am](https://user-images.githubusercontent.com/13125516/32797227-d6302baa-c925-11e7-8c77-1cb4d4a56d6d.png)

Notice that the rendered results are small and improperly formatted.  This is because the fiddle is always rendered inside an iframe.  The meta tag needs to be added to the outermost document.   If anyone wants to view the fiddle standalone, then the wrapper page must have that meta tag.

Here, I've taken the liberty of editing the outer jsfiddle html and inserting the meta tag.  Notice how it renders correctly in mobile and desktop.

Mobile:
![screen shot 2017-11-14 at 10 09 58 am](https://user-images.githubusercontent.com/13125516/32796591-0919dc70-c924-11e7-8772-4d78f4c1da2f.png)

Desktop:
![screen shot 2017-11-14 at 10 11 01 am](https://user-images.githubusercontent.com/13125516/32796617-271d6444-c924-11e7-84ba-3b4c4a5696ea.png)

**Comment by oskarkrawczyk** [comment]
@tcurrie Very good point, I'll make the change today. Thanks!

**Comment by oskarkrawczyk** [comment]
Done.

@majkelcc Can you :shipit:

**Comment by tcurrie** [comment]
Awesome!  Thank you!  When will it show up in production?

**Comment by oskarkrawczyk** [comment]
@tcurrie most likely tomorrow

**Comment by majkelcc** [comment]
@oskarkrawczyk @tcurrie done

**Comment by oskarkrawczyk** [comment]
Thanks @majkelcc!
