### ISSUE TITLE
404 Error when trying to save/update fiddle

### ISSUE THREAD

**Issue by kellyclemons** [jsfiddle/jsfiddle-issues#1097]
Hi, I'm having trouble saving my code. I've created a test file to demonstrate the problem (see bottom)...

I have saved my fiddle as public by entering a Title, however, when I click save/update I'm getting the following error in my console:

_Failed to load resource: the server responded with a status of 404 (Not Found)_

Then if I try to access my code from a different computer (without being logged into my account), I'm getting a page that says 404 Not Found - nginx.

This is the link to my test code: [https://jsfiddle.net/kellyclemonscode/h55dp9k9/3/](url)

Please help!!!!!

**Comment by oskarkrawczyk** [comment]
As far as I can see saving/updating works fine.

There is a 404, but it's related to embeds. We'll look into it.

@majkelcc Any ideas why embeds on some fiddles might be throwing a 404?

Interestingly:

- https://jsfiddle.net/kellyclemonscode/h55dp9k9/3/ - problem exists
- https://jsfiddle.net/oskar/4ss51994/ - no problem

**Comment by kellyclemons** [comment]
Ok thanks @oskarkrawczyk. I'm able to save/update now with no issue, but whenever I was doing so, it was throwing a 404 error in the console. Also, I was having trouble accessing my public fiddles when not logged in. It seems to be resolved now!!

**Comment by majkelcc** [comment]
@kellyclemons @oskarkrawczyk found the problem, all should be working now.

**Comment by kellyclemons** [comment]
Thanks so much guys!! @oskarkrawczyk @majkelcc
