### ISSUE TITLE
Add allowpaymentrequest to render iframe

### ISSUE THREAD

**Issue by athyuttamre** [jsfiddle/jsfiddle-issues#1099]
The W3C Payment Request API is supported within iframes only if the `allowpaymentreqeust` property is set on the iframe. It would be useful to add this property to jsfiddle's render iframe so that we can test the API.

https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API

**Comment by oskarkrawczyk** [comment]
@athyuttamre will do.

@majkelcc I've updated both apps to have this change, can you deploy?

**Comment by athyuttamre** [comment]
Awesome, thanks so much @oskarkrawczyk!

**Comment by atty-stripe** [comment]
Hi there! Looks like the latest release of JSFiddle shipped with a typo, and now the field says "allowpaymentreqeust" rather than "allowpaymentrequest". Could we fix this please?

**Comment by oskarkrawczyk** [comment]
Regression. Will fix soon.

**Comment by oskarkrawczyk** [comment]
Should be fixed.

**Comment by atty-stripe** [comment]
Awesome, thanks!

**Comment by atty-stripe** [comment]
@oskarkrawczyk looks like the typo is back. Could you fix again please?

**Comment by oskarkrawczyk** [comment]
@atty-stripe Dammit! Thanks for letting me know, fixed (again).

**Comment by oskarkrawczyk** [comment]
@atty-stripe Are you guys using JSFiddle for checkout examples? Or just internally?

**Comment by athyuttamre** [comment]
@oskarkrawczyk mostly internally for debugging and creating quick examples! Sometimes to help users debug their integrations as well.

**Comment by oskarkrawczyk** [comment]
@athyuttamre gotcha, awesome to hear that!
