### ISSUE TITLE
Putting an emoji in HTML or JS causes jsfiddle to crash with "500 internal server error"

### ISSUE THREAD

**Issue by Herteby** [jsfiddle/jsfiddle-issues#1100]
example: https://jsfiddle.net/Herteby/xbkkwa6y/

**Comment by oskarkrawczyk** [comment]
@Herteby nice catch, thanks for letting us know!

@majkelcc any chance this is related to the UTF DB issue?

**Comment by majkelcc** [comment]
@Herteby @oskarkrawczyk random issue after upgrading database version, I had to temporarily allow drafts to fail when saving.

**Comment by Herteby** [comment]
@majkelcc It's failing again now.
