### ISSUE TITLE
chrome M64+ requires permissions for getUserMedia in iframes

### ISSUE THREAD

**Issue by fippo** [jsfiddle/jsfiddle-issues#1101]
https://jsfiddle.net/uvhkoacj/ is broken in Chrome canary which requires some special treatement to allow this in iframes. This is described here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/32natnrbP6U/0dgpWLMkAwAJ

The gist seems to be adding a semicolon-separated list of permissions in an allow tag:
```<iframe src="https://example.com" allow="microphone; camera"></iframe>```

**Comment by oskarkrawczyk** [comment]
Done. Will land on production later today.
