### ISSUE TITLE
allowpaymentreqeust

### ISSUE THREAD

**Issue by birbilis** [jsfiddle/jsfiddle-issues#1102]
When I use "embed" and select to use iframe instead of script, I see

<iframe width="100%" height="300" src="//jsfiddle.net/birbilis/23nt74se/embedded/" allowpaymentreqeust allowfullscreen="allowfullscreen" frameborder="0"></iframe>

what is "allowpaymentreqeust" there and why is it misspelled?

**Comment by oskarkrawczyk** [comment]
Thanks for the heads up about the typo. Will fix soon.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/allowPaymentRequest

**Comment by birbilis** [comment]
since that one is supposed to be a security feature, maybe should detect if payment API is used and only then include it 

but guess I'm asking for too much and one could have a checkbox "Allow Payment Request API" (marked with the above link) for that when in iframe mode to make sure user understands any security implications of adding the parameter (checking the box would add the parameter to the output
