### ISSUE TITLE
Feature Request: Auto Save

### ISSUE THREAD

**Issue by Hillsie** [jsfiddle/jsfiddle-issues#1105]
#Feature Request
Like js Fiddle. Thanks. Any chance auto save could be added?

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

https://trello.com/c/CLVT3f8K/14-autosaving-fiddles
