### ISSUE TITLE
Setting universal CSS selector * to display:inline breaks result frame.

### ISSUE THREAD

**Issue by Frondor** [jsfiddle/jsfiddle-issues#1107]
See: https://jsfiddle.net/gm02ndwr/

Uncomment <code>// display: inline</code> for reproduction

**Comment by oskarkrawczyk** [comment]
Unfortunately we have no idea why is this happening, please use `body * {}`. Rewrite hopefully won't have this issue.

**Comment by tanevarez3** [comment]
I need to make my on screen arrow contols, for andoid and tablet to work with my tetris game using Javasvipt. Pc controls work fine
