### ISSUE TITLE
cannot show only result when embedding jsfiddle into medium

### ISSUE THREAD

**Issue by ghandzhipeng** [jsfiddle/jsfiddle-issues#1108]
Hi all, 
I tried to embed a jsfiddle into a blog(https://medium.com) and I only want to see the "result" button, but it turns that all things are displayed, like CSS, HTML, js, result. 

I have tried several choices including:
https://<myjsfiddleURL>/show
https://<myjsfiddleURL>/embedded/result

But it doesn't work :(. Any ideas?
Thanks!

**Comment by oskarkrawczyk** [comment]
Embedding on Medium is done via embed.ly, unfortunately there's no configuration options for this.

**Comment by ghandzhipeng** [comment]
Hi oskarkrawczyk,
Thanks for your reply. I have come across a blog and it seems that the embedding is perfect:

https://blog.mapbox.com/3d-features-in-mapbox-gl-js-e94734f12110

Any ideas about how this is implemented?

Zhipeng

**Comment by oskarkrawczyk** [comment]
I'd love to know how they did that!

**Comment by ghandzhipeng** [comment]
Or can we control the order of displaying these stuff? Like I want the result to be the default ones?

**Comment by oskarkrawczyk** [comment]
Looks like to show the results panel only you can use a URL like this `http://jsfiddle.net/USER/FIDDLE/show`

**Comment by ghandzhipeng** [comment]
Actually it doesn't help :(

**Comment by ghandzhipeng** [comment]
Can you use this kind of url to show the result panel only?

**Comment by oskarkrawczyk** [comment]
Weird, worked once, now it doesn't. I don't have a way to get custom panels to appear on Medium.

**Comment by ghandzhipeng** [comment]
Ok, thanks a lot. 
Will let you know if I have some other finding. Also please let me know if there is some progress :)

**Comment by lonbinder** [comment]
I'm curious why this issue was closed. It still seems to be broken. Is there no way around? using the trailing /show doesn't seem to affect anything. And, similarly, the /result configuration doesn't apply either. Ideally would love to just show the result output.
