### ISSUE TITLE
Roadmap Idea: Integrate CDNJS search into "External Resources"

### ISSUE THREAD

**Issue by gregbacchus** [jsfiddle/jsfiddle-issues#1109]
It would be great to be able to simply add external resources by searching from cdnjs.com.

The place where you currently put the external resource URI could also double as a search box.

**Comment by oskarkrawczyk** [comment]
This was planned as a part of the big refactor, but that is delayed so I'll have a look if I can integrate it somehow using their API on the client side.

**Comment by oskarkrawczyk** [comment]
Had a look into it, and can't seem to get client side requests to their API to work. If that was working, I would probably be able to put something together this week.

**Comment by oskarkrawczyk** [comment]
Scratch that, got it to work.

**Comment by oskarkrawczyk** [comment]
Done.
