### ISSUE TITLE
saving/updating fiddle with command :w in vim key binding

### ISSUE THREAD

**Issue by sohnryang** [jsfiddle/jsfiddle-issues#1110]
It would be nice to save a fiddle with using `:w` command in vim mode.

**Comment by sohnryang** [comment]
Ping

**Comment by oskarkrawczyk** [comment]
Since VIM in CodeMirror doesn't have an active maintainer, we've decided to disable supporting it inside of JSFiddle. Sorry for all who were using it, but it's not worth the potential issues it might cause for the few people that use it.

**Comment by timmywil** [comment]
I could understand that, except it's [been updated more recently and more frequently](https://github.com/codemirror/CodeMirror/search?o=desc&q=vim&s=committer-date&type=Commits) than both [Emacs](https://github.com/codemirror/CodeMirror/search?o=desc&q=emacs&s=committer-date&type=Commits) and [Sublime Text](https://github.com/codemirror/CodeMirror/search?o=desc&q=sublime&s=committer-date&type=Commits). Do you mean there isn't a core maintainer assigned to it? Seems a pretty major feature to drop so suddenly.

**Comment by copremesis** [comment]
Thats fine I'll just use codepen

**Comment by sangdth** [comment]
I will change to use CodeSandbox.

**Comment by laoshaw** [comment]
no more vim mode, can't switch between panes by ctrl+arrowkey, disappointed :(
