### ISSUE TITLE
New Fiddle button

### ISSUE THREAD

**Issue by jany-boi** [jsfiddle/jsfiddle-issues#1112]
No button to start a new fiddle. Kinda annoying.

**Comment by oskarkrawczyk** [comment]
We had it a long time ago, nobody was using it.

--

**Comment by jany-boi** [comment]
How does a user get to create a new fiddle then?

Best,
Shreyas

**Comment by oskarkrawczyk** [comment]
jsfiddle.net = blank fiddle
