### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by GLaureys** [jsfiddle/jsfiddle-issues#1113]
Idea: Add help window with HTML, CSS and JS documentation

Thank you

**Comment by oskarkrawczyk** [comment]
Can you elaborate? Not sure I understand.

--

**Comment by GLaureys** [comment]
As I am new to coding, it would be nice to have help



















































































































































































































































































As I am new to coding, it would be a great to have a help window with links to documentation on HTML / Javascript / CSS syntax.

Thank you

**Comment by KieranHolroyd** [comment]
https://www.w3schools.com/
