### ISSUE TITLE
Using backticks in JavaScript panel breaks rendering

### ISSUE THREAD

**Issue by yuriy636** [jsfiddle/jsfiddle-issues#1115]
**Using backticks ( ` ) in the JavaScript panel breaks the rendering when opening a saved fiddle in new tab. "Run" works fine while in the same tab.**

A new blank fiddle with
```
let string = `hello`;
```
in the JavaScript panel, when saved and opened in a new tab renders a broken fiddle view:
![image](https://user-images.githubusercontent.com/6631050/34467927-fd10c45c-eefd-11e7-98ef-1db92a2eb902.png)

with these errors in the console:
![image](https://user-images.githubusercontent.com/6631050/34467931-17a1aa70-eefe-11e7-9747-8a7ca29232c0.png)

[JSFiddle with the code above that will fail to render](https://jsfiddle.net/mrqfhnby/)

**Comment by oskarkrawczyk** [comment]
I'm aware. Working on a revert to the previously working code.
