### ISSUE TITLE
Light theme - can't see cursor

### ISSUE THREAD

**Issue by charlietfl** [jsfiddle/jsfiddle-issues#1116]
I'm a fairly heavy jsfiddle user (almost daily) and like the new theme switch concept. Although I like dark themes I do find syntax coloring a bit too brash for my tastes and tend to toggle back to the light theme.

Cursor color in light theme makes it almost invisible though. 

Would also be nice to see more distinction where each of the actual code editing boundaries are and a bit more contrast on line numbers

**Comment by oskarkrawczyk** [comment]
The cursor color snafu was a regression after trying to push out grid switching today. I've cherry picked the fixes and it should be fine again.

As to the contrast, I'll take it under consideration, will take another stab at it if more people feel there's to little contrast.

**Comment by charlietfl** [comment]
Cursor better now...thanks.
One other side note. In dark theme, highlight some code ... highlight definitely hard to see that it is highlighted

**Comment by oskarkrawczyk** [comment]
> One other side note. In dark theme, highlight some code ... highlight definitely hard to see that it is highlighted

100% agree
