### ISSUE TITLE
Atom-styled snippets

### ISSUE THREAD

**Issue by realsrikar** [jsfiddle/jsfiddle-issues#1117]
[Atom](https://atom.io) code editor has some very smart snippets for javascript built-in. The file is up on their repo -> [file](https://github.com/atom/language-javascript/blob/master/snippets/language-javascript.cson).

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
