### ISSUE TITLE
Unable to load from GitHub

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#1118]
Live demo: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-basic/

All the panes are empty, and in addition the browser opens up a new tab, pointing to http://fiddle.jshell.net/_display/, which is also empty.

**Comment by oskarkrawczyk** [comment]
Working on a fix. Sorry for the trouble.

--

**Comment by oskarkrawczyk** [comment]
Reverted to the previously working version. The new one needs more testing, clearly.
