### ISSUE TITLE
Loading a fiddle based on the POST variables not working

### ISSUE THREAD

**Issue by budnix** [jsfiddle/jsfiddle-issues#1119]
The latest version of https://jsfiddle.net does not accept html, javascript and css source code via API. By using the following demo http://jsfiddle.net/zalun/sthmj/embedded/result/ I can only fill it with a title or description etc. but without a source code.

The API was changed (form fields were renamed) or this is a bug?

**Comment by oskarkrawczyk** [comment]
Working on a fix. Sorry for the trouble.

--

**Comment by oskarkrawczyk** [comment]
Reverted to the previously working version. The new one needs more testing, clearly.
