### ISSUE TITLE
jsfiddle.net doesn't have link to this repo

### ISSUE THREAD

**Issue by IllusionMH** [jsfiddle/jsfiddle-issues#1121]
There is no surprise that [people used "Report fiddle"](https://twitter.com/jsfiddle/status/948921092344774657) functionality because reporting actual issue requires using their preferred search engine first to find this repo. Even About page doesn't have link.

Please make link to this repo available and **noticeable** on jsfiddle.net. And make clear description when user should use "Report fiddle" or navigate to this repo.

**Comment by oskarkrawczyk** [comment]
Thanks for the suggestion, I'll think about it.
