### ISSUE TITLE
The examples on Echo in the docs throws exception

### ISSUE THREAD

**Issue by dmartensson** [jsfiddle/jsfiddle-issues#1122]
The page on the Echo api has examples, but they fail in borth FireFox and Chrome

http://doc.jsfiddle.net/use/echo.html

GET http://fiddle.jshell.net/js/lib/mootools-1.2.5-core-nc.js net::ERR_ABORTED
(index):52 Uncaught TypeError: window.addEvent is not a function
    at (index):52

**Comment by oskarkrawczyk** [comment]
Thanks, fixed
