### ISSUE TITLE
Apparent issue with the ` character

### ISSUE THREAD

**Issue by taplar** [jsfiddle/jsfiddle-issues#1123]
https://jsfiddle.net/f1Larng7/

It appears that jsfiddle has an issue parsing the ` character for multiline strings.  Even commented out it is still erroring.  If I take it out completely it appears to start working again.

**Comment by oskarkrawczyk** [comment]
@taplar Template Literals have nothing to do with the problem but the fact that you have a `script` tag inside and not escaping it.

https://jsfiddle.net/oskar/f1Larng7/1/

**Comment by chrisjohnson** [comment]
@taplar:

HTML parsing happens before Javascript parsing. The HTML parser sees `<script>` and immediately starts to look for the corresponding `</script>`. HTML parser doesn't know about the JS inside and doesn't know to ignore certain `</script>` tags. It sees `</script>` and assumes your script is done, and then now you've got an incomplete JS which results in your JS error.
