### ISSUE TITLE
New Dark theme seems to have wrong background color for result on Firefox

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#1125]
Since the default background color is white I'd expect the result in JSFiddle to be white. It is in Chrome and Safari but not in Firefox at least on MacOS

Chrome:

<img width="858" alt="screen shot 2018-01-05 at 14 29 35" src="https://user-images.githubusercontent.com/234804/34596721-6946f2f2-f225-11e7-930c-05342eb20dde.png">

Firefox:

<img width="859" alt="screen shot 2018-01-05 at 14 30 07" src="https://user-images.githubusercontent.com/234804/34596728-6f040248-f225-11e7-97bd-23108bf3a375.png">

**Comment by greggman** [comment]
verified this doesn't happen on Firefox on Windows so I suppose it's a Firefox bug? Though IIRC it's long standing

**Comment by oskarkrawczyk** [comment]
@greggman cache issue?

**Comment by greggman** [comment]
yea, cache issue. Sorry about that
