### ISSUE TITLE
Previews use non-standard colors?

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#1126]
I notice the new previews don't use standard colors. Instead they are reversed. That seems problematic since many samples will expect black text and a white background and will have other styles that expect those to be the default?

Fiddle:

![preview-color-issue-result](https://user-images.githubusercontent.com/234804/34596992-5544ad1a-f227-11e7-8903-e7d268bb067e.PNG)

Preview:

![preview-color-issue](https://user-images.githubusercontent.com/234804/34596997-5b0face0-f227-11e7-87b8-a5c1d3daa243.PNG)

**Comment by oskarkrawczyk** [comment]
Switched embed to light theme.
