### ISSUE TITLE
Syntax highlighting breaks when changing FRAMEWORKS & EXTENSIONS

### ISSUE THREAD

**Issue by MrUpsidown** [jsfiddle/jsfiddle-issues#1127]
# Problem:

- When I change something in FRAMEWORKS & EXTENSIONS (for example, add jQuery, or even switch to No-Library (pure JS)), the JS syntax highlighting goes away.

# Info:

- Tested on macOS 10.13.2 with Chrome 63.0.3239.132 and Safari 11.0.2 (13604.4.7.1.3)

<img src="https://i.imgur.com/rp2nWsc.png">

**Comment by oskarkrawczyk** [comment]
Thanks, fix is in the works.

**Comment by MrUpsidown** [comment]
Perfect, thanks very much!

**Comment by charlietfl** [comment]
There seems to be a regression if this was ever fixed.  Has been broken for many days now

**Comment by oskarkrawczyk** [comment]
**Note to self:** Issue is most likely caused by lang+framework name passed to highlighter instead of just lang.

**Comment by oskarkrawczyk** [comment]
Fixed!
