### ISSUE TITLE
dummy.js is 404'ing

### ISSUE THREAD

**Issue by ChainsawBaby** [jsfiddle/jsfiddle-issues#1128]
The fiddle iframe seems to link to a dummy.js file, that is throwing a 404 error in my console.

![https://i.bratteng.me/PJISShjybx.png](https://i.bratteng.me/PJISShjybx.png)
![https://i.bratteng.me/JZh6gcNeOY.png](https://i.bratteng.me/JZh6gcNeOY.png)

**Comment by oskarkrawczyk** [comment]
No longer should throw a 404
