### ISSUE TITLE
Legal issues : About section, privacy policy, EU/UK cookie law (?) (+ link to this repo to submit a bug report)

### ISSUE THREAD

**Issue by theblackhole** [jsfiddle/jsfiddle-issues#1130]
Hello,

I searched a way to report a bug but there's no such link on the website, neither an about, terms or privacy policy link. You could have legal issues:
- I think you're a registered company (the SSL certificate is registered to JSFiddle, Ltd [GB] and you have ads on your website) so you must display the company info (name, address, etc.)
- I think you collect user data so you must display a Privacy Policy
- If you're using cookies, you must also comply to the EU/UK Cookie Law by displaying the annoying cookie banner.

More info
here : https://www.amityweb.co.uk/blog/is-your-website-legal
and here : https://www.cookielaw.org/blog/2016/6/27/brexit-and-the-cookie-law/

I know this is the boring part of creating a website but after adding that, it will be done once and for all 😉 

(And I suggest taking advantage of this addition to also display a bug report link)

**Comment by oskarkrawczyk** [comment]
@theblackhole thanks, I'll get it done soon :-)

**Comment by oskarkrawczyk** [comment]
- [ ] Privacy Policy
- [x] Terms of Service
- [ ] Cookie info

**Comment by jens-duttke** [comment]
What's the progress here?

It's almost 2 years ago that this issue has been created, and it's still not possible to legally embed JSFiddle in European projects.

On the [Terms of Service](https://jsfiddle.net/terms) page there is a link to "[JSFiddle's Privacy Policy](https://jsfiddle.net/privacy)", which just show `#privacy#` - is that a joke or a bug?

**Comment by oskarkrawczyk** [comment]
Work in progress.

**Comment by oskarkrawczyk** [comment]
Privacy Policy updated.
