### ISSUE TITLE
Automatically executing fiddles in dashboard results in browser crash (out of memory)

### ISSUE THREAD

**Issue by amberjs** [jsfiddle/jsfiddle-issues#1131]
All my fiddles are now automatically executed on opening of the dashboard. 
I have some fiddles that are quite heavy, and this results in a browser crash (**out of memory**) when they are all executed at the same time. 

Now I cannot access some fiddles anymore, because the browser crashes before I can open the right fiddle. 

Is there going to be an option to disable this feature in the near future?

**Comment by oskarkrawczyk** [comment]
@amberjs I need more details. Rendering 10 iframes with fiddles shouldn't cause this at all.

If you could provide links to the fiddles, I'll fork them and see how they behave on my end.

**Comment by amberjs** [comment]
I have 4 pages of fiddles and the crash occurs on the last page. Unfortunately, I cannot get the links for those fiddles, because the browser crashes before it is loaded.

**Comment by oskarkrawczyk** [comment]
Ok, so one or a few fiddles on a single page causes the issue - previous pages don't matter.

Is the page crashing your tab when it's still completely white (nothing at all is rendered) or once fiddles start rendering, in which case you can hit `escape` to stop loading, prevent the crash and get the fiddle links.

Thanks!

**Comment by amberjs** [comment]
Hi, thank you for the quick response. 

It is crashing when the fiddles start rendering. Unfortunately hitting escape does not prevent the crash. I've tried to do this several times. Even spamming the escape button all the time, but no luck.
However, I could quickly scroll down right before the crash and take a screenshot.

![2018-01-09 1](https://user-images.githubusercontent.com/3751341/34744790-a9faaee4-f58e-11e7-87c5-dee12ae69ed6.png)

It seems the problem is with at least these fiddles: 
- http://jsfiddle.net/amberjs/xyg71b80/ 
- http://jsfiddle.net/amberjs/x3jkfzm3
I sometimes use jsFiddle to test certain limits, so I understand completely that this can result in a crash. But I still really want to see the other fiddles on the page.

**Comment by oskarkrawczyk** [comment]
Thanks for the details.

No optimizations will "fix" it, since these fiddles are pretty much meant to strain the CPUs.

I'll leave this ticket open for now, and think about an alternative way of listing fiddles if more people hit this problem with their fiddles.

**Comment by amberjs** [comment]
Ok, I understand. 

For now, I'll just delete my fiddles that are causing the crash. 
For future fiddles that are performance heavy, I'm going to create a button to trigger the methods, so it is not automatically executed anymore on load as a workaround.

**Comment by jckuhl** [comment]
I have a similar issue.  I can't get my dashboard to load because one of my fiddles has an infinite loop in it and I can't get that fiddle deleted.  I've even tried going into the fiddle itself and purposely putting break statements in the code, removing function calls.  So I can't get ANY of my scripts I've saved over the past year because of this one script that I can't keep my dashboard from trying to run.

**Comment by oskarkrawczyk** [comment]
@jckuhl That's unfortunate indeed. I'd suggest installing something that blocks iframes (https://encrypted.google.com/search?hl=en&q=block%20iframe%20chrome%20extension), remove the malicious fiddle.

As mentioned before, JSFiddle works as designed, so I won't change this. That said I'll put a manual (hidden) measure to temporarily disable loading the results panel.

**Comment by oskarkrawczyk** [comment]
It's now possible to add `?disable_render=true` to the end of URL's where fiddles are listed - this will disable the results tab.

**Comment by davidcwilliams** [comment]
> It's now possible to add `?disable_render=true` to the end of URL's where fiddles are listed - this will disable the results tab.

This saved me. I couldn't even delete the problem fiddle before my whole browser would stop responding. Thanks for adding that.
