### ISSUE TITLE
Repositioned layout on Firefox, light theme only

### ISSUE THREAD

**Issue by oskarkrawczyk** [jsfiddle/jsfiddle-issues#1132]
https://twitter.com/0ndras/status/950629214478323713

**Comment by jan-ivar** [comment]
It also blanks out the js, html and css fields, quite debilitating when it happens, as it's impossible to flip back. Avoiding light theme for now.

**Comment by oskarkrawczyk** [comment]
Turns out this is some sort of a layout building issue in Firefox, had to redo a couple of things for it to start behaving.

I'll do some testing on the staging server before pushing it out to production later today.

**Comment by oskarkrawczyk** [comment]
I believe all should work fine now.

If something still broken be sure to clear browser cache.
