### ISSUE TITLE
HTML, JS, CSS dropdowns overlap code when "Enable line wraping" is turned off

### ISSUE THREAD

**Issue by alphestdev** [jsfiddle/jsfiddle-issues#1135]
Also as a consequence, you cannot click to place cursor on the first few lines of code. 
![jsfiddle overlapping bug](https://user-images.githubusercontent.com/32202/34832967-9bcf3842-f6ee-11e7-86e5-f400d301fa90.png)

**Comment by oskarkrawczyk** [comment]
Clear your browser cache please.

**Comment by alphestdev** [comment]
@oskarkrawczyk Cleared. Does not help.
