### ISSUE TITLE
Text in editor windows is not visible on Mobile Safari

### ISSUE THREAD

**Issue by jtara** [jsfiddle/jsfiddle-issues#1136]
Text in editor windows is not visible in Mobile Safari. 

Expected: I can read the text.

What happens: I can't read the text. 

- If I go to an existing Fiddle, there is no text visible at all. There is only a black background.
- If I create a fiddle, or type in an existing one, some very faint, very tiny text is visible which is dark grey in color.
- If I change from dark theme to light theme, then typed text is visible. However, original text is still blank.

Additional information: nice syntax-colored text on a black background on desktop browsers. Content of results window is visible as expected.

Result: jsFiddle is completely unusable on Mobile Safari.

**Comment by oskarkrawczyk** [comment]
We don't support mobile devices. That said the text should at least be visible. 

I'll see what can be done.

**Comment by oskarkrawczyk** [comment]
Enabled CodeMirror on mobile - works good enough.
