### ISSUE TITLE
Is there a set name of the theme used on JSFiddle?

### ISSUE THREAD

**Issue by jrdnbrn** [jsfiddle/jsfiddle-issues#1139]
I want to use it on VS Code

**Comment by oskarkrawczyk** [comment]
No, it's custom

**Comment by JohannesMP** [comment]
Any chance you might distribute it separately some day? I also really like it (the dark theme specifically), and would really like to use it in Sublime Text 3.

If you don't plan on releasing it separately, would you mind if people made their own version of it?

**Comment by oskarkrawczyk** [comment]
@JohannesMP If I end up releasing it, it'll be for Atom, but no plans for now.

You can recreate the theme, no problem. It would be cool if some sort of mention of JSFiddle would be included.
