### ISSUE TITLE
Results panel iframe issue causes scrollbar to appear

### ISSUE THREAD

**Issue by jmarikle** [jsfiddle/jsfiddle-issues#1142]
# Description of the Problem
If the results panel contains a 100% height `body` and `html` tag, a scrollbar appears for the results panel.  If the contents of the results panel is large enough to cause a natural scrollbar, two scrollbars are visible.  This is because `iframe` elements are inline by default.  They therefore are subject to the same whitespace rules as text nodes and other inline tags.  The result is that your iframe (although set to `height:100%`) is slightly taller than 100% of its container's height.  The additional space originates from the default font size and vertical alignment properties.

# My Browser/OS Specs
Chrome 63.0.3239.132 on macOS 10.13.2

# Demos
https://jsfiddle.net/jmarikle/8ty0wh5z/ (Fixed height of 100%. No content.)
https://jsfiddle.net/jmarikle/8ty0wh5z/1 (Auto height. Lots of content.)

# Screen Captures
![Fixed Height](https://i.imgur.com/n7SLRNw.png)
![Content Forced Height](https://i.imgur.com/lKg2Y1E.png)

# Potential Fixes
Adding `display:block` to the `#editor iframe` CSS rule.
Adding `vertical-align:top` to the `#editor iframe` CSS rule.
Adding `font-size:0` to the `#editor .panel-h, #editor .panel-v` CSS rule. (Not recommended, but it demonstrates why the problem occurs).

**Comment by oskarkrawczyk** [comment]
@jmarikle Thanks a lot for the potential fixes, pushed fix to production!
