### ISSUE TITLE
Dragging panel splitters doesn't stop resizing window when mouse button released 

### ISSUE THREAD

**Issue by myanglingnet** [jsfiddle/jsfiddle-issues#1143]
When dragging a panel splitter to resize, the panel continues to resize after I have released the mouse button.  The only way I can break out of resize mode is to change the panel grid view.  This is only happening in Chrome, Edge and FF seem unaffected.  Anyone else experiencing this?

![image](https://user-images.githubusercontent.com/18079923/35008635-f7f0c6aa-fb61-11e7-9c36-8b25fd56ad27.png)

**Comment by myanglingnet** [comment]
I am now observing the same behaviour in Edge.

**Comment by oskarkrawczyk** [comment]
Duplicate #1140
