### ISSUE TITLE
Remove resources button is very hidden; is it being phased out?

### ISSUE THREAD

**Issue by acrylic-origami** [jsfiddle/jsfiddle-issues#1144]
The button to remove external resources doesn't render. Looking at the DOM element that contains it, it looks like it's on its way out, being `display: none`'d with no size (see screencap of the DevTools window below). However, it does still remove the resource when clicked.

<img width="950" alt="jsfiddle" src="https://user-images.githubusercontent.com/13635288/35017389-a76cfcac-faea-11e7-8da4-0922d808df56.png">

I'm not sure if this is a bug report because it seems very deliberate, so I assume my role is to justify a feature request? I use JSFiddle primarily to test various versions of libraries, and it's wasteful at best and conflicting at worst to load multiple versions without cleaning up the ones I'm not interested in. Is there more context behind this?

**Comment by oskarkrawczyk** [comment]
It's a bug, the remove link should appear on hover. Need to fix this.

**Comment by oskarkrawczyk** [comment]
Fixed.

@acrylic-origami thanks for the heads-up!
