### ISSUE TITLE
Cannot save fiddle

### ISSUE THREAD

**Issue by sakopqiu** [jsfiddle/jsfiddle-issues#1145]
A new fiddle can be saved but "update" does not seem to work, every time I try to save sth, the version number is bumped up while the content still remains the old one. 
![image](https://user-images.githubusercontent.com/29721000/35039678-8d21759c-fbb9-11e7-86eb-3bd6edb11c9a.png)

As is shown in the above screenshot, the version number is 18 while the code is at a very crude state, nearly all my code has gone....
This bug is really frustrating, plz help

**Comment by oskarkrawczyk** [comment]
This is not a bug. A specific version needs to be `set as base` (actions in the editor) for it to be shown as the primary in the listing.

**Comment by sakopqiu** [comment]
Thank you for the quick response!
