### ISSUE TITLE
When HTML tab is selected, embedding shows all tabs.

### ISSUE THREAD

**Issue by TurboTobias** [jsfiddle/jsfiddle-issues#1146]
![screen shot 2018-01-18 at 07 25 09](https://user-images.githubusercontent.com/13901140/35083743-e7706de8-fc20-11e7-8d1c-2192ce6adabc.png)
I've only selected the HTML tab, but when embedding on Medium, all tabs are visible.

![screen shot 2018-01-18 at 07 23 39](https://user-images.githubusercontent.com/13901140/35083779-15fd41f4-fc21-11e7-8a44-fdbded2e594f.png)

Also, this might be a separate issue, but when using the script embed, i.e: `jsfiddle.net/ty2s50mt/embed/html`, the code block renders actual code like this:
![screen shot 2018-01-18 at 07 28 50](https://user-images.githubusercontent.com/13901140/35083855-65ae3d34-fc21-11e7-93f9-0ef3539e3a98.png)
I've worked around it by using the iframe embedded code.

**Comment by oskarkrawczyk** [comment]
@TurboTobias so this is a little bit of an inception, but here's an embed example in JSFiddle:

https://jsfiddle.net/oskar/a4Lcvk3x/

As you can see the `iframe` mode presents a single tab.

Not sure what's going on with the `script` mode, need to investigate.

**Comment by oskarkrawczyk** [comment]
`script` mode also seems to work, only not in "inception" mode, like the example above.

**Comment by TurboTobias** [comment]
Sorry, I'm not sure what you mean by inception?

When embedding the link from the iframe from the html, from the link you posted (`https://jsfiddle.net/oskar/hpLhx35t/embedded/html`) it looks like this (on medium)
<img width="747" alt="screen shot 2018-01-19 at 06 48 06" src="https://user-images.githubusercontent.com/13901140/35136711-6bf5a064-fce5-11e7-9315-09a041566ea8.png">

When using all other links, the one you posted and the ones provided by jsfiddle  (`https://jsfiddle.net/oskar/a4Lcvk3x`, `https://jsfiddle.net/oskar/a4Lcvk3x/embedded/html` and `https://jsfiddle.net/oskar/a4Lcvk3x/embed/html`) it looks like this:
<img width="747" alt="screen shot 2018-01-19 at 06 48 06" src="https://user-images.githubusercontent.com/13901140/35136743-9d4f072c-fce5-11e7-98da-8ec5d99266aa.png">

**Comment by Groxan** [comment]
This is still the case. When you embed jsfiddle into medium, tabs settings and color theme are ignored: I see all tabs and light theme...

**Comment by daledesilva** [comment]
I can confirm that the embed issue is still the case when posting to medium. (all tabs and light mode always appear).
@TurboTobias , The _inception_ comment was just a reference to the movie inception and to the idea of putting a jsfiddle inside another jsfiddle.
