### ISSUE TITLE
🐞 Light theme doesn't persist after closing the browser

### ISSUE THREAD

**Issue by dwiyatci** [jsfiddle/jsfiddle-issues#1152]
*Steps to reproduce*
- Open https://jsfiddle.net and login.
- Switch to light theme by toggling the switch button.
- Close the browser.
- Open the browser again and go to https://jsfiddle.net.

*Actual*
- The theme goes back to dark (although the toggle switch button is in the "Light theme" state).

*Expected*
- The light theme should persist.

*Screenshot*
![jsfiddle net_](https://user-images.githubusercontent.com/4405796/35520063-4034115c-0516-11e8-87ca-07dbe459b690.png)

**Comment by oskarkrawczyk** [comment]
While I cannot replicate this behavior on any browser, I think it might have something to do with theme cookies being stored for session.

Will look into this.

**Comment by oskarkrawczyk** [comment]
Added a potential fix. Let me know if you encounter this problem again.

**Comment by dwiyatci** [comment]
Great, thanks! I'll give it a spin then :pray:
