### ISSUE TITLE
strings can get rendered by mistake

### ISSUE THREAD

**Issue by dpatterson-aio** [jsfiddle/jsfiddle-issues#1154]
Script tags in strings don't seem to get escaped the same way as other tags, which is probably a security concern. i.e., go to https://jsfiddle.net/reactjs/69z2wepo/ and run this:
```javascript
class Hello extends React.Component {
  render() {
    return <div>Hello {this.props.name}</div>;
  }
}

ReactDOM.render(
  <Hello name="<script>oops</script>" />,
  document.getElementById('container')
);
```

if you change the `script` to `div` or something, it gets escaped ok.

**Comment by nwalters512** [comment]
Just ran into this problem myself. Here's an even simpler working example: https://jsfiddle.net/dm5dhwa7/

**Comment by samsch** [comment]
Still an issue, can this be re-opened?
