### ISSUE TITLE
Randomly forgets the no dark theme option

### ISSUE THREAD

**Issue by ferrybig** [jsfiddle/jsfiddle-issues#1156]
SOmetimes, when jsfiddle loads, it defaults to the dark theme, even when light theme is selected in the options in the right click. To fix tiss till the next time, you need to open your profile in the upper right, click the checkbox 1 time to make it dark again, and then again to make it white.

This is affecting my usage of jsfiddle, as the only reason I used jsfiddle over other editors is the default white theme, but as long as this bug is there, I have to search for a different editor that doesn't burn my eyes

**Comment by oskarkrawczyk** [comment]
As far as I know the issue you're referring to was fixed here #1152 – you might want to refresh cache so JS fully reloads, and cookie can be stored for 200 days instead of just the session.
