### ISSUE TITLE
Ability to disable linting

### ISSUE THREAD

**Issue by oskarkrawczyk** [jsfiddle/jsfiddle-issues#1157]
At the moment linting is always enabled for JS, CSS, HTML – it would be good to have the option to disable it.

**Comment by dfsq** [comment]
I don't know if it's related but whenever I use `const something = ''` I get warnings like `const is available in ES6 (use esversion: 6)`. Without clear instructions how to actually use it. I also don't see hot it can be disabled.

**Comment by dfsq** [comment]
Well I don't want to use `Babel + JSX` or `JavaScript 1.7` it's simply not needed to most of the things as it's already in available in Chrome. The point is how to disable those warnings, which is same warnings you get with linting, like `missing semicolons`.

**Comment by oskarkrawczyk** [comment]
I have plans on adding the ability to disable linting.

**Comment by oskarkrawczyk** [comment]
It's now possible to disable linting.

![2018-02-01 14 26 06](https://user-images.githubusercontent.com/34213/35681008-57ed0ba8-075c-11e8-9e53-ac0603d984b7.gif)

**Comment by john-harding** [comment]
Was this renamed to `code validation`?  If yes, disabling it no longer works.  If not, please add this back.
