### ISSUE TITLE
fork and update seem to be broken

### ISSUE THREAD

**Issue by sillyslux** [jsfiddle/jsfiddle-issues#1159]
I was trying to edit https://jsfiddle.net/jquarks/x83s39jd/20/ as anonymous user just now, both, fork and update button only change the url to https://jsfiddle.net/ but leave editor contents as they are. Same behaviour before and after changing some code. Disabling adblocker and clearing localStorage had no effect.
On a side note, there's a 404 for https://jsfiddle.net/css/single-page.css?update_30_01_2018_2

**Comment by oskarkrawczyk** [comment]
From what I see everything works as it always had:

- add code
- hit `save`/`update` or `fork`
- url changes to have the fliddle slug (+ version if updating)
- refresh page
- previously saved/updated/forked code appears correctly

**Comment by sillyslux** [comment]
Well, doesn't work for me, but my computer is known to behave strange sometimes...
besides changing the url, `window.history.length` increments and i get error messages in the browser console `GET https://jsfiddle.net/embedded/ 404 ()` as well as for the css file i've mentioned.

**Comment by oskarkrawczyk** [comment]
Which browser (and version) are you using?

**Comment by sillyslux** [comment]
I've tried Chromium Version 63.0.3239.84 (Developer Build) built on Debian 9.3, running on Debian 9.0 (64-bit) and Firefox ESR 45.8.0

**Comment by zalun** [comment]
It was happening to me as well, but I've force-reloaded the site and fork worked as well as the update.
Should author info remain on the page after the anonymous user forked it?

**Comment by oskarkrawczyk** [comment]
> Should author info remain on the page after the anonymous user forked it?

I think so, it's a clone of the original - including all meta

**Comment by sillyslux** [comment]
you can't leave the original author as the owner once it's forked by somebody else

**Comment by oskarkrawczyk** [comment]
Refreshing cache solves the problem. Closing.

**Comment by brigand** [comment]
Tried in chrome and firefox (osx), did cmd-shift-r to skip cache, tried in incognitio, no luck.
