### ISSUE TITLE
support token 1fr for css-grid

### ISSUE THREAD

**Issue by hunboy** [jsfiddle/jsfiddle-issues#1161]
`grid-template-columns: 1fr;`

throws an error, says unexpected token in the css panel

**Comment by oskarkrawczyk** [comment]
Created an issue https://github.com/CSSLint/csslint/issues/734, seems like a bug in the parser.

**Comment by jwhitleybb** [comment]
Any update on this bug?

**Comment by oskarkrawczyk** [comment]
@jwhitleybb see my comment above. I don't see a way of fixing it, since the library code implies that it should work.

**Comment by tommedema** [comment]
JSFiddle is mostly not usable for people using CSS grid

**Comment by oskarkrawczyk** [comment]
Added a maintainer linter that solves this problem. Will deploy this week.

**Comment by jxt-martin** [comment]
> Added a maintainer linter that solves this problem. Will deploy this week.

Where can I find and get this?
I have latest version (1.0.5) and have this error still. Through both Visual Studio and my grunt tasks.
