### ISSUE TITLE
no collaboration connection

### ISSUE THREAD

**Issue by davidsgrogan** [jsfiddle/jsfiddle-issues#1165]
Togetherjs down? Friend going to collab link doesn't connect to original fiddle (no collaboration dock shows up at all on their end). Their JS console is empty.

**Comment by oskarkrawczyk** [comment]
I think I know what's wrong, will fix tomorrow morning

**Comment by oskarkrawczyk** [comment]
Note to self: `together.js` is no longer loaded along with the page, but it probably should when the URL contains info that collaboration needs to be used.

**Comment by oskarkrawczyk** [comment]
Fixed
