### ISSUE TITLE
Favicon is MIA

### ISSUE THREAD

**Issue by oskarkrawczyk** [jsfiddle/jsfiddle-issues#1166]
For some reason it's throwing a 404 even though the files is on the server.

**Comment by coolreader18** [comment]
Bump

**Comment by henser** [comment]
Quite annoying bug for multi-tab users and very easy fix. The favicon tag `<link rel="icon" href="/favicon.png"> `should have the 'img' folder path inserted to it like `<link rel="icon" href="/img/favicon.png">`
