### ISSUE TITLE
Typescript not working?

### ISSUE THREAD

**Issue by mindplay-dk** [jsfiddle/jsfiddle-issues#1167]
Can't select Typescript from the dropdown anymore 😢 

![typescript-bug](https://user-images.githubusercontent.com/103348/36107253-c208f2ca-1019-11e8-903d-9f3cba728589.gif)

**Comment by oskarkrawczyk** [comment]
Thanks for reporting, will fix the picker soon

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by mindplay-dk** [comment]
> Fixed

Confirmed, thanks 😄👍

**Comment by mindplay-dk** [comment]
@oskarkrawczyk this is broken again - selecting "Babel + JSX" from the drop-down (in a new fiddle) just keeps highlighting errors for JSX expressions, until you save the fiddle and reload the entire page.
