### ISSUE TITLE
White theme not working on dashboard page

### ISSUE THREAD

**Issue by ferrybig** [jsfiddle/jsfiddle-issues#1168]
At the moment, when you configured jsfiddle to use a white theme, it doesn't apply to https://jsfiddle.net/user/dashboard/

**Comment by oskarkrawczyk** [comment]
Theme switcher works on the editor only - this is by design.

Maintaining two theme versions is an overhead enough for the editor alone.

**Comment by ferrybig** [comment]
Is there a reason why the default changed from the easy to read black on white, to the eyes straining white on black?

**Comment by oskarkrawczyk** [comment]
Yes, according to the poll I've made, most users prefer using a dark theme.
