### ISSUE TITLE
JSHint doesn't recognize async and await keywords

### ISSUE THREAD

**Issue by dotnetCarpenter** [jsfiddle/jsfiddle-issues#1170]
**The linter used on jsfiddle does not recognize `async` and `await` keywords and gives up parsing the js.**

I don't know if the linter is bundled with the [monaco editor](https://microsoft.github.io/monaco-editor/index.html) or if it's based on the chosen language setting. But the latest version (0.10.1) of the monaco editor supports both keywords.

Here is an example of using **Babel + JSX** (which correctly transpile `async` functions to a generator): https://jsfiddle.net/bpb0fbc2/135/ - line 121

**Comment by oskarkrawczyk** [comment]
Unfortunately the newest JSHint doesn't support these keywords.

Pinged them to see if they plan od patching this anytime soon – https://github.com/jshint/jshint/issues/2604#issuecomment-366334331

If not, I'll probably replace JSHint with ESLint.

**Comment by oskarkrawczyk** [comment]
ESLint also doesn't support `async/await` – not seeing a viable solution for the moment.

**Comment by dotnetCarpenter** [comment]
Since async function support is coming to jshint, I guess you're right. Just wait for the next minor release.

**Comment by damianb** [comment]
Not sure what you mean about ESLint not supporting async/await; it entirely does, but the parser needs configured for the correct JS version.

https://github.com/eslint/eslint/issues/8366#issuecomment-326776306

**Comment by slikts** [comment]
Having a linter that does not support standard syntax and throws spurious errors is worse than nothing. If you're not going to fix it, at least disable it by default.

**Comment by dotnetCarpenter** [comment]
ping @oskarkrawczyk to try out [ESLint](https://github.com/eslint/eslint)

The configuration needs ecmaVersion 2017 for `async`/ `await`.

```json
{
    "parserOptions": {
        "ecmaVersion": 2017
    }
}
```

**Comment by slikts** [comment]
The current version is ES2018, though.

**Comment by oskarkrawczyk** [comment]
@dotnetCarpenter I'll try this out (and move to JSHint) if JSLint is not going to fix their `async/await` issue this month.

**Comment by oskarkrawczyk** [comment]
Did some preliminary research and I see no way of getting ESLint to work on the browser side – the ESLint team does this on their website, but a) they do not support that, b) I can't figure out a way to replicate what they're doing there, c) as they say on in many issues regarding to running ESLint in the browser, they do not support that.

If anyone ends up figuring out how to run it in the browser, I'll happily take some hints and try integrating it into JSFiddle again.

**Comment by slikts** [comment]
Turning off the broken linter doesn't even work:

![image](https://user-images.githubusercontent.com/137872/46925229-7df64080-d033-11e8-8976-95e8acfbec14.png)

It only turns off after toggling the option, and then is back on for new fiddles.

**Comment by badfun** [comment]
ended up here after much frustration thinking there was something wrong with my code.

**Comment by elpeleq42** [comment]
Can confirm the problem still exists.
Even trying "experimental: [asyncawait, asyncreqawait]" doesn't work

**Comment by oskarkrawczyk** [comment]
As of yet JSHint doesn't support these keywords == issue in JSFiddle remains

**Comment by slikts** [comment]
jshint is a badly dated tool that shouldn't be used.

**Comment by slikts** [comment]
To elaborate, the issue is the choice to rely on an outdated, unmaintained tool. jshint doesn't support features that have been in the browsers for years; it's bound to cause more confusion for learners than it's worth.

**Comment by oskarkrawczyk** [comment]
Until a new #1394 is implemented and new linters are added, a warning banner will show notifying that linter is incorrect sometimes and it can be turned off.

<img width="632" alt="screen shot 2019-01-04 at 17 36 13" src="https://user-images.githubusercontent.com/34213/50699148-4d78de00-1047-11e9-996a-af660c65d0ef.png">

**Comment by oskarkrawczyk** [comment]
Also, fixed Linter not staying off when it should.

**Comment by oskarkrawczyk** [comment]
JSHint was updated to 2.10.0 and now recognizes ecma8 features.
