### ISSUE TITLE
My JSfiddle account won't load

### ISSUE THREAD

**Issue by Jesta1972** [jsfiddle/jsfiddle-issues#1174]
So today I was using JSfiddle in a javascript class that I am taking. I was entering the instructors code and clicked on run. The code did not work as it was supposed to. In the code was an alert box that made a pop up that should have only triggered 10 times. but mine kept on going in and infinite loop, I was at 75-80. The only way that I could get rid of it seemed to be to force quit Chrome. Now every time I log in I get a spinning wheel of death and then a message telling my the pages are unresponsive and I need to click to either wait or exit the page. I am tried clearing out any saved data such as history and cache.  If I attempt to use a new window or tab those windows are unresponsive as well. I have tried using Safari, FireFox and Chrome and I get the same results. Not sure what to do at this point as I have a lot of code that I have saved on my account that i need access to for the class that I am taking. Not sure how to kill whatever is messing up the page from loading. Hopefully you will have some answers or some troubleshooting suggestions, Thanks

# Note on existing issues:

- ‼️ Known and minor issues will **not be addressed and most likely will be closed**
- ‼️ More info in README.md

# Library update request

- Be sure your library (in the correct version) exists on cdnjs.org

**Comment by oskarkrawczyk** [comment]
Please see `Common questions` for the solution.
