### ISSUE TITLE
Error when clicking on left nav menu items

### ISSUE THREAD

**Issue by marcelobart** [jsfiddle/jsfiddle-issues#1177]
Hi, I've receiving this error when I try to click in any of left nav menu items.

Uncaught TypeError: Cannot read property 'call' of undefined at HTMLHeadingElement.<anonymous> (_dist-editor.js?update_19_02_2018_1:1)

This happened after the update of settings redesign.

**Comment by oskarkrawczyk** [comment]
@marcelobart Can you try refreshing browser cache?

**Comment by marcelobart** [comment]
Does not fix. :/

In firefox, the error that appear is: TypeError: self.showItem is undefined - _dist-editor.js:1:1594705

**Comment by oskarkrawczyk** [comment]
@marcelobart Fixed. Thanks for the heads-up!

**Comment by marcelobart** [comment]
Thanks so much! Tested here and its fixed!
