### ISSUE TITLE
Idea: opportunity hide Fiddle meta/Resources/etc panel

### ISSUE THREAD

**Issue by nibytes** [jsfiddle/jsfiddle-issues#1178]
subj
![default](https://user-images.githubusercontent.com/15169344/36399039-bd2fc6de-15d2-11e8-8f63-be52b54682d8.png)

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap).

**Comment by roostercrab** [comment]
I'd like to upvote this idea, it is incredibly annoying to view in half screen and makes the site unusable
