### ISSUE TITLE
Text in the update mouseover dialog is hard to read because of the contrast

### ISSUE THREAD

**Issue by ferrybig** [jsfiddle/jsfiddle-issues#1179]
The contrast on the update mouseover dialog section is too low and this is making it hard to read.
![chrome_2018-02-20_11-10-44](https://user-images.githubusercontent.com/1576684/36418595-99eabf1e-162f-11e8-9651-3bb42ac0a26e.png)

**Comment by oskarkrawczyk** [comment]
Yeah, need to fix the text in the light theme.
