### ISSUE TITLE
firefox issue with JSfiddle

### ISSUE THREAD

**Issue by wayneker18** [jsfiddle/jsfiddle-issues#1181]
could you have a look at this issue for me please. when i mouse over the Run-Update-Fork etc menu, i get a blank area pop up next to the HTML/JS windows.

I am using the latest version of firefox

this doesnt happen if i use chrome and only recently started happening.

https://youtu.be/_RIFprWuMOs

TIA

wayne

**Comment by oskarkrawczyk** [comment]
@wayneker18 Does refreshing browser cache for jsfiddle.net help?

**Comment by wayneker18** [comment]
no it doesnt...

**Comment by oskarkrawczyk** [comment]
@wayneker18 can you try incognito or a private window? Any change?

Unfortunately I cannot replicate this in Firefox (58.0.2), nor any other browser.

**Comment by wayneker18** [comment]
just noticed that my firefox isnt set for auto update, was on version 48.0.2,,, just upgrading now and will keep informed

**Comment by wayneker18** [comment]
i am on 58.0.2 and all is working ok now... dont think it liked version 48. dont know why it wasnt set to auto update
