### ISSUE TITLE
"Only auto-run validating code" Option not working properly

### ISSUE THREAD

**Issue by mintyknight** [jsfiddle/jsfiddle-issues#1182]
"Only auto-run validating code" Option checks previous validation result, not current validation result.

Reproduce steps:
1. open a fresh jsfiddle page.
2. turn on "Auto-run code (beta)" and "Only auto-run validating code".
3. open browser's dev tools console.
4. copy&paste `console.log('auto-run');` into js panel (without double quotes).
Expectation === Observation: console output "auto-run".
5. change `console.log('auto-run');` to `con sole.log('auto-run');` by inserting one space.
Expectation: 1. validation error show up, 2. no console output.
Observation: 1. validation error show up, 2. console output error `Uncaught SyntaxError: Unexpected identifier`.
6. change `con sole.log('auto-run');` back to `console.log('auto-run');` by removing the extra space.
Expectation: 1. validation error disappear, 2. console output "auto-run".
Observation: 1. validation error disappear, 2. no console output.

BTW, you might want to change the text from "Only auto-run validating code" to "Only auto-run validated code" and move it right below "Auto-run code (beta)", since it changes how auto-run works.

**Comment by dwiyatci** [comment]
I was almost creating a new issue regarding the wording, i.e. "Only auto-run validating code" ➡️  "Only auto-run validated code". I think the latter reads better and less confusing ;)
