### ISSUE TITLE
"Auto-run code (beta)" in not working without "Only auto-run validating code"

### ISSUE THREAD

**Issue by kongyuyu** [jsfiddle/jsfiddle-issues#1183]
"Auto-run code (beta)" in not working at all if "Only auto-run validating code" is not checked.

Reproduce steps:
1. open a fresh jsfiddle page.
2. turn on "Auto-run code (beta)" and make sure "Only auto-run validating code" is off.
3. open browser's dev tools console.
4. start typing "something", then stop.
Expectation: console output error "Uncaught ReferenceError: something is not defined".
Observation: no console output.
5. type "console.log('auto-run');" (no quotes).
Expectation: console output "auto-run".
Observation: no console output.

**Comment by oskarkrawczyk** [comment]
Fixed.

@kongyuyu thanks for the details.
