### ISSUE TITLE
Ethereum trade scam jsfiddles

### ISSUE THREAD

**Issue by th0mk** [jsfiddle/jsfiddle-issues#1184]
Reporting 2 scam jsfiddles:

https://jsfiddle.net/rLhqwozg/show/
https://jsfiddle.net/11kfwr8k/show/

These are linked underneath tweets from Elon Musk, and quite a few people are falling for it according to Etherscan.

**Comment by oskarkrawczyk** [comment]
@th0mk thanks for the heads-up, fiddles removed.

**Comment by th0mk** [comment]
2 more:

https://jsfiddle.net/0t9k9gpa/show/
https://jsfiddle.net/61ksLkn6/show/

**Comment by oskarkrawczyk** [comment]
Removed

**Comment by th0mk** [comment]
https://jsfiddle.net/r70q6n2q/3/show/
https://jsfiddle.net/5j1r4gw9/22/show/
https://jsfiddle.net/jeka01/9o5oqp9d/87/View/
https://jsfiddle.net/ethergiveaway/bj0cbzfw/show/
https://jsfiddle.net/binance/9o5oqp9d/6/show/
https://jsfiddle.net/c957k6hx/7/show/

Seems like they're moving to github pages now. I'll keep posting more as i spot them. 
They all seem to be using the same template.

**Comment by oskarkrawczyk** [comment]
Removed fiddles and accounts

**Comment by th0mk** [comment]
https://jsfiddle.net/ethertrx/13gjazhf/show/
https://jsfiddle.net/ethaddresse/h1xxy3gc/1/show/
https://jsfiddle.net/etherscan_io/t1gvczfh/1/show/
https://jsfiddle.net/r6gcqzty/2/show/
https://jsfiddle.net/k20t0bqg/show/

**Comment by oskarkrawczyk** [comment]
🔥 fiddles and accounts

**Comment by th0mk** [comment]
https://jsfiddle.net/ethnetwork/orwqs4dc/show/
https://jsfiddle.net/hf3v9kn0/1/show/
https://jsfiddle.net/xh0zkbjf/20/show/
https://jsfiddle.net/yz8j9gvs/show/
https://jsfiddle.net/thedonationpage/62xu4n9t/6/show/
https://jsfiddle.net/zhihang053/a2f1hqnf/1/embedded/result/#Result
https://jsfiddle.net/gcy0w7e9/58/embedded/result/#Result

Most of the scammers are switching to different sites now. That's a good thing for you, but it also kinda sucks since the other sites don't respond at all, and you take them down as quickly as possible.
I've seen multiple addresses from scammers with over $10k and one even has $50k. Insane.

**Comment by oskarkrawczyk** [comment]
🔥 fiddles and accounts

How do people fall for that scam is beyond me, especially that in theory people that deal with crypto should at least be aware of what scam is.

**Comment by oskarkrawczyk** [comment]
- https://jsfiddle.net/8d9k9k8e/1/

**Comment by oas** [comment]
https://jsfiddle.net/ez57vq9s/7/show/

**Comment by oskarkrawczyk** [comment]
Removed

**Comment by oskarkrawczyk** [comment]
Opened this ticket so everyone can be more informed about spammers posting on ethereum scams on JSFiddle.

**Comment by oskarkrawczyk** [comment]
Added some banning and filtering on the backend, should make it more difficult to post that kind of scam.

**Comment by oskarkrawczyk** [comment]
Closing (for now).
