### ISSUE TITLE
There is no possibility use username less than 10 chars for login.

### ISSUE THREAD

**Issue by Bershik** [jsfiddle/jsfiddle-issues#1185]
Username less than 10 chars in login form returns error:

> Ensure this value has at least 10 characters (it has 7).

and there no possibility to change it.

**Reproduce steps:**

1. open a fresh jsfiddle page.
2. click Sign in in top left corner.
3. type username less than 10 chars and pass.
4. press Log in button.

**Expectation**: normal login process or, in case of change rules for username, button/link for change username.
**Observation**: there is no any way to login or change username.

**Comment by oskarkrawczyk** [comment]
@Bershik use your e-mail as the input states.

**Comment by Bershik** [comment]
@oskarkrawczyk Login with email works. Thanks for you replay.
