### ISSUE TITLE
Please update CoffeeScript

### ISSUE THREAD

**Issue by GeoffreyBooth** [jsfiddle/jsfiddle-issues#1186]
The current version is 2.2.2: http://coffeescript.org/

**Comment by oskarkrawczyk** [comment]
Added the `2.x` branch as a new option in the `Languages` dropdown.

Can't just update `1.x` since they're incompatible.

**Comment by GeoffreyBooth** [comment]
Fair enough. Thanks for the quick update!

**Comment by GeoffreyBooth** [comment]
Are you sure CoffeeScript 2 is loading in the results pane? See https://jsfiddle.net/GeoffreyBooth/bnmt6caj/

It’s the example from http://coffeescript.org/#async-functions; when run, it should cause your (modern) browser to say “3, 2, 1, blastoff!”. Currently for me it says “3“ and stops, because the version of CoffeeScript compiling the code still seems to be 1.12.5, loaded via https://fiddle.jshell.net/js/coffeescript/coffeescript.js. Maybe this is just a caching issue?

You might also want to upgrade CoffeeScript v1 to 1.12.7, that was the last 1.x version of CoffeeScript.

**Comment by oskarkrawczyk** [comment]
Looks like something is indeed wrong. Will look into this.

**Comment by oskarkrawczyk** [comment]
Fixed, although the options in the dropdown have to be out of order for now.

There's also an issue with syntax highlighting – #1188
