### ISSUE TITLE
Feature Request: console.clear() on each run

### ISSUE THREAD

**Issue by marceloadsj** [jsfiddle/jsfiddle-issues#1189]
Hi, can you put a config to auto run a console.clear() in each run?

I do not know if it's just me but, the first line of my js box is always 'console.clear();'

What do you think?

**Comment by oskarkrawczyk** [comment]
Sounds good. Will think about how can this be implemented.

**Comment by marceloadsj** [comment]
You're awesome. :D tks!

**Comment by oskarkrawczyk** [comment]
Added

**Comment by marceloadsj** [comment]
Tks so much! 👍 😄
