### ISSUE TITLE
Unicode characters with codepoints > FFFF

### ISSUE THREAD

**Issue by Andre-Schappo** [jsfiddle/jsfiddle-issues#1190]
When I am not signed in I can use Unicode chars > FFFF, no problem. I can update and run javascript, html, css with Unicode chars > FFFF, no problem.

But... when I am signed in, any use of Unicode chars > FFFF, results in "Error 500". I then have to resort to using NCRs.

thank you

André Schappo

**Comment by oskarkrawczyk** [comment]
@Andre-Schappo can you provide a test case?

**Comment by Andre-Schappo** [comment]
@oskarkrawczyk Yes indeed. [https://jsfiddle.net/coas/h7ux52dL](url) works fine if I am not signed in but I get Error 500 when signed in.

**Comment by oskarkrawczyk** [comment]
Interesting, I get not 500, no matter if I'm signed in or not
<img width="704" alt="screen shot 2018-02-26 at 12 40 30" src="https://user-images.githubusercontent.com/34213/36668673-5b54dd1c-1af2-11e8-9e13-24b1222aa820.png">

Will keep this ticket open for now.

**Comment by Andre-Schappo** [comment]
@oskarkrawczyk When I sign in and select https://jsfiddle.net/coas/h7ux52dL I also see the Emoji displayed fine but when I click Run I get the Error 500

I have just tested from Linux, just in case, and I still have the same problem.

**Comment by oskarkrawczyk** [comment]
@Andre-Schappo Ah, ok, thanks. The issue is more complicated that it seems, it'll take some time before it's fixed.

**Comment by Andre-Schappo** [comment]
@oskarkrawczyk ok, thank you

**Comment by godders** [comment]
Just hit this myself. This emoji causes 500s: 🎛️, this one does not: ⚙️.

**Comment by Andre-Schappo** [comment]
@godders Ah😀 That is because 🎛️ has codepoint >FFFF but ⚙️ has codepoint <FFFF

For more Emoji with codepoint <= FFFF see http://schappo.blogspot.co.uk/2017/11/computer-science-internationalization_65.html

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by Andre-Schappo** [comment]
@oskarkrawczyk Excellent! thank you very much
