### ISSUE TITLE
Choosing JS + Knockout 3.0.0 fails to load the knockout script

### ISSUE THREAD

**Issue by flmbray** [jsfiddle/jsfiddle-issues#1192]
The default link for JS + Knockout 3.0.0 is currently:
https://knockoutjs.com/downloads/knockout-3.0.0.js

But jsfiddle fails to load this script.  When trying to load this script directly in Chrome, it reports:
GET https://knockoutjs.com/downloads/knockout-3.0.0.js net::ERR_CERT_COMMON_NAME_INVALID
This server could not prove that it is knockoutjs.com; its security certificate is from *.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

This doesn't happen for KO 2.2.1, since it gets loaded from CDNJS.  Setting the fiddle to 'No-library (pure js)' and manually linking the KO 3.0.0 from CDNJS works.

Example: https://jsfiddle.net/flmbray/b3r76vvp/  (it's set to load KO 3.0.0...  change to KO 2.2.1 and it works).

**Comment by oskarkrawczyk** [comment]
✅ Fixed. Thanks for reporting!
