### ISSUE TITLE
Indenting does not respect indentation setting.

### ISSUE THREAD

**Issue by ryanpcmcquen** [jsfiddle/jsfiddle-issues#1193]
With indentation set to 4 spaces, hitting <kbd>Tab</kbd> still indents 2 spaces.

**Comment by rinodrummer** [comment]
I have the same problem.

**Comment by TorsteinHonsi** [comment]
+1

**Comment by oskarkrawczyk** [comment]
What browser are you guys using?

As far as I see the indentation works fine

![2018-03-08 11 04 28](https://user-images.githubusercontent.com/34213/37145208-970f1b1c-22c0-11e8-8c22-132e4360465e.gif)

**Comment by TorsteinHonsi** [comment]
I'm using Chrome. In the capture below, you can see the problem when I create new object literal and hit tab. Hitting tab indents 2 spaces where I expected 4.

![jsfiddle-indenting](https://user-images.githubusercontent.com/227836/37148454-c6b83330-22ca-11e8-9efa-11f1ca86cff8.gif)

**Comment by oskarkrawczyk** [comment]
Thanks @TorsteinHonsi, I can reproduce it now

**Comment by oskarkrawczyk** [comment]
Ok, found the issue, should be fine now.

**Comment by mindplay-dk** [comment]
This still isn't working for me - it's still inserting TABs.

**Comment by mindplay-dk** [comment]
Tried clearing the cache, which didn't help.

Changing the tab value didn't fix it.

However, changing the setting to use tabs and then back again seemed to fix it - I think there's a problem with fiddles for which this setting has already been persisted?

**Comment by mindplay-dk** [comment]
Or perhaps the problem is with files already containing tabs?

I ran my code through `prettier` to get rid of all the tabs.

**Comment by mindplay-dk** [comment]
Er, nope, sorry - still broken. It just reverted back to tabs for the same fiddle that seemed to be working.
