### ISSUE TITLE
Login says my username needs to be 10 characters and won't let me login with my existing 9 character userID

### ISSUE THREAD

**Issue by jfriend00** [jsfiddle/jsfiddle-issues#1194]
When I try to login to jsFiddle on Mar. 1 2018, it tells me that my user name is not long enough, that it needs to be 10 characters and is only 9.  But, I'm not creating a new account.  I'm trying to login with a userID that I've had for many years.

As it turns out, you can bypass the error by adding a space onto the end of my existing login name and then it lets me login, but it was somewhat by accident that I discovered that - most people will just think they are locked out or that they have to create a new account and lose access to all their existing fiddles.

**Comment by oskarkrawczyk** [comment]
There are a few issues that need to be sorted out, but as the login form states, to log in user should user email+password - we left the ability to use username just for convenience.

**Comment by jfriend00** [comment]
Seriously.  So a 10 character userID can be used, but not a 9 character userID?  And you think this is not an issue?  Lots of us use password managers.  They auto-filll what was previously used.  So, you don't care that any user that was previously using a 9 character or less user name will just have login fail?
