### ISSUE TITLE
Set attributes on the script tag

### ISSUE THREAD

**Issue by coolreader18** [jsfiddle/jsfiddle-issues#1197]
Currently there is no official way to set attributes on the script tag, be it `type=module` or `data` attributes for a framework. You can do it by doing something like this:
```js
//]]></script><script attributes data-foo=bar type=custom>//<![CDATA[
console.log("hello");
//code
```
without wrapping it for window.onload (or start with a `}` and put a `{` after the opening script tag for onload, but that's kinda pointless, it doesn't wait for load as it's in a different script tag).

However, it'd be a lot nicer if you'd be able to set attributes from the JavaScript dropdown menu, maybe below the framework script attributes input box. Anything input into that box should be put into the script tag as such:
```html
<script $ATTRS type="text/javascript">
```
This ensures that an alternate `type` attribute would take effect if added.

This would be helpful, and I know for one that it would make developing PaperScript easier, as evidenced by the [docs](http://doc.jsfiddle.net/use/hacks.html#working-with-paperscript).

**Comment by dguzzo** [comment]
Hi, I was just poking around with JSFiddle for the first time in forever, and happened to notice this in the language/framework dropdown:

![screen shot 2018-05-31 at 12 53 17 pm](https://user-images.githubusercontent.com/571624/40805122-232eae16-64d2-11e8-84b9-68dc5e5cd477.png)

Is this not what you need?

**Comment by coolreader18** [comment]
That only applies to the script tag used to load the framework, i.e. React or jQuery. I was looking for a way to add attributes to the script tag containing the JS the user puts in to the panel.

**Comment by dguzzo** [comment]
Ah, gotcha—sorry I couldn't be helpful 😎

**Comment by justinbmeyer** [comment]
@coolreader18 did you ever figure anything like this out?

**Comment by coolreader18** [comment]
Jsfiddle isn't open source and I don't work on it, @oskarkrawczyk is who you're looking for.

**Comment by Link2Twenty** [comment]
Anyone that feels this would be helpful should add a vote here https://trello.com/c/r0HnI5vf/73-ability-to-change-js-panel-to-typemodule as it means the team are more likely to look at it.

**Comment by oncletom** [comment]
I added a vote. I have to put my code in the HTML panel to make my ESM imports to work.

**Comment by TorsteinHonsi** [comment]
I can see from Trello that this is implemented. But how do I enable it?
