### ISSUE TITLE
Q: support files, how to use/view them

### ISSUE THREAD

**Issue by suntong** [jsfiddle/jsfiddle-issues#1198]
jsfiddle.net is so useful that it is always my favorite. However, for so many years, I think it can *only* handle .html, .css and .js code, which is obviously from the web GUI. 

But today, I found that you can actually make use of support files in the .html  / .js code, for example, a `.csv` file for supporting data -- 

http://jsfiddle.net/flexmonster/08wf6fgL/

      report: {
        dataSource: {
          dataSourceType: "csv",
          filename: "data/data.csv"
        },

Note the above "`filename: "data/data.csv"`"? How can I view its content? If I forked that jsfiddle to my own, how can I replace that `data/data.csv` file?

**Comment by oskarkrawczyk** [comment]
This more of a generic JavaScript question, but I'll answer it anyway. 

`data/data.csv` is fetched asynchronously from `https://cdn.flexmonster.com/2.4/` - notice the `componentFolder` param. The `data.csv` file does not reside on JSFiddle servers.

**Comment by suntong** [comment]
Oh, thanks a lot!
