### ISSUE TITLE
Cannot log in with current username

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#1199]
I have a username which is not an email address, but the new login requires a valid email address. I hacked passed the validation by removing the `type="email"` attribute from the `input`. Inside my profile page I can't find a way to add an email address login to my account.

**Comment by TorsteinHonsi** [comment]
![skjermbilde 2018-03-07 kl 08 55 50](https://user-images.githubusercontent.com/227836/37080453-95c56124-21e6-11e8-8ae6-8a6344dce31b.png)

**Comment by oskarkrawczyk** [comment]
The switch to email is by design.

As to setting/changing email:

<img width="795" alt="screen shot 2018-03-07 at 09 06 48" src="https://user-images.githubusercontent.com/34213/37080550-f778c762-21e6-11e8-994b-f42478b43211.png">

**Comment by oskarkrawczyk** [comment]
Btw. there in fact is an email associated with your account - `***@highsoft/com`

**Comment by TorsteinHonsi** [comment]
Oh, thanks, I was looking for a place to edit my profile, but didn't find it. I think the dimmed color on the "Settings" and "Logout" menu items here indicate that the links are not active:

![skjermbilde 2018-03-08 kl 09 19 33](https://user-images.githubusercontent.com/227836/37140457-0e58213c-22b2-11e8-990f-9bb03061ef5a.png)
