### ISSUE TITLE
JSX highlighting is broken

### ISSUE THREAD

**Issue by mindplay-dk** [jsfiddle/jsfiddle-issues#1200]
Looks like inlining string interpolations in JSX breaks the syntax highlighter.

![image](https://user-images.githubusercontent.com/103348/37200230-7902de3c-2384-11e8-8c29-d696436a36e8.png)

**Comment by oskarkrawczyk** [comment]
@mindplay-dk can you provide a test case fiddle?

**Comment by oskarkrawczyk** [comment]
Never mind, I see where the problem lays. Will fix soon.
