### ISSUE TITLE
signup email filter does not allow dots

### ISSUE THREAD

**Issue by mpalasis** [jsfiddle/jsfiddle-issues#1202]
issue: The signup process at https://jsfiddle.net/user/signup/ has an email filter that does not allow dots in the email.name@foo.tld

error msg returned:

    This value must contain only letters, numbers and underscores.

expected action:
It should allow dots in email names ;)

**Comment by oskarkrawczyk** [comment]
You can use dots in the email, this error refers to the username field - I've altered the message so it's more clear.

**Comment by mpalasis** [comment]
oh, *facepalm* cheers for the clarification.
