### ISSUE TITLE
Unable to create/edit a fiddle

### ISSUE THREAD

**Issue by StandishMan25** [jsfiddle/jsfiddle-issues#1203]
I'm unable to create or edit any fiddles. I can type in HTML and CSS, albeit it's covered by the labels of the area and difficult to read. I am unable to edit any javascript.

Loading an existing project (as shown below) results in empty areas with a rendered result. Clicking "Run" after initial load leads to an empty result. I'm using Chrome 65 (tried Incognito, clearing cache, etc), IE 11 appears to work.

![image](https://user-images.githubusercontent.com/10331270/37476339-ec9d9374-2842-11e8-99cc-2c5b5f72e677.png)

Error from Developer Console:
```
Uncaught TypeError: Cannot read property 'attach' of undefined
    at Object.keyMap (_dist-editor.js?update_10_03_2018_3:1)
    at new xa (_dist-editor.js?update_10_03_2018_3:1)
    at xa (_dist-editor.js?update_10_03_2018_3:1)
    at Object.initialize (_dist-editor.js?update_10_03_2018_3:1)
    at Object.<anonymous> (_dist-editor.js?update_10_03_2018_3:1)
    at Object.r.extend.$owner (_dist-editor.js?update_10_03_2018_3:1)
    at Object.t (_dist-editor.js?update_10_03_2018_3:1)
    at Object.initialize (_dist-editor.js?update_10_03_2018_3:1)
    at Object.<anonymous> (_dist-editor.js?update_10_03_2018_3:1)
    at Object.r.extend.$owner (_dist-editor.js?update_10_03_2018_3:1)
```

**Comment by oskarkrawczyk** [comment]
Tested in Chrome, Firefox and Safari. No errors when hitting `Run` nor after initial load.

Perhaps it's specific to the fiddle you're trying to load. Can you share the URL?

**Comment by StandishMan25** [comment]
Sure: https://jsfiddle.net/standishman/ypo6Lob3/

This also happens just navigating to jsfiddle.net

![image](https://user-images.githubusercontent.com/10331270/37477582-048837b6-2846-11e8-8701-ccb1017f3fa9.png)

**Comment by StandishMan25** [comment]
I'm running 64 bit Windows 10 Enterprise 1511. if that helps at all. Just ended all chrome processes, restarted, same issue.

**Comment by oskarkrawczyk** [comment]
I don't have a windows machine to test, but I'd assume Chrome would work the same on all operating systems.

Can you disable all extensions, and see if that changes anything?

**Comment by StandishMan25** [comment]
All extensions/apps disabled, still no luck. I had a coworker try and his appears to be fine. 

If I'm the only one experiencing this, then this issue could probably be closed and I'll just keep trying every few days, hoping Chrome eventually works. I can use other browsers for now.

**Comment by oskarkrawczyk** [comment]
The weird thing here is that the error states that the method `attach` is being invoked on an undefined variable/object. The only two references of that method are within the MooTools framework, and that has full test coverage which should have pick up any problems on windows+chrome.

This makes me think there's something off with your setup – I know this isn't the answer you're looking for.

I'll keep this ticket open for the time being.

**Comment by eu81273** [comment]
@oskarkrawczyk
same problem.

Save any jsfiddle in 'http'.  (ex. [http://jsfiddle.net/eu81273/o7yvL2jd/](http://jsfiddle.net/eu81273/o7yvL2jd/) )
Open same jsfiddle in 'https'. (ex. [https://jsfiddle.net/eu81273/o7yvL2jd/](https://jsfiddle.net/eu81273/o7yvL2jd/) )

**Comment by oskarkrawczyk** [comment]
@eu81273 I see no errors on any of these fiddles.

Is this happening on Windows as well? The exact same error as mentioned by @StandishMan25?

**Comment by diarmuids** [comment]
Yep, exact same issue here. Windows 7. 

whatsmybrowser.org/b/4ZXZU48

`_dist-editor.js?update_10_03_2018_3:1 Uncaught TypeError: Cannot read property 'attach' of undefined
    at Object.keyMap (_dist-editor.js?update_10_03_2018_3:1)
    at new xa (_dist-editor.js?update_10_03_2018_3:1)
    at xa (_dist-editor.js?update_10_03_2018_3:1)
    at Object.initialize (_dist-editor.js?update_10_03_2018_3:1)
    at Object.<anonymous> (_dist-editor.js?update_10_03_2018_3:1)
    at Object.r.extend.$owner (_dist-editor.js?update_10_03_2018_3:1)
    at Object.t (_dist-editor.js?update_10_03_2018_3:1)
    at Object.initialize (_dist-editor.js?update_10_03_2018_3:1)
    at Object.<anonymous> (_dist-editor.js?update_10_03_2018_3:1)
    at Object.r.extend.$owner (_dist-editor.js?update_10_03_2018_3:1)`

**Comment by oskarkrawczyk** [comment]
@StandishMan25 @diarmuids I've uncompressed `_dist-editor.js` so the error at least has better variable names, can you test again and paste in the error stack? Thanks

**Comment by oskarkrawczyk** [comment]
Ok, I know where the issue lays, will fix today.

**Comment by diarmuids** [comment]
it's working again now! thanks

**Comment by StandishMan25** [comment]
Awesome! Will check on Monday. Good work!

**Comment by oskarkrawczyk** [comment]
Interesting, haven't fixed anything yet. Will do it later today :-)

**Comment by diarmuids** [comment]
ya, it seem sot be back working now for whatever reason.

**Comment by StandishMan25** [comment]
Just getting back to this. It's working in incognito, still not my regular instance. It's possible something's cached. Did you deploy the fix or did I get lucky?

**Comment by oskarkrawczyk** [comment]
It's a problematic thing to fix. One it ONLY happens on production servers, the exact same environment on any other server or local, doesn't have the issue.

I'll update CodeMirror later today to see if that changes anything.

**Comment by eu81273** [comment]
@oskarkrawczyk 
> Is this happening on Windows as well?
I'm using mac so couldn't check Windows env.
> The exact same error as mentioned by @StandishMan25?
Yes.

Always works fine with 'http' protocol. **Sometimes** it works fine with 'https' protocol.

**Comment by oskarkrawczyk** [comment]
I see no difference between HTTPS and HTTP - always fails when switching to `Sublime Text` or `EMACS`.

Need to do more digging into the issue. So far no idea why it fails.

**Comment by StandishMan25** [comment]
Could be luck, but it's working in my regular instance now. No incognito or special tricks.

**Comment by oskarkrawczyk** [comment]
Looks like it's fixed, closing.

**Comment by justinross** [comment]
Sooo ... I'm running into this issue now. Loading jsfiddle in a normal chrome window, even with all extensions disabled (Version 75.0.3770.100, MacOS 10.14.3), the page throws this error and the loading indicator cloud just keeps bouncing away: 

![image](https://user-images.githubusercontent.com/1120106/61073656-bf512c00-a3ca-11e9-81bf-5599a7e4847e.png)

On any keypress, the following error is thrown:

![image](https://user-images.githubusercontent.com/1120106/61073689-d42dbf80-a3ca-11e9-946b-fd87adaf0ff3.png)

An incognito window does not encounter this issue.

**Comment by oskarkrawczyk** [comment]
@justinross Refresh browser cache, or remove all local storage/cookies under the `jsfiddle.net` domain.

I can't replicate this, so most likely a local issue.

Hope this helps.

**Comment by justinross** [comment]
Yeah, disregard. Sorry. I had cleared my cache, but forgot about localstorage. Deleting all localstorage entries and refreshing cleared it up. Sorry for any alarm.

Thanks! :)
