### ISSUE TITLE
high cpu usage 

### ISSUE THREAD

**Issue by ninab731** [jsfiddle/jsfiddle-issues#1204]
I cannot open my dashboard to jsfiddle - when I attempt to open the dashboard the cpu usage goes crazy and the page becomes unresponsive.  
# Note on existing issues:

- ‼️ Known and minor issues will **not be addressed and most likely will be closed**
- ‼️ More info in README.md

# Library update request

- Be sure your library (in the correct version) exists on cdnjs.org

**Comment by oskarkrawczyk** [comment]
Read the Readme.md
