### ISSUE TITLE
JS auto-close brackets

### ISSUE THREAD

**Issue by KacperMadej** [jsfiddle/jsfiddle-issues#1206]
When typing in JS window an opening bracket (like `[` or `{`) the closing bracket was added automatically (like `]` or `}`). This was working before and now looks like the feature was removed.

Is there an option to enable this feature?

**Comment by oskarkrawczyk** [comment]
Thanks for reporting.

Looks like some default editor options were mistakenly overwritten in the code.

Should be back to normal.
