### ISSUE TITLE
Change username fails with no errors

### ISSUE THREAD

**Issue by jeremyheiler** [jsfiddle/jsfiddle-issues#1207]
I've tried to change my username to a three character string, however, it doesn't seem to take effect, and their are no errors displayed. This seems to happen for any username that's less than 8 characters long. Could you either display an error, or allow shorter usernames?

Thanks!

**Comment by oskarkrawczyk** [comment]
Minimum length of a username is 5 chars.

There seems to be an issue with error message missing when it should state that the username is already taken.

**Comment by jeremyheiler** [comment]
Ah, right. I guess I should've been more careful with how unique my tests where :-P

But yeah, and error for these scenarios would be nice:
- when a username is too small
- when a username is already taken

Thank you!
