### ISSUE TITLE
Display issues in Firefox

### ISSUE THREAD

**Issue by jeremyheiler** [jsfiddle/jsfiddle-issues#1208]
The code seems to sneak up underneath the panel headers. It doesn't matter which configuration the panels are in.

<img width="301" alt="screen shot 2018-03-22 at 4 24 00 pm" src="https://user-images.githubusercontent.com/183600/37796416-a052cb3c-2ded-11e8-949b-c67f03cb2fa7.png">

I'm running Firefox 59.0.1 on macOS.

**Comment by oskarkrawczyk** [comment]
Seems to look fine from here, same Firefox version and OS.

<img width="429" alt="screen shot 2018-03-22 at 21 28 05" src="https://user-images.githubusercontent.com/34213/37796631-0a7447be-2e18-11e8-9281-0d17d166b134.png">

Can you try and refresh your cache?

**Comment by jeremyheiler** [comment]
No effect. It appears that the `CodeMirror` div is missing the class `CodeMirror-wrap` when I load the page in Firefox. If I add it manually, the panel renders correctly. I deleting the cache and restarting the browser isn't enough! I loaded the editor up in Firefox on another Mac, and it renders correctly. Sorry for the noise!

**Comment by jeremyheiler** [comment]
It happens when I turn of line numbering!

**Comment by KieranHolroyd** [comment]
https://www.nitrexdesign.co.uk/s/da18f8f9.png

**Comment by KieranHolroyd** [comment]
![alt text](https://www.nitrexdesign.co.uk/s/da18f8f9.png "Same Issue Here")

**Comment by oskarkrawczyk** [comment]
Fixed
