### ISSUE TITLE
No labels on the change password form

### ISSUE THREAD

**Issue by jeremyheiler** [jsfiddle/jsfiddle-issues#1209]
The change password form could be clearer :-)

<img width="699" alt="screen shot 2018-03-22 at 4 28 25 pm" src="https://user-images.githubusercontent.com/183600/37796697-40b029da-2dee-11e8-97ce-19be8b8f2359.png">

**Comment by oskarkrawczyk** [comment]
No way to fix this at the moment. Will have to stay this way till the rewrite is finished.

Closing since I won't be fixing this in the old codebase.
