### ISSUE TITLE
Settings forms not rendering correctly in Chrome

### ISSUE THREAD

**Issue by jeremyheiler** [jsfiddle/jsfiddle-issues#1210]
It seems like they shouldn't be stacked like that? At least, it's not like that in Firefox and Safari.

<img width="413" alt="screen shot 2018-03-22 at 4 31 10 pm" src="https://user-images.githubusercontent.com/183600/37796795-7c9940da-2dee-11e8-93b5-c343f1e48786.png">

**Comment by oskarkrawczyk** [comment]
Wow, that is weird, Chrome supports CSS Grid, yet completely ignores it here.

**Comment by oskarkrawczyk** [comment]
Turns out Chrome doesn't support `display: grid` on `<fieldset>` elements. Who knew ...

**Comment by jeremyheiler** [comment]
Weird. Thanks for fixing this 👍
