### ISSUE TITLE
Rendering on very thin width screen is broken

### ISSUE THREAD

**Issue by dbkaplun** [jsfiddle/jsfiddle-issues#1211]
Couldn't find an existing issue so opening here. On my MBA 13" 2013, I have my Chrome window at 2/3 width and open my devtools. The top navbar breaks, and I am unable to see the bottom of the JS/output windows.

Thanks for reading!

**Comment by oskarkrawczyk** [comment]
@dbkaplun Can you upload a screenshot?

**Comment by dbkaplun** [comment]
![screen shot 2018-03-22 at 5 23 39 pm](https://user-images.githubusercontent.com/1765130/37799417-03f89c2c-2df6-11e8-9097-a6885c67a2ef.png)
