### ISSUE TITLE
JavaScript error when calling from file

### ISSUE THREAD

**Issue by leomaia97** [jsfiddle/jsfiddle-issues#1212]
Hey guys,

I've been using the site from a while, but late today an Error pretty anoing is getting me stress.
Here is what is happen:

Link to the Code:
http://jsfiddle.net/leomaia97/uhrr8wvr/

The Error when I call a function inside de .js file:
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.

**Comment by oskarkrawczyk** [comment]
Can you elaborate or provide an example? I'm not sure what you're talking about.

**Comment by leomaia97** [comment]
Sorry, I press the enter and send it the comment.

I've edit the comment...

**Comment by leomaia97** [comment]
Here is a print:

![image](https://user-images.githubusercontent.com/32986455/37853277-b2dee420-2ec4-11e8-8337-b9369e6b8601.png)

**Comment by leomaia97** [comment]
My other code, have the same issue(not running a JS from a file) :
http://jsfiddle.net/leomaia97/n8nttc23/

Look the Print:
![image](https://user-images.githubusercontent.com/32986455/37853413-5ec66bb4-2ec5-11e8-8d69-5f5d3fdf7d18.png)


Text error:
{"error": "Shell form does not validate{'html_initial_name': u'initial-js_lib', 'form': <mooshell.forms.ShellForm object at 0x7fbbb9489e90>, 'html_name': 'js_lib', 'html_initial_id': u'initial-id_js_lib', 'label': u'Js lib', 'field': <django.forms.models.ModelChoiceField object at 0x7fbbb8689610>, 'help_text': '', 'name': 'js_lib'}{'html_initial_name': u'initial-js_wrap', 'form': <mooshell.forms.ShellForm object at 0x7fbbb9489e90>, 'html_name': 'js_wrap', 'html_initial_id': u'initial-id_js_wrap', 'label': u'Js wrap', 'field': <django.forms.fields.TypedChoiceField object at 0x7fbbb8689690>, 'help_text': '', 'name': 'js_wrap'}"}



I know the site auto-load from whatever is write in the JavaScript field, but when I call it whit a function in it, is getting this error.

I've tried from a .html and .js in my PC, and my code works.
I'm not an Expert in web-programing yet, if I mistake something, I'm sorry.

P.S From Brazil, my english is not very nice. Be patience. =D
Thanks for your time and thanks for this awesome programming-tool.
