### ISSUE TITLE
Simple javascript function not working

### ISSUE THREAD

**Issue by diarmuids** [jsfiddle/jsfiddle-issues#1216]
https://jsfiddle.net/diarmuids/45nLdsqv/

This isn't working for some reason with the javascript in the JS pane. However, when it's used in the HTML pane, it works. 

Can anyone let me know why?

**Comment by oskarkrawczyk** [comment]
@diarmuids 

See console: `ReferenceError: Can't find variable: myFunction`

Your code is wrapped in `onLoad`, you need to change the wrap mode for inline code to see the one defined in `<script>`.

Inspecting source code of the frame causing the error would show where the problem lays.

<img width="514" alt="screen shot 2018-03-29 at 11 35 44" src="https://user-images.githubusercontent.com/34213/38081968-a41e2114-3345-11e8-82d5-e348f0343593.png">

**Comment by diarmuids** [comment]
Thank you for your help - I really appreciate it!

**Comment by Rax-shiftware** [comment]
Helppp! i can't use function in jsfiddle. i needed Mozilla javascript on my samsung j6 phone
