### ISSUE TITLE
Unhelpful JS error messages

### ISSUE THREAD

**Issue by 12Me21** [jsfiddle/jsfiddle-issues#1217]
Line numbers in JavaScript error messages does not match the line numbers in your code.
For example, the program:
```
0=1
```
Will throw this error:
```
ReferenceError: invalid assignment left-hand side[Learn More]  _display:67
```
I know *why* this happens, but it makes debugging a whole lot harder.

**Comment by oskarkrawczyk** [comment]
No way around that AFAIK.
