### ISSUE TITLE
Add "JSPerf" template

### ISSUE THREAD

**Issue by Alex-ray** [jsfiddle/jsfiddle-issues#1218]
➕ Feature Request:

Imagine how much faster the web would be if you introduced performance testing functionality?

Original conceived here => https://twitter.com/ianstormtaylor/status/979545802946129920

Would love to hear the teams thoughts on this!

**Comment by oskarkrawczyk** [comment]
@Alex-ray how do you imagine this working? I'm not quite sure how to approach this.
