### ISSUE TITLE
Menu bar pushes screen but provides no scroll bars

### ISSUE THREAD

**Issue by alallier** [jsfiddle/jsfiddle-issues#1220]
Menu bar pushes screen but provides no scroll bars making parts of the screen un-viewable

![topmenubarpushesscreensopartsofitareunavailabletobeseen](https://user-images.githubusercontent.com/13004518/38137266-c16a3d32-33f1-11e8-8284-ac356f9683de.gif)

**Comment by oskarkrawczyk** [comment]
This is so minor it's not worth the time of figuring out a way modify how the layout can be altered to "fix" this, just close the boilerplate bar.

Closing, otherwise it would stay unsolved forever.
