### ISSUE TITLE
choosing "empty" as boilerplate asks after boilerplate again

### ISSUE THREAD

**Issue by nitwhiz** [jsfiddle/jsfiddle-issues#1221]
When using "Empty" as boilderplate, it shows the overlay again and again and again. jQuery for example doesn't do this.

**Comment by oskarkrawczyk** [comment]
Merging into #1408

**Comment by antoniooi** [comment]
So no empty boilerplate now? Are we solving the right issue while thinking of removing the empty boilerplate option?
