### ISSUE TITLE
change font size

### ISSUE THREAD

**Issue by unluisco** [jsfiddle/jsfiddle-issues#1223]
Hi, thanks for make jsFiddle.

Could we change the font size of the panels from settings at a future time? I use it in a classroom with students.
Thanks.

**Comment by oskarkrawczyk** [comment]
Added.

![kapture 2018-04-05 at 15 30 59](https://user-images.githubusercontent.com/34213/38368750-6872611a-38e6-11e8-8f9f-1a787a55625d.gif)
