### ISSUE TITLE
POST a fiddle is broken

### ISSUE THREAD

**Issue by Leopoldthecoder** [jsfiddle/jsfiddle-issues#1224]
According to http://doc.jsfiddle.net/api/post.html , we can send a POST request and get a fiddle. This works fine until about half an hour ago. Now when I do a POST request, I get the following errors:

![image](https://user-images.githubusercontent.com/10095631/38301378-f295ac68-3831-11e8-8bed-f8a064bd47f2.png)

**Comment by oskarkrawczyk** [comment]
Reverted code
