### ISSUE TITLE
The boilerplate bar appears when loading from GitHub

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#1225]
The boilerplate bar assumes that we are starting an empty fiddle, but we're not:

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-basic/

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by TorsteinHonsi** [comment]
The boilerplate bar appeared again a couple of days ago...
