### ISSUE TITLE
Dropdown Choices Grayed Out - HTML, CSS, JavaScript + No Library, etc.)

### ISSUE THREAD

**Issue by kmiklas** [jsfiddle/jsfiddle-issues#1227]
I am unable to select HTML versions, framework, etc. All choices are grayed out and inaccessible.

In my case, I need Babel transforms for decorators. I was previously able to select this; now, the select is grayed out.

Very frustrating. Not sure if there's some setting somewhere that I need to flip.

I've cleared cookies, reloaded, tried a different browser... all grayed out.

**Comment by oskarkrawczyk** [comment]
Looking into it.

**Comment by oskarkrawczyk** [comment]
Should be fixed. 

Note that nothing's grayed out, that's the design, the popovers weren't clickable.

**Comment by kmiklas** [comment]
That does not sound right.

Are you looking at the popover with select boxes? Where I should be able to choose Language, Frameworks & Extensions, Load Type, Framework <script> attribute?

These are clearly select boxes.

A moment ago I was able to choose Babel under Frameworks & Extensions.

**Comment by oskarkrawczyk** [comment]
Not sure what doesn't sound right – that is in fact the design.

Popovers weren't clickable (there was `pointer-events: none` on all of them), removed that and everything is back to normal – ie. `selects` are selectable, `inputs` are focusable, etc.

![kapture 2018-04-04 at 18 49 10](https://user-images.githubusercontent.com/34213/38321817-eba3ac14-3838-11e8-9d51-29118d35aa69.gif)

**Comment by oskarkrawczyk** [comment]
> Is the gif above the current behavior?

Yep.

Try refreshing your cache.

**Comment by kmiklas** [comment]
Working now... some glitch. Thanks for your help.

**Comment by oskarkrawczyk** [comment]
Cool, thanks for reporting this in!
