### ISSUE TITLE
Slider Rounding Issue in Max Position

### ISSUE THREAD

**Issue by smanoj08** [jsfiddle/jsfiddle-issues#1229]
I facing issue in unrounding value in max position

http://jsfiddle.net/Lh6aoaep/23/
http://jsfiddle.net/Lh6aoaep/22/

i provided step "1" for both link, but values in Max position mismatched. **i dont want step to 1.1 or 0.1** 

see the difference of max value

![slider_rounding](https://user-images.githubusercontent.com/14068971/38367280-e05db148-38ff-11e8-9081-e483929ce215.jpg)

**Comment by oskarkrawczyk** [comment]
This is for JSFiddle-related issues only. I suggest asking on a JS forum or StackOverflow.
