### ISSUE TITLE
div.windowLabelCont covers code in div.panel-h

### ISSUE THREAD

**Issue by svarlitskiy** [jsfiddle/jsfiddle-issues#1230]
When you select to disable line wrapping in the settings, the div.windowLabelCont element covers the code in div.panel-h. It seems that the code slides up. Can you guys add some padding or something so that this doesn't happen.

Using chrome Version 65.0.3325.181 (Official Build) (64-bit)
on Ubuntu 16.04 LTS (64-bit)

**Comment by oskarkrawczyk** [comment]
Same as #1208
