### ISSUE TITLE
Embed Goes Off The Screen

### ISSUE THREAD

**Issue by KieranHolroyd** [jsfiddle/jsfiddle-issues#1234]
![alt text](https://www.nitrexdesign.co.uk/s/6456cf25.png) got this on chrome and firefox on dark and light theme.

**Comment by oskarkrawczyk** [comment]
Tested on Chrome and Firefox, looks fine on both.

<img width="1330" alt="screen shot 2018-04-07 at 19 36 36" src="https://user-images.githubusercontent.com/34213/38458148-0fcb6b36-3a9b-11e8-9ec7-41b55c9ec685.png">

<img width="1243" alt="screen shot 2018-04-07 at 19 36 16" src="https://user-images.githubusercontent.com/34213/38458149-0fe696d6-3a9b-11e8-9f70-05bebabe1efa.png">
