### ISSUE TITLE
Support vue-devtools

### ISSUE THREAD

**Issue by tony-pitchblack** [jsfiddle/jsfiddle-issues#1235]
Currently vue-devtools don't recognize Vue in jsfiddle.
![image](https://user-images.githubusercontent.com/36202157/38457597-5dcfcc64-3a9b-11e8-97ca-ed2150c237f2.png)

**Comment by oskarkrawczyk** [comment]
The extension won't work since the rendered result is 1) in an iframe, 2) on a different domain

**Comment by suterma** [comment]
FYI, I have described a solution using the standalone dev-tools here: https://stackoverflow.com/a/59823141/79485
