### ISSUE TITLE
Add option to disable dashboard rendering by default

### ISSUE THREAD

**Issue by SheetJSDev** [jsfiddle/jsfiddle-issues#1237]
As part of https://github.com/jsfiddle/jsfiddle-issues/issues/1131 , the escape hatch `?disable_render=true` was added to prevent immediately evaluating every fiddle.  However, when signing in, you are always directed to the dashboard without the option, so it will always evaluate the fiddles.  Is there an option to disable rendering by default?

**Comment by oskarkrawczyk** [comment]
No way to disable it by default. No plans on adding that.
