### ISSUE TITLE
Unable to load /user/dashboard in Chrome: 65.0.3325.181 (Official Build) (64-bit) (cohort: Stable)

### ISSUE THREAD

**Issue by SquozenOrange** [jsfiddle/jsfiddle-issues#1241]
When trying to view the "All Fiddles" or "Public Fiddles" page in Chrome, It crashes with either a memory overload or just an "Aw snap" error.

Screenshot below from Network Debugger in Dev Console shows it failing to load 3 files

react-with-addons-0.12.0.js
JSXTransformer-0.12.0.js
react-js-fiddle-integration.js

They return status "(Blocked:Mixed-Content)"

I can browse the dashboard in IE, after accepting that only secure content is shown.

![image](https://user-images.githubusercontent.com/2794355/38630013-a5b764d2-3dad-11e8-9a74-5ca48364c609.png)

**Comment by SquozenOrange** [comment]
I have managed to workaround this by deleting the Fiddles which were using the Blocked React libraries

**Comment by oskarkrawczyk** [comment]
@sohnryang See `README.md`

**Comment by sohnryang** [comment]
Huh? Why did you mentioned me, @oskarkrawczyk ?

**Comment by oskarkrawczyk** [comment]
Wrong username.
