### ISSUE TITLE
jsfiddle.net Certificate Error

### ISSUE THREAD

**Issue by alt-jero** [jsfiddle/jsfiddle-issues#1242]
Hi Guys!

I wanted to let you know: Although it's jsfiddle.net (as the address), Siri's browser suggestion sent me to www.jsfiddle.net upon which, although it apparently points to the right server, a certificate error is shown because the "www" prefix is not listed in the certificate.
Suggest:
- Update certificate with "www" prefix (conservative)
- Update certificate with wildcard prefix (liberal)
- Redirect http://www.jsfiddle.net to https://jsfiddle.net *before* the toSSL redirect.

Also: On the Readme, it's "Rogue" not "Rouge" which means RED. Unless you actually meant a red (rouge) fiddle, in which case nevermind. :P

**Comment by andreasvirkus** [comment]
Would also like to point out that http://jsfiddle.net has no redirect to `https://`.
Please re-open this and get it fixed ASAP, as it's such a simple config issue
