### ISSUE TITLE
Highlighting HTML closing tags to make quick reading easier

### ISSUE THREAD

**Issue by sbling1993** [jsfiddle/jsfiddle-issues#1245]
I would greatly appreciate it if JSFiddle would highlight the closing tag when you selected the opening tag, and visa versa. For example, if you have highlighted the second <div> in the following sequence, then the closing tag would also highlight: 
```
<div>
     <div>
          <div>
          </div>
     </div>
</div>
```

It's a very minor suggestion, one that would just make my life a little easier. 

It might also be nice if, when highlighting a class in either CSS or HTML (or any where really), all the other instances of that class would appear. For example, one would highlight .classOne in the CSS section, then all of the tags with class="classOne" would highlight as well. Basically, here I would be asking for a constantly running Find function for CSS classes only. An on/off function for both of these might be nice.

While I'm in here, I would also appreciate it if the boilerplate dropdown appeared once, and then every other time you load JSFiddle, it appears as a close-able bar at the top of the page. A lot of times I use JSFiddle to tidy up blocks of code that have been compressed by a program I have to use, so it's just a tad annoying to have to close that every time. 

Thank you!

**Comment by oskarkrawczyk** [comment]
> I would greatly appreciate it if JSFiddle would highlight the closing tag when you selected the opening tag, and visa versa. For example, if you have highlighted the second

Good idea! Added, you can find this is editor settings.

> While I'm in here, I would also appreciate it if the boilerplate dropdown appeared once

It only appears for new fiddles (no code), and will go away once code is ran or saved, which I think is fair enough.

For now most people seems to generally happy with the boilerplate bar, so I'm leaving it as it is.
