### ISSUE TITLE
Js Fiddle not working properly on Firefox

### ISSUE THREAD

**Issue by vishaltatva** [jsfiddle/jsfiddle-issues#1246]
The loader doesn't gets hide and in console I can see following error.

> TypeError: document.querySelectorAll(...).forEach is not a function
> 
> document.querySelectorAll("select.panelChoice").forEach(function(select){
> 

Js Fiddle not working properly on Firefox(49.0.2)

**Comment by oskarkrawczyk** [comment]
@vishaltatva Your Firefox version is pretty ancient – you're 10 versions behind the current (59.0.2).
