### ISSUE TITLE
Allow to display only certain tabs (sharing included)

### ISSUE THREAD

**Issue by kud** [jsfiddle/jsfiddle-issues#1247]
I'd like to display only certain tabs like html + result or js + result.

It should also work when you share a link.

**Comment by oskarkrawczyk** [comment]
@kud Tabs in embed you can already do. Panels in the full editor is on the roadmap – https://trello.com/c/XwX7xzTK/47-ability-to-show-and-hide-specific-editor-panels

**Comment by kud** [comment]
Thank you! :)

I knew it for embed yeah but I'm not always in a case of embed, more direct share.

Thanks, I voted so!
