### ISSUE TITLE
Feature Request: Find and Replace

### ISSUE THREAD

**Issue by tigregalis** [jsfiddle/jsfiddle-issues#1248]
Apologies if this already exists, and I just can't find it, but if not:

Please add a Find and Replace (and Highlight) function as in text editors / IDEs.

notepad++ is the ideal model in my mind in terms of Find-and-Replace features/functionality.

Shortcut key (Ctrl+F or Ctrl+H) accessible when the focus is in the html/css/js block.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
