### ISSUE TITLE
Visiblity of the Embed tool

### ISSUE THREAD

**Issue by koryukov** [jsfiddle/jsfiddle-issues#1249]
The left part of the Embed tool form is not visible in following borowsers (see screenshor below):

- Google Chrome 65.0;
- Firefox 59.0.

![embed-tool-issue](https://user-images.githubusercontent.com/29269573/38922479-b24fd6e8-4311-11e8-95be-7f8a8c68a086.PNG)

**Comment by oskarkrawczyk** [comment]
@koryukov Cannot replicate. Please provide the the fiddle URL, perhaps it's something specific to the fiddle code.

<img width="1398" alt="screen shot 2018-04-18 at 14 17 52" src="https://user-images.githubusercontent.com/34213/38931396-4f155998-4313-11e8-87b8-2bd137da127e.png">

**Comment by koryukov** [comment]
@oskarkrawczyk , the Embedded tool is trimmed in all my fiddles. Some simple fiddles:

- https://jsfiddle.net/1zou7gfL/
- https://jsfiddle.net/arkdhbmu/
- https://jsfiddle.net/yafbyf81/

**Note.** I find, the issue occurs when browser window is wide. For example, if desktop window is maximized, the form is [trimmed][fullscreen]. But if the desktop window is 
minimized, then the tool is displayed [correctly][windowed]. 

[fullscreen]: https://user-images.githubusercontent.com/29269573/39038023-cb41b8d4-449b-11e8-8a2b-d7d755ca5de9.png
[windowed]: https://user-images.githubusercontent.com/29269573/39038025-cfcb9dac-449b-11e8-8a40-47107ade6104.png

**Comment by oskarkrawczyk** [comment]
@koryukov Thanks for the info, I see there the problem lays. Will fix soon.

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by koryukov** [comment]
Now navigation links of the *Resources* and *Result* tabs are shifted to a tab content area:

![tab issue](https://user-images.githubusercontent.com/29269573/39043589-3d58d58c-44a7-11e8-8651-e2c0bf0b09b8.PNG)
