### ISSUE TITLE
Save fiddle as Template

### ISSUE THREAD

**Issue by ThomasBurleson** [jsfiddle/jsfiddle-issues#125]
Need abililty to create custom jsFiddle templates:

After 
- selecting the framework options, managed resources
- setting the base html shell
- setting the base css
- seeting the base js

User could then save as a TEMPLATE to be reused in new Fiddles
User could save with custom name

Later... when choosing a new Fiddle, the button is a dropdown menu that shows custom templates or blank Fiddle.

**Comment by calraith** [comment]
Suggested addendum: allow saving a template as default, so when a logged in user creates a new fiddle, the default is already active.

**Comment by kindlychung** [comment]
Has this been implemented?

**Comment by oskarkrawczyk** [comment]
No, it's on the roadmap.
