### ISSUE TITLE
JS fiddle doesn't recognise CSS variables

### ISSUE THREAD

**Issue by NoOorZ24** [jsfiddle/jsfiddle-issues#1251]
If I try adding CSS variable - https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

    :root {
        --top-blue: #267cdc; //warning
    }

warning message: expected BRACE at line X, col Y
I know CSS variable is quite new and not largely supported but it can help a lot for testing purposes so I think it would be nice id logic was implemented to detect CSS variables and not to show warnings.

**Comment by oskarkrawczyk** [comment]
If a browser supports CSS Variables, you'll be able to use them in JSFiddle. As to having it available through PostCSS/CSSNext, we don't have this implemented – it's on the roadmap though.

Error you're mentioning is just the linter that doesn't know how to parse CSS Vars, ignore it or just turn it off in editor settings.

**Comment by oskarkrawczyk** [comment]
No progress. Depends on a new renderer #1394
