### ISSUE TITLE
Fix login when editing a new fiddle

### ISSUE THREAD

**Issue by eliluong** [jsfiddle/jsfiddle-issues#1255]
When you are editing a fiddle and you realize you aren't logged in, clicking on sign in will show an overlay box, but logging in will wipe the current page/fiddle and push you to an empty fiddle page. Going back will not revert your work. Can a smoother login system be implemented? Or prevent a user from doing something like this?

**Comment by oskarkrawczyk** [comment]
> clicking on sign in will show an overlay box

That is incorrect, there's no overlay box, only a redirect.

That said, I have a better login flow in the works + it's on the roadmap.

**Comment by q00u** [comment]
It's 2020 and this is still broken.
