### ISSUE TITLE
JSON request fails

### ISSUE THREAD

**Issue by cyberjetx** [jsfiddle/jsfiddle-issues#1259]
requests for the JSON fail with 404 

example: 
http://jsfiddle.net/api/user/cyberjetx/demo/list.json 

This just started in the last few hours.

**Comment by oskarkrawczyk** [comment]
Users are case sensitive: `http://jsfiddle.net/api/user/Cyberjetx/demo/list.json`

**Comment by cyberjetx** [comment]
I'm cool with this   I use a hard coded link on my dev home page so it is a change of behavior though.   I'm stoked it's just case sensitive and not removed functionality.  Updating the link and moving on.  
Thank you for all you do.  Looking for the donate button...
