### ISSUE TITLE
Thumbnail previews & meta info do not update.

### ISSUE THREAD

**Issue by jaylitten** [jsfiddle/jsfiddle-issues#1261]
Thumbnail previews & meta descriptions, which are seen in the All Your Fiddles screen, do not update after changes to the fiddles. The thumbnail and meta description remain as they appeared the first time we saved the fiddle.

This is true in Safari (stable) and Chrome (stable) in macOS High Sierra (stable). I have already cleared the browser cache, which did not help.

Thank you for jsfiddle! 😄

**Comment by oskarkrawczyk** [comment]
You have to set the fiddle as base version.
