### ISSUE TITLE
Firefox : Zooming out breaks the layout (hover menu item)

### ISSUE THREAD

**Issue by ThomasFerro** [jsfiddle/jsfiddle-issues#1262]
On Firefox (Quantum 59.0.2) only, when zooming out of the window will causes the layout to break when hovering menu items.

100% zoom :
![image](https://user-images.githubusercontent.com/14331186/39364401-2642662e-4a2e-11e8-8f03-39e9c9c9e527.png)

90% zoom :
Hovering a menu item :
![image](https://user-images.githubusercontent.com/14331186/39364424-39897038-4a2e-11e8-82d3-0eec4795c21f.png)

Hover the editor area :
![image](https://user-images.githubusercontent.com/14331186/39364441-4677725e-4a2e-11e8-870e-51c9d860f747.png)

Not a big issue but I thought it will be interesting to know.

**Comment by oskarkrawczyk** [comment]
I'll be honest, this is such an edge case I don't see investigating this in the foreseeable future, so I'm going to go ahead and close this. 

If anyone finds a way to patch this up I'll happily copy'n'paste a fix to the codebase.
