### ISSUE TITLE
The 'start with a boilerplate' menu pops open on EVERY visit, even if it was closed previously.

### ISSUE THREAD

**Issue by RoryMcCrossan** [jsfiddle/jsfiddle-issues#1263]
This is incredibly annoying. I don't want a boilerplate. I don't need a boilerplate. Neither do I want a quarter of the screen taken up with such an obtrusive banner. 

Please save the state of the menu when 'close' is clicked.

**Comment by oskarkrawczyk** [comment]
See editor settings.

**Comment by RoryMcCrossan** [comment]
Thank you. Although I would argue this isn't very intuitive. If I close something I would expect it to stay closed.

**Comment by arshad115** [comment]
This is the most annoying feature of Jsfiddle when it opens by itself. I had changed the setting to show boiler plates less often and somehow it reverted the setting to original annoying setting! I also don't need a boilerplate! If I need it, I will click the menu to create one!

**Comment by oskarkrawczyk** [comment]
- The boilerplate feature stays
- Showing it can be reduced in Editor settings (if it disables itself, means that cookie expired)
- Stats show that most users use it
