### ISSUE TITLE
There are console logs in production collaboration mode

### ISSUE THREAD

**Issue by alexcushing** [jsfiddle/jsfiddle-issues#1266]
I noticed while trying to add my own logs that there were already so many that it made it hard to find my own. Fixing this would make a world of difference for me.

**Comment by oskarkrawczyk** [comment]
You can enable log clearing in editor settings

**Comment by alexcushing** [comment]
Thanks why is this not enabled by default? Seems like a no brainer unless I'm missing something

**Comment by alexcushing** [comment]
The event listener I'm talking about. The event listener that logs Everytime anyone clicks

**Comment by alexcushing** [comment]
I don't want it cleared I want to see my own logs not your logs that fire off all the time when people join leave or click
