### ISSUE TITLE
Support for multiple files

### ISSUE THREAD

**Issue by IPWright83** [jsfiddle/jsfiddle-issues#1267]
# Feature Request
Allow multiple files (JS, HTML, CSS) in Fiddles to better support building small modular examples.

At the moment you can end up producing some really big Fiddles because there's no way to split anything up. With a lot of front end libraries (Knockout, React, Vue) they encourage a componentized pattern, which lends itself well to splitting the code up into logical components.

It would be great if JSFiddle could support this.

**Comment by Riyad1414** [comment]
R

**Comment by NoOorZ24** [comment]
I was just about to suggest this feature as well. Hope this gets to accepted idea list.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

**Comment by appelgran** [comment]
I can't see how to experiment with js/es modules as it is now. You can not import modules unless they have a url. So for experimenting with modules you'd need to be able to create multiple js panes, name them (or be given a name) and then be able to import them using that name.

![bild](https://user-images.githubusercontent.com/4532739/212021417-62fcd742-6209-40c9-b200-762583a8363f.png)
