### ISSUE TITLE
Grouping Fiddles

### ISSUE THREAD

**Issue by IPWright83** [jsfiddle/jsfiddle-issues#1268]
# Feature Request
Grouping Fiddles

I've got quite a lot of Fiddles now, and to find the one I'm interested in I normally have to go through each page. It'd be really nice if there was a way of grouping these together so I could immediately jump to `D3 examples` or to `React Learning Area` for example and see all the related fiddles.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by IPWright83** [comment]
@oskarkrawczyk Sorry! I did look at the roadmap but managed to miss that one.
