### ISSUE TITLE
Built-in React-JSX boilerplate has a console error

### ISSUE THREAD

**Issue by eblancperso** [jsfiddle/jsfiddle-issues#1269]
Tested with Chrome Version 66.0.3359.139 (Official Build) (64-bit).

[React-JSX boilerplate](https://jsfiddle.net/boilerplate/react-jsx/)

1. Create a new JSFiddle
2. Open the Chrome console
3. Choose the React + JSX boilerplate
4. There is an error in the console: "Each child in an array or iterator should have a unique "key" prop."

**Comment by samsch** [comment]
This line `<li key={item.id}>` expect each item to have an id property, but the items do not.

Can be fixed by changing the items array to be:
```js
items: [
  { id: 0, text: "Learn JavaScript", done: false },
  { id: 1, text: "Learn React", done: false },
  { id: 2, text: "Play around in JSFiddle", done: true },
  { id: 3, text: "Build something awesome", done: true }
]
```
