### ISSUE TITLE
Ability to hide HTML/CSS/Javascript Panels 

### ISSUE THREAD

**Issue by sbr7** [jsfiddle/jsfiddle-issues#1270]
### Here is the problem
* Most of the developers come to jsFiddle to play with their js code snippets. This does not require HTML/CSS panels to be open all the time. JS panel alone can do this. Even result panel is not required most of the times when we can print the result in the developer tools console.

* In other cases designers/developers are playing with HTML and CSS only which makes JS panel a distraction.

### So here is what I propose. 

* introduce more panels in settings which include JS only panel or HTML/CSS/Result only panel thereby giving more real estate and more focus on code.

**Comment by oskarkrawczyk** [comment]
While both assertions are incorrect as our stats tell us, I agree that having the ability to toggle panel visibility would be a nice thing to have – we already have this on our roadmap.
