### ISSUE TITLE
The XSS Auditor blocked access to 'http://fiddle.jshell.net/_display/'

### ISSUE THREAD

**Issue by xr0master** [jsfiddle/jsfiddle-issues#1272]
When I press the "Run" button.

Example: http://jsfiddle.net/rzrgmL09/2/

Chrome 66.0.3359

**Comment by allenluce** [comment]
Same thing happens to me with https://jsfiddle.net/allenluce/c49r5b4b/5/ after I remove and replace the resource link to `spellaphone.js` and then hit Run.  Full message:

```
The XSS Auditor blocked access to 'https://fiddle.jshell.net/_display/' because the source code of a script was found within the request. The auditor was enabled as the server did not send an 'X-XSS-Protection' header.
```

**Comment by allenluce** [comment]
I also get the message when I pull up https://jsfiddle.net/allenluce/c49r5b4b/7/ and hit Run.
