### ISSUE TITLE
JSFiddle not showing preview of fiddles anymore and shows errors in console

### ISSUE THREAD

**Issue by usmanajmal** [jsfiddle/jsfiddle-issues#1274]
Since past few months JS Fiddle has stopped showing a preview of my code and its very hard now to find a fiddle. All I see is a white background like following on Safari as well as Chrome.

Also, I see following errors in my JavaScript console. Those errors might be from one of my fiddles though but can't tell which one exactly.

<img width="1450" alt="screen shot 2018-05-06 at 11 52 46 am" src="https://user-images.githubusercontent.com/1510307/39676841-03b9ede4-5126-11e8-9443-1b5381d1b665.png">
<img width="1661" alt="screen shot 2018-05-06 at 11 55 26 am" src="https://user-images.githubusercontent.com/1510307/39676842-03f26e80-5126-11e8-8c61-818fc3e8d2ff.png">

**Comment by Launder** [comment]
Also like as a Firefox
