### ISSUE TITLE
Chrome warn 'X-XSS-Protection' when frame load js tags

### ISSUE THREAD

**Issue by Glenfiddish** [jsfiddle/jsfiddle-issues#1275]
# Note on existing issues:

- Chrome warn 'X-XSS-Protection' when frame load js tags, make pages load unexpected
- link: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/height-percent/

# Library update request

- highcharts(https://code.highcharts.com/highcharts.js)

**Comment by oskarkrawczyk** [comment]
Same as #1272
