### ISSUE TITLE
Fiddles attributed to my account not showing list

### ISSUE THREAD

**Issue by seraphx2** [jsfiddle/jsfiddle-issues#1276]
I have this particular fiddle: https://jsfiddle.net/seraphx2/xpvt214o/179705/
It is not showing in my saved list of fiddles. I only have 3 there now and this would be my fourth.

**Comment by oskarkrawczyk** [comment]
Hard to say, can you fork it and see if it appears in your fiddles list?

**Comment by seraphx2** [comment]
Hmm.. Interesting. I didn't try that because I originally had an "anonymous" fiddle that I made. Logged in, then forked it hoping it would save it and it didn't. So then, I worked on it for a while, but didn't think even think forking it again would work.  Thanks.
