### ISSUE TITLE
Changes not being saved

### ISSUE THREAD

**Issue by victorqribeiro** [jsfiddle/jsfiddle-issues#1277]
I made a sketch celebrating mother's day this past Sunday and made it public so I could share ir on Facebook. When I log this morning it was gone. A previous version was saved, but not published with the meta tags I wrote.

**Comment by oskarkrawczyk** [comment]
Most likely it wasn't saved correctly - failed silently, or you're just accessing the base version instead of the latest one (fiddle listings default to base version not latest).
