### ISSUE TITLE
When collaborating, Javascript window always scrolls to top

### ISSUE THREAD

**Issue by comp615** [jsfiddle/jsfiddle-issues#1278]
When collaborating with a colleague today, we created a fiddle that had a fairly long (>50 lines) amount of JS. Anytime they edited the javascript or clicked, it would reset my cursor all the way to the top of the JS window, scrolling the panel up. The effect of this is that I was unable to view their typing / changes in the JS window in real-time. Instead I had to ask them to stop editing so that I could scroll the window down. 

Both using Chrome latest.

**Comment by oskarkrawczyk** [comment]
Unfortunately no idea how to fix that.

**Comment by comp615** [comment]
It looks like you manually position the cursors (CodeMirror-cursor), so maybe when an update is received it's just a matter of remembering/computing roughly where the new cursor should be and keeping it there?
