### ISSUE TITLE
Bug: Page sometimes scrolls down

### ISSUE THREAD

**Issue by IPWright83** [jsfiddle/jsfiddle-issues#1281]
I'm unfortunately not 100% certain on the exact steps to reproduce this, but on a number of occasions I've hit the run button and the page has scrolled down slightly.

Unfortunately it's just enough that I've lost access to all the buttons at the top of the page (so I can't re-run or even save any changes). I've found that inspecting the DOM and turning the `overflow: hidden` off on the `body` gives me a scrollbar so I can get back up fortunately!

**Comment by oskarkrawczyk** [comment]
This happens sometimes, but never found a way to fix this – the `overflow: auto` workaround isn't something I want to do.
