### ISSUE TITLE
Update "start with a boilerplate" to act more like a modal

### ISSUE THREAD

**Issue by skcorroh** [jsfiddle/jsfiddle-issues#1282]
Idea for a slight tweak.

I love the new boilerplate feature, but I hate that it pushes the screen down. Can you make it position: fixed to the top so it doesn't push down the main content, and is dismissed once you click in any of the edit boxes.

![image](https://user-images.githubusercontent.com/21206433/40274608-02aa67fe-5b98-11e8-9d00-92ed5d5fba34.png)

**Comment by oskarkrawczyk** [comment]
Thanks for the suggestion but it'll stay as it is.
