### ISSUE TITLE
Cannot add CSS resource to fiddle

### ISSUE THREAD

**Issue by miketalley** [jsfiddle/jsfiddle-issues#1286]
I am trying to add a css resource to my fiddle(https://jsfiddle.net/miketalley/ez2801x4/), but I get an error when trying to do so. Using latest Chrome. Trying to add - https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/components/grid.css

/_add_external_resource/:1 Failed to load resource: the server responded with a status of 422 ()
_dist-editor.js?update_14_05_2017_1:114173 Uncaught (in promise) Error: Request failed with status code 422
    at createError (_dist-editor.js?update_14_05_2017_1:114173)
    at settle (_dist-editor.js?update_14_05_2017_1:114143)
    at XMLHttpRequest.handleLoad (_dist-editor.js?update_14_05_2017_1:114016)

**Comment by y-nk** [comment]
same here with JS resources.

**Comment by oskarkrawczyk** [comment]
Tested, seems to work fine now. Thanks @majkelcc!
