### ISSUE TITLE
Any fiddle with a UI blocking bug will lock out the "my fiddles" screen

### ISSUE THREAD

**Issue by joshcomley** [jsfiddle/jsfiddle-issues#1289]
I have a couple of fiddles that have a loop running forever, locking the UI thread.

Now I am unable to load my fiddles overview page because it tries to preview every single fiddle, thus locking up the UI and leaving me locked out of my own fiddles.

Could we perhaps have the option to disable this feature? I can't get at anything anymore.

**Comment by oskarkrawczyk** [comment]
`README.md`
