### ISSUE TITLE
Keep login credentials valid forever or at least 10x longer

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#1290]
JSFiddle is one of the view sites I have to constantly re-login to. Would love it if it acted more like github/facebook/twitter/stackoverflow/etc... and never logged me out.

thanks for listening

**Comment by oskarkrawczyk** [comment]
Makes sense, will look into it.

**Comment by dwiyatci** [comment]
I've got the same annoyance. The current behaviour is that I have to sign in again every time the browser window is closed 😕 

Hope it's easy to fix. Thank you for the effort @oskarkrawczyk.

**Comment by bulrush15** [comment]
Yes please!

**Comment by oskarkrawczyk** [comment]
Should be fixed.
