### ISSUE TITLE
VIM + Tabbed layout suggestion

### ISSUE THREAD

**Issue by Godje** [jsfiddle/jsfiddle-issues#1292]
In VIM `gt` moves on to the next tab
or `gT` to move to the previous tab.
It would be great to implement this in tabbed layout to be able to move between tabs without using the mouse every time. Minor corrections in class names and similar issues make you go scrolling between tabs all the time, and this feature would fix this.

**Comment by oskarkrawczyk** [comment]
I'll leave this open for now, but this is so minor I don't know if I'll ever get around to addressing it.

**Comment by Godje** [comment]
I hoped that if it's minor, it would be easier to implement.
I am most definitely sure that there are VIM people who really appreciate
how accurate the layout you guys did is. And `gt` would be the only thing
they lack :)

2018-06-10 12:41 GMT-07:00 Oskar Krawczyk <notifications@github.com>:

**Comment by oskarkrawczyk** [comment]
Minor as in a marginal user percentage is actually using the VIM mode. Adding this would take implementing a keyboard shortcut manager

**Comment by Godje** [comment]
That is understandable, I guess. Speaking about tabs and shortcuts, it
would be great to have one, if it doesn't exist yet, not even talking about
VIM users.

2018-06-11 6:55 GMT-07:00 Oskar Krawczyk <notifications@github.com>:
