### ISSUE TITLE
Unclosed regular expression in React + JSX

### ISSUE THREAD

**Issue by VlivesRaw** [jsfiddle/jsfiddle-issues#1293]
Syntax checking doesn't work in React + JSX template as there is "Unclosed regular expression" error in JSX syntax.
To reproduce simply create a new fiddle with React + JSX, then edit something in the JS pane to enable syntax checking -> ` </h2>` tag will be highlighted with the error.

**Comment by steinitz** [comment]
I confirm this issue and note discussions of it, unresolved, around the web.

**Comment by josemigallas** [comment]
Yep, still happening!

**Comment by nermin99** [comment]
Are the developers even working on this??

**Comment by jonshaw199** [comment]
This is still reproducible.

**Comment by bthooper** [comment]
Seems to me like this is still an issue...??
