### ISSUE TITLE
When i am trying Sign up server response with 500 error

### ISSUE THREAD

**Issue by andrew-vogulkin** [jsfiddle/jsfiddle-issues#1295]
![image](https://user-images.githubusercontent.com/31400894/41398948-b0479fca-6fc1-11e8-8463-356d9bbbbdad.png)

**Comment by oskarkrawczyk** [comment]
Looking into it

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by andrew-vogulkin** [comment]
@oskarkrawczyk checked, sing up succes
