### ISSUE TITLE
Tabbed layout

### ISSUE THREAD

**Issue by PogromistDev** [jsfiddle/jsfiddle-issues#1296]
When choosing tabbed layout everything is reset in another areas. It happens not all the time but i missed some code.

**Comment by oskarkrawczyk** [comment]
@PogromistDev Not sure what you mean. Can you provide a screencast of what you're seeing?

**Comment by PogromistDev** [comment]
@oskarkrawczyk choosing "tabs layout" deletes all text in ("html", "css") areas. I can't provide some screencast because this bug doesn't happen all the time.

**Comment by PogromistDev** [comment]
@AMBudnik thank you for proof screencast.

**Comment by AMBudnik** [comment]
@PogromistDev 👍 

@oskarkrawczyk I just got a very similar issue. 
1. I've opened a saved project
2. Made some changes being on `Columns` layout
3. Changes to `Tabs` layout

**Result**: All my changes are gone.

It looks like only the `Tabs` layout messes things up. I did not have any problems using other forms of layout.

**Comment by j-greig** [comment]
Just encountered this bug, lost an hours worth of code 👎

**Comment by oskarkrawczyk** [comment]
Fixed the code being hidden when switching layouts – it wasn't lost, just hidden, refreshing the page would bring the code back.

**Comment by PogromistDev** [comment]
Again it's same thing. It clears all html/js/css and offers "apply local draft version" but pressing that button does nothing. All i can do is copy drafts from that popup.
