### ISSUE TITLE
embed not working

### ISSUE THREAD

**Issue by ghost** [jsfiddle/jsfiddle-issues#1297]
don't know how to explain it other than embed just does not work

1. go to http://jsfiddle.net/uzMPU

2. click embed

3.

404

That page doesn't exist.

**Comment by oskarkrawczyk** [comment]
Thanks for the heads-up, I know where the issue lays. Will fix today.

**Comment by TiesdeKok** [comment]
Just a heads-up, the embed functionality is still broken.  

From what I can tell it should be a quick fix, the `src` used for the iframe is missing a forward slash:
``` 
src="//jsfiddle.net/uzMPUembedded/"
```

to:

```
src="//jsfiddle.net/uzMPU/embedded/"
```

**Comment by sok0** [comment]
issue still exists, thanks
