### ISSUE TITLE
New Feature: It would be great if a console panel could be provided

### ISSUE THREAD

**Issue by lff0305** [jsfiddle/jsfiddle-issues#1298]
Currently to debug, I usually use console.log() and open the Dev tool from Chrome/Firefox.
I think if there is a console panel on UI to show the log messages, it will be much more convenient.

Or maybe some pre-defined log functions ?

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
