### ISSUE TITLE
404 for fiddle.jshell.net

### ISSUE THREAD

**Issue by tgreening** [jsfiddle/jsfiddle-issues#1299]
When I try to access, or do a callback to, https://fiddle.jshell.net/tgreening/eszqkttL/ I get a 404 error.  This worked a few weeks ago.  Any help appreciated.

**Comment by oskarkrawczyk** [comment]
Accessing `fiddle.jshell.net` was never something anyone should do, it was accessible because of a bug, that bug is now fixed.

**Comment by tgreening** [comment]
I didn't know that.  OK is there still a way to do an OAuth2 callback URL?

**Comment by oskarkrawczyk** [comment]
Not sure what OAuth2 you're referring to, since we don't have that in JSFiddle. That fiddle is accessible from `jsfiddle.net` – http://jsfiddle.net/tgreening/eszqkttL/

**Comment by tgreening** [comment]
OAuth2 callback will be https://jsfiddle.net/tgreening/eszqkttL/?code=ajaj.....

I need to intercept that call and grab that code in mu javascript code without rendering the page first.

Thanks for your help.

**Comment by tgreening** [comment]
I figured it out!  If you do a document.referrer in the JavaScript you get the full request with parameters and can parse it.
