### ISSUE TITLE
GitHub-integration does not update fiddle when demo.details changes

### ISSUE THREAD

**Issue by SirBif** [jsfiddle/jsfiddle-issues#1302]
If you update the demo.details file in your GitHub project, the change does not get picked up by jsfiddle, which will still display the old version.

Steps to reproduce:

1. Create a project with all the necessary files on GitHub (following instructions here http://doc.jsfiddle.net/use/github_read.html) (e.g. https://github.com/SirBif/jsFiddleGithubDemo)
2. Open the link to the GitHub integration (e.g. http://jsfiddle.net/gh/get/mootools/1.2/SirBif/jsFiddleGithubDemo/tree/master/Demo/)
3. Push a change on the project (see https://github.com/SirBif/jsFiddleGithubDemo/commit/f24845d35624df77c8501197c0f2f4abe2303541)
4. Reopen the GitHub integration link. Notice that it still uses the demo.display file that was available at step 2

Expected behaviour:
The jsfiddle should use the updated demo.details file (in my example, it should show "bug report" as name and description)

**Comment by oskarkrawczyk** [comment]
Should be fixed
