### ISSUE TITLE
Is collaboration still supported? It just doesn't seem to want to function at all

### ISSUE THREAD

**Issue by RandomDude777** [jsfiddle/jsfiddle-issues#1304]
Is collaboration a thing or has it been deprecated? It doesn't seem to actually do anything / work correctly..

**Comment by oskarkrawczyk** [comment]
@RandomDude777 Can you elaborate? Saying that "it doesn't seem to actually do anything" and "work correctly" are two different things.

What are you seeing. Are you getting errors. Can other people connect to your session. Can you provide a detailed explanation or at least a screencast.

**Comment by RandomDude777** [comment]
I was a tad upset when typing that, apologies.

When I initiate a collaboration I send the link to a friend and once in the session things seem to look quite synced. When I start writing code however, the code does not sync, the only thing that appear to sync was the settings, themes, layout etc.

Upon hitting refresh things start to get weird, the end of the url starts to iterate in numbers every refresh and then when my partner is to refresh he loses connection to me permanently and I'm spammed with the ability to join him. Upon clicking the join him button my code syncs for him but I cant see the code he sees.

Only way to fix this was to wipe cookies on both myself and partner.

This behavior is as bizarre as my explanation and I'll update with a video as I honestly can not explain this.

No console errors, newest version of chrome.

**Comment by ashubham** [comment]
@oskarkrawczyk I am seeing the same issue as @RandomDude777 is seeing above. I did not try clearing the cookies though. It used to work nicely earlier but recently its broken.

It goes out of sync right of the bat and the numbers in the address bar keep incrementing. The remote user does not see any changes as the numbers on his address bar are not incrementing perhaps.

**Comment by camflan** [comment]
Same issues here, I can see the mouse movements of others but no code ever syncs.

**Comment by aashishnagpal** [comment]
@oskarkrawczyk @ashubham @camflan @RandomDude777 
Even I have been seeing this since past 2 months. I did get it to work some of the times by joining the session (which I created and sent to my friend) as a third collaborator. Somehow when the auto bumping the version feature is on, no two people are on the same page and thus can't see what the other is typing. I had to switch that feature off and then create a brand new session to be able to let my friend and myself see the same code.

There could be other underlying problems as well which we aren't aware of.

**Comment by RevolvingDCON** [comment]
good bot

**Comment by RevolvingDCON** [comment]
oh.. bad bot

**Comment by RevolvingDCON** [comment]
@oskarkrawczyk @ashubham @camflan @RandomDude777

> Is collaboration a thing or has it been deprecated? It doesn't seem to actually do anything / work correctly..

Having the same issues as all above, collaboration has too many bugs to be able to debug on my own. Form strange iterative bugs to permanent disconnection of partner I understand that a blanket statement such as "it doesn't work" does not help the team solve the issue. The only steps I can give to help replicate the issues is: Literally try use it, it's plagued by bugs.

**Comment by RevolvingDCON** [comment]
Does the future of jsfiddle have much room for future development of collaboration? It does appear to be promising I just wish it worked.

**Comment by stalniy** [comment]
```
Uncaught TypeError: Cannot read property 'dependencies' of undefined
    at r (_dist-editor.js?update_14_12_2018_1:1)
    at HTMLScriptElement.<anonymous> (_dist-editor.js?update_14_12_2018_1:1)
togetherjs.com/lib/codemirror.js?bust=1545989843890:1 Failed to load resource: the server responded with a status of 404 ()
require.js?bust=1545989843890:8 Uncaught Error: Script error for: ../../lib/codemirror
http://requirejs.org/docs/errors.html#scripterror
    at A (require.js?bust=1545989843890:8)
    at HTMLScriptElement.onScriptError (require.js?bust=1545989843890:29)
```

**Comment by oskarkrawczyk** [comment]
@stalniy Completely unrelated error message.

**Comment by oskarkrawczyk** [comment]
Few things with the collaboration:

1. TogetherJS is no longer maintained, it was previously maintained under Mozilla Labs but that's no longer the case, looks like part of the library just broke.
2. In the meantime there are some problems with the collaboration that constituted after the introduction of layout switcher - basically both connected parties should have the same layout turned on, currently that is not enforced.

**Comment by oskarkrawczyk** [comment]
Fixed a bunch of things in the collaboration tool. Should work fine for now.

Since TogetherJS is no longer maintained and it [doesn't look like there's much hope it will be](https://github.com/mozilla/togetherjs/issues/1127), we'll eventually have to find an alternative solution.
