### ISSUE TITLE
Autocomplete popup when not wanted

### ISSUE THREAD

**Issue by cobalthex** [jsfiddle/jsfiddle-issues#1305]
Autocomplete opens after pasting code, which is particularly annoying when pressing enter to create a new line after pasting will autocomplete something random

autocomplete also opens after opening braces

suggestion, only open auto complete after a word character is typed or after period, etc

**Comment by oskarkrawczyk** [comment]
Disabled a few key combinations that were opening the autocomplete previously.

**Comment by regs01** [comment]
INS, DEL, HOME, END, PGUP, PGDN also opening autocomplete window. Navigating through lines and deleting something is quite tricky.
