### ISSUE TITLE
Missing top-menu 

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1306]
Sorry if it has been posted before (I've checked 2 first sites of the board).

I'm having an odd issue from time to time when the top-menu (Run, Update, ..) is being shifted outside of a visible area, As you can see here 

![image](https://user-images.githubusercontent.com/10757813/41775766-83487e44-7625-11e8-92f7-5071f06a4564.png)

there's no scroll to move to the top-menu.

What I do to get it back and be able to save my fiddle:
1. find  
```html
<form method="post" id="show-result" target="result" action="http://fiddle.jshell.net/_display/">
```
2. add `margin-top:7em` to the element via dev tools.

I believe that it happens only when I have the console (bottom layer) opened but I did not have time to test it more.

Besides that I'm really happy with JSFiddle. I've been working on it since 2015. Good work guys 👍 

### Replicated at:
Browser: Chrome 67,
System: Windows 10

**Comment by shockthetoast** [comment]
I've been having this issue since at least the time the OP posted, and am still having it now. Is there any chance this will be fixed? It completely breaks jsfiddle for me.

**Comment by juan-dalmasso-lrn** [comment]
Same issue

**Comment by AMBudnik** [comment]
Not sure if they open an already closed issue report. It's 1.5 years since I've posted it.

**Comment by AMBudnik** [comment]
Just to let you know that this happened to me today 2 times
1. on Chrome 79
2. on FF 72

**Comment by oskarkrawczyk** [comment]
https://github.com/jsfiddle/jsfiddle-issues/issues/1385
