### ISSUE TITLE
I cannot choose a `classic` layout

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1308]
As shown below. I try to choose the `Classic` layout but end up with `Tabs`. I've already closed and reopened the browser and it is still the same.

![gif](https://user-images.githubusercontent.com/10757813/41845293-4cf2a27a-7873-11e8-9158-ab94c46d7c40.gif)

the issue with missing content has been already mentioned at https://github.com/jsfiddle/jsfiddle-issues/issues/1296

**Comment by oskarkrawczyk** [comment]
Should be fixed
