### ISSUE TITLE
Tidy wipes indentations.

### ISSUE THREAD

**Issue by XTard** [jsfiddle/jsfiddle-issues#1309]
I have the "indent with tabs" option enabled and i have indent size defined and everything works well, but after I use the "tidy" option from the menu it wipes all indentations with tabs and replaced them with spaces.

**Comment by XTard** [comment]
This issue is still not fixed... Really important quality of life issue.

**Comment by oskarkrawczyk** [comment]
No plans on fixing this in the current Tidy implementation as it’s going to be refactored.

As tag states, will not fix.
