### ISSUE TITLE
jsfiddle visits statistics

### ISSUE THREAD

**Issue by vitorhsb** [jsfiddle/jsfiddle-issues#131]
Whenever we share a fiddle to the public, it would be awesome to have statistics about page views, "run" actions, etc.

**Comment by jaseonline** [comment]
Has this feature been implemented or are you still considering it?

**Comment by oskarkrawczyk** [comment]
It'll be there for the 2.0 rewrite – progress can be tracked here https://trello.com/b/LakLkQBW/jsfiddle-roadmap
