### ISSUE TITLE
Missing a fiddle in my fiddles list

### ISSUE THREAD

**Issue by fharper** [jsfiddle/jsfiddle-issues#1310]
I created and have access with the link to this fiddle https://jsfiddle.net/fharper/ywx79grv/1/ but it doesn't appear in either my public or all fiddles list.

**Comment by zalun** [comment]
Please add a title in the `Fiddle meta` section to make it appear in your public list.

**Comment by majkelcc** [comment]
This fiddle has been created anonymously (checked in the database). You could create version 1 of this fiddle, but that does not make this fiddle appear on your fiddles list.

Note that on jsfiddle:

1. You can add a new version to anyone's existing fiddle (including created anonymously).
2. Username in the url can be swapped with any other username and the link will still work:
  https://jsfiddle.net/fharper/ywx79grv/
  https://jsfiddle.net/majkel/ywx79grv/

I guess this is the source of confusion here.

**Comment by fharper** [comment]
Oh, sorry about that, thanks.

**Comment by binki** [comment]
How do I convert an anonymous fiddle to a named one then?

**Comment by oskarkrawczyk** [comment]
Anonymous fiddle can be forked under your account. Title and description can be set from the sidebar.
