### ISSUE TITLE
Getting Error while trying to get the user's fiddle using API 

### ISSUE THREAD

**Issue by MANOJMANI07** [jsfiddle/jsfiddle-issues#1311]
Getting following error on calling API to get the user's fiddle:

Refused to execute script https://jsfiddle.net/api/user/{username}/demo/list.json?callback=Api because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

The API is not returning the callback which could be used for JSONP request. Earlier this API used to work for JSONP request.

**Comment by MANOJMANI07** [comment]
Any updates on the issue??

**Comment by majkelcc** [comment]
Hi @MANOJMANI07, we just deployed a fix to this API. Can you confirm it works as expected?

**Comment by MANOJMANI07** [comment]
Still, it's throwing the MIME type ('application/json') is not executable, and strict MIME type checking is enabled. The MIME type for the response of the URL is application/json, so can't be used for jsonp request as it should have been application/javascript.

**Comment by MANOJMANI07** [comment]
Any update?

**Comment by majkelcc** [comment]
@MANOJMANI07 please check if it's working now, if not could you provide us with an example fiddle?

**Comment by MANOJMANI07** [comment]
Thanks for the fix. One more thing I wanted to know, is there any limit on how many fiddle's info we can get from API?

**Comment by majkelcc** [comment]
You can fetch up to 100 fiddles in one request + you can use a `start` param, which works exactly like `offset`. With that, you can fetch all of the user's fiddles.

**Comment by MANOJMANI07** [comment]
Thanks for the info
