### ISSUE TITLE
Why not have the favicon.ico?

### ISSUE THREAD

**Issue by ifyour** [jsfiddle/jsfiddle-issues#1317]
Why not have the `favicon.ico`? It can increase the recognition and brand of the website.

### Screenshot
![image](https://user-images.githubusercontent.com/15377484/42311753-2c96125e-8071-11e8-9a6c-8f5644d48768.png)

**Comment by ifyour** [comment]
## SVG files

<div align="center">🙌 free provide by Iconfont </div>

<br>

![image](https://user-images.githubusercontent.com/15377484/42720465-bc9052fe-8759-11e8-97e9-20b6affc166c.png)

## Download

👉[*Click here*](http://www.iconfont.cn/search/index?searchType=icon&q=JSFiddle&fromCollection=-1)

**Comment by contentter** [comment]
I support, Will.

**Comment by oskarkrawczyk** [comment]
Fixed
