### ISSUE TITLE
Resources don't work with POST

### ISSUE THREAD

**Issue by mhevery** [jsfiddle/jsfiddle-issues#132]
jsFiddle allows creation of fiddles from other pages using the form POST API. However this does not work with resources.

Steps to Reproduce
1) open http://jsfiddle.net/mhevery/pperN/
2) click on the 'edit in jsFiddle' this will open new jsFiddle window using the POST API
3) Notice that the Result pane shows: Hello {{name}}! (INCORRECT)
4) click on the run
5 Notice that the Result pane shows: Hello World! (CORRECT)

What happened?
1) When the POST is first made the resource is not included in the Result pane HTML which causes the initialization block to fail
2) Clicking on 'run' without any edits updates, correctly places the resource into the result pane resulting in the correct behavior.

It should not be necessary to click 'run' before the pane has the right resource included.

**Comment by KyleMit** [comment]
Still an issue on Chrome 41.  Any external resources in a POST request are not returned to the result panel on the initial response.  They are however loaded into the resources tab and included in subsequent runs.

Here's an example that will repo the issue:

```html
<form method='post' target='check' action='http://jsfiddle.net/api/post/library/pure/'>
    <input name='resources' value="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js" />
    <input name='js' value="$('body').css('background','blue');" />
    <input type='hidden' name='wrap' value='l'/>
    <input type='submit' value="Create Fiddle" />
</form>
```

1. Open up the demo in this [fiddle][2]
2. Click `Create Fiddle` to submit a post
3. The resulting page *should* turn blue from the included jQuery. Instead it is white.
4. Click run again and the resources are included

If you monitor the requests that get made over the wire in [Fiddler][3], it'll look like this:

[Imgur Album][5]

After the initial post, jsFiddle will make a second post to load the result panel.

In Chrome, but not in firefox, it won't send along the `add_external_resources` during the first automatic post for the `/_display/` panel.  When re-running, it will send along the request.  This is probably related to [Refused to execute a JavaScript script when source code of script found within request][4]

[1]: http://doc.jsfiddle.net/api/post.html
[2]: http://jsfiddle.net/KyleMit/ebkg5kwh/
[3]: http://www.telerik.com/fiddler
[4]: http://stackoverflow.com/q/1547884/1366033
[5]: http://imgur.com/a/zBGPY
