### ISSUE TITLE
API delivers invalid JSON

### ISSUE THREAD

**Issue by KooiInc** [jsfiddle/jsfiddle-issues#1323]
The [jsFiddle-api](http://doc.jsfiddle.net/api/fiddles.html) currently seems to change pretty frequently, without changes being reflected in the documentation. 

Currently the json delivered by it looks like (formatted for readability) 

```javascript
[
  {
    :framework=>"No-Library", 
    :version=>27, 
    :description=>"", 
    :title=>"Automated form field validity checker #2", 
    :url=>"//jsfiddle.net/Someone/rmyuzafv/", 
    :author=>"Someone", 
    :latest_version=>27, 
    :created=>"2018-06-24 12:12:11"
  }, 
  {:framew ... }
]
````

Will there be a definitive and documented version any time?

**Comment by majkelcc** [comment]
@KooiInc mind pointing out what changed? 😉

**Comment by majkelcc** [comment]
@KooiInc sorry, we spotted the problem. Should be fixed now!

**Comment by KooiInc** [comment]
@majkelcc Yes, fixed, thanks! I'm using the api [here](https://testbed.nicon.nl/fiddles/), added more error handling up there to be able to log and report unexpected errors from the api
