### ISSUE TITLE
How do I turn off the Javascript pane? 

### ISSUE THREAD

**Issue by bulrush15** [jsfiddle/jsfiddle-issues#1325]
Firefox v61 on Windows 7

Sometimes I don't use the JS pane, how do I turn it off? I tried right clicking the pane, clicking the JS dropdown arrow to set language to "none" (there is no "none") and can't seem to turn it off. 

Sorry, there doesn't seem to be a FAQ, the wiki on Github is blank.

**Comment by oskarkrawczyk** [comment]
There's no way to turn off a panel, but you can switch to tabbed mode.
