### ISSUE TITLE
[Suggestion] Pure code fiddles.

### ISSUE THREAD

**Issue by VasVadum** [jsfiddle/jsfiddle-issues#1327]
I couldn't think of any keywords to find if this has been posted before or not..

I was hoping that jsfiddle, would add a method of having pure code only fiddles that don't render as a mini webpage in the user's fiddle folder.

![image](https://user-images.githubusercontent.com/1490797/42595934-7cb5302e-8519-11e8-8917-deb0de1857e4.png)

As you can see there, my user page shows two blank white fiddles because those two are pure javascript only, for the game Screeps.  jsfiddle is the best collaborative tool I could find for coding with others after all so I came back to start using jsfiddle again. (Would actually be nice if you expanded to support other languages too like lua and C#, but then you'd have to rename your site to codefiddles or something. xP)

But anyway, so I'm using jsfiddle for pure javascript right now and would like to not have the big blank white preview things.  And while editing I don't want an HTML tab or a CSS tab or even the preview tab as it wouldn't run anyway.  I just couldn't find any better alternatives for collaborating coding with someone unfortunately.

I would also have suggested folders but it looks like thats already in the roadmap.  :P

**Comment by VasVadum** [comment]
Seriously? So you hide away issues and requests after they've been here a while to make it seem like you guys maintain things when you just have a bot hide it all for you?

**Comment by oskarkrawczyk** [comment]
Added request to our trello board - https://trello.com/c/iNDtwwMo/80-show-code-in-fiddle-listings-instead-of-results

If this gets a number of upvotes we'll implement it.
