### ISSUE TITLE
Showing all Fiddles with disable_render=true crashes the browser

### ISSUE THREAD

**Issue by MatheusMCuba** [jsfiddle/jsfiddle-issues#1329]
When loading all my fiddles with the option `disable_render=true`, the page starts to load the Iframe's with the `data-target` set to `#`, causing then to load the own page of _All Fiddles_, and causing a infinite loop, finnaly crashing the browser

![image](https://user-images.githubusercontent.com/32616871/42762632-2b00323e-88e7-11e8-8ec4-557442a19403.png)

Also, complementing [#1327](https://github.com/jsfiddle/jsfiddle-issues/issues/1327), I consider making this option more visible to the user's, letting they know they can disable the previewing of their fiddles in the dashboard

**Comment by oskarkrawczyk** [comment]
Thanks for the info. This has now been fixed.
