### ISSUE TITLE
The JavaScript section isn't working

### ISSUE THREAD

**Issue by Tacoman495** [jsfiddle/jsfiddle-issues#1333]
I'm just trying to use an extremely basic JavaScript function, and it's not doing anything:
https://jsfiddle.net/Tacoman495/ozb8ug1v/1/

**Comment by oskarkrawczyk** [comment]
Not a JSFiddle issue, see console for errors in your JS.

**Comment by Tacoman495** [comment]
What console?

**Comment by oskarkrawczyk** [comment]
Devtools console
