### ISSUE TITLE
Echo features not working

### ISSUE THREAD

**Issue by KooiInc** [jsfiddle/jsfiddle-issues#1338]
It seems like none of the [echo](http://doc.jsfiddle.net/use/echo.html) features work anymore.

**Comment by KooiInc** [comment]
Tnx @oskarkrawczyk, are you going to update te docs?

**Comment by nhuynh3** [comment]
what is the correct usage? @oskarkrawczyk

**Comment by zalun** [comment]
http://jsfiddle.net/zalun/NF2jz/ is not working and it's quite old - was there a change in API?
