### ISSUE TITLE
I would ask for help. To connect files through Do.js and Do.css in Do.html

### ISSUE THREAD

**Issue by Trzinka** [jsfiddle/jsfiddle-issues#1339]
Hello.
 I would ask for help. 

I'm sorry for the mystery because I'm trying to get help for the first time. 

Namely, I try to activate through individual files through Do.js and Do.css in Do.html and we at https://jsfiddle.net/ works fine when, however, I want to run through the browser, but it only shows me the inscription as not taking into account the Do.js file . 

Thank you. 
Robert.
https://jsfiddle.net/#&togetherjs=wxURqUy5Hr

**Comment by oskarkrawczyk** [comment]
@Trzinka Sorry, I'm not sure I'm following. Can you provide a screeencast of the issue you're having?

**Comment by Trzinka** [comment]
Thanks for the answer, but I solved the problem.
