### ISSUE TITLE
Some options not visible.

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [jsfiddle/jsfiddle-issues#1341]
Cant choose jquery ui for example:
![imagem 3](https://user-images.githubusercontent.com/3578953/43169759-ba789b6c-8f78-11e8-8016-c43076d7c485.png)

**Comment by oskarkrawczyk** [comment]
@erickdeoliveiraleal Can you elaborate? I'm not sure what's not visible.

**Comment by oskarkrawczyk** [comment]
Ah ok, the `Framework script attr`. Will look into that.

**Comment by oskarkrawczyk** [comment]
Since the panel can be resized, and the popover will then show in full, I'm closing this issue.

This is so minor there's no point in reworking the popover library if there's already a way to mitigate the problem.
