### ISSUE TITLE
API: 404 when listing fiddles by user

### ISSUE THREAD

**Issue by facundovictor** [jsfiddle/jsfiddle-issues#1343]
### Description
The endpoint `/api/user/{username}/demo/list.json` is not working.

See reference: http://doc.jsfiddle.net/api/fiddles.html#input
### Expected behavior
HTTP `200` response with following body:
```js
Api({
  "status": "ok",
  "list": [
    {
      "description": "...",
      "author": "{username}",
      "url": "...",
      "created": "...",
      "framework": "...",
      "version": 123,              // base version number
      "latest_version": 234,       // latest version number
      "title": "..."
    },
    // ...
  ],
  "overallResultSetCount": 12      // number of the results
});
```
### Observed behavior
HTTP `404` response with following body:
```
{"status":404,"error":"Not Found"}
```

### How to reproduce it?
```
curl https://jsfiddle.net/api/user/facucode/demo/list.json
```

**Comment by oskarkrawczyk** [comment]
There's no `facucode` user - please note that this is case sensitive.

Tested with my username and it works fine: https://jsfiddle.net/api/user/oskar/demo/list.json

**Comment by loganscabbyface** [comment]
>  @``
