### ISSUE TITLE
code hinting makes another guess after typing ;

### ISSUE THREAD

**Issue by jlocca** [jsfiddle/jsfiddle-issues#1346]
Safari 11.1.2
macOS 10.13.6

After closing a css declaration with a semi-colon, code hinting seems to assume (incorrectly) that I want to add another declaration. Unfortunately, this usually results in accidentally starting a new declaration (align-content:), which becomes annoying after a while. :)

I realize that code hinting is in beta. Just hoping the behavior will be addressed.

Thank you!

![screen shot 2018-07-31 at 1 54 39 pm](https://user-images.githubusercontent.com/16841852/43486982-0f65d990-94ca-11e8-9315-c2691c9ac3da.png)

**Comment by oskarkrawczyk** [comment]
Thanks for the heads-up @jlocca. It's weird, I'm sure I've fixed this already :)

**Comment by oskarkrawczyk** [comment]
This has now been fixed.
