### ISSUE TITLE
Boilerplate pops up when jsfiddle is called from the API

### ISSUE THREAD

**Issue by michaelkolber** [jsfiddle/jsfiddle-issues#1349]
When clicking on any link on the MDN docs to open code in JSFiddle, the boilerplate pops up. I don't think this makes sense because the POST request should be asking for any libraries it needs. As a user I should just be viewing and perhaps editing the POSTed MDN code.

Example: https://developer.mozilla.org/en-US/docs/Sandbox (Click on the button that says "Open in JSFiddle").

At the very least, I think it would make more sense to have the Close button on the top right, as that's where they usually are in UI's. I don't think pushing down the whole screen to show these options is good UI, but that's just personal opinion :)

**Comment by jeremiahsmall** [comment]
Agreed, it would be quite nice if the form had an option to specify this should be closed. E.g.

    <input type="hidden" name="closeHB" value="true">

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by jeremiahsmall** [comment]
I confirmed that the hello-bar now defaults to closed when posting content via form to http://jsfiddle.net/api/post/library/pure

Thanks!
