### ISSUE TITLE
Not working typescript inheritance

### ISSUE THREAD

**Issue by digilab2017** [jsfiddle/jsfiddle-issues#1351]
Hello,

this simple code does not work in JsFiddle. 

http://jsfiddle.net/Corvi/pm2nktbg/

"Uncaught ReferenceError: _super is not defined"

What is going wrong here? Seems to work everywhere else.

**Comment by oskarkrawczyk** [comment]
The TypeScript transpiler is outdated, until we change the way transpilers are working in JSFiddle we have to stick with the outdated one since the new one doesn't work in our setup.

**Comment by oskarkrawczyk** [comment]
Merging into #1079
