### ISSUE TITLE
Fiddles not showing in "All your fiddles"

### ISSUE THREAD

**Issue by BarryStokes** [jsfiddle/jsfiddle-issues#1352]
I have created an account on https://jsfiddle.net and created several fiddles.

When I click the button in the top-right and select "All your fiddles" I get taken to a page which tells me "You don't have any fiddles"

I can access the fiddles I have made by typing the URL in, so they're definitely somewhere.

Am I doing something wrong?

**Comment by BarryStokes** [comment]
Ok, so doing further testing if I create a fiddle entirely from scratch it then seems to work (and I get different buttons at the top of the screen).

If I create one from the boilerplate options it doesn't seem to work.

**Comment by majkelcc** [comment]
Hi @BarryStokes,

> I can access the fiddles I have made by typing the URL in, so they're definitely somewhere.

Can you give an example of such fiddle?

**Comment by BarryStokes** [comment]
https://jsfiddle.net/Ceisc/xpvt214o/579269/

**Comment by majkelcc** [comment]
@BarryStokes this is a fiddle created originally by a different user. You can add new versions to it, but it won't appear on your fiddles list until you fork it.

**Comment by BarryStokes** [comment]
OK, I find it slightly confusing that the "Start with a boilerplate" option functions in this way as these effectively appear to be new fiddles and the URL for it has my username in it, hence making me think it should appear under my fiddles.

Obviously it's not overly arduous to click on the fork button after starting a new fiddle from boilerplate, but it seems unnecessary.

**Comment by majkelcc** [comment]
@BarryStokes when you click on "Start with a boilerplate" you see your username in the url?

**Comment by BarryStokes** [comment]
If I go to "Start with a boilerplate" and select "Bootstrap", for example, I get a URL of https://jsfiddle.net/boilerplate/bootstrap

If I then press Ctrl-S, which I assumed is a save function, it changes the URL to https://jsfiddle.net/Ceisc/aq9Laaew/146418/

Which totally makes me believe that this is a fiddle I own and should show up in My Fiddles.

**Comment by majkelcc** [comment]
@BarryStokes oh, I see the problem now. As you can see, `Save` button is hidden on boilerplate fiddles, so working `Ctrl-S` is a bug. At least it should automatically fork the fiddle before saving.

cc @oskarkrawczyk

**Comment by BarryStokes** [comment]
I would have thought the best default behaviour for it would be that when someone starts from boilerplate that it just forks the code and makes what they get theirs and part of their fiddles.

The assumption on this being that they want a blank template to start working on something new.

**Comment by oskarkrawczyk** [comment]
@majkelcc Indeed, having `CTRL+S` on that view is a bug. Thanks for the info! Will fix.

@BarryStokes The boilerplate is the systems fiddle, forking it makes it yours - this is the way it was designed.

**Comment by alph4delta** [comment]
> I have created an account on https://jsfiddle.net and created several fiddles.
> 
> When I click the button in the top-right and select "All your fiddles" I get taken to a page which tells me "You don't have any fiddles"
> 
> I can access the fiddles I have made by typing the URL in, so they're definitely somewhere.
> 
> Am I doing something wrong?

it sometime is gone, it sometime back again. you can re type it via search engine and enter.

**Comment by hawkeye64** [comment]
This bug (https://github.com/jsfiddle/jsfiddle-issues/issues/1388) may be related.

**Comment by johnyradio** [comment]
automatically forking a boilerplate makes sense. That's an obvious, always workflow. 
Otherwise, if it's not forked, then you're letting everyone edit your boilerplates.
