### ISSUE TITLE
Code validation confused by rest/spread operators

### ISSUE THREAD

**Issue by KooiInc** [jsfiddle/jsfiddle-issues#1354]
Code validation doesn't seem to like rest/spread operators. See image and [fiddle](http://jsfiddle.net/KooiInc/tLoc387j/)

![image](https://user-images.githubusercontent.com/836043/43992081-3947eff2-9d79-11e8-98cf-4f64764dd271.png)

**Comment by oskarkrawczyk** [comment]
I've updated to the latest https://github.com/jshint/jshint version, hopefully it patches up these issues.

**Comment by KooiInc** [comment]
Works, thanx @oskarkrawczyk

**Comment by DRSAgile** [comment]
> 
> 
> I've updated to the latest https://github.com/jshint/jshint version, hopefully it patches up these issues.

Sadly, it was not enough; I am still getting this error:
https://jsfiddle.net/fv94x5wd/2/

**Comment by oskarkrawczyk** [comment]
@DRSAgile Yep, file the issue on their end. We're using version 2.9.6

**Comment by oskarkrawczyk** [comment]
Nope
