### ISSUE TITLE
Privacy policy has a broken link or is not available.

### ISSUE THREAD

**Issue by marc22alain** [jsfiddle/jsfiddle-issues#1355]
When visiting `https://jsfiddle.net/privacy`, all that is shown is this text: "#privacy#".

Maybe this is a bug, maybe you haven't got one yet, it's hard to tell.

Surely this doesn't comply with GPDR (or the privacy legislation in many other jurisdictions), and since you are (probably) selling my info for ad revenue, I need to know what you are going to do with it before I sign up.

**Comment by oskarkrawczyk** [comment]
Privacy was outdated and I'm in the middle of rewriting.

We're not selling user data and never were. Our Ad provider is specifically chosen because it doesn't do remarketing and has no need for user data.
