### ISSUE TITLE
jquery boilerplate should have toggleClass

### ISSUE THREAD

**Issue by joshbouganim** [jsfiddle/jsfiddle-issues#1356]
The jquery boilerplate code has a button that allows the user to change the color.  after the button is clicked, the colors change but the button remains leading the user to believe the color can be changed back. 

steps to reproduce:
1. load jquery boilerplate example
2. click "Change Color" button
3. click "Change Color" button

Results:

Actual:
color does not change back

Expected:
color changes back

Resolution:
change ```banner.addClass("alt");``` to ```banner.toggleClass("alt");```

**Comment by SimonSands** [comment]
Yeah
