### ISSUE TITLE
Closing Pane

### ISSUE THREAD

**Issue by BenHayat** [jsfiddle/jsfiddle-issues#1357]
Hi;
Is there a way to close the following pane? It's just waste of space being open at all time.
If not, I'd like to request as a feature request.
Thanks!

![pane](https://user-images.githubusercontent.com/7861196/44158421-9f15d180-a082-11e8-8250-f80c03f41203.jpg)

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
