### ISSUE TITLE
Saved Fiddles not showing when logged in

### ISSUE THREAD

**Issue by mark01001101** [jsfiddle/jsfiddle-issues#1359]
When logged in, none of my save fiddles show up when I click on all your fiddles.

It goes to this address: https://jsfiddle.net/user/dashboard/fiddles/

And receive this message:
404
That page doesn't exist.

**Comment by mark01001101** [comment]
When logged in, none of my save fiddles show up when I click on all your fiddles.

It goes to this address: https://jsfiddle.net/user/dashboard/fiddles/

And receive this message:
404
That page doesn't exist.

**Comment by oskarkrawczyk** [comment]
What's your username?

**Comment by mark01001101** [comment]
login is springston.mark@gmail.com

Here is an example of a saved program: https://jsfiddle.net/mark01001101/uq6ymf42/

I've attached a screenshot of the page doesn't exist. I have many saved programs.

Any help is appreciated.
<img width="549" alt="receive this message" src="https://user-images.githubusercontent.com/42771557/44814346-6873a700-abaa-11e8-82ce-c1d0fc55d4a9.png">
<img width="263" alt="click all your fiddles" src="https://user-images.githubusercontent.com/42771557/44814347-690c3d80-abaa-11e8-87d0-b9dd1a3d0a39.png">



--Mark

**Comment by mark01001101** [comment]
How do I contact JSfiddle on this issue?

**Comment by mark01001101** [comment]
my username is mark01001101

**Comment by mark01001101** [comment]
It has been almost 2 weeks and I have not received any response. I still receive the same message and thus do **not** have access to any of my non-public fiddles.

**Comment by mark01001101** [comment]
I am now 40 plus days in not being able to access my saved JSfiddles and there also has been no response here by JSfiddle staff.

**Comment by oskarkrawczyk** [comment]
Unfortunately I don't see why you're getting a 404, cannot replicate this on any other account.

This needs further investigation.

**Comment by alexweinstein** [comment]
I also get the 404 when trying to view non-public fiddles. 

![jsfiddle_bug](https://user-images.githubusercontent.com/222681/47876399-a3cf6380-ddef-11e8-9cfe-511e9acd1d0d.gif)

**Comment by hawkeye64** [comment]
@mark01001101 I believe you may be talking about this bug: https://github.com/jsfiddle/jsfiddle-issues/issues/1388
Unfortunately, your fiddles may be gone. :(

**Comment by alexweinstein** [comment]
I have the same issue when navigating to https://jsfiddle.net/user/settings/

Would #1388 explain this behavior too?

**Comment by hawkeye64** [comment]
@alexweinstein Nope.  https://jsfiddle.net/user/settings/ works for me though. Have you tried to go to that link on a different computer?

**Comment by alexweinstein** [comment]
Yes, I've tried multiple browsers. Here's a screencast of the behavior when navigating to user/settings in Chrome Version 70.0.3538.77 macOS 10.12.6:
![jsfiddle_bug2](https://user-images.githubusercontent.com/222681/48227320-f371da00-e36f-11e8-9da2-cd931da91003.gif)

**Comment by alexweinstein** [comment]
Update: My issue is now resolved. My settings and non-public fiddles are now showing correctly.

**Comment by oskarkrawczyk** [comment]
We've added a fix and are currently running updates on the database to resolve problems with fiddles created in the past.

I'm leaving this ticket open until we finish updates and check that everything is running correctly.

**Comment by mark01001101** [comment]
Oskar,

Currently I can also see my fiddles in All your fiddles. Thanks to you and
the JSfiddle team.

--Mark

**Comment by oskarkrawczyk** [comment]
Fixed.
