### ISSUE TITLE
Width tooltip doesn't always show.

### ISSUE THREAD

**Issue by dailytabs** [jsfiddle/jsfiddle-issues#1361]
The little tool-tip that displays the width when you resize the results container doesn't always show up.

After a page refresh, I will get to see it 1 or 2 times, then nothing until I refresh again.

Win10/FF61.0.2

**Comment by oskarkrawczyk** [comment]
@dailytabs do you get any sort of error messages in devtools console?

**Comment by oskarkrawczyk** [comment]
I tested this a couple of times on Firefox and can't replicate.
