### ISSUE TITLE
TypeScript silently (and incorrectly) changing arrow function into normal function

### ISSUE THREAD

**Issue by amadanmath** [jsfiddle/jsfiddle-issues#1362]
https://jsfiddle.net/z4vo5u5d/18781/ as asked about on StackOverflow at https://stackoverflow.com/questions/52184064/cannot-call-private-function-from-constructor-in-typescript

    this.button.click(() => { this.buttonClick() });

is translated incorrectly into

    this.button.click(function () { this.buttonClick(); });

Meanwhile, the compiler at typescriptlang.org/play translates it correctly as:

    var _this = this;
    ...
    this.button.click(function () { _this.buttonClick(); });

**Comment by oskarkrawczyk** [comment]
The TypeScript transpiler is outdated, until we change the way transpilers are working in JSFiddle we have to stick with the outdated one since the new one doesn't work in our setup.
