### ISSUE TITLE
Support Custom Boilerplate

### ISSUE THREAD

**Issue by hatelove85911** [jsfiddle/jsfiddle-issues#1365]
I would like a feature which I can create my custom boilerplate which will be sitting together with the built-in ones so that I can quickly start writing code without the need to setup the boilerplate code again.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

https://trello.com/c/PPlpEUd3/60-template-fiddles-save-fiddle-as-template
