### ISSUE TITLE
[Bug] Can't open All your fiddles

### ISSUE THREAD

**Issue by SkyTien** [jsfiddle/jsfiddle-issues#1367]
When I click All your fiddles after login,
the web will continue loading, and make my browser stop doing anything else. The only way to stop it is Force closed the browser through the system. 
I tried different computer, different browser, different OS even different mobile phone, the situation is the same. Probably only happened on my account.
And it happened about an half year. Please help.

**Comment by oskarkrawczyk** [comment]
You have a fiddle that has an infinite loop. See `Common questions` here https://github.com/jsfiddle/jsfiddle-issues
