### ISSUE TITLE
Bug in Editor layout - classic view does not work when user is authorized

### ISSUE THREAD

**Issue by testgit-1** [jsfiddle/jsfiddle-issues#1370]
UI when a user is authorized
http://prntscr.com/l039ph
![image](https://user-images.githubusercontent.com/22541150/46244420-583c2b00-c3e7-11e8-8b2b-f0158b8f1674.png)

UI whien a user is not authorized
http://prntscr.com/l03zvv
![image](https://user-images.githubusercontent.com/22541150/46244413-507c8680-c3e7-11e8-832b-9c3cd9971be1.png)

**Comment by oskarkrawczyk** [comment]
Should be fixed
