### ISSUE TITLE
Embed Border

### ISSUE THREAD

**Issue by starpause** [jsfiddle/jsfiddle-issues#1374]
I would like the option to put a border on the embed. When I try and simply wrap the embed in a div with a border there is awkward spacing (see attached image). Use case for this is when I'm doing a demo of a component which has a white background inside of a documentation site that also has a white background. Thanks!

![screen shot 2018-10-12 at 12 29 41 pm](https://user-images.githubusercontent.com/408953/46890112-9fc8ab00-ce1a-11e8-85ab-13257db3c6d0.png)

**Comment by oskarkrawczyk** [comment]
There's no extra padding inside of the embed `iframe`, there's zero gap between the iframe and its contents. So this is probably something on your end.
