### ISSUE TITLE
Live code validation error on css custom variables declaration

### ISSUE THREAD

**Issue by SvetaSR** [jsfiddle/jsfiddle-issues#1376]
Declaring custom css variables is not supported by the site's validator, and throws "Expected RBRace".

![10-23-2018 6-46-29 am](https://user-images.githubusercontent.com/11496011/47334415-7d8f2280-d68f-11e8-84ce-0847eb009bc3.jpg)

The Error:
![10-23-2018 6-42-01 am](https://user-images.githubusercontent.com/11496011/47334219-d14d3c00-d68e-11e8-83b0-288bab22d39e.jpg)

**Comment by oskarkrawczyk** [comment]
Merged into ^
