### ISSUE TITLE
Replace CSSLint with a maintained alternative

### ISSUE THREAD

**Issue by oskarkrawczyk** [jsfiddle/jsfiddle-issues#1377]
Looks like @CSSLint is not maintained anymore.

Missing lots of CSS4 support, like Custom Properties (#1376).

**Comment by oskarkrawczyk** [comment]
Potentially this fork of @stylelint could be used: https://github.com/openstyles/stylelint-bundle

**Comment by oskarkrawczyk** [comment]
Note, looks like @CSSLint is completely unmaintained, tried getting in touch with contributors and creators but nobody got back.

Need to put more research into a viable alternative.

**Comment by oskarkrawczyk** [comment]
Added a maintainer linter that solves this problem. Will deploy this week.

**Comment by catarak** [comment]
@oskarkrawczyk which CSS linter did you add? I'm running into the same issue for the [p5.js Web Editor](https://github.com/processing/p5.js-web-editor) and would love to figure out a solution.
