### ISSUE TITLE
Update page title on Save / Update / Fork

### ISSUE THREAD

**Issue by tigregalis** [jsfiddle/jsfiddle-issues#1382]
I tend to bookmark the fiddles I write. The default name for a bookmark is the page title, but by default, the page title:

1. for a new fiddle, even after saving it: will show as "Create a new fiddle - JSFiddle".
2. for an update or a fork: will show as the old title.

To work around it, I have to do the Save/Update/Fork, refresh the page (F5), then bookmark it (or manually update the bookmark name).

This is a very minor thing, but should also require a very minor fix, e.g. ``document.title = `${fiddleTitle} - JSFiddle`;``

**Comment by oskarkrawczyk** [comment]
While not as easy as one might think, it's a good idea to improve this.
