### ISSUE TITLE
Need more information under All Fiddles listing

### ISSUE THREAD

**Issue by Whirl3d** [jsfiddle/jsfiddle-issues#1384]
I searched this repository for Fiddles Listing and couldn't find this issue. When viewing All Fiddles under your account, the window is divided into panels. 

Each panel is a preview of the HTML results from one of your old  Fiddles, The problem is that if your fiddle had no preview because it generated no HTML, it's impossible to find the work you just did. 

And since there is no date or other information, it is not possible to sort (by date, for example, so I could grab the latest version cause it came first). 

Please modify the "all fiddles" previiew section to allow sorting by date, by title, etc. Also, please let us switch modes between HTML output view and coding view when vieiwing all of your fiddles. 

Thanks for a great product..

**Comment by oskarkrawczyk** [comment]
We'll add sorting. Just so it's clear, all fiddle listings are sorted by creation date.
