### ISSUE TITLE
Fiddle shifting up bug

### ISSUE THREAD

**Issue by clapynick** [jsfiddle/jsfiddle-issues#1385]
This bug shifts the entire page up.

To recreate this bug you need to create a <textarea> in the HTML.
Once you run the code enter some text into the textarea and then press 'PgUp'

The entire website shifts up and you cannot scroll back down or press 'PgDn' to restore the page.

I am using Chrome.

**Comment by oskarkrawczyk** [comment]
No idea how to fix this. If anyone has a clue, please let me know.

**Comment by Teranode** [comment]
@oskarkrawczyk element `#app-updates-highlighter` gets shifted into a relative position under the form content, not sure how, but it does, giving it a position of "fixed" solves the issue but im not sure what the element is in the first place so there's where u should look.

**Comment by oskarkrawczyk** [comment]
Unfortunately that doesn't seem to resolve the issue as it's still being reported.

**Comment by oskarkrawczyk** [comment]
Merged into #1535
