### ISSUE TITLE
Issue with results frame and the menu bar

### ISSUE THREAD

**Issue by thekodester** [jsfiddle/jsfiddle-issues#1386]
**Bug Information:**

_Description:_
'Result' button/menu bar repeatedly appears in the result frame. This happens both on profile page and embedded fiddles.

_Additional Information:_
I don't see any errors in the console.

_Images:_
<img width="1449" alt="screen shot 2018-11-03 at 9 40 42 am" src="https://user-images.githubusercontent.com/23484460/47952975-48b38300-df4d-11e8-9841-4335579b1be5.png">

<img width="1680" alt="screen shot 2018-11-03 at 9 53 16 am" src="https://user-images.githubusercontent.com/23484460/47953077-7a791980-df4e-11e8-8aed-01a75c96151c.png">

**System Information:**
_Operating System:_ macOS v10.14
_Browser Version:_ Safari Version 12.0 (14606.1.36.1.9)

**Comment by oskarkrawczyk** [comment]
@thekodester this tends to happen only if your browser or network have very custom settings, preventing for certain headers to be sent, and this is by design so that code cannot be posted to JSFiddle embeds from malicious domain names.

Normally this would never happen.

**Comment by thekodester** [comment]
I reset my browser and it fine now. I close as it hears your correct. Thanks.
