### ISSUE TITLE
Auto inserting anchor tag after paste with autocomplete running

### ISSUE THREAD

**Issue by Whirl3d** [jsfiddle/jsfiddle-issues#1387]
When pasting content the new item is placed and the autocomplete menu is displayed. So when I hit the spacebar, it assumes I want the anchor element (the first element on the autocomplete) so it adds it. This causes problems with lots of repeat paste events. You end up with a lot of extra <a pieces.

One possible solution could be to change the paste routine to not show autocomplete after. Totally a minor problem-hope this helps.

**Comment by oskarkrawczyk** [comment]
Ok, I believe I've pinpointed the issue. Fix now on production.
