### ISSUE TITLE
console.log errors

### ISSUE THREAD

**Issue by username1565** [jsfiddle/jsfiddle-issues#1393]
Just leave this here:
```
Uncaught SyntaxError: Unexpected token ILLEGAL /js/_dist-editor.js?update_28_11_2018_1:1
Uncaught ReferenceError: Cookie is not defined (index):1287
```

**Comment by username1565** [comment]
Any jsfiddle in Google Chrome with version "34.0.1847.131 m" (32 bit, windows XP).
In mozilla Firefox ESR, version 52.9.0 (32-bit) - all fiddles are working fine.

Maybe you say my Chrome is old, but earlier all jsfiddles worked good...
You can fix this errors to save backward compatibility.

**Comment by oskarkrawczyk** [comment]
Can't reproduce on any browser. Closing.
