### ISSUE TITLE
JSFiddle opening in new tab on run

### ISSUE THREAD

**Issue by Reader8765** [jsfiddle/jsfiddle-issues#1395]
JSFiddle just started using `target: blank` behavior on run. Is anyone else experiencing the same issue is is it just me?

**Comment by donggyu04** [comment]
@Reader8765 

The same issue is happening to me. when run code it is open new tab this url 

`https://fiddle.jshell.net/_display/`

did i set something wrong JSFiddle settings?

**Comment by oskarkrawczyk** [comment]
@Reader8765 @donggyu04 What browser, OS? Are there any JS errors in the devtools console? Does restarting the browser help? Does disabling extensions help?

**Comment by donggyu04** [comment]
@oskarkrawczyk 
I'm using windows 10 and chrome browser. i used it without any problems until yesterday, but I have an issue today. 

1. Windows 10, chrome
2. No errors
3. Not help
4. Not help
5. Yes, but i remove issued fiddle and create new, but the problem reappears.

**Comment by oskarkrawczyk** [comment]
Ok, so it appears the behavior happens when you modify the `window` object.

After removing `window.name = "I'am Window";`, saving, reloading the page, all goes back to normal.

Interesting bug, at the moment I have no idea why is that happening. Will have to investigate.

**Comment by PogromistDev** [comment]
I deleted result area's html content with inspect and fiddle open in new tab

**Comment by Reader8765** [comment]
It works now. I don't know what happened. Maybe because of the Chrome update? I did it yesterday after the bug and it works fine now. I don't see how that would be connected, though. I made no modifications to the window and the code I ran yesterday works fine now.

**Comment by oskarkrawczyk** [comment]
Turns out changing `window.name` inside of the render iframe, is like changing `iframe.name` from the editor context, and having a specific `name` of the `iframe` is a must for JSFiddle to work.

So while surprising, it's now clear why it breaks the editor.

Not sure what would be a workaround to this.
