### ISSUE TITLE
getUserMedia doesn't work when loading from github

### ISSUE THREAD

**Issue by Sean-Der** [jsfiddle/jsfiddle-issues#1397]
I believe this is related to https://github.com/jsfiddle/jsfiddle-issues/issues/1106

Currently I am able to use getUserMedia if I create a fiddle like [this](https://jsfiddle.net/usd3xmtz/45/)

However when I use the GitHub embed feature like [here](https://jsfiddle.net/gh/get/library/pure/pions/webrtc/tree/master/examples/gstreamer-receive/jsfiddle) I get `NotAllowedError: Permission denied`

**Comment by Sean-Der** [comment]
@oskarkrawczyk is there anything I can do to help with this? Happy to add more info/more minimal examples if this isn't a good report!

**Comment by oskarkrawczyk** [comment]
@Sean-Der What browser are you using? Testing on Safari, and both examples work fine

**Comment by Sean-Der** [comment]
@oskarkrawczyk `Version 72.0.3626.53 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)`

Both examples work fine in FireFox also, seems to be a Chromium specific issue (I only have Linux available can't confirm Safari sorry).

**Comment by oskarkrawczyk** [comment]
## Safari iOS, Firefox:

Both URLs work fine, the normal fiddle and one from the POST GH API.

## Chrome, Safari macOS:

Both URLs don't work. I have no idea why. The `iframe` has flags to allow permissions for the camera and mic: `midi; geolocation; microphone; camera; encrypted-media;`

Interestingly, nor Chrome or Safari asks me for any permissions on fiddle load.

**Comment by oskarkrawczyk** [comment]
Ok, looks like I've previously blocked Mic access on both, so the fiddle works, but the ones from POST API don't.

Not a clue why.

**Comment by Teranode** [comment]
@oskarkrawczyk The iframe also has origin permissions ( `*` indicating to allow from all or specify specific domains)

```
midi; geolocation *; microphone *; camera *; encrypted-media *;
```

**Comment by Sean-Der** [comment]
Hey @oskarkrawczyk 

Did you get a chance to specify the origin permissions? No rush! thanks

**Comment by oskarkrawczyk** [comment]
Fixed
