### ISSUE TITLE
Indented .sass syntax support

### ISSUE THREAD

**Issue by Purpzie** [jsfiddle/jsfiddle-issues#1398]
There have been previous issues about this but they're over a year old, and they've either been misunderstood (#975) or closed due to other reasons. Therefore, I've opened up this new issue in case it might be reconsidered.

*Sass* is actually slightly different than *SCSS*, using a whitespace-sensitive, indented syntax rather than depending on braces and semicolons. Otherwise, it functions exactly the same way as SCSS (except for a couple simple things explained [here](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html#Sass_Syntax_Differences)).

This format, at least in my own and some others' opinions, is easier to read. It would be awesome if JSfiddle would add support for this, probably under the name "Indented Sass" (instead of just "Sass") for clarity. If the site is using the ruby gem or something similar, it should be able to parse `.sass` files already. 👍

**Comment by oskarkrawczyk** [comment]
Added SASS support.
