### ISSUE TITLE
A JSFiddle Tags Manager please.

### ISSUE THREAD

**Issue by dangtu-work** [jsfiddle/jsfiddle-issues#1399]
I'm aware that the dev team has been developing a feature call `Grouping fiddles`. That's really nice. However I want to suggest a better way to manage all fiddles is tag (aka. label). A fiddle could have many tags and a tag can exist in many fiddles.

**Comment by oskarkrawczyk** [comment]
https://trello.com/c/dgQLwViT/46-ability-to-tag-fiddles
