### ISSUE TITLE
Can't select options below

### ISSUE THREAD

**Issue by tatva181** [jsfiddle/jsfiddle-issues#1401]
I can't select options below. Attached screenshot.  I have to drag up that column everytime to make any changes
Browser: FF (62.0)
Os: Windows 10(64-bit)
![js_f](https://user-images.githubusercontent.com/5110127/49985837-70a5f580-ff93-11e8-992a-676da604c386.png)

**Comment by oskarkrawczyk** [comment]
Decided not to address this, since there is a solution by simply resizing the JS panel, and there are far more important issues to be addressed first.
