### ISSUE TITLE
Disable automatic closing ), } or ]

### ISSUE THREAD

**Issue by parsimonhi** [jsfiddle/jsfiddle-issues#1402]
When one enters a "(", “{" or "[", a closing ), } or ] is added automatically.

Nice feature! But if you don't use it in your life outside jsfiddle, it's somewhat disturbing.

Is there a possibility to disable it? (i didn't find anything in the settings panel that can do that)

**Comment by oskarkrawczyk** [comment]
Currently it's not possible, but looks like an easy one to implement. Will have a look into it.

**Comment by oskarkrawczyk** [comment]
<img width="261" alt="screen shot 2019-01-07 at 15 55 09" src="https://user-images.githubusercontent.com/34213/50774792-a8ebdb80-1294-11e9-9942-688a11deb45b.png">

**Comment by parsimonhi** [comment]
Perfect, thank you!
