### ISSUE TITLE
Feature to define Google Maps Javascript API Key

### ISSUE THREAD

**Issue by ergec** [jsfiddle/jsfiddle-issues#1405]
We all know that Google stopped using it's services without api key. People are having issues on stackoverflow asking google maps javascript api related questions (and also other services) . Because no one wants to predefine their own api keys, and without key nothing works.

What might be a solution is,

Every user be able to define their own api key privately in their profile. When user asks a question and links to jsfiddle, he/she will give maps api reference without api key (because he/she already has predefined key in his profile) linked resource url will not have key parameter.

If we click on the link and open jsfiddle, system will use our own api key automatically and run the code.

**Comment by oskarkrawczyk** [comment]
Due to GDPR we don't want to have API keys stored on our end. At least not at this point in time.

I will think about how we might help out users that come to test their Google JSAPI's without the need of us hosting keys.

**Comment by oskarkrawczyk** [comment]
Added suggestion to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap)
