### ISSUE TITLE
accessibility of jsfiddle for screen reader users

### ISSUE THREAD

**Issue by mehgcap** [jsfiddle/jsfiddle-issues#1407]
I've seen jsfiddle around the web, but today was the first time I tried to use it for myself. I wanted a quick, easy way to test a Jquery event handler, and rather than make a new file and find the CDN for Jquery, I tried to use jsfiddle. I was completely unable to do so, because the website doesn't seem to play nicely with screen reading software used by the visually impaired to access computers. For reference, I am running [NVDA](www.nvaccess.org) as my screen reader, with Firefox 64 as my browser.

The first, and possibly largest, problem is that edit fields don't show any text to screen readers. If I select text, I can hear the text being selected, but regular arrow navigation results in NVDA reporting that the edit field is completely empty. Of course, this makes it hard to do any typing or editing, so I have to resort to doing all that outside of the browser, then pasting in my code.

Second, the toggles for line numbers, formatting, auto-completion, and so on are clickable elements that don't indicate state. This poses two issues:

* there is no way to tab to them
* there is no way to determine whether they are enabled or disabled

Third, the tabs (HTML, JS, CSS, results) don't seem to be activated by any means I could think of. I could never switch them, even if I tried to simulate a mouse click. Of course, it could be that they are visual, while NVDA is seeing all the page content already, so I didn't notice a difference when clicking any of them.

Finally, I couldn't get my fiddle to run. I may have had an error, of course, but I didn't even get anything about that. There was no change in the page that I could find, whether I hit the Results tab, used ctrl-enter in some of the text fields, or hit the Update button.

Those are the major accessibility problems I ran into today. Let me know if you need clarification on any of them. Thanks.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

https://trello.com/c/VBivR6Sm/79-introduce-accessibility
