### ISSUE TITLE
Unable to create new fiddle without starting with boilerplate

### ISSUE THREAD

**Issue by richsapien** [jsfiddle/jsfiddle-issues#1408]
There doesn't appear to be a way to easily start a new fiddle once you have a fiddle active. When I click on the top left icon, all I'm presented with are options to start with a boilerplate. I just want to start a new fiddle without any boilerplate. Am I missing something?

**Comment by oskarkrawczyk** [comment]
Agreed, there should be a way to do that. Will work on this.

**Comment by richsapien** [comment]
Thanks!

**Comment by vanowm** [comment]
2 years later still waiting for a solution...

**Comment by vanowm** [comment]
Funny thing, looking at the source of the page, there is a commented list item, which does exactly as requested when uncommented:
![image](https://user-images.githubusercontent.com/511517/118633990-0f0b9600-b7a0-11eb-87c0-52c32f31092d.png)
