### ISSUE TITLE
Save as Base button disappears

### ISSUE THREAD

**Issue by kiminyme** [jsfiddle/jsfiddle-issues#1411]
A new problem as of this morning.

When I open a base version of a fiddle (with no version number at the end of the URL), I see the Save as Base button. However, when I modify the code and click the Save button (which I swear used to read "Update" rather than "Save"), the Save as Base button disappears completely. I run the code and it works as expected, but I can't save the changed version as the base version.

I also see (for the first time that I've noticed) an Unsaved draft notice above the toolbar, which appears even after I've saved the changed version. When I click there, all windows are empty, even when I have made changes.

I am logged into my account, but interestingly, the logout option is unavailable in the user menu. I have cleared the cache and logged back in, but it does not resolve the problem. I was using Firefox but switched to Edge to see if it was a browser issue, but I see exactly the same problems in both places. I have also tried multiple saved fiddles, to no avail.

**Comment by oskarkrawczyk** [comment]
@kiminyme Thanks for the report. I need some more info:

1. By `Save as base` you mean `Set as base` or `Save`? Two separate actions.
2. Draft - will look into it. The drafts were always there, but it should disappear when you save the code and no additional changes were made.
3. Screenshot please, I don't see a way the `Logout` link can disappear, the user menu will either show either in full when logged in or not at all when logged out.

**Comment by oskarkrawczyk** [comment]
Rolled back today's changes to how saving works. Need to bug-fix a little. 

1 and 2, are related to the same problem.

3 is an unknown to me, so need more details on this.

**Comment by oskarkrawczyk** [comment]
1 and 2 fixed.
