### ISSUE TITLE
Fiddle disappeared

### ISSUE THREAD

**Issue by markuzzi** [jsfiddle/jsfiddle-issues#1412]
After some hours of work, my fiddle simply disappeared.
The page shows a 404 error.

Missing fiddle: http://jsfiddle.net/mluckey/1faz2t4k/90

Another fiddle with another name but an old version the one above appeared instead
https://jsfiddle.net/mluckey/cqLozprt/

Unfortunately, it is missing about 45 revisions.

**Comment by aaronortiz** [comment]
I'm having the same problem, I have to type a revision number after the URL to go to a previously saved version and get my work back. But if I click on it from the "Your fiddles" link, the code is reset to blank again.

**Comment by Vicedivic** [comment]
Same problem here - I spend a lot of time on a project and it just disappeared from my dashboard. And I don't have the URL for it
