### ISSUE TITLE
Providing just the "Result" tab as a public link

### ISSUE THREAD

**Issue by saveshodhan** [jsfiddle/jsfiddle-issues#1421]
Is it possible to provide just the `Result` box as a sharable link?

This way, one may not need to share the entire fiddle. Also, it will appear better on mobile phone screens.

**Comment by oskarkrawczyk** [comment]
Sharing results directly has been disabled due to scammers and spammers misusing that functionality.

You can link the embed directly, for example: https://jsfiddle.net/oskar/b00kfu61/embed/result/

**Comment by saveshodhan** [comment]
You mean  https://jsfiddle.net/oskar/b00kfu61/embedded/result/ ?
