### ISSUE TITLE
Bootstrap boilerplate is outdated

### ISSUE THREAD

**Issue by vanillajonathan** [jsfiddle/jsfiddle-issues#1422]
https://jsfiddle.net/boilerplate/bootstrap

It references the old Bootstrap 4.1.0. Please update to the latest.

**Comment by vanillajonathan** [comment]
Still outdated. 😢

**Comment by oskarkrawczyk** [comment]
Ah, yeah, looked at the wrong version number

**Comment by oskarkrawczyk** [comment]
Done

**Comment by vanillajonathan** [comment]
Great!

Note that the [jQuery template](https://jsfiddle.net/boilerplate/jquery) goes against version 3.3.1, version 3.4.1 shows up available as an option in the dropdown though.

It might be worth checking if the React and Vue templates are outdated too.
