### ISSUE TITLE
Suggestion: Re-add CTRL + SHIFT + ENTER, a keybind to view your fiddle in full-screen

### ISSUE THREAD

**Issue by MichaelXF** [jsfiddle/jsfiddle-issues#1423]
This feature was recently removed, you would press CTRL + SHIFT+ ENTER and it would open your fiddle in a full screen window which is great for cool Canvas stuff and see your HTML in full screen.

Would love for this to added back! It is very annoying that I must squint my eyes to view my canvas and it was nice to display my fiddle in full screen to my friends.

+ Keyboard shortcuts are awesome!

I used to this all the time it's sad I have to move to _[censored]_ to view code in full screen

**Comment by oskarkrawczyk** [comment]
As previously mentioned, there was no such feature, if this worked like that it was only as a byproduct of a bug that has been addressed.

Adding this suggestion to the roadmap, for the people to decide.
