### ISSUE TITLE
Self closing input tag with missing ending quote will leak JavaScript into Preview window

### ISSUE THREAD

**Issue by augbog** [jsfiddle/jsfiddle-issues#1424]
This is probably a low priority issue since it's because of invalid HTML but when creating an input with a missing double quote to close an attribute, JavaScript ends up leaking into the editor. Example below.

![screen shot 2019-02-07 at 2 34 46 pm](https://user-images.githubusercontent.com/2054339/52447534-d4f1bb00-2ae5-11e9-974b-5a591e660375.png)

If there is a dupe of this issue, feel free to close but looked through and didn't see any that looked directly related.

**Comment by oskarkrawczyk** [comment]
Unfortunately I don't see a way to fix this, apart form passing inputs via a validator+fixer, but that would alter the intended input (even if erroneous) done by the user.

I'll leave this open for now and give it a second thought, but nothing comes to mind right now.

**Comment by oskarkrawczyk** [comment]
@venedie Any chance you know of a way that could mitigate this? Nothing comes to mind on my end

**Comment by oskarkrawczyk** [comment]
I have no ideas how this behavior can be mitigated apart from validating+fixing HTML, which I won't do for reasons explained above.

**Comment by augbog** [comment]
No worries thanks for responding :)
