### ISSUE TITLE
loses action buttons after runing script

### ISSUE THREAD

**Issue by enuggetry** [jsfiddle/jsfiddle-issues#1426]
The current incarnation seems to loses the action buttons, like "run" after the JS script has run.
Not very useful in this state.

**Comment by oskarkrawczyk** [comment]
@enuggetry Can you provide a screencast of what you're seeing, and the link to the fiddle that's causing this behavior on your end?

Would be helpful as I cannot replicate the reported issue.

**Comment by oskarkrawczyk** [comment]
Author never got back with the details, closing.
