### ISSUE TITLE
Advert blocks entry on mobile

### ISSUE THREAD

**Issue by mplungjan** [jsfiddle/jsfiddle-issues#1431]
Impossible to use jsFiddle on iOS iPhone in either landscape or portrait.
Advert which cannot be removed squashes the interface so the setting links are all one can click

**Comment by oskarkrawczyk** [comment]
Please provide a screenshot of what you're seeing

**Comment by mplungjan** [comment]
![8a9c35b0-5b52-4080-8bbd-c42f06c74f75](https://user-images.githubusercontent.com/1433276/53040937-f8701a80-3482-11e9-99d5-0019167c7a06.png)
![6bc2fb70-d725-4956-bd3b-2ab42ba2b949](https://user-images.githubusercontent.com/1433276/53040939-f8701a80-3482-11e9-87c5-168f14343c48.png)
![19a72b21-e366-4018-b0f1-9e075d91c949](https://user-images.githubusercontent.com/1433276/53040940-f8701a80-3482-11e9-9327-4af8e0b570a4.png)

**Comment by mplungjan** [comment]
Impossible to paste in the editor too
