### ISSUE TITLE
Typescript doesn't work correctly

### ISSUE THREAD

**Issue by ecSpl01t** [jsfiddle/jsfiddle-issues#1433]
A lot of problems related to typescript.

for ex:
`class Api {
		public get() {
    		return fetch('https://jsonplaceholder.typicode.com/')
        	.then(data => data.json);
    }
}`

https://jsfiddle.net/ecSpl01t/xak47wop/

Doesn't support something like this: 
let data = \`${varible}\`;

**Comment by oskarkrawczyk** [comment]
Merging into #1079
