### ISSUE TITLE
Let me set my jslint/csslint configuration in my account 

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#1434]
I know I can add various jslint/csslint comments but they clutter my code and I have to manually insert them every single time. Sure I can copy and paste them from elsewhere but it's a huge hassle.

It would be great if I could set them in my account profile and have them applied automatically to my fiddles.

I don't want to turn off the linting that catches errors but the style stuff drives me nuts, can be wrong, and often makes the code less readable but because the default jshint/csshint warnings are highlighted that also makes the code unreadable.

Another option would be for these setting to be part of the fiddle's metadata so they don't clutter the code but it would still be amazing to be able to set my own defaults for new fiddles.

(mixing stuff up here but it would also be amazing to be able to set my default fiddle content and my own list of templates. In the entire history of jsfiddle I've never once picked a template at the top so that whole workflow basically just gets in the way as it is. If I could set my own templates then others with similar needs might find it more useful)

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/c/L4AZdKyW/85-csslint-jshint-rules-personalization). Thanks!

> but the style stuff drives me nuts

Can you elaborate which style rules drive you nuts? I may just readjust them, since both JSHint and Stylelint are freshly added to JSFiddle, and most of them have default rules.

**Comment by greggman** [comment]
It doesn't seem like there is any way you can just set a few rules and please everyone. Like emacs vs vi code style is very subjective. In fact just you tell me no, you think that rule should stay could easily cause a flame war 😅

I'm sure I could list 50 or more if I write enough code.

<img width="673" alt="screen shot 2019-02-26 at 14 26 53" src="https://user-images.githubusercontent.com/234804/53389523-036f0180-39d3-11e9-8156-20ea29810490.png">

I get the warning but I'm a big boy. I know what I'm doing. The code above is generating an array of distances between 2 sets of points. So it uses map to iterate over one array and used the index to compare to another. Don't need a warning for this common pattern

<img width="621" alt="screen shot 2019-02-26 at 14 23 52" src="https://user-images.githubusercontent.com/234804/53389524-036f0180-39d3-11e9-9bf9-ce5f865032a7.png">

Never confused a decimal point for a dot. Can't (or never have) named a property starting with a number. Not even possible to use dot notation with numbers, it would generate a syntax error so this is a silly style warning.

<img width="458" alt="screen shot 2019-02-26 at 14 22 17" src="https://user-images.githubusercontent.com/234804/53389525-04079800-39d3-11e9-89ef-863300937aa9.png">

Again, someone's silly style nazi rule. Sure, for a 100k line project maybe this is important. For a fiddle I'm usually trying to explain something to someone. When the CSS is **not** the point then I try to make it compact so it is easily ignored. Don't need this warning

<img width="313" alt="screen shot 2019-02-26 at 14 22 11" src="https://user-images.githubusercontent.com/234804/53389526-04079800-39d3-11e9-8169-932fe7c108cd.png">

Yet again a style nazi rule. I get the tradeoffs. I prefer this over function style.

**Comment by oskarkrawczyk** [comment]
Ok, so you have a few fair points and the linters rules can be improved – I'll do that.

But at this point in time, I won't be adding a way to set custom rules for accounts.

**Comment by amoliski** [comment]
Could you also remove the "Unexpected Whitespaces" rule in the CSS validator? 
In the example: 

```
.foo {
  .bar {
    display: block;
  }
  .baz {
    display: block;
  }
}
```
It will yell at you for not having a blank line before .baz (also really annoying). 

![2019-06-04 16_52_22-Start](https://user-images.githubusercontent.com/880466/58916421-42ef6d00-86e9-11e9-8bbf-d595be65045f.png)

If you hit enter at the end of the .bar block, it will try to auto-indent to match the tab height, and then it will yell at you for the spaces that _it inserted on your behalf_. 

![2019-06-04 16_52_34-Start](https://user-images.githubusercontent.com/880466/58916432-497de480-86e9-11e9-9456-4595954af57e.png)

This leads to you having to hit backspace a bunch of times to make sure the line is completely free of whitespace, but god help you if you backspace one too many times, remove the newline, and have to start over.

The other complaint is the rule that requires a space before the opening bracket in a rule- also seems like more of a personal style choice than something that you should be yelled at for. 

![2019-06-04 16_55_19-Start](https://user-images.githubusercontent.com/880466/58916546-91047080-86e9-11e9-936b-9a8ad70d3cbd.png)

**Comment by oskarkrawczyk** [comment]
@amoliski all fair points, will change

**Comment by oskarkrawczyk** [comment]
Changed a few of these.

Notes:

- Couldn't find a way to turn off the warning about floating decimals
- Couldn't find a way to turn off `Expected no more than 1 declaration`

If someone finds a way to turn them off, let me know :)
