### ISSUE TITLE
Applying unsaved draft doesn't populate the editor with code on non-saved fiddles

### ISSUE THREAD

**Issue by MarkSchultheiss** [jsfiddle/jsfiddle-issues#1435]
Started a fiddle, worked on it for some time.  Noticed I was not logged in.  Clicked the login, completed login.  Fiddle contents were empty.

Clicked "back" button until I saw a "unsaved draft" in upper right
Clicked that, was presented with the original fiddle draft in a pop-up.  Tried to click the "Apply local draft version" button, nothing happened.  Had to click back button again, cut and paste from the popup into a new (other) jsfiddle window to recover the content.
Was using Chrome browser.  This has happened several times.

**Comment by peyremorgan** [comment]
Same here with Firefox 62. Created an account to publish a draft, only to see it completely gone after I signed up. Not a huge deal AFAIC, but not a great onboarding experience either

**Comment by shockthetoast** [comment]
I'm seeing this as well. Unsaved drafts no longer are recoverable for me.

**Comment by oskarkrawczyk** [comment]
Fixed
