### ISSUE TITLE
Three.js r54 is blocked from loading

### ISSUE THREAD

**Issue by tommai78101** [jsfiddle/jsfiddle-issues#1436]
I see this error message mentioned in the console.

```
Blocked loading mixed active content “http://mrdoob.github.io/three.js/examples/js/RequestAnimationFrame.js”[Learn More]
<script> source URI is not allowed in this document: “https://mrdoob.github.com/three.js/examples/js/RequestAnimationFrame.js”.
```

Link to JsFiddle:

https://jsfiddle.net/63csgzov/

I'm not sure what to do at this point. Thanks.

**Comment by oskarkrawczyk** [comment]
That URL throws a 404, looks like the project was scrapped as there's no mentioning of that in Three.js docs. `RequestAnimationFrame.js` is hidden from users to pick in JSFiddle, I guess the aforementioned was the reason.

Added v105 of Three.js.
