### ISSUE TITLE
Errors in console when opening JS braces

### ISSUE THREAD

**Issue by ianrosedev** [jsfiddle/jsfiddle-issues#1439]
- Chrome 73.0.3683.86

When opening JavaScript braces I'm getting two errors. They are both happening every time I create a new function and littering the console `message`. The first one is also in `user message`.

```
onloadwff.js:71 Assertion failed: Input argument is not an HTMLInputElement
```
```
onloadwff.js:71 Uncaught TypeError: Cannot read property 'type' of undefined
  at e.setFieldValue (onloadwff.js:71)
  at HTMLFormElement.formKeydownListener (onloadwff.js:71)
```
![JSFiddle](https://user-images.githubusercontent.com/8762358/54849473-c38df800-4cba-11e9-8da0-560c293156ce.gif)

**Comment by oskarkrawczyk** [comment]
Chrome extension issue

**Comment by ianrosedev** [comment]
Whoops! Thanks for the quick reply.
