### ISSUE TITLE
Truly hide the diff interface when not open so that Control-F does not find invisible matches

### ISSUE THREAD

**Issue by CertainPerformance** [jsfiddle/jsfiddle-issues#1441]
Often, when searching for strings in the code with the browser's Control-F or equivalent, more matches than those that are actually visible are shown. For example:

![uniquestring1](https://user-images.githubusercontent.com/37674520/55299170-60593f80-53f7-11e9-8a58-428457efa93a.png)

This can easily cause confusion, especially when there's lots of code in multiple sections. The culprit is the diff interface:

    <div class="dropdownCont hidden" data-popover-ref="draft" data-popover-position="left">

![uniquestring2](https://user-images.githubusercontent.com/37674520/55299195-77982d00-53f7-11e9-942f-760806787635.png)

The `hidden` class makes the content inside *appear* hidden to the user via

    opacity: 0;
    transform: translateY(10px);
    pointer-events: none;

but text inside an element with `opacity: 0` is still Find-able by the browser. At least in Chrome, FF, and Opera, to make text inside an element un-findable, use `display: none` or `visibility: hidden`. (There may be other methods too, but `opacity: 0` doesn't work.) Can the CSS be tweaked?

**Comment by oskarkrawczyk** [comment]
Diff interface is no more as Unsaved Draft feature has been completely refactored.
