### ISSUE TITLE
Tidy button missing ??????????????????????

### ISSUE THREAD

**Issue by GreatFireWall** [jsfiddle/jsfiddle-issues#1443]
![image](https://user-images.githubusercontent.com/4510984/55745104-10b6eb80-5a69-11e9-94fa-bd9b0c9d93b1.png)

**Comment by oskarkrawczyk** [comment]
1. No need for that title... Please clean it up.
2. Please provide a fiddle URL

**Comment by oskarkrawczyk** [comment]
Merging into #1449
