### ISSUE TITLE
Add `allow-top-navigation` to result iframe

### ISSUE THREAD

**Issue by jenan-stripe** [jsfiddle/jsfiddle-issues#1445]
The [new version of Stripe Checkout](https://stripe.com/docs/payments/checkout) requires top-level navigation. Currently, using it with jsfiddle results in an error:

> The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

It'd be great to add `allow-top-navigation` on the result iframe to allow triggering Checkout from a jsfiddle.

Example:

```
// performs a `window.top.location = ...` under the hood
stripe.redirectToCheckout({ ... })
```

Full example: https://jsfiddle.net/u4f21qbg/

**Comment by oskarkrawczyk** [comment]
@jenan-stripe `allow-top-navigation-by-user-activation` seems safer, would that suffice for Stripe Checkout?

**Comment by oskarkrawczyk** [comment]
Added `allow-top-navigation-by-user-activation`. Hope this is enough.

**Comment by jenan-stripe** [comment]
@oskarkrawczyk Ah, alas it would not. We need to `fetch` before navigating, which can break `user-activation` heuristics on slow connections.
