### ISSUE TITLE
Can you make a function to hide the sidebar?

### ISSUE THREAD

**Issue by madeas** [jsfiddle/jsfiddle-issues#1447]
Hello! 
Can you make a function to hide the sidebar? I did a small demo to show how to implement this with CSS. https://twitter.com/andrejsharapov/status/1116673414499110913 I think it would be very convenient. Small but very nice feature.

I put this code https://jsfiddle.net/madeas/u6fgqwhc/3/ on the page in front of `<div id="sidebar">`

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
