### ISSUE TITLE
Nodejs support to share live coding

### ISSUE THREAD

**Issue by ozkary** [jsfiddle/jsfiddle-issues#1448]
‼️‼️‼️

Since Node.js is a JavaScript platform, it would only make sense to support it. It is understood that this is a server side process, but it would greatly enhance jsfiddle as a one stop shop for all of our live code sharing in the world of JavaScript.

‼️‼️‼️

**Comment by oskarkrawczyk** [comment]
No plans for supporting Node.js as it's backend and JSFiddle is for frontend code.
