### ISSUE TITLE
Feature Request: Make Embeds editable

### ISSUE THREAD

**Issue by toxin20** [jsfiddle/jsfiddle-issues#145]
How difficult would it be to make embedded fiddles directly editable? i don't mean it in a sense where you can change the code and save it (that would be a problem of course because you don't want other people to mess up your code) but in a way where you can change the loaded code and directly see what changes in the result tab. 

then when i would reload the site on which the fiddle is embedded the changes would be gone of course, but it would be possible to connect this with the "+" (fork) button. when i have changed something in the embedded fiddle and then click on "+", the jsfiddle editor would directly display my changed code so that i can save it in my own dashboard permanently.

**Comment by yairEO** [comment]
why was this archived? It's unclear what is the status of this
