### ISSUE TITLE
Delete fiddle confirmation overlapped by meta text

### ISSUE THREAD

**Issue by FabianLauer** [jsfiddle/jsfiddle-issues#1451]
Nothing serious, but anyway:

1. log in
1. make sure to have at least 2 fiddles
1. open dashboard
1. hover over a fiddle
1. click the ⚙️ icon of any fiddle but the last one in a row
1. tooltip is overlapped by text from neighbouring fiddle

Reproducible in Chrome 74.0.3729.108, macOS.

Screenshot:

![Dashboard   JSFiddle   Code Playground](https://user-images.githubusercontent.com/2205595/56952213-140a3800-6b3a-11e9-8941-e8f37587afc8.png)

**Comment by oskarkrawczyk** [comment]
Not sure how to fix this, any help would be appreciated.
