### ISSUE TITLE
Need CDATA section around JavaScript

### ISSUE THREAD

**Issue by satchamo** [jsfiddle/jsfiddle-issues#1453]
There should be a CDATA marker around the user supplied JavaScript, otherwise weird stuff happens if your JavaScript includes the string "</script>" 

Here's how to reproduce the bug:

https://jsfiddle.net/20tv9qr6/

and here's a solution:

https://stackoverflow.com/questions/3302648/should-i-use-cdata-in-html5

**Comment by oskarkrawczyk** [comment]
@satchamo thanks for the explanation, brought back the `CDATA` marker
