### ISSUE TITLE
Delete multiple fiddle

### ISSUE THREAD

**Issue by undless** [jsfiddle/jsfiddle-issues#1455]
Hi there,

Is there a way to delete multiple fiddle at once ? I'm using jsfiddle and saving both public and private fiddle for a while now and, i just realised that i have an incredible number of old fiddle that a could delete...

Thank you for the time you'll spend on my question.

You're doing a great job btw, i really love the app

Cheers

**Comment by oskarkrawczyk** [comment]
Hi, there's no way to delete multiple fiddle at once.

To be honest this is the first time in years I've heard anyone asking for it.

**Comment by undless** [comment]
ok. i'll do it once by once. thank you.
