### ISSUE TITLE
Feature Request: Allow private fiddles to be titled.

### ISSUE THREAD

**Issue by james0r** [jsfiddle/jsfiddle-issues#1456]
Have a toggle button to make private/public instead of basing it off whether fiddle is titled or not. Seems kinda arbitrary and lots of times I like to title my private work for future reference.

Thanks!

**Comment by oskarkrawczyk** [comment]
Already on roadmap.

FYI: Unnamed fiddles are not private, they're simply not listed on your profile page – which they might in the future.
