### ISSUE TITLE
Arrow Methods incorrectly highlighted as bad code?

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#1457]
Arrow methods are apparently a shipping thing

A normal class

```
class Foo {
   someMethod() {
   }
}
```

An arrow class method

```
class Bar {
   someMethod = () => {
   }
}
```

this is apparently a shortcut for binding the method to the instance. In other words if I understand correctly it's a shortcut for this

```
class Bar {
   constructor() {
      this.someMethod = this.someMethod.bind(this);
   }
   someMethod{
   }
}
```

It's already working in Chrome but JSFiddle is marking it as bad code

<img width="562" alt="Screen Shot 2019-05-18 at 0 25 46" src="https://user-images.githubusercontent.com/234804/57938666-926d2500-7903-11e9-8f7f-4563d4d194d3.png">

Note: It doesn't work in Firefox Nightly nor Safari Tech Preview so maybe I'm jumping the gun here.

**Comment by oskarkrawczyk** [comment]
I can't seem to find a ECMA proposal for this, nor a list of browsers that plan to support it. Any chance you have it somewhere?

Worth asking if @jshint will be willing to add it to the linter.

**Comment by greggman** [comment]
It falls out of this proposal

https://github.com/tc39/proposal-class-fields

In particular this section

https://github.com/tc39/proposal-class-fields#execution-of-initializer-expressions

says points out they're basically field declarations and they're evaluated anytime the class is constructed/intialized

They've been shipping since Chrome 72

https://developers.google.com/web/updates/2019/01/nic72#public-class-fields

**Comment by greggman** [comment]
Note that private class fields also shipped

https://developers.google.com/web/updates/2019/04/nic74#private-class-fields

**Comment by greggman** [comment]
browsers: Chrome, Opera, Edge(Chromium Version), [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1499448), [Safari](https://bugs.webkit.org/show_bug.cgi?id=174212)

**Comment by oskarkrawczyk** [comment]
Note to self:

Update JSHint if this ticket is closed: https://github.com/jshint/jshint/issues/3139
