### ISSUE TITLE
Autocomplete fires in wrong places

### ISSUE THREAD

**Issue by regs01** [jsfiddle/jsfiddle-issues#1459]
INS, DEL, HOME, END, PGUP, PGDN firing autocomplete window. Navigating through lines and deleting something is quite tricky.

Another issue is typing decimal numbers. Autocomplete could appear after a point because there are helpers. But it also appears on every digit placed after the point.

**Comment by oskarkrawczyk** [comment]
Codemirror autocomplete implementation isn't the greatest, it has downsides especially in the area when should it appear or not.

Will look into cases you've raised.

**Comment by oskarkrawczyk** [comment]
Potentially fixed – tested on macOS

**Comment by regs01** [comment]
works well now
