### ISSUE TITLE
Lodash does not load

### ISSUE THREAD

**Issue by roman4e** [jsfiddle/jsfiddle-issues#1460]
‼️‼️‼️

Does not work in Vivaldi 2.5 which based on Chrome v74

![image](https://user-images.githubusercontent.com/10156713/58109449-4f0e0180-7bf6-11e9-8b1a-de7fc81df7f8.png)

the code run with connected lodash.min.ja
```
const a = {name:"asdf", slug: "asfd-1"};
console.log(
_.setWith(a, 'name', 'dddd', (value, key, obj) => `${value}-2222`),
a
);
```
‼️‼️‼️

**Comment by oskarkrawczyk** [comment]
Tested on Chrome 69+, works fine.

**Comment by oskarkrawczyk** [comment]
Tested, `loadash.min.js` loads fine, code runs fine. Cannot replicate issue = closing.

<img width="824" alt="Screen Shot 2019-06-14 at 10 51 28" src="https://user-images.githubusercontent.com/34213/59496742-67d6a380-8e92-11e9-9c81-ddcf8c1b8e5b.png">
