### ISSUE TITLE
JavaScript + jQuery (edge) 

### ISSUE THREAD

**Issue by akotulu** [jsfiddle/jsfiddle-issues#1462]
Hey!

Selecting JavaScript + jQuery (edge) + clicking Firebug Lite switch has not effect. It used to open console, and was working today morning. But now it is broken, I have tried with Safari, Opera, Chrome - no effect.

**Comment by oskarkrawczyk** [comment]
Hard to say, perhaps it's a Firebug Lite issue. There haven't been any changes to JSFiddle codebase lately that might have broken things.

Please provide a test case, if this is still an issue.

Closing for now.

**Comment by akotulu** [comment]
Why close the issue? You can test case it yourself, open jsfiddle.net and select Jquery (edge). Use the switch button and validate, it is not working. As Firebug has been deprecated, its support is beeing slowly removed. 

Well the grand plan seems to be disabeling basic users ability to see page source and cookies. Another how to say move to centrialized control where people have apsolutely nothing to worry about. Its working right now, goverments, centrialized banking and food supply. Internet is already a virtual layer on real network, but who gives a shit, centrialized pest control is coming. It is already implemented and has been working for hundreds of years.

**Comment by oskarkrawczyk** [comment]
> Use the switch button and validate

What switch button?

**Comment by akotulu** [comment]
[Here](http://existanz.planet.ee/temp/jquery_edge_switch.png) is a snippet.
