### ISSUE TITLE
Editor Layout: Horizontal Tabs

### ISSUE THREAD

**Issue by madeas** [jsfiddle/jsfiddle-issues#1463]
In continuation of the conversation on Twitter https://twitter.com/andrejsharapov/status/1135441317188820992

It would be nice to have such a horizontal layout. This is similar to the “Bottom results”, but tabs are used here (i.s. the visibility of only one workspace + result)

Thanks.

**Comment by oskarkrawczyk** [comment]
Done!

<img width="1250" alt="Screen Shot 2019-06-05 at 18 26 23" src="https://user-images.githubusercontent.com/34213/58973114-743a6c80-87bf-11e9-8999-1f4840de2590.png">
