### ISSUE TITLE
Colaboration not working 

### ISSUE THREAD

**Issue by darkeye2** [jsfiddle/jsfiddle-issues#1464]
Since today I am unable to open an existing colaboration link. 
There ist an error in the console output:

ReferenceError: currentGrid is not defined
launchCollaboration https://jsfiddle.net/js/_dist-editor.js?update_05_06_2019_1:1
    r https://jsfiddle.net/js/_dist-editor.js?update_05_06_2019_1:1
    checkCollaboration https://jsfiddle.net/js/_dist-editor.js?update_05_06_2019_1:1
    render https://jsfiddle.net/js/_dist-editor.js?update_05_06_2019_1:1

I allrady tried in ff and chrome and also cleared the cache

**Comment by oskarkrawczyk** [comment]
Regression from yesterdays update. Will fix.

**Comment by oskarkrawczyk** [comment]
Fixed!
