### ISSUE TITLE
The "CSS linting" is a joke

### ISSUE THREAD

**Issue by MichaelXF** [jsfiddle/jsfiddle-issues#1466]
‼️‼️‼️

Known issues (see README.md) will not be 
addressed and most likely will be closed.

‼️‼️‼️

While writing some css, a linter is a very nice tool that lets you know when you're doing stuff wrong. However the CSS linter on JSFiddle should really be looked at. It's very annoying that the css linter shows RED dots for warnings. Linting is a warning thus it should be yellow. AND the CSS Linter should be revised.

CSS Linter flaws:
1. Marks empty lines as an ERROR(red), empty lines should be allowed since it allows to read the code easier.
![image](https://user-images.githubusercontent.com/25538372/59718527-5d950c00-91e8-11e9-97e2-7e87882df00b.png)
2. Linting is not an error, its a warning, thus it should in yellow
3. The linter doesn't check basic display: inline rules
![image](https://user-images.githubusercontent.com/25538372/59718732-c2506680-91e8-11e9-91df-b0b5a0990ab6.png)

4. The linter allows you define rules for IDs (which is bad practice
![image](https://user-images.githubusercontent.com/25538372/59718905-22470d00-91e9-11e9-8a0a-e6d2ec61b77e.png)
)

Again all these are warnings, they should show with a yellow dot.

This should be removed as its not helpful:

![image](https://user-images.githubusercontent.com/25538372/59718997-5b7f7d00-91e9-11e9-870b-a732c2ff2ab9.png)

**Comment by oskarkrawczyk** [comment]
Please change the title to something less aggressive and I'll look into this.

**Comment by oskarkrawczyk** [comment]
Adjusted a few rules in Stylelint. Severity should now default to `warning` instead of `error`.

Closing and locking since the issue author seems aggressive, and I don't need this here.
