### ISSUE TITLE
No security contact listed anywhere

### ISSUE THREAD

**Issue by thephpjedi** [jsfiddle/jsfiddle-issues#1467]
There is no security contact listed at jsfiddle.net nor in this repo.

I want to report a potential security issue, but cannot find how to do so. I do not want to publish the details on a public repo. :) There should also be a security contact published for any future reports to be handled sensitively.

**Comment by oskarkrawczyk** [comment]
@thephpjedi you can drop an email to support@jsfiddle.net, I'm reading it.

Note: we don't run a bug bounty program

**Comment by thephpjedi** [comment]
@oskarkrawczyk Thanks for the contact info. While verifying the tests today, I realized the issue is already mitigated by JSFiddle. Was testing a lot of different sites in a short period of time, and mistakenly thought this one was also vulnerable. Apologies for opening this unecessary issue yesterday.

Even without a bounty program, providing a contact form or email address as a security contact would help folks attempting to disclose responsibly. The contact methods should be easily findable on jsfiddle.net and anywhere else a user or security researcher is likely to look. Took a bit of effort to determine this issue tracker was the best place to reach out. Others with less patience or more malicious intent may give up sooner.

Apologies again, and have a great week!
