### ISSUE TITLE
Unexpected syntax highlighting for two Mozilla prefixed media queries

### ISSUE THREAD

**Issue by bershanskiy** [jsfiddle/jsfiddle-issues#1469]
## Summary
 - JSFiddle incorrectly highlights `min--moz-device-pixel-ratio` and `max--moz-device-pixel-ratio` as "unknown media feature"
 - JSFiddle incorrectly accepts `-moz-min-device-pixel-ratio` and  `-moz-min-device-pixel-ratio` as valid media features

## Demo
Live demo: https://jsfiddle.net/ecxspq30/
![image](https://user-images.githubusercontent.com/45960703/59982381-f35cdc80-95d6-11e9-875a-8af5bfd06ca6.png)

## Related issues
This bug was discovering while working on https://github.com/mdn/browser-compat-data/pull/4316 where you can see more background information on these weird media feature names.

**Comment by oskarkrawczyk** [comment]
This is a non-standard feature, which is why @stylelint doesn't support it.

<img width="724" alt="Screen Shot 2019-07-10 at 15 59 07" src="https://user-images.githubusercontent.com/34213/60975145-bbba9800-a32b-11e9-99f1-d1c517d1eccb.png">
