### ISSUE TITLE
Lag on Chrome

### ISSUE THREAD

**Issue by AyanaA450** [jsfiddle/jsfiddle-issues#1471]
All I want to do is check my fiddles via clicking my profile and clicking "All your fiddles". What then happens is that it loads well for a second or two, then slows down drastically to the point where clicking on anything on the site does not change anything. 

Below are things ive tried to fix it

- Switching google accounts

- Switching computers (three times)

- Changing internet

- Going incognito

- Going guest mode on a Chromebook

- Combinations of the above

On my desktop and laptop (no incognito) this causes chrome to freeze and I need to switch tabs or use task manager to get out of it (also, while looking at task manager it says that my CPU is at 100 for both my laptop and desktop, leading to my laptop heating up and the fans going at 100%). This result was consistent despite what internet I used. 

When switching to incognito/using the chromebook, jsfiddle loaded for a while, then the site sent an alert saying "Page Unresponsive, You can wait for it to become responsive or exit the page. (with the text) fiddle.jshell.net, in Dashboard - JSFiddle - Code Playground." This was also consistent despite my internet.

Am I the only one having this problem?

Edit: Tried it with no other tabs open and no background processes, same thing

I added an image of the alert on my chromebook (when i switched internet and went guest mode)
![image](https://user-images.githubusercontent.com/19824915/60751955-ac82c580-9f8c-11e9-93d6-e269a3a1a951.png)

this is the pure lag on my desktop/laptop
![lag](https://user-images.githubusercontent.com/19824915/60751990-46e30900-9f8d-11e9-9b34-bc1726efebf5.PNG)

**Comment by oskarkrawczyk** [comment]
The listing is trying to render one (or more) of your fiddles that's hogging the CPU, hence the unresponsive behavior.

It's possible to add `?disable_render=true` to the end of URL's where fiddles are listed - this will disable the results tab, allowing you to remove or fix the rogue fiddle.

We cannot detect on our end if a fiddle is taking 100% of the CPU, so there are no ways to mitigate this unless it's fixed by the author.
