### ISSUE TITLE
Code area bad word-break hides right columns

### ISSUE THREAD

**Issue by brunocapu** [jsfiddle/jsfiddle-issues#1473]
# Code area bad word-break

The JavaScript code area does not break lines on big string values correctly, which is hiding far away the right columns.

Example: https://jsfiddle.net/brunocapu/1tpyw3ea/

## Fix

On Inspect, changing the class `CodeMirror-wrap`
from: `word-break: normal;`
to: `word-break: break-word;` or `word-break: break-all;`
might fix.

**Comment by brunocapu** [comment]
Hi guys! We have a [jslib](https://docs.lacunasoftware.com/en-us/content/typedocs/web-pki/classes/_lacuna_web_pki_d_.lacunawebpki.html) with many code samples on jsfiddle. All samples have base64 strings which is now totally hiding away the **Result area**. Could we get some feedback on this?  Thanks.

**Comment by oskarkrawczyk** [comment]
I see the issue. `word-break: break-word` won't fix this, need to find a different solution to the problem.

**Comment by brunocapu** [comment]
Hi Mr @oskarkrawczyk ,
I can't tell if it will break other code behavior, but I was pretty able to reproduce the fix on both Chrome and Firefox. I would opt for `break-word`: [word-break](https://user-images.githubusercontent.com/3412136/61980381-00515f00-afcd-11e9-943a-936376073ce9.gif)
Thanks for your consideration.

**Comment by oskarkrawczyk** [comment]
@brunocapu Double checked again, and in fact the solution you've provided addresses the issue so thank you for that!

I've just updated the code, should be fine now.
