### ISSUE TITLE
Sidebar bugged out on "All your fiddles" page

### ISSUE THREAD

**Issue by Christopher-Hayes** [jsfiddle/jsfiddle-issues#1474]
For some reason the sidebar is overlaping the page content on the "All your fiddles" page. I'm not sure what the expected behavior is for this page other than to be fixed to the left edge, but the weird overlap is distracting.

![image](https://user-images.githubusercontent.com/6013871/61597174-1630df80-abdb-11e9-889c-c6a8584d4aae.png)

**Comment by BerkerYuceer** [comment]
I was exactly writing the same issue just now : here is an image: [https://drive.google.com/open?id=1OZokd0yd3W9PjrFZaX1ICZIqbY8SozZ-](url)

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by BerkerYuceer** [comment]
ty nice touch there "calc(100vh - 60)" :D is it always been same in mobile or was it on top? @oskarkrawczyk

**Comment by oskarkrawczyk** [comment]
@BerkerYuceer We don't go out of our way to support mobile size devices. It's always been this way.
