### ISSUE TITLE
Forked, Renamed Fiddle Shows Old Name in Editor

### ISSUE THREAD

**Issue by johnyradio** [jsfiddle/jsfiddle-issues#1475]
- Make a fiddle
- Save and make base
- Fork
- Rename, save, make base
- Go to dashboard
- See both copies
- Click to open the renamed copy
- Old name still showing in editor
- Go back to dashboard
- Open new one again
- Now it has the correct name in editor. 

time delay issue?

**Comment by oskarkrawczyk** [comment]
Followed the steps but can't replicate the issue.

Note that if there's a `... is the latest revision` on the fiddle tile in the listing, it hasn't been set as base, hence will have the old name.

Another edge-case, sometimes the cache doesn't get refreshed straight away and title might be outdated.
