### ISSUE TITLE
Can't Move Collaborate Panel

### ISSUE THREAD

**Issue by johnyradio** [jsfiddle/jsfiddle-issues#1476]
hi

in collaborate mode, i cannot move the collaboration panel. dragging the 3-dots handle doesn't work. 

in chrome browser, incognito.

![image](https://user-images.githubusercontent.com/6564280/61680571-e3f8ae00-acbe-11e9-9485-7f8aa044bbd8.png)

**Comment by oskarkrawczyk** [comment]
Yeah, that doesn't work and never did really. It's an issue with https://github.com/mozilla/togetherjs - the library is not maintained anymore.
