### ISSUE TITLE
Помогите найти ошибку

### ISSUE THREAD

**Issue by StarProgramm** [jsfiddle/jsfiddle-issues#1478]
<meta charset="utf-8"> 
<script type="text/javascript">
	var massiv2 = [1, 4, 15, 25, 8, 45, 20, 100, 85],
		max = 0;
	function buba(massiv){
		var count = massiv.length,
			i = 0;
			f = 0;

		console.log(count)
		console.log (massiv[i])

		while (f >= count) {
				if 
				(max < massiv[i]){
				max = massiv[i];
				i++;
			}
				
				else 
				{max = massiv[i];
				i++;
			}

			}
			return max;
		}
		buba(massiv2);
</script>

**Comment by oskarkrawczyk** [comment]
Closing. Please use english and describe your problem.
