### ISSUE TITLE
Long strings break two column layout

### ISSUE THREAD

**Issue by lioras** [jsfiddle/jsfiddle-issues#1480]
In the classic view (and other two column views as well), the number of textarea columns the javascript editor stretches to before wrapping a very long string (that has no punctuation or whitespace) causes the main column to stretch off screen, making it impossible to resize the first column or view the second column. 

![image](https://user-images.githubusercontent.com/3299203/62403884-3b134400-b545-11e9-98c1-a7eda16932df.png)

**Comment by oskarkrawczyk** [comment]
Closing. Dupe #1473
