### ISSUE TITLE
CSS nth-child not working

### ISSUE THREAD

**Issue by alpiepho** [jsfiddle/jsfiddle-issues#1481]
The follow HTML/CSS is suppose to show 4 boxes with different colors.   When I test in a simple test.html it works correctly.  When I run in jsfiddle, only the first box has color.

I would love to understand why this is happening.

`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Articles</title>
  <style>

    html,body {
      padding:0;
      margin:0;
      height:100%;
    }
    article {
      min-height: 50%;
      width: 50%;
      float: left;
    }
    article:nth-child(1) {
      background: red;
    }
    article:nth-child(2) {
      background: yellow;
    }
    article:nth-child(3) {
      background: blue;
    }
    article:nth-child(4) {
      background: green;
    }
  </style>
</head>
<body>
  <article>First</article>
  <article>Second</article>
  <article>Third</article>
  <article>Fourth</article>
</body>
</html>`

**Comment by oskarkrawczyk** [comment]
Works fine as far as I can see: https://jsfiddle.net/cmjou7x2/

**Comment by alpiepho** [comment]
Thanks for looking.  It is working on my fiddle now too.  Next time I will try some more experiments and grab a screenshot.
