### ISSUE TITLE
Lost My Website!!!

### ISSUE THREAD

**Issue by LouisPi** [jsfiddle/jsfiddle-issues#1483]
Hello,

I started creating a website a week or two ago but after a while, I thought it would be wise to sign up to jsfiddle rather than doing it without being logged in. However, after logging in, wy website code and hours of work had disappeared! Can anyone help (I had saved it anonymously)?

Thanks,
Louis

**Comment by oskarkrawczyk** [comment]
1. After signing up, go back to the fiddle you were working on, the code will be there
2. There’s a big red “unsaved changes” link in top right, if you had unsaved changed they would be there
3. Go to the anonymous fiddle you’ve saved, fork it, it’ll fork under your username

Note for future: after logging you have the ability to auto-save code.

We don’t store unsaved drafts on the server for privacy reasons so we can’t bring your unsaved code back.

**Comment by LouisPi** [comment]
Thanks for the help! I'm pretty sure I tried this earlier and all I got back was the first version of the code (not the edited version which I saved after every edit).

**Comment by LouisPi** [comment]
Thank you once again for the help. I've just got back home and it worked.
