### ISSUE TITLE
XTK updates

### ISSUE THREAD

**Issue by oskarkrawczyk** [jsfiddle/jsfiddle-issues#1484]
Update The X Toolkit to newest version, change name to XTK and load via CDN

**Comment by haehn** [comment]
and via https please :)

**Comment by oskarkrawczyk** [comment]
An edge version of XTK is loaded. But the library itself seems abandoned, so leaving as it is.

**Comment by haehn** [comment]
whaaat its not abandoned.. we are using it to teach at umass boston. https loading would allow me to include jsfiddle in iframes

**Comment by haehn** [comment]
why did you remove it?

**Comment by haehn** [comment]
@oskarkrawczyk please add it again, all the lesson links are broken now.

**Comment by haehn** [comment]
i opened a new issue #1570
