### ISSUE TITLE
Add publishing options

### ISSUE THREAD

**Issue by JeromeA** [jsfiddle/jsfiddle-issues#1485]
Feature request: add an option to upload the files of a project to an FTP web hosting server, so that the project is effectively published.

**Comment by oskarkrawczyk** [comment]
While it would be nice to have, that's for sure, I can tell straight away is not going to happen.

One simple reason: I don't want to store any login credentials to 3rd party servers – this is too much of a recipe for disaster.

Not storing any private information about our users is top priority for us, we don't require any information apart from user/pass, we don't even have Google Analytics, just in case Google decides to track users via their JS snippet.
