### ISSUE TITLE
Allow WebHID in feature policy

### ISSUE THREAD

**Issue by robatwilliams** [jsfiddle/jsfiddle-issues#1486]
The WebHID API is available behind a flag in Chrome 78, currently in beta - https://www.chromestatus.com/features/5172464636133376

Developers will want to share demos using WebHID. Currently this isn't possible on JSFiddle (or JSBin, bl.ocks.org, ...) as it's blocked by feature policy.

Could it please be allowed?

https://wicg.github.io/webhid/index.html#feature-policy

Regarding security/privacy, a page cannot access (or even learn of the presence of) a device before a user provides consent using a built-in dialog in Chrome. That dialog can only be launched from within a user-initiated context such as a mouse click.

**Comment by oskarkrawczyk** [comment]
There are no signals from any other browser vendor on supporting this. Way too early to add it to JSFiddle.
