### ISSUE TITLE
Diff Latest Revision to Base

### ISSUE THREAD

**Issue by BananaAcid** [jsfiddle/jsfiddle-issues#1487]
At least diff the latest revision to the saved base.

Having "#17 is the latest revision" may just happen because the browser window was open and an unnecessary auto save happened.

OR: do not autosave if it all is equal.

**Comment by oskarkrawczyk** [comment]
Diffing is for unsaved code, not to compare revisions.

**Comment by BananaAcid** [comment]
@oskarkrawczyk 
> Diffing is for unsaved code, not to compare revisions.

So, there is something usefull missing.

**Comment by oskarkrawczyk** [comment]
Already on roadmap.
