### ISSUE TITLE
Why is JSFiddle down right now?

### ISSUE THREAD

**Issue by Reader8765** [jsfiddle/jsfiddle-issues#1488]
https://www.isitdownrightnow.com/jsfiddle.net.html is returning that it cannot access jsfiddle.net and I can't reach it either. Why is it down right now?

**Comment by Reader8765** [comment]
UPDATE: I can access the site now and am getting this screen: 
![Capture](https://user-images.githubusercontent.com/20914635/65920928-9da28800-e3ae-11e9-87f0-9eee403d22d6.PNG) Why is this coming up?

**Comment by KPS-GitHub** [comment]
Same for me. I can get into the site if I'm not logged in and run the code I write, but when I try to login, I get this same screen after submitting my username and password.
