### ISSUE TITLE
Dashboard links open to an older (first?) version of the fiddle

### ISSUE THREAD

**Issue by mindplay-dk** [jsfiddle/jsfiddle-issues#1489]
Many of my recent fiddles, when I try to open them from the dashboard link, they open up to a very old version - possibly the first version, I'm not sure.

For example, this links opens to a very early version:

https://jsfiddle.net/mindplay/7L5fxdrk/

If I manually put a version number at the end, there are newer versions:

https://jsfiddle.net/mindplay/7L5fxdrk/35

10 or so of my most recent fiddles currently open to an old version.

Could be a bug in the dashboard when it emits the links maybe?

**Comment by mindplay-dk** [comment]
Okay, I see now, the large white link goes to the older/first version, and the little orange label next to it goes to the current version.

Has this changed recently? Why is going to an older version the default?

Shouldn't the most prominent link go the latest/current version?

**Comment by oskarkrawczyk** [comment]
It was always this way, it’s by design. 

Unless you explicitly save a fiddle version as the base, the main version is the initial one.
