### ISSUE TITLE
API example post form results in a 500 page

### ISSUE THREAD

**Issue by yyyc514** [jsfiddle/jsfiddle-issues#1490]
I'm using the sample POST page to hit up the API, but it fails every time:

http://jsfiddle.net/zalun/sthmj/embedded/result/

Have the urls changed?

**Comment by MichaelErmer** [comment]
POST is broken in general, since about 2-3 weeks, any updates on this?

**Comment by yyyc514** [comment]
It works if you hack it to post to a different URL... so I think something has changed on the backend and no one though of this little utility.

**Comment by PhilippeTrounev** [comment]
Does anyone know how to make it work with different URL as was described above? We were using  and like this feature, and would like to fix it.

**Comment by oskarkrawczyk** [comment]
The example link in the docs was using the wrong framework version in the URL. Fixed to the right one, and the example works as expected.

Sorry for the confusion.

**Comment by yyyc514** [comment]
Link or reference to the fix?

**Comment by oskarkrawczyk** [comment]
Docs: https://app.gitbook.com/@jsfiddle/s/help/api/display-a-fiddle-from-post

**Comment by yyyc514** [comment]
The docs are outside the purview of GitHub then I presume?

**Comment by oskarkrawczyk** [comment]
Indeed
