### ISSUE TITLE
Basic fiddle works in Codepen not in jsfiddle ?!

### ISSUE THREAD

**Issue by joe-oli** [jsfiddle/jsfiddle-issues#1491]
nothing complicated, click on blue tiles

https://jsfiddle.net/prideaux/0mbh97k5/

https://codepen.io/prideaux/pen/JjjjVNy

where is the issue with jsfiddle?

**Comment by oskarkrawczyk** [comment]
`unload` is implied by default

<img width="673" alt="Screen Shot 2019-10-08 at 14 17 53" src="https://user-images.githubusercontent.com/34213/66394876-795e3100-e9d6-11e9-8ade-2023ae72013c.png">

**Comment by joe-oli** [comment]
Got it, works now after i commented window.onload out.
