### ISSUE TITLE
Add Svelte boilerplate

### ISSUE THREAD

**Issue by mikemaccana** [jsfiddle/jsfiddle-issues#1492]
At this point it's fairly clear that Svelte is the 'next thing' after React / Vue. It would be useful to have a Svelte boilerplate in jsfiddle.

**Comment by oskarkrawczyk** [comment]
What’s Svelte?

**Comment by HoraceKeung** [comment]
@oskarkrawczyk https://svelte.dev/, and here is a collection of resources that more or less support the idea of using it: https://why-svelte-js.firebaseapp.com/

**Comment by oskarkrawczyk** [comment]
@mikemaccana unfortunately can't find a way to run it in the browser env.

If anyone manages to get it running on the frontend let me know and I'll add it to JSFiddle.

**Comment by mikemaccana** [comment]
Thanks @oskarkrawczyk! 😃 Maybe newer node supporting ES6 imports will help? 🤔

**Comment by oskarkrawczyk** [comment]
When we move to a node-based renderer we sure will use the newest node :)
