### ISSUE TITLE
Privacy page is still missing :/

### ISSUE THREAD

**Issue by JaneJacqui** [jsfiddle/jsfiddle-issues#1493]
Like... I wanted to make a JSFiddle account to save prototypes but the Privacy Policy link from the Sign Up page resolves to the linked #privacy# placeholder page.

I have to assume this is a known issue, and I'm aware the jsfiddle Git repo isn't the place to log bugs on the site, but it's been several weeks and the page is still a placeholder so in case you weren't awar, you're still missing a privacy policy page...
https://jsfiddle.net/privacy

**Comment by oskarkrawczyk** [comment]
Duplicate
