### ISSUE TITLE
Hello bar forces content below page.

### ISSUE THREAD

**Issue by Betanu701** [jsfiddle/jsfiddle-issues#1495]
‼️‼️‼️

Known issues (see README.md) will not be 
addressed and most likely will be closed.

‼️‼️‼️

If you have content in the JS editor, more than 18 lines, content gets pushed below page where it is not accessible while "hello-bar" is open.
id="show-result" has a height of 100vh. With hello-bar open, the 100vh is below screen. To fix this:

Add the following
```
body.hasHelloBar #editor {
   height: calc(100vh - 256px);
}

body.hasHelloBar #sidebar{
   height: calc(100vh - 256px);
}

```
This will force the editor to be aligned with the rest of the screen. Editor has a calculation, but it does not account for hello-bar being opened.

The second allows for the advertisements to be shown when hello-bar is open.

**Comment by Betanu701** [comment]
Also, The settings popup gets pushed off screen. You can add the following to fix it as well.

```
body.hasHelloBar .dropdownCont .dcWrapper{
    height: calc(100vh - 300px);
}
```

Note: 256 seems to be the magic number, at least on my system on different screens. The popup is pushed a little further so 300 seems to work. Feel free to fiddle with these if you wish.

**Comment by oskarkrawczyk** [comment]
This is by design.
