### ISSUE TITLE
Display a fiddle from POST is broken

### ISSUE THREAD

**Issue by it-s** [jsfiddle/jsfiddle-issues#1496]
Trying to initiate JSFiddle from POST api results in 
500
Oops. This shouldn't have happened.

To reproduce go to documentation:
https://docs.jsfiddle.net/api/display-a-fiddle-from-post
click Example:
http://jsfiddle.net/zalun/sthmj/embedded/result/
and then click Submit, with any settings

**Comment by oskarkrawczyk** [comment]
Duplicate #1490
