### ISSUE TITLE
Add languages (PHP, Python, MySQL ...)

### ISSUE THREAD

**Issue by imabot2** [jsfiddle/jsfiddle-issues#1498]
It would be great to create Fiddles for new languages like :
- **PHP**
- MySQL
- Python
- C / C++

To be honest, I'm a computer science professor. I use JSFiddle for my class : it's simple, easy to understand and can be embedded in my lessons, for example : [CSS colors](https://www.lucidar.me/fr/web-dev-class/lesson-2-06-css-colors/).

I would like to do the same for PHP and MySQL. For MySQL, there is this [DB-Fiddle](https://www.db-fiddle.com/) which has a similar interface, but I wonder if it is a competitor or not.

If I can help in any way.

**Comment by oskarkrawczyk** [comment]
We have no plans to support server-side languages.

**Comment by imabot2** [comment]
OK, I understand your choice, but competitors will. And JSFiddle is my favorite ! ;-)

**Comment by oskarkrawczyk** [comment]
I doubt any front-end playground will add backend languages, they would do that already.

Not mentioning Node-centric stuff, as this is a completely different breed of playgrounds.

**Comment by imabot2** [comment]
I understand, but from the user point of view, I don't care about how it is build since it works properly !
Thank you.
