### ISSUE TITLE
502 Bad Gateway when requesting `jsfiddle.net` !!

### ISSUE THREAD

**Issue by Eslam3bed** [jsfiddle/jsfiddle-issues#1499]
> #### I was creating a demo on `jsfiddle.net` and I noticed that some times when I save the on the display area `502 Bad Gateway` and when I refreshed the page all the page gave me `502 Bad Gateway`

![image](https://user-images.githubusercontent.com/20760072/68211380-1e712700-ffe0-11e9-91f8-7d474e51a486.png)
![image](https://user-images.githubusercontent.com/20760072/68211461-48c2e480-ffe0-11e9-9576-6e1a90537026.png)

**Comment by oskarkrawczyk** [comment]
Yes, we're working on a solution to the issue.
