### ISSUE TITLE
Window size in pixels disappears on running code

### ISSUE THREAD

**Issue by aurangzaib-danial** [jsfiddle/jsfiddle-issues#1500]
When I resize the output window, I can see the window size in pixels. This functionality stops working if I run a new code by clicking Run or by pressing Ctrl + Enter.  When I reload the entire fiddle page then it starts working again and I can look at the output window current size as I resize the window.

**Comment by oskarkrawczyk** [comment]
Can confirm it does disappear, weird. Will look into that.

**Comment by oskarkrawczyk** [comment]
Fixed
