### ISSUE TITLE
[feature request] Export My Fiddles

### ISSUE THREAD

**Issue by Nycticorax** [jsfiddle/jsfiddle-issues#1501]
I think the title is clear enough. Over the last two years my 'study' fiddles have quite accumulated and I would be glad printing t-shirt with my transducers, monads and other custom Symbols class factories ;D

More seriously, a simple Export feature, where the user could select all / some of her or his fiddles would be very handy. 

edited: I am thinking of a downloadable .zip of .js files, with an option to have just as many .js files as fiddles, or to have only 1 .js file with some trivial separator between fiddle contents.

**Comment by oskarkrawczyk** [comment]
Export to...?

**Comment by Nycticorax** [comment]
Downloadable .zip of .js files, with an option to have just as many .js files as fiddles, or to have only 1 .js file with some trivial separator between fiddle contents. 

Added to OP.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
