### ISSUE TITLE
BigInt literals show as an error

### ISSUE THREAD

**Issue by i-e-b** [jsfiddle/jsfiddle-issues#1503]
Javascript `BigInt` literals are shown as errors in the editor, but should not be.

Example:
Page
```html
<pre id="output"></pre>
```
Script
```javascript
document.getElementById("output").innerHTML+= 492367237969n;
```

This runs as expected, showing the output `492367237969`.
However, the script editor gives the error `Unexpected '4'`. (This error message will give whatever is the first digit of the number. For example, `0xffn` will give `Unexpected '0'`)

![image](https://user-images.githubusercontent.com/576220/69417442-92b20700-0d10-11ea-9c0e-95ebc1ea78d6.png)

Tested in Chrome 78 on Win10.

**Comment by i-e-b** [comment]
This can be worked around by using the string constructor syntax:
`BigInt("492367237969")`

**Comment by oskarkrawczyk** [comment]
We'll have to wait until @jshint adds support for this. Until then three solutions:

- ignore it
- turn off code linting
- use the costructor
