### ISSUE TITLE
Styles dissappearence on view resize to lesser % with Mozilla Developer Edition 71.0b12 (x64)

### ISSUE THREAD

**Issue by BerkerYuceer** [jsfiddle/jsfiddle-issues#1504]
With Mozilla Developer Edition on window resize to 90% or 80% or less, all styles are getting mixed up while mouse is on Run button. See screenshots:

![Mozilla_DeveloperEdition_71 0b12_(64bit)0](https://user-images.githubusercontent.com/2599466/69867970-7e927a80-12b9-11ea-8108-f611ff5fef97.jpg)
![Mozilla_DeveloperEdition_71 0b12_(64bit)1](https://user-images.githubusercontent.com/2599466/69867975-80f4d480-12b9-11ea-8cd5-01a1eb000680.jpg)

And output window gives secure connection faliure:

![Mozilla_DeveloperEdition_71 0b12_(64bit)2](https://user-images.githubusercontent.com/2599466/69868005-9833c200-12b9-11ea-8d8c-b4e994e26ccb.jpg)

On Chrome also styles are all messed up:

![Chrome](https://user-images.githubusercontent.com/2599466/69868192-13957380-12ba-11ea-99f3-ee648700f1c1.png)

Also gives secure connection faliure.

Microsoft Edge is the same.

It's been going on for sometime. I do not know if it is informed yet cause I couldn't see any report about it.

**Comment by oskarkrawczyk** [comment]
@BerkerYuceer I can't seem to replicate any of these problems.

- Can you provide the fiddle you see this happening on?
- Can it be that you're using some kind of a system content blocker that blocks css/js from our domain?
- Can you refresh your cache for jsfiddle.net and try again?

Nobody earlier reported these problems, but it is weird that you have the same problems on three different browsers.

**Comment by BerkerYuceer** [comment]
Turned connection into http to see what is the issue. Seems like my provider made some changes without noticing yet in TLS connection it supposed to thrust. The issue can be closed for now until I solve the provider problem in Monday. If there is no changes in result I will inform you! Thanks for quick support...

**Comment by BerkerYuceer** [comment]
Ok issue with style disappearence is continues. Firefox Developer Edition 71.0b12 (x64)
When view only is resized to low sizes %90 or less **(by CTRL + MiddleMouseScroll)** at the left side or at the right end of view empty space taking place. I have marked with red where this resize is made! and marked the buttons where style getting mixed by when mouse is on them.

    Can you provide the fiddle you see this happening on? 
    **All fiddles!**

    Can it be that you're using some kind of a system content blocker that blocks css/js from our domain?
    **All css request completes successfully. No blocker is in motion.
    -Web Developer Tool
    -uBlock
    -NoScript 
    are all closed or in thrusted.**

    Can you refresh your cache for jsfiddle.net and try again?
    **Cleanced triple times... Also done cleaning in local storage following the issue:
    "https://github.com/jsfiddle/jsfiddle-issues/issues/493" **

![styledisappears](https://user-images.githubusercontent.com/2599466/69939565-35c50680-14f1-11ea-8361-dec752242e51.png)

![resim](https://user-images.githubusercontent.com/2599466/69940025-49bd3800-14f2-11ea-83f9-038aa311c09c.png)

**Comment by BerkerYuceer** [comment]
I have located the source of this as:  (in hover state only)
![resim](https://user-images.githubusercontent.com/2599466/69941927-395a8c80-14f5-11ea-92b7-3863de92d3a2.png)

**Comment by oskarkrawczyk** [comment]
Mmm, ok, super edge-case caused by how Firefox scales content. I can replicate this only in 30% size on macOS, but on Windows it's clearly more severe.

**Comment by BerkerYuceer** [comment]
Incredible fix thanks a lot life is much more easier now.. :) 👍
