### ISSUE TITLE
testing my js-class inherited from 'moment'

### ISSUE THREAD

**Issue by hshahus** [jsfiddle/jsfiddle-issues#1505]
I need help to test my javascript class inherited from js-moment.
- I am trying to use js-fiddle for moment : link: https://jsfiddle.net/0fj9r321/

I am not able to use moment methods or my class IsoMoment methods either.
Need help to understand where I am wrong while inheritance the js-moment.

**Comment by oskarkrawczyk** [comment]
@hshahus This is not a JS support forum. I'd suggest asking on StackOverflow or anywhere where `js-moment` is developed.

This repo is for JSFiddle issues only.
