### ISSUE TITLE
About IPv6 support

### ISSUE THREAD

**Issue by ikomwrestling** [jsfiddle/jsfiddle-issues#1508]
Jsfiddle.net website doesn't support IPv6.

Since JSFiddle seems to use Digitalocean, fixing this should be easy as [enable IPv6 on droplets](https://www.digitalocean.com/docs/networking/ipv6/how-to/enable/).

**Comment by oskarkrawczyk** [comment]
Since there's more downside to upside of supporting IPv6, we're leaving it out (for now). Will obviously add support sometime in the future.

**Comment by michaelkkl** [comment]
I second this request.
Especially in Europe and global IPv6 Traffic is growing.
