### ISSUE TITLE
Internal server error 500 on certain demo.details

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#1509]
Demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/dumbbell/

This page pulls the content from GitHub. Preliminary testing reveals that something in the [demo.details](https://github.com/highcharts/highcharts/blob/master/samples/highcharts/demo/dumbbell/demo.details) causes the error. Especially the line `new_until: 2020-03-11` seems to have an impact. We are using the `demo.details` or jsFiddle related data as well as other meta data.

**Comment by oskarkrawczyk** [comment]
Our validator expects only JSFiddle data, any other is invalid and will cause an error.

Will have to look into that.

**Comment by TorsteinHonsi** [comment]
> any other is invalid and will cause an error

But it doesn't. We have had other data there for years. Until we now added `new_until`.

**Comment by oskarkrawczyk** [comment]
Partly you're correct, but in this instance, providing a date was the problem since we did not expect the YAML parser to have to load a date. 

It should now handle dates.

Let me know if it works for you.

**Comment by TorsteinHonsi** [comment]
It does, thanks so much for the swift reply and fix!
