### ISSUE TITLE
Register jsfiddle as a Brave creator

### ISSUE THREAD

**Issue by rossjrw** [jsfiddle/jsfiddle-issues#1510]
While using the Brave browser I had a popup on jsfiddle advising me to add an exception in my ad blocker for privacy-respecting, tracker-free ads.

If that's the case, why not cut out the middleman (me) and register jsfiddle as a Brave creator?

Brave has a system wherein users earn BAT, a cryptocurrency, for being exposed to privacy-respecting ads. Users are then given the option to contribute a portion of that BAT to content creators they've visited, which is automatically determined based on how much of their browsing time was spent with that creator.

By registering jsfiddle as a Brave creator, you'd be able to accept automatically-generated tips (and explicity-donated tips) from Brave users. I'm not sure what the process is for having an advertising provider approved with Brave, but if your ads are truly tracker-free as you assert, then I can't imagine it'd be an issue.

It's entirely possible that users have already donated tips to jsfiddle, just you're currently not able to pick them up.

https://creators.brave.com/

**Comment by oskarkrawczyk** [comment]
Ok, gotta be honest with myself here - no plans on supporting Brave in any way.
