### ISSUE TITLE
Embedded JSfiddle snippet is not loading inside cordova app.

### ISSUE THREAD

**Issue by debashish4** [jsfiddle/jsfiddle-issues#1511]
I am trying to embed jsfiddle snippet into my cordova app but it doesn't show app. but it does show up if i view directly from browser. I have tried using this  "<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"/>" but still it doesn't work in my cordova app.

**Comment by oskarkrawczyk** [comment]
I don't know, not using Cordova. Do you have any debug details? Errors, anything?
