### ISSUE TITLE
Dark theme option hidden; cannot switch to light theme

### ISSUE THREAD

**Issue by senocular** [jsfiddle/jsfiddle-issues#1514]
Dark theme option in the settings menu

https://docs.jsfiddle.net/editor-settings#layout-and-themes

is no longer available.  Users cannot switch to light theme.

![image](https://user-images.githubusercontent.com/3536716/71834175-93aeb600-307c-11ea-9203-167391c40d22.png)

**Comment by oskarkrawczyk** [comment]
Yes, light theme has been removed since it's a lot of overhead to support multiple and not enough users really used it.

**Comment by RichardD2** [comment]
Please reconsider this. I'm sure I'm not the only one who can't look at a dark theme on a computer monitor for more than a few minutes without getting a headache!

**Comment by oskarkrawczyk** [comment]
I've been reconsidering it for the past 2 years, did 2 polls, results are pretty clear. Coding overhead to keep the light theme in is not worth it.

**Comment by ThePendulum** [comment]
In the poll on Twitter, 20% voted they're using the light theme, which is not quite a "low single digit percentage" imo, especially considering it became the default some time ago and a lot of people may not even have realized a light theme was available. I understand the development overhead is a pain, but it is a really really unfortunate change to my favorite tool none the least.

I don't know how much of a hassle it would be to have an older stale version with the light theme available at old.jsfiddle.net, similar to what reddit does.

**Comment by oskarkrawczyk** [comment]
The one on Twitter was not the only poll. I understand the light theme retirement might be unfortunate for some users, but it's either that or the coding overhead for a single dev working on JSFiddle.

I'm going to put the light theme on the [public roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), if it gets enough traction from users that miss it, I'll swallow the bullet and bring it back.

**Comment by sillyslux** [comment]
traction +1 from me

**Comment by dwiyatci** [comment]
+also from me :smiley::guitar:

**Comment by cayhorstmann** [comment]
The reason I would like the light mode back is presentations and classes. Projectors do a **much** better job showing light mode than dark mode.

**Comment by oskarkrawczyk** [comment]
No +1's please. Closing topic so there's no +1 temptation.

**Comment by ryanpcmcquen** [comment]
This alone has caused me to switch to JSitor after many years of using JSFiddle. It's an unfortunate removal as presenting with a light theme is far more useful.

**Comment by ryanpcmcquen** [comment]
One thing you could do to limit the burden of maintaining this, is to restore the light theme, and then just make the dark theme switch apply a CSS filter like this:

```css
.dark-mode {
    filter: invert(1) hue-rotate(180deg);
}
```

**Comment by oskarkrawczyk** [comment]
I'll bring it back if it gets a reasonable amount of votes on the roadmap.

**Comment by jayhilwig** [comment]
Relevant HN article (Apr 28, 2020) citing Nielsen/Norman references on science/usability of light background interfaces:
https://kevq.uk/is-dark-mode-such-a-good-idea/

**Comment by enryco** [comment]
This is a no-brainer. @ryanpcmcquen even presented you with a one-liner to fix this. Besides, there are couple of other ways to achieve and maintain this easily.

I can't even use the site during the day and ended up using one of the [alternatives](https://alternativeto.net/software/jsfiddle/)

**Comment by MikeWilliams-UK** [comment]
Bring back light mode please.

**Comment by sarahcburnett** [comment]
If found a hack so my students can read the comments I type when I teach.
I go to .cm-comment and the .css source file and make it brighter. 
It works as long as I don't refresh the page.

**Comment by alex-kovalchuk** [comment]
Don't ask more. The developer doesn't care about us.

**Comment by andresams** [comment]
Please, bring it back. I can not see anything on a black background. I'm no hookie: 20+ years of coding.
