### ISSUE TITLE
JSFiddle not loading on Chrome, works on Safari

### ISSUE THREAD

**Issue by philipmjohnson** [jsfiddle/jsfiddle-issues#1515]
After a few months away from JSFiddle, I tried it this morning on Mac Chrome (Version 79.0.3945.88 (Official Build) (64-bit)) and got a bouncing blue cloud and the following error message in the console:

<img width="1260" alt="Screen Shot 2020-01-06 at 11 12 11 AM" src="https://user-images.githubusercontent.com/290288/71849221-a1147200-3075-11ea-8ac2-f23a1656ea78.png">

I tried in Safari and JSFIddle loaded normally.

**Comment by oskarkrawczyk** [comment]
Can't seem to replicate behavior.

@philipmjohnson Can you refresh your Chrome cache and try again?

If the issue is persistent, can you let me know if running in incognito changes anything? Any additional debug info would be appreciated.

**Comment by SFoskitt** [comment]
@oskarkrawczyk - if there is a better place to report issues with the site, please do let me know.

I am also having issues loading JSFiddle in Chrome today, Version 79.0.3945.88.  The code panels load (HTML, JS, CSS) but the preview pane is broken and loads a Cisco Umbrella server error "502 Bad Gateway".  Below is the whole message.

This happens in Chrome (version mentioned above), Safari, and Firefox on Mac.

In the Network tab of the dev tools I see the 502 status on this network call:
Request URL: https://fiddle.jshell.net/kq06hmy6/show/
Request Method: GET
Status Code: 502 Bad Gateway
Remote Address: 146.112.45.33:443
Referrer Policy: strict-origin-when-cross-origin

These are the JSFiddles I have attempted to load today and all have returned with the same issue - code panels are okay, preview panel is not.
https://jsfiddle.net/kq06hmy6/
https://jsfiddle.net/kogcyc/L9apLxLs/
https://jsfiddle.net/zinoui/BmLpV/

=========
502 Bad Gateway
--
An upstream server error has occurred. If you believe you are seeing this message in error, please contact your network administrator.

**Comment by oskarkrawczyk** [comment]
@SFoskitt Github Issues is for reporting Issues. The one you're reporting has nothing to do with the original issue. Please post a new one.

**Comment by georgir** [comment]
Same issue here. Thing works fine in incognito mode tho, so its indeed some mess up with the settings in localStorage: `{"editor_mode":"grid_1","showHints":false,"darkTheme":true}`
After removing the keys one by one, it seems to be `"editor_mode":"grid_1"` that caused the issue for me.

**Comment by oskarkrawczyk** [comment]
@georgir Thanks, this will help debugging the issue, will look into it.

**Comment by oskarkrawczyk** [comment]
Fixed.

Thanks again @georgir

**Comment by lazylester** [comment]
In case it's useful to you... I have long had an issue with jsfiddle in chrome... the bouncing cloud (loading animation) never goes away. Finally I stumbled across this thread and tried clearing the Local storage... presto problem solved! Unfortunately now the problem is solved, I can't give you the console error message to help you when if/when the problem surfaces again.
