### ISSUE TITLE
500 on Firefox

### ISSUE THREAD

**Issue by castortech** [jsfiddle/jsfiddle-issues#1516]
Since about 2 days ago I'm always getting "500 Oops. This shouldn't have happened." on Firefox Windows.

Restarted, cleared cache, tried in private mode and always same issue. Works fine on Chrome.

**Comment by oskarkrawczyk** [comment]
@castortech Where exactly are you getting that 500?

**Comment by castortech** [comment]
Home page; https://jsfiddle.net/
and here: http://jsfiddle.net/jchaplin2/nfz9sucn/824/ 
and here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/column-borderradius/

seems to be everywhere AFAICT

**Comment by oskarkrawczyk** [comment]
@castortech are you by any chance using a content blocker or do something to your User-Agent string?

**Comment by castortech** [comment]
I have the standard Firefox protection on, but I just added an exception for jsfiddle and no change

**Comment by oskarkrawczyk** [comment]
A tough one. Any chance you could paste here what  `navigator.userAgent` (in webdev console) outputs on your Firefox? That might help pinpointing what's going on

**Comment by castortech** [comment]
Here you go

![image](https://user-images.githubusercontent.com/85858/71980400-ec519080-31ed-11ea-89ac-471a909636c7.png)

**Comment by oskarkrawczyk** [comment]
@castortech Should be fixed, can you confirm please?

**Comment by castortech** [comment]
It is indeed, thanks so much

**Comment by oskarkrawczyk** [comment]
Thanks for reporting this in, it was a really weird edge-case.
