### ISSUE TITLE
Can't Save My Fiddle

### ISSUE THREAD

**Issue by FiZiX** [jsfiddle/jsfiddle-issues#1517]
Hello,

I'm trying to save a modified version of this fiddle:

http://jsfiddle.net/alfg/sr0tpn4x/

However, it never saves and I get the following error in the console:

`Access to XMLHttpRequest at 'https://jsfiddle.net/_save' (redirected from 'http://jsfiddle.net/_save/') from origin 'http://jsfiddle.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by AMBudnik** [comment]
I get this https://github.com/jsfiddle/jsfiddle-issues/issues/1522 when I wan to save your demo

**Comment by oskarkrawczyk** [comment]
Use SSL (`https`)
