### ISSUE TITLE
Changing username cause 500 error

### ISSUE THREAD

**Issue by webtop** [jsfiddle/jsfiddle-issues#1518]
Go to the user profile and change the username.

Expected behavior: error message informing user of reason the profile update failed.
Actual behavior: Message stating "Oops, that shouldn't have happened" and 500 error.

Not a big deal, just thought you should be aware.

Thx

**Comment by oskarkrawczyk** [comment]
@webtop I'm going to guess and say you tried to change the username to something really short?

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by webtop** [comment]
No. I was changing it from “webtop” to “digital_pig”

It ain't easy being green! Please recycle.
