### ISSUE TITLE
Editor behavior doesn't change after setting options

### ISSUE THREAD

**Issue by CurleyWebDev** [jsfiddle/jsfiddle-issues#1520]
When I turn off "Only auto-run code that validates" and "Live code validation", this doesn't change the editor's behavior. Also, these settings are turned "on" by default.

**Comment by oskarkrawczyk** [comment]
Known issue. Working on a fix.

**Comment by CurleyWebDev** [comment]
Great!

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by CurleyWebDev** [comment]
Great!
