### ISSUE TITLE
404 on 'save' and 'fork' when using a non-SSL connection

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1522]
Since yesterday I get `404` each time I wan to `save` or `fork` a demo.

I saw this topic https://github.com/jsfiddle/jsfiddle-issues/issues/1512 but it relates to loading resources and mine is pure vanilla.

I wanted to fork this demo http://jsfiddle.net/sezpqa8m/2/, and even when I remove all the resources and keep this clean I still get `404` in the result page (not like [here](https://github.com/jsfiddle/jsfiddle-issues/issues/1412) where there's 4040 for the whole page) and browser slows down really bad.

![image](https://user-images.githubusercontent.com/10757813/72344874-a3f50f80-36d2-11ea-8bc3-44aea59c2a92.png)

**Comment by oskarkrawczyk** [comment]
@AMBudnik Will it work for you after switching to `HTTPS` instead of `HTTP`?

**Comment by AMBudnik** [comment]
nope @oskarkrawczyk works the same

**Comment by AMBudnik** [comment]
@oskarkrawczyk it forks well if I open the demo in incognito (Chrome). When I tried to open it in a new FF 72 window I also got the `404`. Well...I guess that might be one of the cache misteries so you can feel free to close this ticket. 

Thanks for the help!

**Comment by oskarkrawczyk** [comment]
I'll leave it open because there is something wrong with saving and forking when using a Non-SSL connection.

**Comment by AMBudnik** [comment]
An additional description

If you'd like to use a mouse button to open FORK in another tab you get the [missing menu bug](https://github.com/jsfiddle/jsfiddle-issues/issues/1385)

![GIF](https://user-images.githubusercontent.com/10757813/72714812-a393c300-3b6f-11ea-97b4-aa5aff0cf717.gif)

so basically there is no way to save the project...

**Comment by TorsteinHonsi** [comment]
For me it first hangs, with complaints about CORS in the console:

![Skjermbilde 2020-02-25 kl  10 55 43](https://user-images.githubusercontent.com/227836/75236193-ba0bea80-57bd-11ea-85ef-3cea3f1cb210.png)

Then, upon clicking Run again, the 404 appears.

**Comment by oskarkrawczyk** [comment]
Should be fixed. Please confirm it's working for you.

**Comment by AMBudnik** [comment]
I've made a couple attempts to fork and all succeeded - good job @oskarkrawczyk !

**Comment by oskarkrawczyk** [comment]
Perfect!

**Just a note:** In the coming months there's going to be a redirect put in for old fiddles that were saved over HTTP. We really want to move away from non-SSL connections.
