### ISSUE TITLE
Tidy button is missing.

### ISSUE THREAD

**Issue by mateuszkornecki** [jsfiddle/jsfiddle-issues#1523]
**Actual behavior**
The tidy button is no longer visible in the toolbar, after inspecting the page I found out that the button code has been commented, uncommenting it doesn't fix the problem (the button is visible again, but it is not working).

<img width="901" alt="Zrzut ekranu 2020-01-15 o 14 48 35" src="https://user-images.githubusercontent.com/50931078/72438897-239fde80-37a6-11ea-8297-7013c88debec.png">

**Comment by oskarkrawczyk** [comment]
<img width="940" alt="Screen Shot 2020-01-15 at 15 01 51" src="https://user-images.githubusercontent.com/34213/72439896-1a177600-37a8-11ea-8c36-0bea5dc54581.png">
