### ISSUE TITLE
Display a fiddle from POST response 500

### ISSUE THREAD

**Issue by katydecorah** [jsfiddle/jsfiddle-issues#1524]
* Documentation reference: https://docs.jsfiddle.net/api/display-a-fiddle-from-post#url-structure
* Reduced test case: https://jsfiddle.net/decorah/rjoz90vy/5/

The Edit in JSFiddle buttons we have on our production site are returning a 500 response page. I created a reduced test case https://jsfiddle.net/decorah/rjoz90vy/5/ that also returns a 500.

```html
<form action="https://jsfiddle.net/api/post/library/pure/" method="POST">
  <input type="hidden" name="html" value="hello world!" />
  <input type="submit">
</form>
```

**Comment by oskarkrawczyk** [comment]
Thanks for reporting. Fixing.

**Comment by oskarkrawczyk** [comment]
Fixed. Let me know if you confirm.

**Comment by katydecorah** [comment]
Works perfectly, thanks @oskarkrawczyk! We appreciate the speedy fix.
