### ISSUE TITLE
Tidying JS doesn't seem to work

### ISSUE THREAD

**Issue by turtlemaster19** [jsfiddle/jsfiddle-issues#1525]
This is not #1523, because I am aware it's no longer global, and not #1521 because I'm writing pure JavaScript, which would tidy just a few days ago. However, unlike the previous tidy button, it will no longer do anything to my JavaScript code. There aren't even errors thrown to the console. If it's necessary, I can provide the code in question.

**Comment by oskarkrawczyk** [comment]
> I can provide the code in question

That would be helpful. In form of a fiddle please.

**Comment by turtlemaster19** [comment]
https://jsfiddle.net/9p7Lcsaf/

**Comment by oskarkrawczyk** [comment]
> I assume they don't work either.

Wrongly. Only JS doesn't seem to work.

**Comment by turtlemaster19** [comment]
@oskarkrawczyk I didn't actually check that; I will delete that.

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by turtlemaster19** [comment]
@oskarkrawczyk Thank you! When should I expect this to go live on the web?
