### ISSUE TITLE
Unable to delete fiddles

### ISSUE THREAD

**Issue by gfdesign** [jsfiddle/jsfiddle-issues#1526]
Dear support
I have some fiddles I'd like to delete. However when I click on 'Delete fiddle', nothing happens. I've tried with Firefox and Chrome but I get same results.
Could you confirm this is so?
Best regards

**Comment by lharby** [comment]
Ditto. I also tried Safari. 
`Uncaught ReferenceError: confirmMessage is not defined`

**Comment by Matias110** [comment]
Hello, the same thing happens to me too and it doesn't let me eliminate two public violins that I have -.-

**Comment by oskarkrawczyk** [comment]
Will fix today.

**Comment by oskarkrawczyk** [comment]
Fixed. Thanks for the heads-up guys. Missed this error during some code refactoring.
