### ISSUE TITLE
scss min() max() not supported in used scss version

### ISSUE THREAD

**Issue by BananaAcid** [jsfiddle/jsfiddle-issues#1528]
css min() and ccs max() is supported by current scss - but it does not work in a fiddle - preview becomes a "502 Bad Gateway"

```
div {
  width: min(100vw, 100vh);
  height: min(100vw, 100vh);
}
```

https://jsfiddle.net/BananaAcid/qz03mfsw/

**Comment by oskarkrawczyk** [comment]
The actual error: `Incompatible units: 'vh' and 'vw'. on line undefined at column undefined`

The `libsass` we're using is the latest version.

**Comment by BananaAcid** [comment]
https://sass-lang.com/documentation/syntax/special-functions#min-and-max

It does not seem to get passed through, as it should - as sass says it supports it. Is the libsass not using the latest sass version?
