### ISSUE TITLE
console.log() not working

### ISSUE THREAD

**Issue by BananaAcid** [jsfiddle/jsfiddle-issues#1529]
console.log() does not output to chrome inspector.

https://jsfiddle.net/BananaAcid/vykruh7n/

**Comment by oskarkrawczyk** [comment]
Works fine as far as I can see.

<img width="651" alt="Screen Shot 2020-01-17 at 08 34 45" src="https://user-images.githubusercontent.com/34213/72593062-5233cb80-3904-11ea-95da-23a04a6e5ae7.png">

**Comment by AMBudnik** [comment]
@oskarkrawczyk sometimes we need to click <kbd>RUN</kbd> second time to get the log() but it's not a rule. I'll update you once I get any replicable scenario.

**Comment by oskarkrawczyk** [comment]
You NEED to have a fiddle running (saved or not) for the console to be able to work - it needs to communicate with the results iframe
