### ISSUE TITLE
If using GET to /echo you point people to http://doc.jsfiddle.net/use/echo.html

### ISSUE THREAD

**Issue by nonopolarity** [jsfiddle/jsfiddle-issues#1530]
but it doesn't exists... and changing doc to docs doesn't work either

**Comment by oskarkrawczyk** [comment]
Note to self: At the moment there's no way to update the `echo` app and fix this bug.

**Comment by jianlin** [comment]
(later on I found out the location should be https://docs.jsfiddle.net/async-requests )
