### ISSUE TITLE
Recently when I save or fork a JSFiddle, a lot of times it 404 in the result frame and failed

### ISSUE THREAD

**Issue by jianlin** [jsfiddle/jsfiddle-issues#1532]
The "progress bar" also moving from left to right slowly and can't succeed... so I have to start a new JSFiddle sometimes, but only to config using jQuery and run code on DOM Ready once again... and copy all the code and HTML and CSS over

**Comment by oskarkrawczyk** [comment]
Please provide a fiddle where this happens

**Comment by jianlin** [comment]
for example, right now I am trying http://jsfiddle.net/y8w1o75h/1/ and refreshed the page and clicked the Fork button. The progress bar slowly moved to the right and the result page showed a 404
That page doesn't exist.

**Comment by oskarkrawczyk** [comment]
Please use SSL (`https`)

**Comment by jianlin** [comment]
> Please use SSL (`https`)

Maybe it was due to the URL suggestion from Google Chrome, that when I typed jsfiddle, it suggested the non-https site.  Since many users might have this suggested to them as well, could you redirect the users to https version if they went to the http version?
