### ISSUE TITLE
Sometimes the Save or Fork buttons are missing

### ISSUE THREAD

**Issue by jianlin** [jsfiddle/jsfiddle-issues#1533]
it seems like the ad at the bottom left of the page pushed the buttons up. So there can be JS and HTML and CSS and there is no way to save it.

**Comment by oskarkrawczyk** [comment]
Can you confirm this is 100% the case? Or is it just an assumption?

**Comment by jianlin** [comment]
It is missing sometimes.
Whether it is due to the ad is not entirely sure. But definitely the buttons are missing.

**Comment by oskarkrawczyk** [comment]
Merged into #1535
