### ISSUE TITLE
Add jQuery 3.4.1

### ISSUE THREAD

**Issue by mgol** [jsfiddle/jsfiddle-issues#1534]
jQuery 3.4.0 was released on April, 2019, version 3.4.1 on May, 2019. They're not available in the jQuery version picker yet, though. Can you add 3.4.1 there?

**Comment by oskarkrawczyk** [comment]
Added

**Comment by mgol** [comment]
Hmm, I still don't see it. Also, jQuery Slim versions are missing even more entries (3.2.1, 3.3.1 & 3.4.1 are all missing from there as well). See the screenshot:
<img width="224" alt="Screen Shot 2020-01-22 at 13 24 55" src="https://user-images.githubusercontent.com/1758366/72893989-a41c8d00-3d1a-11ea-93c6-665a85328d2b.png">

**Comment by oskarkrawczyk** [comment]
3.4.1 should be there now

**Comment by mgol** [comment]
Thank you!
