### ISSUE TITLE
No option to turn off vendor prefixes.

### ISSUE THREAD

**Issue by CurleyWebDev** [jsfiddle/jsfiddle-issues#1536]
It would be great if vendor prefixes were optional.

for example, typing "an-f-m", and clicking tab would execute:
_animation-fill-mode: both;_

**instead of:**

_-webkit-animation-fill-mode: both;
  -moz-animation-fill-mode: both;
  -o-animation-fill-mode: both;
  animation-fill-mode: both;_

**Comment by oskarkrawczyk** [comment]
Super edge-case. I'll be honest, there are no plans on providing an option to turn off vendor prefixes.

Might as well just type in `animation-fill-mode`.

**Comment by CurleyWebDev** [comment]
That's exactly what I do now for all properties that include prefixes.
Thanks for your response! 👍
