### ISSUE TITLE
Feature to switch layout and checkbox to select multiple fiddle and delete

### ISSUE THREAD

**Issue by sameerthekhans** [jsfiddle/jsfiddle-issues#1538]
This is a Ideas/Requests

Please add below features to [Your Fiddles page](https://jsfiddle.net/user/fiddles), would be very helpful to every one

1. Switching between layouts - grid to list (only title and description will display in list view layout)

2. Checkbox to select multiple fiddles and delete multiple selected fiddles (This [issue](https://github.com/jsfiddle/jsfiddle-issues/issues/1455) has been raised already)

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
