### ISSUE TITLE
i saved a fiddle, but it won't load

### ISSUE THREAD

**Issue by lonelychicken** [jsfiddle/jsfiddle-issues#1539]
I worked on a fiddle for a good 30 minutes and saved it. Later, on a different PC, I opened up the same fiddle and none of the work I had done loaded (despite me saving it). On top of that, while I was working on the project before, I changed some of the settings around. However, these stayed in effect on my other PC, unlike the fiddle. Am I not saving it right, or do I need to Set as Base before switching computers?

**Comment by oskarkrawczyk** [comment]
Sounds like you're simply not accessing the latest fiddle version you were previously working on.

Here's an explanation of how **Save as base** works: https://docs.jsfiddle.net/getting-started#setting-fiddle-as-base-version

To access your latest version click the yellow link in the fiddle listing:

<img width="639" alt="Screen Shot 2020-01-25 at 08 20 38" src="https://user-images.githubusercontent.com/34213/73117826-9dc12780-3f4b-11ea-85c6-c0112c497119.png">

**Comment by lonelychicken** [comment]
thanks! this fixed everything.
