### ISSUE TITLE
Jsfiddle won't allow me to create private fiddles

### ISSUE THREAD

**Issue by ApoloSiskos** [jsfiddle/jsfiddle-issues#1540]
As a start, I saw that my untitled fiddles (which used to be private if they had no tittle) are now public. I tried creating a private fiddle but it appears in my public section. 

Is that a bug? Shouldn't also all the old private (according to the old set up where private fiddles were the untitled ones) automatically go in the Private section?

**Comment by oskarkrawczyk** [comment]
Duplicate https://github.com/jsfiddle/jsfiddle-issues/issues/1519#issuecomment-573440191
