### ISSUE TITLE
Responsive CSS Grid Boilerplate returns a 500 error

### ISSUE THREAD

**Issue by co-avitaldrucker** [jsfiddle/jsfiddle-issues#1542]
Broken link in question: https://jsfiddle.net/boilerplate/responsive-css-grid

Link is accessed in the boilerplate bar on the main fiddle page: https://jsfiddle.net/

**Comment by oskarkrawczyk** [comment]
Thanks, will have a look.

**Comment by Siscrad** [comment]
https://jsfiddle.net/boilerplate/postcss
This link is also broken.
