### ISSUE TITLE
Fiddles are showing the first version, but clicking "Latest Version" Actually shows the current code

### ISSUE THREAD

**Issue by skylerspark** [jsfiddle/jsfiddle-issues#1546]
![Capture](https://user-images.githubusercontent.com/44554976/75290835-176c5f80-57ef-11ea-9c80-ba015d75699a.PNG)

When opening my fiddle home page, I can see one of my fiddles, the current one Im working on,

It shows a typescript boiler plate. The first version.

If you go into it by just going into the pen, it shows the first version: [https://jsfiddle.net/SirCode/gp5sqn6w/](https://jsfiddle.net/SirCode/gp5sqn6w/)

However, if you go into the pen via "latest version" you'd see, I'm not working on typescript at all anymore, its a completely different name and pen, but the current version is STUCK on the first version.
See version 152, current as of posting this, same link, different code.
[https://jsfiddle.net/SirCode/gp5sqn6w/152/](https://jsfiddle.net/SirCode/gp5sqn6w/152/)

This means if I want to get any work done, I have to click the little "latest" version link in the fiddle list.

**I tried copying all my code from the current version (152) into the base fiddle, changed name, and then saved it again, but it just saved it as 153. Meaning it does nothing, and once I go back to the fiddle list, it still shows my old version.**

![Capture](https://user-images.githubusercontent.com/44554976/75291229-d1fc6200-57ef-11ea-919f-0105395f3330.PNG)

This is a very aggravating glitch/bug/error or something of the sort, Im not even sure whats causing it.

**Comment by oskarkrawczyk** [comment]
It's not stuck, you're simply not saving the fiddle as base version.

Here's an explanation of how **Save as base** works: https://docs.jsfiddle.net/getting-started#setting-fiddle-as-base-version

**Comment by skylerspark** [comment]
@oskarkrawczyk Why is version control set like this... isnt that a bit useless/irrelevant to development... and just makes things harder.

**Comment by oskarkrawczyk** [comment]
Fiddles need to be set as base versions so no unifinished/buggy/incomplete fiddles end up in the listing. It's on the user to decide when a fiddle is completed and is displayed for others (if fiddle is public).
