### ISSUE TITLE
Collaboration not working anymore

### ISSUE THREAD

**Issue by darkeye2** [jsfiddle/jsfiddle-issues#1547]
Since yesterday (maybe longer, just noticed it on yesterday), the collaboration feature did not work anymore.
The message in console is:
"Unable to connect to wss://hub.togetherjs.com/hub/Tni5zEThSd"
WebSocket error: undefined channels.js:193:15
    onerror https://togetherjs.com/togetherjs/channels.js?bust=1582806766572:193
    bind https://jsfiddle.net/js/_dist-editor.js?22896e263556c0998cc87ebb32a6709da34a9115:1
WebSocket close unclean code: 1006 reason: none

**Comment by oskarkrawczyk** [comment]
Looks like the TogetherJS hub server is down for maintenance at the moment: http://hub.togetherjs.com/

**Comment by zalun** [comment]
As far as I can tell Mozilla is preparing to shut down the project.
We should take over if we want to use it.

**Comment by darkeye2** [comment]
Oh, sorry, didnt saw it. 
Thanks for info

**Comment by oskarkrawczyk** [comment]
@zalun I'm currently looking into how to setup the server on our end. Any chance you could confirm with someone from the ex-TogetherJS team that they're shutting down?

**Comment by zalun** [comment]
Ian Bicking would be the guy to talk to.
I believe it is just unmaintained. Which means it might be shut down if in trouble.

**Comment by oskarkrawczyk** [comment]
@zalun Gotcha. Tried contacting Ian many times prior, with no response unfortunately.

**Comment by oskarkrawczyk** [comment]
**It does look like Mozilla has shut down the project along with the Hub server for [TogetherJS](https://github.com/mozilla/togetherjs)**

I'll be trying to spawn a server for the hub hosted on our end in the next couple of days.

Until then the Collaboration feature will not work.

**Comment by oskarkrawczyk** [comment]
Temporary hub server is now up, Collab should work again.
