### ISSUE TITLE
Improve resource input data visibility

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1548]
Hey @oskarkrawczyk 

I find it pretty difficult to check if the resource has been added correctly as the bg color and the font color of the `resources` are way too similar.

![Zrzut ekranu 2020-02-28 o 10 20 40](https://user-images.githubusercontent.com/10757813/75530273-02bce100-5a14-11ea-9840-d9705213f6a9.png)

**Chrome 80 / Mac Catalina**
![Zrzut ekranu 2020-02-28 o 10 12 10](https://user-images.githubusercontent.com/10757813/75528026-5d097200-5a13-11ea-9dfd-8214a8b7fddd.png)

**Firefox 73 / Mac Catalina**
![Zrzut ekranu 2020-02-28 o 10 12 54](https://user-images.githubusercontent.com/10757813/75528132-6561ad00-5a13-11ea-8723-e9e5fe9a0ccf.png)

**Comment by oskarkrawczyk** [comment]
Regression after adding Groups styling.

**Comment by AMBudnik** [comment]
Thanks for fixing :)
