### ISSUE TITLE
Cannot Reset Password

### ISSUE THREAD

**Issue by MartinErskine** [jsfiddle/jsfiddle-issues#1550]
I exist as a user/email but when requesting a password reset I get a 500 Server error?

**Comment by VanquishedWombat** [comment]
> I exist as a user/email but when requesting a password reset I get a 500 Server error?

Me too. Same issue last weekend, left it a while, need to log in now but password not working and I get a 500 error when I submit my reset password.  To be clear, the requesting of the reset link works - its the submission of the new password step that crashes.

**Comment by oskarkrawczyk** [comment]
Note to self:

- `https://jsfiddle.net/user/reset_password/` after submit throws 500, but the reset email arrives
- `https://jsfiddle.net/user/change_password/confirm` form displays, but 500 after submitting form
