### ISSUE TITLE
Enhancement: Include AlpineJs in the list of "FRAMEWORKS & EXTENSIONS" in jsFiddle

### ISSUE THREAD

**Issue by ahmed-musallam** [jsfiddle/jsfiddle-issues#1553]
Please add AlpineJS to the list of default  "FRAMEWORKS & EXTENSIONS" in the fiddle editor: 

https://github.com/alpinejs/alpine

Thank you!

**Comment by oskarkrawczyk** [comment]
Added

**Comment by ahmed-musallam** [comment]
@oskarkrawczyk Thank you!!
I don't see it in the list on https://jsfiddle.net/
Is there a timeline for that?

**Comment by ahmed-musallam** [comment]
I see it now! Thank you!!
