### ISSUE TITLE
login loses current fiddle

### ISSUE THREAD

**Issue by tcurdt** [jsfiddle/jsfiddle-issues#1555]
I created a fiddle - but I wasn't logged in yet.
To save it I logged in and by that lost all I just created.
Not great.

**Comment by oskarkrawczyk** [comment]
If you log in, in a new tab and hit save in the previous tab, it'll save the fiddle under your profile.

I assume you left the editor without saving hence losing core - at least that's what I figured by the vague description of the "issue"

**Comment by tcurdt** [comment]
It's quite easy to reproduce. Enter some html. Then press sign-in. After the sign in the html is gone.
