### ISSUE TITLE
Using * in allow="microphone *; camera *" is unsafe & unnecessary

### ISSUE THREAD

**Issue by jan-ivar** [jsfiddle/jsfiddle-issues#1557]
JSFiddle is using of `*` in its iframe allow list, which is [unsafe](https://github.com/w3c/webappsec-feature-policy/issues/348):
```js
allow="midi *; geolocation *; microphone *; camera *; encrypted-media *;"
```
In short, it allows fiddles to permission-escalate a user's trust in JSFiddle to the rest of the web, e.g. using `window.location`.

It fools browsers (other than Firefox) into presenting camera + microphone permission prompts as if the request is from JSFiddle, when in reality the request comes from another (potentially malicious) site. In Chrome where trust is persisted, a site may gain immediate access to the user's camera and microphone this way.

In Firefox `*` causes a prompt every time and withholds the `☑ Remember this decision` option.

Example: https://jsfiddle.net/jib1/79xo3gcp/

Fortunately, there's rarely a need to use `*`. Please use [`'src'`](https://w3c.github.io/webappsec-feature-policy/#iframe-allow-attribute) instead:
```js
allow="midi 'src'; geolocation 'src'; microphone 'src'; camera 'src'; encrypted-media 'src';"
```
A fiddle may still delegate permission by opening its own sub-iframe with an allow list, but at least that makes it auditable.

**Comment by oskarkrawczyk** [comment]
@jan-ivar Thanks for educating me on this - switched to `'src'` instead of `*`!

**Comment by jan-ivar** [comment]
@oskarkrawczyk Thanks for the quick response! Works great in Firefox and Chrome!

Unfortunately, it looks like this broke Safari which apparently doesn't support the `'src'` and related keywords in the allow list yet. See https://bugs.webkit.org/show_bug.cgi?id=189901

FYI.

**Comment by jan-ivar** [comment]
I _believe_ `'src'` is the default and that
```
allow="microphone; camera"
```
is the same as 
```
allow="microphone 'src'; camera 'src'"
```
but I'm not 100% sure if this is true in all browsers.

**Comment by jan-ivar** [comment]
@clelland ^

**Comment by clelland** [comment]
Yes, `src` should be the same as just naming the feature, so `allow="microphone; camera"` should be sufficient. (And should also work in Safari, AFAIK)

**Comment by jan-ivar** [comment]
Hi @oskarkrawczyk did this get reverted?

I'm seeing `*` again e.g. in https://jsfiddle.net/jib1/zcuwfpnh/ I just created.
```js
allow="midi *; geolocation *; microphone *; camera *; display-capture *; encrypted-media *"
```

Is there a reason not to use the following (which should work in Safari as well)?
```js
allow="midi; geolocation; microphone; camera; display-capture; encrypted-media"
```
