### ISSUE TITLE
getDisplayMedia does not work

### ISSUE THREAD

**Issue by jan-ivar** [jsfiddle/jsfiddle-issues#1558]
Screen capture using `getDisplayMedia` does not work: https://jsfiddle.net/jib1/q75yb8pf/

In contrast, this works: https://fiddle.jshell.net/jib1/q75yb8pf/show/

The former needs [`display-capture`](https://w3c.github.io/mediacapture-screen-share/#feature-policy-integration-0) in the iframe allow list:
```js
allow="midi 'src'; geolocation 'src'; microphone 'src'; camera 'src'; display-capture 'src'; encrypted-media 'src';"
```

Note also https://github.com/jsfiddle/jsfiddle-issues/issues/1557

**Comment by oskarkrawczyk** [comment]
Added
