### ISSUE TITLE
All editor tabs are gone

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1559]
Hey @oskarkrawczyk 

Today I logged in and saw this

![Zrzut ekranu 2020-03-25 o 08 27 35](https://user-images.githubusercontent.com/10757813/77512142-b332cf00-6e72-11ea-835e-1986e2dca476.png)

All the tabs are gone and there's an issue in the console.

![Zrzut ekranu 2020-03-25 o 08 30 10](https://user-images.githubusercontent.com/10757813/77512219-dbbac900-6e72-11ea-9277-b2aa4c0b0515.png)

### Additional info
- I get this message on all demos, new and saved
- testing environment OS Catalina, Chrome 83

**Comment by oskarkrawczyk** [comment]
Can you reload your cache and try again?

**Comment by AMBudnik** [comment]
Sorry, there's no difference. I've cleared the cache, tried it in an incognito mode, and with Firefox (that I barely use).

![fiddle](https://user-images.githubusercontent.com/10757813/77513623-a2378d00-6e75-11ea-8e3d-f4f9902cbb61.gif)

**Comment by oskarkrawczyk** [comment]
Hmm, really weird, can't replicate the behavior.

Can you tell me if there are any `draft[]` items in your sessionStorage in devtools?

**Comment by oskarkrawczyk** [comment]
Does switching to any other layout changes things?

**Comment by AMBudnik** [comment]
> Does switching to any other layout changes things?

That's it! Once I change the layout system it works again.

**Comment by oskarkrawczyk** [comment]
Ok, will have to investigate anyway, that error shouldn't have happened.

**Comment by AMBudnik** [comment]
Thanks. I've shared a demo with my colleague and he also got the missing tab issue, so I guess that some people may think that the demo is broken. 

Now when I've switched the layout (and then switched back to classic) all the demos are working fine, so it has to be client-based.

**Comment by ar2oor** [comment]
Same here
![image](https://user-images.githubusercontent.com/1141686/77516447-bc279e80-6e7a-11ea-9f31-34b234493ef6.png)

**Comment by oskarkrawczyk** [comment]
Hard to debug.

@ar2oor in `Local Storage` in devtools there's a `editor-grid-mode` key, can you tell me what's the value for you?

**Comment by oskarkrawczyk** [comment]
Nevermind. I see where the issue is. Deploying fix.

**Comment by oskarkrawczyk** [comment]
Thanks @AMBudnik for reporting this in!
