### ISSUE TITLE
Set as base not working

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#1560]
JavaScript error when clicking "Set as base":

![Skjermbilde 2020-03-25 kl  09 33 07](https://user-images.githubusercontent.com/227836/77517039-b2526b00-6e7b-11ea-83ea-98bc005622d7.png)

Tried Chrome and Firefox. Tried flushing cache, all in vain.

**Comment by AMBudnik** [comment]
I get the same error once I click <kbd>RUN</kbd>

**Comment by oskarkrawczyk** [comment]
Fixed. Thanks for the heads up.

**Comment by TorsteinHonsi** [comment]
Thanks for the quick reaction!
