### ISSUE TITLE
GitHub hosted demos fail

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#1561]
Live demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-basic/

It happens since today. GitHub responds with 403. As far as I know, nothing has changed in our end.

**Comment by oskarkrawczyk** [comment]
Refactoring regression. Will fix ASAP

**Comment by TorsteinHonsi** [comment]
It's still failing: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-allowpointselect-line/

**Comment by oskarkrawczyk** [comment]
@emq can you double check please? 🙏

**Comment by AMBudnik** [comment]
![Zrzut ekranu 2020-03-26 o 11 16 53](https://user-images.githubusercontent.com/10757813/77635738-50653480-6f53-11ea-9087-3534d7b06808.png)

works well on my Chrome 83

ps. @TorsteinHonsi HighCharts are awesome. Glad that our libraries work well together https://jsfiddle.net/cgv7dqeh/.

**Comment by emq** [comment]
We hit a rate limit problem; @oskarkrawczyk plz check your email; should be resolved shortly, will keep you posted; sorry for the troubles!

**Comment by emq** [comment]
Alright - again sorry for the troubles; there was a mixup regarding types of github credentials, that caused 403 on production as invalid credentials were silently dropped by GH. Should be resolved now, thank you again for letting us know @TorsteinHonsi ! ❤️  and feel free to ping me directly in case of problems today (tho I hope there will be no need 😅  )
