### ISSUE TITLE
Save button fails

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#1562]
Fails with JS error. Tried Chrome, Firefox, flushed cache, to no avail.

![Skjermbilde 2020-03-25 kl  13 53 57](https://user-images.githubusercontent.com/227836/77538536-31f23100-6ea0-11ea-88c4-833a2d49b11b.png)

**Comment by AMBudnik** [comment]
It works well if I use the JS editor only
https://jsfiddle.net/Lht5vmo1/
But once I want to any anything in the HTML or CSS sections I get the error.

**Comment by oskarkrawczyk** [comment]
Should be fixed.
