### ISSUE TITLE
Unable to use "Light" mode 

### ISSUE THREAD

**Issue by carolinatree** [jsfiddle/jsfiddle-issues#1563]
‼️‼️‼️

Known issues (see README.md) will not be 
addressed and most likely will be closed.

‼️‼️‼️

Visual problems mean dark mode is not accessible.  How do I turn on Light mode? I do not see the option in the menu and it seems it's been "retired"?

Thanks.

**Comment by oskarkrawczyk** [comment]
Yes, it's retired.

**Comment by Enchiridion** [comment]
That's unfortunate, dark mode is unusable for me.

**Comment by MikeWilliams-UK** [comment]
Dark mode is rubbish.

Why are you NOT giving people the choice?

**Comment by MikeWilliams-UK** [comment]
It's a shame to ruin such a good tool by changing such a fundamental thing.

**Comment by wout** [comment]
So 30% of the users want a light theme, and that's not a large enough percentage?

I used to love JSFiddle but I'm not going to use it without a light theme.

**Comment by MikeWilliams-UK** [comment]
The decision to scrap light mode surely goes against all accessibility requirements...

Please re instate it.

**Comment by MikeWilliams-UK** [comment]
The question "Should we bring back the Light Theme – would you use it?" Should have been phrased as TWO questions as the response is ambiguous.

**Comment by stevematdavies** [comment]
Not having a light theme is not about a "nice to have features" its about accessibility and its a very poor move to remove the option. There are many who have issues seeing in dark mode. I hate to think now its time to switch to an alternative. This was a very bad decision.
