### ISSUE TITLE
Fiddles from GitHub does not auto-run

### ISSUE THREAD

**Issue by goransle** [jsfiddle/jsfiddle-issues#1564]
For example: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-basic

**Comment by AMBudnik** [comment]
Confimed on OS Catalina, Chrome 83 👍

**Comment by nischalbc** [comment]
https://jsfiddle.net/gh/get/jquery/3.0/zalun/jsFiddleGithubDemo/tree/master/Demo/ Looks like none of the jsfiddle github integrated code works.

**Comment by oskarkrawczyk** [comment]
Fixed
