### ISSUE TITLE
Would use jsfiddle as code snippet repo if could list by title and search

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#1565]
I just wanted to pass this on as a suggestion.

Saw [this post](https://dev.to/srebalaji/ask-dev-how-are-you-managing-your-code-snippets-1k9e) asking people how they manage code snippets.

I often want to find code I wrote in jsfiddle but my only option is to page through 50 to 200 fiddles.

I realize it's been decided that [search is a no-go](https://github.com/jsfiddle/jsfiddle-issues/issues/684). Just adding that maybe there's a fit. I like the idea of live working code snippets vs just code. That doesn't seem to exist ATM. Maybe jsfiddle could be that.

**Comment by oskarkrawczyk** [comment]
Searching through personal fiddles is now a part of the next development phase.

So yeah, it's going to happen for personal fiddles.

<img width="603" alt="Screen Shot 2020-04-08 at 19 14 50" src="https://user-images.githubusercontent.com/34213/78813487-5fc19480-79cd-11ea-9225-5f5b31ec1160.png">

**Comment by timberzen** [comment]
It would be nice to search thu all the fiddles that are not private when trying to search for a solution like you might do on StackOverflow as score successful hits to your query.

**Comment by oskarkrawczyk** [comment]
Searching for personal fiddles has been deployed.

![Kapture 2020-05-27 at 20 22 28](https://user-images.githubusercontent.com/34213/83057920-de46c400-a057-11ea-8e3c-4fde8a53a402.gif)
