### ISSUE TITLE
add Jasmine 

### ISSUE THREAD

**Issue by timberzen** [jsfiddle/jsfiddle-issues#1566]
https://github.com/firebase/snippets-web/blob/cee9068490fbfb03c123fbda87bc08a73a122520/firestore/test.solution-counters.js
Hi 
Im using Google Firebase/FireStore , and they have a load of sample code on github but it would have been nicer to have pasted it into fiddler and see it run. In the UI it would have been nice to see it run to success.  The only alternative I can see is http://dojo.telerik.com/AZoXU
Maybe I am missing something. 
Equally how do I add additional frameworks above JQuery eg Framework7.io ?
What I would like to do is save a 'Starting Point'  eg in the dojo example it has all the lastest CDN includes (but assumes I an using kendo which is usual).
I would be a subscriber is I had my own scrapbook of starting points and 'good bits' as I would want a scrapbook for each project, explaining UI elements and behaviours.
Also you need a WiKi to start off as  Documentation

Thanks
Doug

**Comment by oskarkrawczyk** [comment]
> Im using Google Firebase/FireStore , and they have a load of sample code on github but it would have been nicer to have pasted it into fiddler and see it run

If it's possible to run Firebase on the frontend you can add it via the **Resources** tab in the sidebar or just plain `<script src="...">` in the JS panel.

> Equally how do I add additional frameworks above JQuery eg Framework7.io ?

You don't. The JSFiddle team has the ability to add new Frameworks.

> What I would like to do is save a 'Starting Point' eg in the dojo example it has all the lastest CDN includes (but assumes I an using kendo which is usual).

I assume you're talking about creating a template fiddle - we don't have that feature but it's on the roadmap, granted it doesn't have a lot of votes so it's not a priority.

> Also you need a WiKi to start off as Documentation

Already linked the docs in #1567
