### ISSUE TITLE
add to  WiKi

### ISSUE THREAD

**Issue by timberzen** [jsfiddle/jsfiddle-issues#1567]
Also you need a WiKi to start off as  Documentation as it looks pretty empty at the moment.
Even if you just added and Outline and users could add to it, esp screen shots .
You could have a word doc that you could fill in with heading outlines that you bookmark what you have not got round to, with luck others that have solved that problem could paste content for you to add to the wiki docs. Make use of all the people that can offer a little bit of their time to help you.

**Comment by oskarkrawczyk** [comment]
https://docs.jsfiddle.net

**Comment by emq** [comment]
I took the liberty to update wiki with a link to official docs for sake of clarity ☝️

**Comment by computamike** [comment]
so if I spot a problem with the documentation - what is the process for raising that as an issue - I'm thinking here that the gitHub integration examples could use some additional notes around supported branch names etc.
