### ISSUE TITLE
Feature Request: Add keyboard shortcut for switching to HTML, CSS, and JS tabs to make it easier to navigate tabs

### ISSUE THREAD

**Issue by shreyasm-dev** [jsfiddle/jsfiddle-issues#1568]

**Comment by oskarkrawczyk** [comment]
What shortcuts would you suggest? Something that would be intuitive and simple enough for users of all common OSs - macOS, Windows.

**Comment by shreyasm-dev** [comment]
Maybe an HTML accesskey? It varies by browser though, so that would be a problem.

**Comment by oskarkrawczyk** [comment]
It would. I have no good cross-browser idea on a discoverable shortcut.

Putting this as a feature request on the roadmap.
