### ISSUE TITLE
Adding "<script></script>" in JS tab (even in comments) causes any following code to be displayed as HTML

### ISSUE THREAD

**Issue by shreyasm-dev** [jsfiddle/jsfiddle-issues#1569]
Example: https://jsfiddle.net/8850s/ru3p56n0/embedded/js,html,css,result/dark/
`&lt;` can be used, but using it is not very readable.

**Comment by oskarkrawczyk** [comment]
I don't have a solution to this issue. Easy enough to do a `"<script><"+"/script>"`. Closing.
