### ISSUE TITLE
re-add XTK

### ISSUE THREAD

**Issue by haehn** [jsfiddle/jsfiddle-issues#1570]
Hello!

Somehow the XTK library was removed and now all our tutorial links are broken. For example: http://jsfiddle.net/gh/get/toolkit/edge/xtk/lessons/tree/master/00/#run

Could you please add `https://get.goXTK.com/xtk_edge.js` again? And maybe this time call it XTK instead of the X Toolkit?

Thank you!

**Comment by oskarkrawczyk** [comment]
@haehn Did you even check before adding the three comments in the old ticket and posting a new about the same thing?

<img width="344" alt="Screen Shot 2020-04-13 at 21 37 47" src="https://user-images.githubusercontent.com/34213/79153984-16a78100-7dcf-11ea-9836-9c3715864beb.png">

Does it look like it's removed?

>  For example: http://jsfiddle.net/gh/get/toolkit/edge/xtk/lessons/tree/master/00/#run

Is it called "toolkit" or "xtk"? You literally requested for the name change, yet you use "toolkit" in the URL expecting it to work.

Please double check your mistakes before flooding with comments, and requests.

**Comment by haehn** [comment]
Hi @oskarkrawczyk Thanks - Great that it works! Keep up the good work and have a wonderful day!
