### ISSUE TITLE
Angular 9 boilerplate / template

### ISSUE THREAD

**Issue by kmturley** [jsfiddle/jsfiddle-issues#1573]
In the section 'Start with a boilerplate' there is a list of applications:
![Screen Shot 2020-04-26 at 12 51 49 PM](https://user-images.githubusercontent.com/1710493/80318134-c9f37b00-87bc-11ea-8f57-034bfdfb2e36.png)

If I select TypeScript, and then go to JS frameworks:
![Screen Shot 2020-04-26 at 12 52 49 PM](https://user-images.githubusercontent.com/1710493/80318158-e2fc2c00-87bc-11ea-9c24-099cd638a8ae.png)

I can only see old versions of Angular. Although I understand Angular expects components in multiple files and not ideal for a single example fiddle, there are many use-cases for running a simple Angular component demo, or directive. It's possible to combine Angular modules into a single TypeScript file to run an app.

Can you support running Angular 9.x as an official boilerplate/template? It seems possible to run by including the following dependencies:

https://unpkg.com/core-js@2.4.1/client/shim.min.js
https://unpkg.com/zone.js@0.10.3/dist/zone.min.js
https://unpkg.com/rxjs@6.5.4/bundles/rxjs.umd.min.js
https://unpkg.com/@angular/core@9.1.0/bundles/core.umd.js
https://unpkg.com/@angular/common@9.1.0/bundles/common.umd.js
https://unpkg.com/@angular/compiler@9.1.0/bundles/compiler.umd.js
https://unpkg.com/@angular/platform-browser@9.1.0/bundles/platform-browser.umd.js
https://unpkg.com/@angular/platform-browser-dynamic@9.1.0/bundles/platform-browser-dynamic.umd.js

Then using the html:
`<my-app></my-app>`

And TypeScript:
```
let { Component, NgModule, VERSION } = ng.core;

@Component({
  selector: 'my-app',
  template: `
  	<h1>Hello, {{ name }}</h1>
        <button (click)="increment()">Click {{ counter }}</button>
  `,
})
class HomeComponent {
    counter = 0;
    name = 'Angular ' + VERSION.full;
    increment() {
    	this.counter++;
    }
}

const { BrowserModule } = ng.platformBrowser;

@NgModule({
  imports:      [ BrowserModule ],
  declarations: [ HomeComponent ],
  bootstrap:    [ HomeComponent ]
})
class AppModule { }

const { platformBrowserDynamic } = ng.platformBrowserDynamic;
platformBrowserDynamic().bootstrapModule(AppModule);
```

See working version here:
https://jsfiddle.net/kmturley/gde3rvq4/

**Comment by oskarkrawczyk** [comment]
That Angular example doesn't seem to work, getting two errors:

```
[Error] TypeError: undefined is not an object (evaluating 'platformBrowser.ɵINTERNAL_BROWSER_PLATFORM_PROVIDERS')
	(anonymous function) (platform-browser-dynamic.umd.js:577)
	(anonymous function) (platform-browser-dynamic.umd.js:10)
	Global Code (platform-browser-dynamic.umd.js:11)
[Error] TypeError: Right side of assignment cannot be destructured
	anonymous (Anonymous Script 1 (line 27))
	exec (typescript.js:41:19869)
	runScripts (typescript.js:41:20386)
```

If you can provide a working example for a boilerplate I'll add it.

**Comment by kmturley** [comment]
@oskarkrawczyk hmm strange, I don't get that error myself. I've just tested in Chrome, Firefox and Safari. Which browser are you using?

**Comment by nawlbergs** [comment]
worked for me.. question i need answered.. is how do you get a router in there?
`const { RouterModule, Route } ng.router;`.. something like this???

**Comment by nawlbergs** [comment]
actually it worked after adding `https://unpkg.com/@angular/router@9.1.0/bundles/router.umd.js`
but i oddly got stumped when trying to create and inject a service into the `HomeComponent`
https://jsfiddle.net/nalberg/8yc2tbaq/71/
