### ISSUE TITLE
Trouble with Collaboration

### ISSUE THREAD

**Issue by toddgower-hiatus** [jsfiddle/jsfiddle-issues#1574]
I've seen other threads that indicate trouble with the collaboration feature but they all seem to be a bit dated...

 I'm having trouble getting collaboration to work in Chrome. I send the collaborate url to someone who then opens it up but they are not able to see my changes and and not present in the chat widget. What's the current status of collaborate?

**Comment by darkeye2** [comment]
Collaboration is working for me.
Is the link you are sending correct? (with togetherjs attribute)
have the athers tried to open a private session in browser (to avoid cookies, cached data)?

**Comment by toddgower-hiatus** [comment]
I was using the togetherjs url but still had trouble. Eventually gave up. codesandbox.io seems to be much more suited for what I was looking to do in the end.
