### ISSUE TITLE
Cannot Scroll Down On IPAD in Safari

### ISSUE THREAD

**Issue by rootbeer23** [jsfiddle/jsfiddle-issues#1576]
Bug: Safari Browser on IPAD wants to scroll outside of the IFRAME tag
Request: add the css to the frame
Due to the lack of -webkit-overflow-scrolling:touch css on the iframe tag of the /show frame,
An IPAD running the safari browser cannot scroll down fiddles. This issue is only on ipads.

**Comment by oskarkrawczyk** [comment]
I'm not sure I understand, can you provide a screen recording?

**Comment by rootbeer23** [comment]
I believe I got it to work. NVM.
