### ISSUE TITLE
Error 500: when we visit https://jsfiddle.net/api/post/library/pure/

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1579]
### Description

Hey @oskarkrawczyk Our product documentation is made based on your API (POST request). In the end when someone clicks edit we generate a new example on the https://jsfiddle.net/api/post/library/pure/ address. Today it shows `error 500.`

### Demo

example https://handsontable.com/docs/7.4.2/demo-scrolling.html

### Environment

Chrome 80,  
macOs Catalina

**Comment by oskarkrawczyk** [comment]
Thanks for the heads-up! 

Reverted some code (clearly needs further testing). Should work fine again.

**Comment by AMBudnik** [comment]
Thank you :) works fine now
