### ISSUE TITLE
console.error handling is eating errors

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#1583]
I have code like this

```
console.error('I need to see this error in the JavaScript console');

const obj = {};
const a = obj.a.b;
```

https://jsfiddle.net/greggman/1br5okt9/

The error never appears in the JavaScript console. In my actual code that error would have told me why the property is missing.

**Comment by oskarkrawczyk** [comment]
Custom console is in beta, please turn it off if it misbehaves.

**Comment by oskarkrawczyk** [comment]
I can also see `console.error` is in fact being displayed in the custom console, so everything works as expected.

Closing.

<img width="718" alt="Screen Shot 2020-05-09 at 09 10 23" src="https://user-images.githubusercontent.com/34213/81466863-09ff2880-91d5-11ea-839e-050bd1e546c0.png">
