### ISSUE TITLE
Error JSFIDDLE_editor_options

### ISSUE THREAD

**Issue by sebastianbochan** [jsfiddle/jsfiddle-issues#1584]
Error in the console does not allow you to use save / fork buttons which are invisible. Loader is in infinity loop.

<img width="1235" alt="Zrzut ekranu 2020-05-12 o 09 55 31" src="https://user-images.githubusercontent.com/2115686/81655992-f2bf7580-9436-11ea-885c-eb713436305c.png">

MacOSX: 10.14.5
Chrome:  81.0.4044.138

ps. all plugins/extensions are disabled in the chrome.

**Comment by oskarkrawczyk** [comment]
For some reason your browsers has limited quota for local storage, meaning that the little amount for saving editor preferences or unsaved draft is not available for JSFiddle. You either have limited your quota for websites or disabled local storage so we can't save anything to it.

Go to `Application` tab, select JSFiddle and remove all items from local storage and session storage.

**Comment by sebastianbochan** [comment]
Solved the probelm, big thanks!
