### ISSUE TITLE
Custom console console.log shows only first param in beta console 

### ISSUE THREAD

**Issue by lehtu** [jsfiddle/jsfiddle-issues#1586]
In beta console `console.log` will print only first parameter.
`console.log(1, 2, 3, "yay")` => 1

it should work like this:
`console.log(1, 2, 3, "yay")` => 1 2 3 "yay"

[https://developer.mozilla.org/en-US/docs/Web/API/Console/log](https://developer.mozilla.org/en-US/docs/Web/API/Console/log)

**Comment by oskarkrawczyk** [comment]
Fixed
