### ISSUE TITLE
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': function h(e,t){return new b(e,t)} could not be cloned.

### ISSUE THREAD

**Issue by ilyaskarim** [jsfiddle/jsfiddle-issues#1588]
I am trying to save content and on each saves button the error pops up:

Uncaught DOMException: Failed to execute 'postMessage' on 'Window': function h(e,t){return new b(e,t)} could not be cloned.

Luckily the jsFiddle is public, Please see https://jsfiddle.net/nm8adc64/2/.

**Comment by ilyaskarim** [comment]
Can this addressed as soon as possible?

**Comment by oskarkrawczyk** [comment]
Turn off Custom Console (beta).

**Comment by AMBudnik** [comment]
@oskarkrawczyk wouldn't it be better to turn off that feature by default? It is causing more issues than favors. It sometimes turns on when I already turned it off.

**Comment by oskarkrawczyk** [comment]
> It sometimes turns on when I already turned it off

Editor settings between being logged in and logged out are not in sync. Most likely why it's like that for you.

**Comment by oskarkrawczyk** [comment]
> It is causing more issues than favors

@AMBudnik Issues like? So far this is the only one reported (that hasn't been fixed already)

**Comment by AMBudnik** [comment]
Experienced users may understand that they should turn off the beta console if they get the error, but newbies get lost (some of our Clients) 🤕 .

**Comment by ilyaskarim** [comment]
> Turn off Custom Console (beta).

Thanks for temporarily solution.

**Comment by oskarkrawczyk** [comment]
**Not to self:** Right now the parent editor is trying to postMessage all payloads, including ones that contain objects where values are functions - this will fail, since browsers prevent this.

**Comment by oskarkrawczyk** [comment]
> Experienced users may understand that they should turn off the beta console if they get the error, but newbies get lost (some of our Clients) 🤕

I'm trying to understand if there's an issue with the custom console that I don't know about or your clients see the little "1 error" in which case the console works as expected as it's presenting found errors, warnings, etc

**Comment by AMBudnik** [comment]
Not sure if that's the place to mention this, but OK.

![Zrzut ekranu 2020-05-21 o 11 23 58](https://user-images.githubusercontent.com/10757813/82544751-e4b7d600-9b55-11ea-9398-f3f9ab94c3b8.png)

When the console in the editor is on, there's no info in the browser console. That is confusing for newbies. And believe me, there are people who need to be instructed to 'fork' a demo if they change anything, so a lack of log in the browser console rings the wrong bells (they think that our callbacks do not work, as they do not log 🙈 ).

**Comment by oskarkrawczyk** [comment]
@AMBudnik Sure, this is by design, but I agree that perhaps muting these was a step too far, can you create a new issue for this?

**Comment by AMBudnik** [comment]
@oskarkrawczyk done https://github.com/jsfiddle/jsfiddle-issues/issues/1592

**Comment by oskarkrawczyk** [comment]
Payload passed to the custom console is now stringified which solves the underlying problem causing some issues, including this.
