### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by ilyaskarim** [jsfiddle/jsfiddle-issues#1589]
This error pops up when I hit CTRL + S to save the jsFiddle, I'm using https://jsfiddle.net/nm8adc64/2/ for testing. 

Specs:

Google Chrome latest
Windows 10

Note: This issue is more than a year older.

**Comment by oskarkrawczyk** [comment]
Thanks for reporting this in! Fixed.
