### ISSUE TITLE
When the console in the editor is on, there's no info in the browser console

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1592]
### Description
That is confusing for newbies. As the editor console is still in beta version I would recommend closing the co console results so they're visible in both consoles.

![82544751-e4b7d600-9b55-11ea-9398-f3f9ab94c3b8](https://user-images.githubusercontent.com/10757813/82563924-2c4f5980-9b78-11ea-9244-9598833415eb.png)

### My environment
browser: Chrome 80
device: MacBook Air
system: macOS Catalina

### Demo
https://jsfiddle.net/AMBudnik/a1bhet2y/

**Comment by sanchezzzhak** [comment]
in addition, the console does not output N values, only the first value
![image](https://user-images.githubusercontent.com/1337066/82812122-f45b5580-9e9a-11ea-95f8-a38817fd3888.png)

TEST BUG
```js
function isEnable(value) {
  if (typeof value === 'string') {
	value = parseInt(value);
  }
  return Boolean(value);
}

console.log(isEnable(1), isEnable(0), 'test');
```
I use this code to debug IOS =) I think it will help you
```js
 // you can replace this function at your own discretion
  const sendToLog = function (arg, type) {
	let message = JSON.stringify(arg);
	let img = new Image();
	img.src = "log.php?message=" + encodeURIComponent(message) + "&type=" + type + "&time=" + ((new Date).getTime() / 1000);
  };

  let console = (function (oldCons) {
	return {
	  log: function () {
		sendToLog(arguments, 'log');
		oldCons.log(arguments);

	  },
	  info: function () {
		sendToLog(arguments, 'info');
		oldCons.info(arguments);
	  },
	  warn: function () {
		sendToLog(arguments, 'warn');
		oldCons.warn(arguments);
	  },
	  error: function () {
		sendToLog(arguments,'info');
		oldCons.error(arguments);
	  }
	};
  }(window.console));

  //Then redefine the old console
  window.console = console;
```

**Comment by AMBudnik** [comment]
Hey @sanchezzzhak that issue has been raised here https://github.com/jsfiddle/jsfiddle-issues/issues/1586

**Comment by oskarkrawczyk** [comment]
Fixed this and #1586

**Comment by AMBudnik** [comment]
Thank you :) works well now

**Comment by oskarkrawczyk** [comment]
Payload passed to the custom console is now stringified which solves the underlying problem causing some issues, including this.
