### ISSUE TITLE
In embedded mode js comment is displayed as code

### ISSUE THREAD

**Issue by KooiInc** [jsfiddle/jsfiddle-issues#1593]
Comment is formatted as code, see first line in the javascript tab of [this embedded jsfidde](https://testbed.nicon.nl/showFiddle/Ltyknpwg). It looks like `//`  is interpreted as `RegExp` (gets className `"hljs-regexp"`).

This is not the case in the js edit screen.

Regards

**Comment by oskarkrawczyk** [comment]
The 3rd party library for code highlighting isn't that great, it is lightweight, but not amazing.

Would have to find a new syntax highlighter and replace the old one.

**Comment by KooiInc** [comment]
I understand. It works as it should with the editor though ...

![image](https://user-images.githubusercontent.com/836043/83325079-e413f380-a269-11ea-8a4f-18b06125dbbb.png)

**Comment by oskarkrawczyk** [comment]
Yep, completely different syntax highlighter

**Comment by oskarkrawczyk** [comment]
Fixed
