### ISSUE TITLE
Powerful features no longer work in embedded jsfiddles in Firefox (NotAllowedError)

### ISSUE THREAD

**Issue by jan-ivar** [jsfiddle/jsfiddle-issues#1594]
Embedded jsfiddles in articles like [this one](https://blog.mozilla.org/webrtc/fiddle-week-downscale-video-peerconnection/) stopped working in Firefox a couple of days ago.

The [new template](https://jsfiddle.net/jib1/pz5pynyf/show/) appears to be using invalid syntax:
```html
<iframe ... allow="midi geolocation microphone camera encrypted-media">
```
The correct syntax is:
```html
<iframe ... allow="midi; geolocation; microphone; camera; encrypted-media">
```

Chrome unfortunately accepts the invalid syntax, which is [crbug 1062400](https://bugs.chromium.org/p/chromium/issues/detail?id=1062400) (please go ★ it).

**Comment by oskarkrawczyk** [comment]
Note that `/show` is not an embed, it's a Standalone View introduced today.

Use `/embedded` (within an iframe) for the embed.

**Comment by jan-ivar** [comment]
The [article](https://blog.mozilla.org/webrtc/fiddle-week-downscale-video-peerconnection/) uses `/embedded` and the problem appears to afflict both.

**Comment by oskarkrawczyk** [comment]
Fixed. Thanks for reporting this in!
