### ISSUE TITLE
Jsfiddle elements are not getting scrolled completely into view so Selenium is failing

### ISSUE THREAD

**Issue by GeorgianaDan** [jsfiddle/jsfiddle-issues#1595]
Jsfiddle is using a different resolution or what the cause is but elements are not getting scrolled completely into view so Selenium is failing when it tries to click on things.

**Comment by oskarkrawczyk** [comment]
Perhaps. Since I see no reason to use JSFiddle via Selenium to be honest. 

Super edge-case, no capacity to look into it, but I'll gladly hear a working solution if someone figures it out.

**Comment by GeorgianaDan** [comment]
Hi Oskarkrawczyk,
 I managed to solve some of my Selenium issues, by changing the Settings, Editor Layout to Tabs(rows) and having height=100%, width=100%.
 Now the problem is that I only see part of the elements in by page. 
![part of the elements appear in the page](https://user-images.githubusercontent.com/66012809/83051273-72b02700-a056-11ea-8973-444421c8c18a.JPG)

**Comment by oskarkrawczyk** [comment]
No idea, looks like the editor is broken on your browser for some reason.

I'd need more details. What browser, what system, are there any JS errors, any resources throwed a 404?

**Comment by GeorgianaDan** [comment]
Hello Oskarkrawczyk,
Browser: Chrome, version 77.0.38.65.90
System: Ubuntu virtual machine, 18.04.3.LTS, 
![ubuntu](https://user-images.githubusercontent.com/66012809/83112522-f1e14180-a0ce-11ea-9b60-c358593a06dd.JPG)
JS errors: 
![console errors and warnings](https://user-images.githubusercontent.com/66012809/83117181-6fa84b80-a0d5-11ea-9454-b26a17fe3ced.JPG)
![warnings](https://user-images.githubusercontent.com/66012809/83117190-72a33c00-a0d5-11ea-9f73-b10b1db6d308.JPG)
![error](https://user-images.githubusercontent.com/66012809/83117209-7636c300-a0d5-11ea-9943-25a330904aac.JPG)
![error 2](https://user-images.githubusercontent.com/66012809/83117216-78991d00-a0d5-11ea-9fbe-71479e57d1d8.JPG)
![status codes 3](https://user-images.githubusercontent.com/66012809/83117226-7b940d80-a0d5-11ea-935c-ceb457fac6b0.JPG)

**Comment by oskarkrawczyk** [comment]
No JS error related to the Editor itself.

Tested on Chrome 80, all works as expected.

**Comment by oskarkrawczyk** [comment]
No other info provided. Can't replicate issue. Closing.
