### ISSUE TITLE
Keyboard events are lost?

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1596]
### Description
We want to copy a TABLE'S TD value in our library via JSFiddle demo. There might be many suspects, but I have tested the same action on our website and in another JS Playground and it works there. I remember that it works well in JSFiddle as well, so it seems that it got broken recently.

@oskarkrawczyk let me know if you need anything to solve this case. 

### Demo
https://jsfiddle.net/AMBudnik/zpuvaj92/ (**broken**)
https://handsontable.com/docs/7.4.2/demo-scrolling.html (website, working)
https://codesandbox.io/s/date-dependent-time-change-p0lx8 (other sandbox, working)

### Scenario
1. Use <kbd>CMD/CTRL + C</kbd> shortcut after selecting any cell in the table
2. Open any console (browser, or beta console) to check if anything's printed

**Result**
Value is not copied. You can try to paste it anywhere (to the table, or the CSS part of the tool).

### Additional info
* copying text between tabs rows well.
* copying anything in the Result that is not a part of the table works well. It seems that the fact that we are using our own callbacks for copying interferes with newer changes in JSFiddle.

### My environment
Browser: Chrome 80
Device: Macbook Air
System: macOS Catalina

**Comment by AMBudnik** [comment]
ps. what's the 
> /* EOS */

in the Rsult tab?

**Comment by oskarkrawczyk** [comment]
@AMBudnik Will copying work when using Standalone View?

**Comment by AMBudnik** [comment]
Sorry, I do not know what do you mean by saying **Standalone View**.

**Comment by oskarkrawczyk** [comment]
@AMBudnik Just add `/show` to the URL

**Comment by AMBudnik** [comment]
That's it! It works well in the Standalone View.

**Comment by oskarkrawczyk** [comment]
Gotcha, I'll do some digging. There's a single thing I've changed in regards to keyboard events in the past year, so it's either that or some unforeseen problem.

**Comment by oskarkrawczyk** [comment]
> ps. what's the
> /* EOS */
> in the Rsult tab?

In reality it's a part of the `<style>` tag, but since you guys are using a hack (mentioned in on your Issues) this is now displayed in Results.

**Comment by oskarkrawczyk** [comment]
@AMBudnik I see whats causing the copy problem - boils to down a JS error, but what triggers it is really weird. Is there any chance the copy feature in Handsontable uses `postMessage` in some way (that would be weird but worth asking).

**Comment by oskarkrawczyk** [comment]
Ok, never mind. I just figured it out.

This is one remaining issue with the Custom Console I'm aware of that needs to be fixed: #1588

Long story short, you have this in your code:

```js
beforeCopy: function(){	
  console.log(arguments)
}
```

The `arguments` variable most likely carries something that's not a simple array or object, something that the browser cannot pass to the Custom Console for security reasons.

I'm going to disable Custom Console by default until this is fixed.

**Comment by oskarkrawczyk** [comment]
**Note to self:** See if converting an Array-like variable with `Array.from(Array-like)` will solve the problem.

**Comment by oskarkrawczyk** [comment]
Payload passed to the custom console is now stringified which solves the underlying problem causing some issues, including this.
