### ISSUE TITLE
Custom Console reloads after entering anything

### ISSUE THREAD

**Issue by flleeppyy** [jsfiddle/jsfiddle-issues#1600]
Tested on Brave Browser, Chrome, Edge, all with no extensions enabled

How to recreate:
Simple: Enter anything (doesn't have to be valid) in to the Custom Console and it will reload the currently editing page.

Here's an example: [https://dl.dropboxusercontent.com/s/5ytn5968zrt76gc/PPAHrrdbP6.mp4](https://dl.dropboxusercontent.com/s/5ytn5968zrt76gc/PPAHrrdbP6.mp4)

Now I could be really stupid and this is supposed to happen, but I highly doubt that.

**Comment by oskarkrawczyk** [comment]
I see this is happening on Blink-based browsers only, all other work as intended (correctly).

This is pretty minor but still, shouldn't work this way. Will have a look into it sometime this or next week.

**Comment by abrichr** [comment]
Also happening on Safari 12.1.2
