### ISSUE TITLE
Adding 'allow-downloads' to the sandbox iframe attributes

### ISSUE THREAD

**Issue by poupougnac** [jsfiddle/jsfiddle-issues#1601]
Latest version of Chrome is blocking any scripts initiating downloads directly from JS.

console message: _Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details._

This script for example that shows how to generate a csv is impacted:
https://jsfiddle.net/yoshi6jp/Qr5eb/

And many others obviously...

It would be useful to add the flag to the sandbox attributes.

Many thanks

**Comment by poupougnac** [comment]
Thanks!!
Hey @oskarkrawczyk,
Sorry to bother you but can you do that also on the embed page (through direct link):
This one : https://fiddle.jshell.net/yoshi6jp/Qr5eb/show/

**Comment by oskarkrawczyk** [comment]
Should work in a few moments.

Btw. Please don't use that domain `fiddle.jshell.net`. The fact that it's working is a bug, which will be fixed by tomorrow. 

The correct way to show a fiddle in full screen is to use the **Standalone View**, in your case: `jsfiddle.net/yoshi6jp/Qr5eb/show/`

**Comment by poupougnac** [comment]
Perfect, I'll do this. Don't bother fixing the old link if it's deprecated.
Thank you !
