### ISSUE TITLE
Embed jsfiddle as iframe with google maps 

### ISSUE THREAD

**Issue by gaelsimon** [jsfiddle/jsfiddle-issues#1603]
Embed a jsFiddle with Google Maps API as an iframe breaks the Google maps API

chrome error: 
```
Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
```
firefox error
```
SecurityError: Permission denied to access property "addEventListener" on cross-origin object
```

sample: <https://demo.woosmap.com/misc/jsfiddle/jsfiddle-gmaps-issue.html>

**Comment by oskarkrawczyk** [comment]
I don't understand why the maps would need to break out of the containing iframe and check for the parents origin.

For now leaving as it is.

**Comment by gaelsimon** [comment]
All our samples are hosted on jsFiddle and displayed on our developers doc via iFrame. The issue has appeared today. 
I thought that's just because of a deployment either on your side or google side. I've tested with different Google Maps version (v3.39, v3.40, v3.41) and get the same error.
I will try to submit an issue on google groups.
Thanks anyway.

**Comment by gaelsimon** [comment]
I've tried to embed the jsFiddle using default script inclusion but that also seems to be broken. I get a 404 on domain fiddle.shell.net.
I've updated the previous sample.

**Comment by oskarkrawczyk** [comment]
Looks to be working from here

![image](https://user-images.githubusercontent.com/34213/83918113-6293f800-a778-11ea-81e0-c47204855e1e.png)

**Comment by JeanCarriere** [comment]
Something changed in jsfiddle and now XHR sent within an iframe embedded fiddle are with a header
access-control-allow-origin:**null**
![image](https://user-images.githubusercontent.com/2640544/83993017-77c47e80-a952-11ea-894c-9313ef836563.png)
which breaks our fiddles (as we control the origin) and generates the console log of google maps
`Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.`

**Comment by oskarkrawczyk** [comment]
Something did change. Can you provide the fiddle in question?

**Comment by JeanCarriere** [comment]
For instance, the fiddle on this page https://developers.woosmap.com/products/widgets/store-locator-widget/sample-usage/ (which is https://jsfiddle.net/woosmap/Lojau2vh/) does generate XHR requests which do not have origin from the iframe

**Comment by oskarkrawczyk** [comment]
Brought back `allow-same-origin` sandbox flag.
