### ISSUE TITLE
Display JSFiddle from POST doesn't auto-run the code after opening in new tab

### ISSUE THREAD

**Issue by MANOJMANI07** [jsfiddle/jsfiddle-issues#1605]
[JSFiddle example](http://jsfiddle.net/3Lwgk4c5/) in the official documentation regarding [displaying JSFiddle from POST](https://docs.jsfiddle.net/api/display-a-fiddle-from-post) doesn't auto-run the code. The expected behaviour is to auto-run the code after submission of the post.

**Comment by oskarkrawczyk** [comment]
Duplicate #1564
