### ISSUE TITLE
Result preview with 404

### ISSUE THREAD

**Issue by JeanCarriere** [jsfiddle/jsfiddle-issues#1606]
From whatever fiddle, in Chrome (Mac OS 10.15.3, Chrome 83.0.4103.61), I get a 404 in the result preview:
![image](https://user-images.githubusercontent.com/2640544/84002709-22479c00-a969-11ea-82ed-6988aa828219.png)

**Comment by oskarkrawczyk** [comment]
Thanks. It's unclear why this is happening on Chrome alone. Investigating.

**Comment by oskarkrawczyk** [comment]
@JeanCarriere Can you provide the **exact** url to the fiddle?

**Comment by JeanCarriere** [comment]
For instance this one : https://jsfiddle.net/woosmap/Lojau2vh/

**Comment by oskarkrawczyk** [comment]
Thanks. So this is a very obscure Chrome/Blink bug, had to work around it but it should now work.
