### ISSUE TITLE
XSS vulnerability with DOM-based in main domain jsfiddle.net

### ISSUE THREAD

**Issue by knoobdev** [jsfiddle/jsfiddle-issues#1608]
Hi jsfiddle,
I have find vuln DOM-based Cross-Site Scripting in jsfiddle.net

**Payload**
https://jsfiddle.net/zjcodez/d3jtvL04

Best Regards,
Ngoc Chanh at J2TEAM

**Comment by oskarkrawczyk** [comment]
Thanks for reporting this in! Fixed.
