### ISSUE TITLE
Dies horribly on MSIE 11

### ISSUE THREAD

**Issue by IanKemp** [jsfiddle/jsfiddle-issues#1609]
Loading any fiddle in IE 11 results in nothing but the blue loading infinity cloud hopping in place forever.

It would be far better to show a "sorry, this browser is no longer supported" message.

**Comment by oskarkrawczyk** [comment]
> It would be far better to show a "sorry, this browser is no longer supported" message.

Indeed, that should be happening already, not sure why it's not. Will look into this soon.

**Comment by oskarkrawczyk** [comment]
@IanKemp Any chance you could let me know what JS error are you getting in the console on IE?

**Comment by oskarkrawczyk** [comment]
Fixed.
