### ISSUE TITLE
Support import maps

### ISSUE THREAD

**Issue by tpluscode** [jsfiddle/jsfiddle-issues#1614]
It would be nice to have simple [import maps](https://jspm.org/#import-maps)

While the feature is not ready in some browsers and flagged in others, I would propose a UI to define such a map so that bare imports in the code are adjusted.

I would propose that a single entry such as `"svelte": "https://jspm.dev/svelte@3"` would also transparently handle subpaths so that in code I can write

```diff
-import svelte from 'https://jspm.dev/svelte@3'
-import store from 'https://jspm.dev/svelte@3/store'
+import svelte from 'svelte'
+import store from 'svelte/store'
```

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

**Comment by sokarax** [comment]
> It would be nice to have simple [import maps](https://jspm.org/#import-maps)
> 
> 
> 
> While the feature is not ready in some browsers and flagged in others, I would propose a UI to define such a map so that bare imports in the code are adjusted.
> 
> 
> 
> I would propose that a single entry such as `"svelte": "https://jspm.dev/svelte@3"` would also transparently handle subpaths so that in code I can write
> 
> 
> 
> ```diff
> 
> -import svelte from 'https://jspm.dev/svelte@3'
> 
> -import store from 'https://jspm.dev/svelte@3/store'
> 
> +import svelte from 'svelte'
> 
> +import store from 'svelte/store'
> 
> ```
