### ISSUE TITLE
Disable autorun?

### ISSUE THREAD

**Issue by lucapivato** [jsfiddle/jsfiddle-issues#1615]
Settings -> Autorun Code is off but it keeps auto running the code.
Turned it on and off again several times.
Is there another way to disable auto running?

**Comment by ScamCast** [comment]
I'm having the same issue. Code keeps running after I type when I have the autorun option turned off.

**Comment by cimenta** [comment]
I am having the same issue. Even though it looks like the feature is turned off in the settings

**Comment by cimenta** [comment]
I am experiencing the same.. any way to turn it off?

**Comment by turtletennis** [comment]
It seems to also be triggered by save, so if you have autosave enabled it will run your code when it autosaves.

**Comment by sripadks** [comment]
This issue is still present. Even if auto run and auto run on validate both are disabled, the code will auto run upon save.

This is super annoying because you will be testing something and boom the auto save triggers rerun of the code and the state of the output that was under test is lost.

**Comment by markusd1984** [comment]
indeed very annoying, if it's supposed to refresh with auto save then there should be a dedicated setting to disable auto-rerun.
