### ISSUE TITLE
Can't change company name

### ISSUE THREAD

**Issue by tiago-peres** [jsfiddle/jsfiddle-issues#1616]
If we go to Upper Right Icon > Settings, change the "Company name" and click the save button, the name of the company won't change and goes back to the value that was initially in there.

**Comment by osmannyildiz** [comment]
Same thing happening for me. All values change except company name.
Tried with VPN and without browser extensions.

**Comment by oskarkrawczyk** [comment]
Yes, already marked as a Bug.

**Comment by emq** [comment]
Sorry for the delay @tiago-peres & @osmannyildiz; fix was just deployed to production, feel free to give it a go
