### ISSUE TITLE
Not clear how to change Fiddle name

### ISSUE THREAD

**Issue by tiago-peres** [jsfiddle/jsfiddle-issues#1617]
If I go to my list of fiddles (https://jsfiddle.net/user/tiagoperes/fiddles/) and from there can see there's one named 72x8fLL0.

If I click in the fiddle with that name (https://jsfiddle.net/tiagoperes/72x8fLL0/) then can see in the right side in Fiddle Meta "Untitled fiddle".

If I write a name for it there, let's say "Reddiant" and click "Save", that's not gonna be enough to save the name. If one wants to change the name, then instead we'll have to click "Save" and after "Set as base".

**Comment by oskarkrawczyk** [comment]
This is exactly how it works and it's by design. We'll be evaluating changing this flow in the future.
