### ISSUE TITLE
console.assert broken via JSFiddle

### ISSUE THREAD

**Issue by dflor003** [jsfiddle/jsfiddle-issues#1619]
Not sure what's going on, but I have old fiddles that were running fine before breaking now. These fiddles make heavy use of console.assert and they now error out with:

```
TypeError: console.assert is not a function
    at assert (?editor_console=true:141)
    at s.run (?editor_console=true:149)
    ...
```

Is jsfiddle overriding the native browser console functions???

**Comment by oskarkrawczyk** [comment]
Just turn off the custom console in JSFiddle settings for now.

**Comment by sheriffderek** [comment]
> Just turn off the custom console in JSFiddle settings for now.

I can turn it off in future fiddles - but I'm not going to go into 600+ past fiddles and do that.

**Comment by oskarkrawczyk** [comment]
Editor options are not set per fiddle but per user account.

**Comment by oskarkrawczyk** [comment]
Added a proxy to the custom console so it pushes more console methods back to the native one.
