### ISSUE TITLE
Feature Request: embed with split view

### ISSUE THREAD

**Issue by mjhm** [jsfiddle/jsfiddle-issues#162]
It would be great to be able to see the embedding with a split side-by-side view.  I would especially like to be able to see the "result" and "js" panels at the same time in the initial embed view.  The URL syntax could look something like

    result,html;js,css,resources

Which indicates that "result" and "html" tabs go on the left panel, and "js", "css", and "resources" go on the right panel.  However any other reasonable approach would be fine with me.

**Comment by select** [comment]
JS Bin has this feature, so you can switch to it. Codepen also seems to miss it.
