### ISSUE TITLE
"All your fiddles" page should show fiddle name from latest version

### ISSUE THREAD

**Issue by RedDragonWebDesign** [jsfiddle/jsfiddle-issues#1620]
"All your fiddles" page should show fiddle name from latest version

Feature request. Up to you. I think it'd be a nice little quality of life tweak. I forget to name my fiddles sometimes.

## Steps to replicate

- Create a fiddle with no name. Add some code. Save a couple of versions of it.
- Add a name to the fiddle. Hit save.
- Go to "All your fiddles" page. Fiddle will not have a name.

![2020-07-30_001854](https://user-images.githubusercontent.com/43397938/88892890-65501e00-d1fa-11ea-9ad6-e9730f26f412.png)
![2020-07-30_001909](https://user-images.githubusercontent.com/43397938/88892892-66814b00-d1fa-11ea-90fb-7156652f7cd7.png)

**Comment by oskarkrawczyk** [comment]
Expected behavior. Saving as base version will display updates in the listing.
