### ISSUE TITLE
"All your fiddles" page - clicking on fiddle should load latest version

### ISSUE THREAD

**Issue by RedDragonWebDesign** [jsfiddle/jsfiddle-issues#1621]
"All your fiddles" page - clicking on fiddle should load latest version

Feature request. Up to you. I think it'd be a nice little quality of life tweak. I rarely need to go to v1 of a fiddle from the "all your fiddles" page. I usually want to go to the latest version. The link with the largest surface area (the screenshot) goes to v1 though.

## Steps to replicate

- Create a fiddle. Add some code. Save a couple of versions of it.
- Go to "All your fiddles" page.
- Click on the fiddle's screenshot (instead of the text link). It will load v1 of the fiddle, instead of the latest version.

![2020-07-30_002255](https://user-images.githubusercontent.com/43397938/88893274-f6bf9000-d1fa-11ea-9aa6-fe4a91608b7c.png)
![2020-07-30_002308](https://user-images.githubusercontent.com/43397938/88893281-f921ea00-d1fa-11ea-9f4a-12146b6897b8.png)

**Comment by oskarkrawczyk** [comment]
already on the tap
