### ISSUE TITLE
Github integration fail

### ISSUE THREAD

**Issue by kmandziuk** [jsfiddle/jsfiddle-issues#1624]
I have these three fiddles:
* https://jsfiddle.net/gh/get/jquery/1.9.1/kmandziuk/jsfiddle_integrations_test/tree/master/jquery-usos-demos/test.qwe - not working
* https://jsfiddle.net/gh/get/jquery/1.9.1/kmandziuk/jsfiddle_integrations_test/tree/master/test.qwe - working
* https://jsfiddle.net/gh/get/jquery/1.9.1/kmandziuk/jsfiddle_integrations_test/tree/master/jquery-usos-demos/test13 - working

Files within them - exactly the same. I am getting "404 Repository/Gist not found: https://api.github.com/repos/kmandziuk/jsfiddle_integrations_test/contents/jquery-usos-demos/test" so maybe something with longer name and dot within it.

**Comment by oskarkrawczyk** [comment]
Long name might be the case. Will look into it.

**Comment by emq** [comment]
@kmandziuk thanks for reporting this and sorry for the lag; should be working now!
