### ISSUE TITLE
JSFiddle is inaccessible

### ISSUE THREAD

**Issue by enryco** [jsfiddle/jsfiddle-issues#1625]
There seems to be no light theme anymore, so it is inaccessible during the day or for people with sight problems

**Comment by kmandziuk** [comment]
Inspired by this issue I have checked elements' contrast and it is too low for people with sight problems. More here: https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum
It is obviously not mandatory standard but it is a good practice to apply these guidelines.

**Comment by oskarkrawczyk** [comment]
Thanks for the input. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

As mentioned many times before, keeping two themes was too much of an development overhead.

**Comment by enryco** [comment]
Yes but wouldn't it then be better to have just a light theme as there are already browser plugins (for example dark reader) that do the trick when dark is needed. Maybe you can port that technology to automatically create a dark theme. (Like darkmode-js or nightly-js)

**Comment by oskarkrawczyk** [comment]
Most people were using the dark one when both were available, so the decision which one to keep was pretty obvious.

**Comment by enryco** [comment]
That's not the point but to make the site [accessible](https://www.w3.org/WAI/fundamentals/accessibility-intro/) for everyone (and not just "most people"). Plus, an idea of how to reduce the development overhead.

Btw: Links to terms & conditions and privacy policy are missing on the homepage.

PS: No need to be passive-aggressive with your defensiveness :/ I'm only trying my best to help because I think it's a great product and sad that I am not able to use it at the moment
