### ISSUE TITLE
console.time() is not supported

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1626]
Hi @oskarkrawczyk 

Here's what I get when I try to use [`console.time()`](https://developer.mozilla.org/en-US/docs/Web/API/Console/time).

browser console
![image](https://user-images.githubusercontent.com/10757813/89784401-e40d5b00-db18-11ea-8c14-163c1f63a982.png)

your console
![image](https://user-images.githubusercontent.com/10757813/89784423-f091b380-db18-11ea-8777-827d9293d65b.png)

Demo: http://jsfiddle.net/p7daeog0/3/
Device: Windows 10 / Chrome 84

**Comment by sheriffderek** [comment]
I think that "console" - as an object... has changed.

`console.clear()` - also gets this error -- 

This will effectively render all my past fiddles broken! LOL

**Comment by guanzo** [comment]
Could've sworn `console.time` worked in the past... Is jsfiddle overriding console or something?

**Comment by oskarkrawczyk** [comment]
Added a proxy to the custom console so it pushes more console methods back to the native one.

**Comment by sheriffderek** [comment]
Does this parameter need to be `args`

![Screen Shot 2020-09-07 at 8 28 04 AM](https://user-images.githubusercontent.com/2066617/92402273-214b1580-f0e4-11ea-8132-af6fb14cc44e.png)
