### ISSUE TITLE
console.clear is not a function

### ISSUE THREAD

**Issue by sheriffderek** [jsfiddle/jsfiddle-issues#1634]
Not sure when - but a little while back - console methods besides log seem to have been removed - 

I often start my JS with a `console.clear()` in the fiddles. Now that method doesn't exist.

This will probably render hundreds of thousands of StackOverflow/Slack/Quora/Discord/ - examples - white-screen / broken. Yikes!

I didn't really foresee that! but - maybe I shouldn't have counted it?

Here's an example: https://jsfiddle.net/sheriffderek/zbekav2h/

Is this purposeful? I read somewhere that you could add the functionality back in with a script - but It wouldn't make sense to go back and add that to

**Comment by guanzo** [comment]
Workaround: https://github.com/jsfiddle/jsfiddle-issues/issues/1619#issuecomment-663677801

**Comment by oskarkrawczyk** [comment]
Added a proxy to the custom console so it pushes more console methods back to the native one.
