### ISSUE TITLE
CSS Property crashed jsfiddle view window.

### ISSUE THREAD

**Issue by moy-source** [jsfiddle/jsfiddle-issues#1635]
CSS property "[all](https://developer.mozilla.org/en-US/docs/Web/CSS/all)" crashed jsfiddle view window.

`* {
  all: unset;
}`

https://jsfiddle.net/vague/nuf1w5s7/

![jsfiddle](https://user-images.githubusercontent.com/70908486/92405714-7d3e8a00-f136-11ea-9e8f-1b2e9841c4fb.png)

**Comment by oskarkrawczyk** [comment]
Use `body * {...}` as per known bugs in README.

No idea why is this happening...
