### ISSUE TITLE
Medium embeds all 404ing

### ISSUE THREAD

**Issue by Gillinghammer** [jsfiddle/jsfiddle-issues#1636]
https://blog.mapbox.com/data-driven-styling-for-live-earthquake-tracking-604bd3767152

We have multiple blog posts that have failing 404 errors where a JSFiddle code example should be displayed. Can someone let me know if there is a way we can quickly fix this? 

Our company unique url also results in 404: https://jsfiddle.net/mapbox/

**Comment by oskarkrawczyk** [comment]
>  have multiple blog posts that have failing 404 errors where a JSFiddle code example should be displayed

You're using this URL: `https://jsfiddle.net/kk13xmL7/show/embedded` which is incorrect, try `https://jsfiddle.net/kk13xmL7/embedded`

> Our company unique url also results in 404: https://jsfiddle.net/mapbox/

https://jsfiddle.net/user/mapbox/
