### ISSUE TITLE
iframe on post does not have valid src for feature policy settings

### ISSUE THREAD

**Issue by jpoehnelt** [jsfiddle/jsfiddle-issues#1637]
When posting contents to JSFiddle via `https://jsfiddle.net/api/post/library/pure/`, the iframe src is incompatible with the allow="geolocation;..." as the src value is not set.

```
<iframe name="result" allow="midi; geolocation; microphone; camera; display-capture; encrypted-media;" sandbox="allow-modals allow-forms allow-scripts allow-same-origin allow-popups allow-top-navigation-by-user-activation allow-downloads" allowfullscreen="" allowpaymentrequest="" frameborder="0" src="">
        </iframe>
```

After saving and reloading the page, the src has a valid value.

```
<iframe name="result" allow="midi; geolocation; microphone; camera; display-capture; encrypted-media;" sandbox="allow-modals allow-forms allow-scripts allow-same-origin allow-popups allow-top-navigation-by-user-activation allow-downloads" allowfullscreen="" allowpaymentrequest="" frameborder="0" src="//fiddle.jshell.net/tvcms187/show/?editor_console=">
        </iframe>
```

A wildcard would work, but perhaps there is a better solution.

**Comment by ayubmetah** [comment]
Do they need to have all those features (midi; geolocation; microphone; camera; display-capture; encrypted-media) in order to get the iframe work? Look at the code;
 https://jsfiddle.net/90Lypj16/embed/js,html,css,result/dark/
 
 Looks suspicious!
