### ISSUE TITLE
UX: Minimized Console shouldn't be position: absolute

### ISSUE THREAD

**Issue by mdizo** [jsfiddle/jsfiddle-issues#1638]
Having the console `position: absolute` ends up hiding elements from the preview screen.

For example, when running this js function [here](https://jsfiddle.net/mdizo/zaL01d2v/5/) on a 1080p screen, it took me forever to figure out what was wrong because the last `<p>` element was hidden behind the console bar. It was only when I decided to change the layout I was able to see and verify that the code was working as it should.

Loving the new console feature btw, it makes it so much more intuitive to debug code now.

**Comment by oskarkrawczyk** [comment]
Hopefully today I'll have this changed so that the console doesn't overlap the results panel anymore.

**Comment by oskarkrawczyk** [comment]
Should now work as expected.
