### ISSUE TITLE
Uncaught TypeError: console.dir is not a function

### ISSUE THREAD

**Issue by dwiyatci** [jsfiddle/jsfiddle-issues#1640]
**Steps to reproduce**:
- simply write code that uses `console.dir` in JavaScript panel:
```js
const arr = [2, 3, 5];
console.dir(arr);
```

**Actual**:
Error thrown in the console:
> Uncaught TypeError: console.dir is not a function
>     at ?editor_console=true:106

**Expected**:
Using `console.dir` should be valid and not throw an error.

**Comment by oskarkrawczyk** [comment]
Thanks for the heads-up. Should now work as expected even when the JSFiddle console is activated.

**Comment by dwiyatci** [comment]
@oskarkrawczyk Sorry, I still got:
```
?editor_console=true:87 Uncaught ReferenceError: args is not defined
    at Object.dir (?editor_console=true:87)
    at ?editor_console=true:108
```
😕 

Maybe I need to wait for quite some time?
