### ISSUE TITLE
Why can't I switch back to light mode

### ISSUE THREAD

**Issue by MikeWilliams-UK** [jsfiddle/jsfiddle-issues#1641]
I can't find out where to switch back to light mode.

I personally find that dark mode sucks.

Why am I being FORCED to use dark mode?

Google Chrome
Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by AMBudnik** [comment]
@MikeWilliams-UK https://github.com/jsfiddle/jsfiddle-issues/issues/1563
