### ISSUE TITLE
Nullish coalescing operator syntax highlighting warning

### ISSUE THREAD

**Issue by Eddcakes** [jsfiddle/jsfiddle-issues#1647]
‼️‼️‼️

Known issues (see README.md) will not be 
addressed and most likely will be closed.

‼️‼️‼️

![image](https://user-images.githubusercontent.com/10856551/96478235-598b5b00-122f-11eb-8c67-7ebb6f42fb99.png)

The code runs how I expected but was confused at first thinking it wouldn't because of the syntax highlighting. 

Code snippet taken from [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

**Comment by JavascriptLearner815** [comment]
Same frustrating issue, use this for now though:
```javascript
// ...
const foo = null ? null : 'default string';
// ...
const baz = 0 ? 0 : 42;
// ...
```

**Comment by drosenba** [comment]
I see above comment "Known issues (see README.md) will not be addressed and most likely will be closed", however, I don't see any such text in the README.md file.
Why won't this null coalescing operator warning issue not be fixed?
