### ISSUE TITLE
`console.assert()` wrong behaviour;

### ISSUE THREAD

**Issue by eof273** [jsfiddle/jsfiddle-issues#1651]
**Current behaviour:**
`console.assert()` prints values always:

```
console.assert(false, 'correct');
console.assert(true, 'wrong');
```
![image](https://user-images.githubusercontent.com/18496223/98772989-88ee4b80-241a-11eb-8373-9566d93ff937.png)

**Expected behaviour:**
`console.assert()` prints values only if the assertion (first argument) is false;

https://developer.mozilla.org/en-US/docs/Web/API/console/assert

**Comment by oskarkrawczyk** [comment]
Will look into this

**Comment by oskarkrawczyk** [comment]
Fixed
