### ISSUE TITLE
Page navigation doesn’t work properly

### ISSUE THREAD

**Issue by britannic124** [jsfiddle/jsfiddle-issues#1652]
The links for switching pages when viewing all (technically, since it’s a separate URL path from dashboard), titled, untitled, private, or public fiddles direct to `jsfiddle.net/user/dashboard/fiddles/[page number]/` instead of `jsfiddle.net/user/fiddles/[category]/[page number]/`. This doesn’t happen when viewing public profile (`jsfiddle.net/user/britannic124/fiddles/`).

I tested this on Safari, Version 14.0 (15610.1.28.1.9, 15610) on macOS Catalina, Version 10.15.7.

**Comment by emq** [comment]
@britannic124 thank you so much for reporting this! seems it has been some long-running issue; should be all good now!
