### ISSUE TITLE
Private fiddles still accessable via "/show"

### ISSUE THREAD

**Issue by ScamCast** [jsfiddle/jsfiddle-issues#1656]
On my private fiddles, I found that I was still able to access them via "/show"...

Tested in a private window

**Private:** `https://jsfiddle.net/<username>/<id>/<build>`
**Private:** `https://jsfiddle.net/<username>/<id>`
**Not Private:** `https://jsfiddle.net/<username>/<id>/<build>/show`
**Not Private:** `https://jsfiddle.net/<username>/<id>/show`

**Comment by emq** [comment]
@ScamCast thank you for reporting this, should be all fine now!
