### ISSUE TITLE
console.time uses apply incorrectly

### ISSUE THREAD

**Issue by MaxPRafferty** [jsfiddle/jsfiddle-issues#1657]
Steps to reproduce:
1) create a fiddle that contains `console.time('a')`
2) run the fiddle. The console will show the error `Uncaught TypeError: CreateListFromArrayLike called on non-object`

console.time is implemented as (around line 80 in https://fiddle.jshell.net/_display/?editor_console=true):
```
           time: function(label){
              pushToConsole(label, "log")
              systemConsole.time.apply(this, label)
            },
```
Apply's second argument should be an array, or `call` should be used:
```
           time: function(label){
              pushToConsole(label, "log")
              systemConsole.time.apply(this, [ label ])
            },
```
This can be proven by calling `console.time(['a'])` directly in the console - no error will occur.

Additionally, `console.timeEnd` is not implemented, making this function somewhat useless. Perhaps adjusting line 96 of the previous file from ` window.console = console` to `window.console = { ...window.console, ...console}` to preserve console functions that will not be or have not yet been implemented.

**Comment by KyleMit** [comment]
Relates to #1626

**Comment by oskarkrawczyk** [comment]
> Additionally, console.timeEnd is not implemented, making this function somewhat useless. Perhaps adjusting line 96 of the previous file from window.console = console to window.console = { ...window.console, ...console} to preserve console functions that will not be or have not yet been implemented.

Thanks for this, added to the codebase so the missing console methods are somewhat covered for now.
