### ISSUE TITLE
Tag Autocomplete error: <input></undefined> : Empty Tags 

### ISSUE THREAD

**Issue by Mafee6** [jsfiddle/jsfiddle-issues#1658]
Tag Autocomplete error: <input></undefined> : Empty Tags 
Pretty Straight-forward HEHE

**Comment by oskarkrawczyk** [comment]
Please provide more details and reproduction steps.

**Comment by PoolloverNathan** [comment]
Striking <kbd>&lt;</kbd> <kbd>/</kbd> when there are no elements left to close causes it to be replaced with `</undefined>` instead of being left as is.

**Comment by Mafee6** [comment]
> Tag Autocomplete error: : Empty Tags
> Pretty Straight-forward HEHE

Striking < / when there are no elements left to close causes it to be replaced with </undefined> instead of being left as is.
