### ISSUE TITLE
console and saving+running are both binded to 'Enter'

### ISSUE THREAD

**Issue by Matt07734** [jsfiddle/jsfiddle-issues#1659]
I'm not experienced with programming, so this might not be a real issue.
If Enter is pressed in the console, the page also automatically saves and runs, preventing me from using it at all.
[Just in case, here's the JSFiddle.](http://jsfiddle.net/b52c91tL/49/)

**Comment by oskarkrawczyk** [comment]
Browser and version?

**Comment by Matt07734** [comment]
Chrome, latest version 87.0.4280.88
