### ISSUE TITLE
Toggle Sidebar Hotkey broken

### ISSUE THREAD

**Issue by KyleMit** [jsfiddle/jsfiddle-issues#1663]
Toggle Sidebar Hotkey <kbd>Ctrl</kbd> + <kbd>T</kbd> is overridden by the browser default handling for *new tab*.

Is it possible to map to another command?  A common option is <kbd>Ctrl</kbd> + <kbd>[</kbd>

This is not addressed by the other three (old/closed) issues on the sidebar toggle

![toggle sidebar example](https://user-images.githubusercontent.com/4307307/102285723-d91e6900-3f04-11eb-9551-dd3cd5399135.png)

* [#43 Create a button to toggle Sidebar](https://github.com/jsfiddle/jsfiddle-issues/issues/43)
* [#41 Toggle Sidebar](https://github.com/jsfiddle/jsfiddle-issues/issues/41)
* [#213 Bottom to collapse configurations painel](https://github.com/jsfiddle/jsfiddle-issues/issues/213)

**Comment by KyleMit** [comment]
Here's a user script as a stop gap:

```js
let toggle = document.getElementById("toggle-sidebar")
document.addEventListener("keydown", (e) => {
    if (e.ctrlKey && e.keyCode == 219) toggle.click()
})
```

**Comment by oskarkrawczyk** [comment]
It appears this shortcut was never really implemented. Removing info about it from the tooltip for now.
