### ISSUE TITLE
A default branch other than master does not work with GitHub integration

### ISSUE THREAD

**Issue by Holayn** [jsfiddle/jsfiddle-issues#1665]
GitHub recently updated the default branch to be 'main' in new repositories. However, this does not work with GitHub integration.

### Reproducer - two identical repos, just different default branch:

https://github.com/Holayn/js-fiddle-test-main (default branch is main) - https://api.github.com/repos/Holayn/js-fiddle-test-main/contents works, but https://jsfiddle.net/gh/get/library/pure/Holayn/jsfiddle-test-main/contents does not.

https://github.com/Holayn/jsfiddle-test (default branch is master) - https://jsfiddle.net/gh/get/library/pure/Holayn/jsfiddle-test/contents works

**Comment by computamike** [comment]
Just ran into this problem myself.  It might be good if the documentation at least mentioned it. Really struggled with this.  Might see if I can update the documentation at least.

My scenario : Created a repo (default branch is main) - keeps failing.  Change default branch to master - all works (I only have 1 example, and 1 branch on my repo)
