### ISSUE TITLE
Document YAML fields in demo.details GitHub integration

### ISSUE THREAD

**Issue by Holayn** [jsfiddle/jsfiddle-issues#1666]
https://docs.jsfiddle.net/github-integration/untitled-1

The documentation lacks descriptions for all the accepted fields in the demo.details file

**Comment by comaldave** [comment]
There are two examples given. Both of them different and both are incorrect.

**Comment by computamike** [comment]
additionally there seems to be problems with default branch =/= master - i had to rename my default branch and it worked.
