### ISSUE TITLE
Unreasonable "Uncaught SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by alexNecroJack** [jsfiddle/jsfiddle-issues#1667]
Plain code, **even placed in comments**, throws exception "Uncaught SyntaxError: Invalid or unexpected token"
Code is
`$.get({
  url: 'https://enasmaragos.gr/temp/jquery_bug_report_file.js',
  cache: false
});
/*
.then(code => $('head').append('<script>'+code+'</script>')).catch((exc)=>{});
*/`
The exception hints at this part:
`')).catch((exc)=>{}); */ //]]>`

**Comment by oskarkrawczyk** [comment]
Please provide an example fiddle since it's hard to figure out what you mean.
