### ISSUE TITLE
JavaScript optional chaining syntax is marked as an error in the editor

### ISSUE THREAD

**Issue by Holayn** [jsfiddle/jsfiddle-issues#1668]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
![image](https://user-images.githubusercontent.com/3732034/103705889-d64deb80-4f79-11eb-947b-f081c6e6c808.png)

**Comment by oskarkrawczyk** [comment]
The Linter doesn't support optional chaining, once the library is updated I'll update JSFiddle to support it.
