### ISSUE TITLE
'Tabs (columns)' is replaced with 'Columns' view when new fiddle is opened

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1671]
Hey @oskarkrawczyk 

Recently I was changing the editor views and I got stuck with the 'Columns' view. 

Even though I change it to 'Tabs (columns)' each newly opened fiddle uses the 'Columns' view. It is not a major issue obviously but I found the 'Columns' view uncomfortable to use so I switch it each time when I load a new fiddle.

![image](https://user-images.githubusercontent.com/10757813/105147131-08765600-5b01-11eb-93d4-c98c3dcac1da.png)

I've tested this with a clean window and this is not a matter of cache.

Tested using Chrome 87, Firefox 84 on Windows 10.

**Comment by oskarkrawczyk** [comment]
Can you log in and test if the layout is retained? If that's the case use it as a workaround for now :)

**Comment by AMBudnik** [comment]
@oskarkrawczyk true. Being logged in can be treated as a solid workaround 👍

**Comment by AMBudnik** [comment]
An update here:
When I left a saved fiddle (not being logged in) in the Chrome tab and rerun the system I got my demo. But the view changed to the **'Columns'** even though I have saved it with the **'Tabs (columns)'**.

Not sure if that helps but that's another clue to the puzzle.
