### ISSUE TITLE
embed.js throws SCRIPT003: Expected ':' on Internet Explorer 11

### ISSUE THREAD

**Issue by hinok** [jsfiddle/jsfiddle-issues#1676]
Hey,
File `embed.js` contains invalid ES5 syntax.
It seems that this file is written in a way to support IE11.

<img width="1679" alt="Screenshot 2021-02-11 at 13 23 37" src="https://user-images.githubusercontent.com/1313605/107636041-5b5cac80-6c6c-11eb-9bf4-09f504a8d87e.png">

**Thrown errror**

```
SCRIPT1003: Expected ':'
embed.js (80,15)
```

<img width="1678" alt="Screenshot 2021-02-11 at 13 25 04" src="https://user-images.githubusercontent.com/1313605/107636177-8f37d200-6c6c-11eb-8cb0-adcc0b6b705c.png">

`embed.js`

```js
    window.parent.postMessage(
      [
        "embed",
        {
          slug: slug, // set in layout <!----------------------------- Should be like this
          height: height,
        },
      ],
      "*"
    );
```

**Comment by thomasaull** [comment]
I just noticed this aswell, it prevents viewing fiddles in IE11 😐️
