### ISSUE TITLE
CSS IntelliSense suggestions are virtually useless

### ISSUE THREAD

**Issue by stamminator** [jsfiddle/jsfiddle-issues#1679]
When typing a CSS property value, all known CSS values for _all_ properties are recommended in the intellisense regardless of which property it's for. See the below screen recording. When I type `table-layout`, the only options that should appear are `auto`, `fixed`, `inherit`, `initial`, and `unset`. Instead, I get _every known CSS value_. That's right: `absoulte`, `nowrap`, `capitalize`, anything you can imagine are in the results. What's the point of intellisense if it's just going to recommend everything all the time?

https://user-images.githubusercontent.com/10633170/109987025-435cd380-7cd4-11eb-8f7c-cabd306dd808.mp4

**Comment by aliceinspase** [comment]
> When typing a CSS property value, all known CSS values for _all_ properties are recommended in the intellisense regardless of which property it's for. See the below screen recording. When I type `table-layout`, the only options that should appear are `auto`, `fixed`, `inherit`, `initial`, and `unset`. Instead, I get _every known CSS value_. That's right: `absoulte`, `nowrap`, `capitalize`, anything you can image are in the results. What's the point of intellisense if it's just going to recommend everything all the time?
> 
> 
> 
> https://user-images.githubusercontent.com/10633170/109987025-435cd380-7cd4-11eb-8f7c-cabd306dd808.mp4
> 
> 
> 
>

**Comment by stamminator** [comment]
@aliceinspase You appear to have simply copied my post in your reply. Did you intend to add something?

**Comment by stamminator** [comment]
Issue still taking place

**Comment by stamminator** [comment]
Hey @oskarkrawczyk, any reason this was closed? The state of the CSS intellisense is still as I described. I don't think this behavior is by design.
