### ISSUE TITLE
Debugging fails more often that not

### ISSUE THREAD

**Issue by ShaCP** [jsfiddle/jsfiddle-issues#1687]
I have to refresh a bunch of times and it will randomly get fixed. This is how it will look if I place a debugger statement in my code and it doesn't work:

![image](https://i.ibb.co/N7FV5yn/jsfiddle.png)

Before I used to get source map warnings but I turned off "Enable JavaScript source maps" in the Chrome devtools settings and I don't get them anymore. But that didn't fix it.

**Comment by oskarkrawczyk** [comment]
This issue doesn't tell a whole lot about any issue in JSFiddle itself, from what I can tell it might as well be a debugger issue.

Need more details, a fiddle, etc.

Closing for now.
