### ISSUE TITLE
autoscroll won't let me work

### ISSUE THREAD

**Issue by minuscog** [jsfiddle/jsfiddle-issues#1690]
hello people from jsfiddle I want to report a problem when I make connections through your platform that every time we are doing something in any environment be it HTTM, CSS or JS it gives us the autoscroll.
Please if you know how to fix that, I would be grateful to you with my soul.
Thank you very much in advance

**Comment by oskarkrawczyk** [comment]
You'd have to provide more details, there's no autoscrolling in JSFiddle so I'm unsure what is this about.
