### ISSUE TITLE
Social media URLs need improvement

### ISSUE THREAD

**Issue by asheroto** [jsfiddle/jsfiddle-issues#1706]
### Medium:
If you have a subdomain set up on Medium, then the traditional `https://medium.com/username` will not work and return a 404 error. The same goes for users with custom domains.

**Example**: https://medium.com/asheroto
**Working URL**: https://asheroto.medium.com

### StackOverflow:
StackOverflow seems to have moved away from the URL scheme `https://stackoverflow.com/username` to several different URLs:

**Profile**: https://stackoverflow.com/users/11404332/asheroto
**Story**: https://stackoverflow.com/story/asheroto
**Traditional**: https://stackoverflow.com/cv/asheroto

The last two are from `Developer Story Preferences` while editing the user profile.

![image](https://user-images.githubusercontent.com/49938263/127747955-5521af39-7220-421c-8151-6817e42a39dd.png)

**Comment by oskarkrawczyk** [comment]
We've tried doing this before but the amount of changes in the codebase required to get it working along with random fiddle slugs is not worth the effort, since this is maybe the second request for this in years.
