### ISSUE TITLE
Tried today again and it isn't sending an password recovery email

### ISSUE THREAD

**Issue by danimesq** [jsfiddle/jsfiddle-issues#1710]

**Comment by DaniellMesquita** [comment]
@oskarkrawczyk this is urgent

**Comment by DaniellMesquita** [comment]
![Screenshot from 2021-08-18 17-40-16](https://user-images.githubusercontent.com/6765277/129969224-34a93571-4d04-421b-b9d7-85f93a9028a8.png)

**Comment by uscribble** [comment]
Same for me. New signup today (a few hours ago), mixed up something with my password manager. Two password reset attempts and still have not received any email.

**Comment by garrettcombes** [comment]
Same here. Tried this yesterday and today. Not receiving a reset email.

**Comment by danimesq** [comment]
Stale? Unsolved.

Dupliced: https://github.com/jsfiddle/jsfiddle-issues/issues/1801

**Comment by danimesq** [comment]
@oskarkrawczyk @zalun

**Comment by tokyorachel** [comment]
Also having this issue. Email accounts with both gmail and mailbox.org have not received the password reset emails after several hours.

**Comment by mvandemar** [comment]
Same, multiple attempts, 0 emails.

**Comment by mahop-net** [comment]
Same for me

**Comment by nasif-co** [comment]
Same problem :(

**Comment by amk221** [comment]
Same problem
