### ISSUE TITLE
Problem, files are lost.

### ISSUE THREAD

**Issue by VirtualD3** [jsfiddle/jsfiddle-issues#1715]
Last year I had no problems, but today I had a couple of problems. I have saved a javascript job and it has disappeared, I have saved another job associated with a group and when I search for it by group, when I open the file it shows me empty, if I open the file from jobs if it opens well (I think it has to be a problem with groups).
I'm sorry but I have had to unsubscribe, I cannot put my work at risk.
I am also sorry for my English.

**Comment by Wohoo961** [comment]
Try again today. if it doesn't work, wait until next year.
if it still doesn't work in 2023, sorry. This may be a glitch.
There are other issues too. Not just this one. Example: Fiddle preview on dashboard doesn't work.
