### ISSUE TITLE
Load Type selection missing

### ISSUE THREAD

**Issue by jgasiorowski** [jsfiddle/jsfiddle-issues#1717]
Hello, I've just tried to use jsfiddle and I cannot find documented option to select Load Type:
![image](https://user-images.githubusercontent.com/5520607/139249944-b5c72ede-994a-4138-b7ee-e7f3abb6b4fd.png)
has that been moved somewhere?

**Comment by xiapeggy** [comment]
Same. Cannot find load type anywhere
