### ISSUE TITLE
Private fields and private methods support

### ISSUE THREAD

**Issue by lobau** [jsfiddle/jsfiddle-issues#1718]
If you write this valid ES6 code in JSFiddle, you get tons of errors

```
class Mosaic {
  #count;
  #view;
  constructor(div) {
    this.#view = document.getElementById(div)
  }
  set videoCount(count) {
    this.#count = count;
    this.#update();
  }
  get videoCount() {
    return this.#count;
  }
  #update() {
  	const result = `<h1>${this.#count}</h1>`;
  	this.#view.innerHTML = result;
  	console.log(this.videoCount);
  }
}

const mosaic = new Mosaic('container')
mosaic.videoCount = 2;
```

![image](https://user-images.githubusercontent.com/6750584/139497168-53f07332-f820-418a-bd4c-12b459b5ff7e.png)

That's because JSFiddle does't understand the # used for private fields and private methods.
https://github.com/tc39/proposal-private-fields/issues/14

**Comment by D-00-python** [comment]
The error stills occurs. Please reopen this issue
