### ISSUE TITLE
Feature request: Smooth Caret

### ISSUE THREAD

**Issue by UnrealApex** [jsfiddle/jsfiddle-issues#1724]
It would be nice if JSFiddle had smooth caret like this:
![image](https://user-images.githubusercontent.com/79121360/142796426-488617c0-cffe-45a3-9e15-3a95a7516f79.png)
![image](https://user-images.githubusercontent.com/79121360/142796436-6d33d4d1-55a6-4e10-a62f-09ae0068a246.png)
![image](https://user-images.githubusercontent.com/79121360/142796447-643f0449-434a-476a-9c38-fb4b131c83de.png)

**Comment by oskarkrawczyk** [comment]
This cannot be done in the version of CodeMirror we're using. Sorry.
