### ISSUE TITLE
JSfiddle loading too long

### ISSUE THREAD

**Issue by Wohoo961** [jsfiddle/jsfiddle-issues#1728]
Guys, I just made a new fiddle about my HTML Homepage. But when I came to my dashboard, it wasn't loading shortly.
Guys, please help me solve this problem. Now I can't delete my fiddle.

**Comment by oskarkrawczyk** [comment]
See if disabling rendering helps in removing the broken fiddle – https://github.com/jsfiddle/jsfiddle-issues#common-questions
