### ISSUE TITLE
Can't embed JSFiddles on website

### ISSUE THREAD

**Issue by sszczep** [jsfiddle/jsfiddle-issues#1729]
Adding script tag with JSFiddle results in error: `Refused to display 'https://jsfiddle.net/' in a frame because it set 'X-Frame-Options' to 'sameorigin'`. Because of that, frames do not render.

It only occurs in chromium-based browsers, works normally on Safari.

Live demo: [https://www.sszczep.dev/blog/ray-casting-in-2d-game-engines/](https://www.sszczep.dev/blog/ray-casting-in-2d-game-engines/). 

cc: @oskarkrawczyk

**Comment by sszczep** [comment]
Not stale

**Comment by sszczep** [comment]
Not stale

**Comment by sszczep** [comment]
Not stale

**Comment by Piotr-Aueternum** [comment]
Not stale

**Comment by schtauffen** [comment]
I came here as I noticed it on the same site as post author.

This is gross but am currently using this to view examples:
```js
const iframes = document.querySelectorAll("iframe");
Array.prototype.forEach.call(iframes, el => {
    const link = document.createElement("a");
    link.href = el.src;
    link.target = "_blank";
    link.innerHTML = "link";
    el.parentNode.appendChild(link);
});
```

**Comment by sszczep** [comment]
Not stałe

**Comment by sszczep** [comment]
Not stale

**Comment by ronykris** [comment]
Even I'm facing the same issue can I get some help?

**Comment by sszczep** [comment]
Not stale

**Comment by XmlmXmlmX** [comment]
This is still a problem
