### ISSUE TITLE
Clipboard API will not work

### ISSUE THREAD

**Issue by aetinx** [jsfiddle/jsfiddle-issues#1732]
Clipboard API will not work anymore for cross-origin frames on Chrome. I'm using Chrome 98.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/65425469/150446115-b2984a15-3b99-4db3-8dba-67a50931ab4b.png">

Edit: Chrome 97 not Chrome 98. Oops!

**Comment by aetinx** [comment]
You might want to use this:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/65425469/150525865-0fbf1746-891e-4df7-9bc0-ccacbc385337.png">

**Comment by aetinx** [comment]
> > You might want to use this:
> > <img alt="image" width="385" src="https://user-images.githubusercontent.com/65425469/150525865-0fbf1746-891e-4df7-9bc0-ccacbc385337.png">
> 
> Do you have an example of a fiddle where the permissions for the clipboard API work correctly? I'm also having issues with this inside a fiddle.

Sadly, I haven't been able to find something where the Clipboard API works in JSFiddle.

**Comment by oskarkrawczyk** [comment]
This flag is something I need to add in the results panel of JSFiddle, not something you can add yourself.
