### ISSUE TITLE
Blank white area on screen in JSfiddle

### ISSUE THREAD

**Issue by jbeschler** [jsfiddle/jsfiddle-issues#1733]
Hi,
Just signed up as supporter. 

I have noticed that when I use the console on JSFiddle, there is a HUGE blank white area above the Console area. It appears to be close to the size of the actual console area.

I am running:
Windows 10 version 20H2
Chrome browser version Version 97.0.4692.71 

Thanks,

**Comment by oskarkrawczyk** [comment]
Please provide a screenshot, as I cannot figure out what you're seeing. Thanks

**Comment by jbeschler** [comment]
Here ya go.


[image: jsfiddless.png]

John Beschler

Nothing is ever lost by courtesy. It is the cheapest of pleasures, costs
nothing, and conveys much. *– Erastus Wiman*

If god intended us to be thin he would not have given us chocolate cake and
ice cream!
