### ISSUE TITLE
All fiddles that use "Vue (edge)" have stopped working.

### ISSUE THREAD

**Issue by AdmiralPotato** [jsfiddle/jsfiddle-issues#1735]
All fiddles that use the "Vue (edge)" Frameworks & Extensions option have stopped working.

![image](https://user-images.githubusercontent.com/820844/152918768-5088d937-0705-4a27-8361-4f04a5de6210.png)

When "Vue (edge)" is selected, the child frame adds a script with a source of `https://vuejs.org/js/vue.js`, but since the recent official transition from Vue v2 to v3, that link is now broken.

I would propose that all existing fiddles currently using the "Vue (edge)" option should instead be changed to use the latest from the v2 series, and that there should not be an "edge" option, but "Vue 3 (latest)" option, so that if Vue 4 comes around, all fiddles built for Vue 2 and Vue 3 keep working, and the new option is simply added to the list.

These are the URLs I would use instead, since the `vue@2`  address is what is referenced in the Vue 2 documentation:

`https://cdn.jsdelivr.net/npm/vue@2`
`https://cdn.jsdelivr.net/npm/vue@3`

Reference: https://v2.vuejs.org/v2/guide/installation.html#CDN

Fiddles which pull their own Vue from the resources panel on the left are not effected.

**Comment by isuke01** [comment]
Yep, also just Boilerplate VUE have same problem.

**Comment by TheJaredWilcurt** [comment]
Still broken
