### ISSUE TITLE
Connection timeout in China, are you using geoip-block, or is it the Great Firewall?

### ISSUE THREAD

**Issue by zypA13510** [jsfiddle/jsfiddle-issues#1737]
Hello, we've been having this issue for several years iirc, jsfiddle times out when accessed from China, but it works just fine elsewhere. I have always thought that it is the Great Firewall blocking jsfiddle.net. (But it doesn't make sense to me, what could jsfiddle do to annoy the Chinese government?)

However, recently I realized that jsfiddle is using Digital Ocean, and all my other Digital Ocean droplets are accessible from China just fine. So could it be that you have configured some geoip-blocking? I can't know for sure, just wish to confirm.

If that's the case, any chance you would consider lifting such restrictions? Can we consider some other abuse prevention techniques?

**Comment by oskarkrawczyk** [comment]
Hi, we've restricted China access to JSFiddle due to the amount of spam and scam created on our service coming from that region – nearly every fiddle created was crypto scam, propaganda, etc.

**Comment by zypA13510** [comment]
@oskarkrawczyk But you are blocking legitimate users as well. I, for one, though not a very frequent user, don't think I have done anything bad. And now I have to circumvent your restriction or to use another service like codepen.

Like I said, just a suggestion, would you consider abuse prevention other than outright blocking all Chinese users? E.g. maybe you can add captcha for suspicious IP, disable anonymous snippet creation (thus forcing account creation which may cost more effort from the spammers and also easier to ban), and I'm sure there're more options we can explore?

**Comment by adoin** [comment]
> @oskarkrawczyk But you are blocking legitimate users as well. I, for one, though not a very frequent user, don't think I have done anything bad. And now I have to circumvent your restriction or to use another service like codepen.
> 
> Like I said, just a suggestion, would you consider abuse prevention other than outright blocking all Chinese users? E.g. maybe you can add captcha for suspicious IP, disable anonymous snippet creation (thus forcing account creation which may cost more effort from the spammers and also easier to ban), and I'm sure there're more options we can explore?

歧视中国而已，国内的骗子早转移到国外了，全世界没有像中国一样甚至有反诈app的，找个由头歧视一下，所以换别的用就好了。jsrun 啥的不挺多的

**Comment by adoin** [comment]
> @oskarkrawczyk But you are blocking legitimate users as well. I, for one, though not a very frequent user, don't think I have done anything bad. And now I have to circumvent your restriction or to use another service like codepen.
> 
> Like I said, just a suggestion, would you consider abuse prevention other than outright blocking all Chinese users? E.g. maybe you can add captcha for suspicious IP, disable anonymous snippet creation (thus forcing account creation which may cost more effort from the spammers and also easier to ban), and I'm sure there're more options we can explore?

歧视中国而已，国内的骗子早转移到国外了，全世界没有像中国一样甚至有反诈app的，找个由头歧视一下，所以换别的用就好了。jsrun 啥的不挺多的

**Comment by zypA13510** [comment]
> > @oskarkrawczyk But you are blocking legitimate users as well. I, for one, though not a very frequent user, don't think I have done anything bad. And now I have to circumvent your restriction or to use another service like codepen.
> > Like I said, just a suggestion, would you consider abuse prevention other than outright blocking all Chinese users? E.g. maybe you can add captcha for suspicious IP, disable anonymous snippet creation (thus forcing account creation which may cost more effort from the spammers and also easier to ban), and I'm sure there're more options we can explore?
> 
> 歧视中国而已，国内的骗子早转移到国外了，全世界没有像中国一样甚至有反诈app的，找个由头歧视一下，所以换别的用就好了。jsrun 啥的不挺多的

Yes, to be honest it is quite racist.
