### ISSUE TITLE
Adding aspect-ratio as supported property

### ISSUE THREAD

**Issue by IJuanTM** [jsfiddle/jsfiddle-issues#1749]
Hi,

The css property; 'aspect-ratio' is available on all major browsers since 2021, but jsfiddle still marks it as 'unknown'.

[Can I Use](https://caniuse.com/mdn-css_properties_aspect-ratio)

Maybe you could add it to the supported properties?

Thanks!

**Comment by ditsuke** [comment]
I think this is yet unsolved.

**Comment by brandonryan** [comment]
bump
