### ISSUE TITLE
Template literal breaking syntax highlighting

### ISSUE THREAD

**Issue by andyewen** [jsfiddle/jsfiddle-issues#1756]
I have a fiddle with JavaScript that uses a template literal. The syntax highlighter doesn't seem to recongnise the end of the literal and keeps highlighting the rest of the code in red.

This fiddle demonstrates the issue: https://jsfiddle.net/xzpmsL12/3/.

![image](https://user-images.githubusercontent.com/7320424/167842314-4a041bc3-fe0f-4766-90b6-3bc10b56cbe5.png)

**Comment by acharbonnet** [comment]
The problem appears to be with line 4
![2022-05-28 101927](https://user-images.githubusercontent.com/65929869/170833861-e38bdf86-25d9-4c21-bc14-59c9c7ae17fc.png)
![2022-05-28 102218](https://user-images.githubusercontent.com/65929869/170833953-30e3a2af-c7fc-4bb7-b82d-0f7d7e334cd9.png)
When I remove the nullish coalescing operator "?? 'Bob'" the syntax highlighting error goes away. Which is still an issue, but I hope this helps someone solve the problem.
