### ISSUE TITLE
Caret Insertion Indicator moves over window with scroll wheel, on IPAD Pro 5th Gen IOS 15, Safari and Chrome

### ISSUE THREAD

**Issue by nmecodes** [jsfiddle/jsfiddle-issues#1759]
The rendering of the lines and cursor position has issues where lines will over lap, and the cursor moves in front of the display when scrolling.

https://user-images.githubusercontent.com/8404873/168100395-c49721a8-a106-46eb-a944-def3c8fcaf39.MOV

**Comment by Kingkhalifa195** [comment]
Can I get more explanation

**Comment by nmecodes** [comment]
More explanation? I think the video says it all, but here goes…

On the most recent IPADOS or in fact any version since 14.x to 15.x and up from what I can see, your interface is buggy.

The caret insertion indicator for typing hovers over what I’ve been calling the “Run” window/iFrame when you use the scroll wheel.  Just look at the video.


Other bugs I can report individually:
-The scroll wheel freezes once in a while after the code is autosaved, forcing you to use the up and down keys to navigate through the code to get it to scroll up.  I’ve tried this on other systems too, but it’s most prevalent on the IPAD in Safari or Chrome in my experience.

-The entire site doesn’t show the bottom, and often hides the console window/iframe

I am using a keyboard with my IPAD on the latest IPadOS release.
