### ISSUE TITLE
allow jsfiddles to be parameterized by url get parameters

### ISSUE THREAD

**Issue by krosaen** [jsfiddle/jsfiddle-issues#176]
jsfiddles are a great way to show how to properly make use of an api. Rather than having the api endpoint hardcoded in the demo, it would be great if the jsfiddle itself as paramterized by a resource id, and then the jsfiddle could access the url get parameters and automatically show an example using the particular resource.

Concretely, here is a demo of using a menu api:

http://jsfiddle.net/fJhLe/1/

you can see the demo fetched the menu for restaurant id 5119151. I would like to be able to customize the demo to show a different menu, so for example, 

http://jsfiddle.net/fJhLe/1?menuid=4945073

could show the demo for menu id 4945073. Instead, I need to fork it and manually replace the id:

http://jsfiddle.net/m2SMk/1/

If the fiddle parameterization were possible, I could show each restaurant a demo using their menu data simply by linking to the fiddle with the appropriate id set (obviously the fiddle would need to be aware that it was being parameterized and adjust accordingly).

I tried accessing the url directly via window.parent.location but since the iframe is running on a different subdomain, this doesn't work.

**Comment by NathanWailes** [comment]
@zalun Was this ever actually completed? I can't figure out how to do it.

**Comment by mkarpicki** [comment]
Interesting, till today I though it is supported actually. I vote up for this feature to get on backlog if possible :)
