### ISSUE TITLE
Serious performance issues

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1760]
Hi @oskarkrawczyk 

Recently I'm having those issues with the overall performance of JSFiddle. I've asked my colleagues to jump in and test it and it seems to jam only for me. I was trying to find a pattern but it seems that there's any - without the fact that I'm using our library - Handsontable.

Here's a gif of all those awaiting times that I got while trying to run a simple demo https://jsfiddle.net/vuLbftnw/3/ 

![Kapture 2022-05-26 at 11 18 22](https://user-images.githubusercontent.com/10757813/170458871-fb704941-f124-437a-866e-26a2d85e6855.gif)

When I wanted to click the `Save` button screen went black and the browser crashed.

![Screenshot 2022-05-26 at 11 23 10](https://user-images.githubusercontent.com/10757813/170459105-923f2a9e-d3e0-4c98-a8ee-3c7736f55a58.png)

*I'm on* Chrome 101, macOS Monterey, using no special addons or browser zoom

**Comment by johnnygodeep** [comment]
I'm deeply appreciating your casual transparency and lack of attachment and concern. I can't help but presume your monologue is tongue in cheek,by that you must realize how funny you are, however,if you are simply that dry you're a riot and if you're ever in Boston (MA) or Richmond (VA) drop me a message I would love to drink sone beers with ya.
