### ISSUE TITLE
Babel + JSX config does not work (Uncaught SyntaxError: Unexpected token '<')

### ISSUE THREAD

**Issue by warpech** [jsfiddle/jsfiddle-issues#1773]
Some time this week our Babel + JSX fiddles stopped working. For example:

- https://jsfiddle.net/warpech/e9bty8xr/ (this one is mine, worked last week)
- https://jsfiddle.net/warpech/h81vnqbL/ (this is the simplest one I can think off)
- https://jsfiddle.net/js_ziggle/a85dnhc0/ (another one)

The error that I get is:

```
Uncaught SyntaxError: Unexpected token '<'
```

<img width="1904" alt="Screen Shot 2022-08-01 at 4 22 11 PM" src="https://user-images.githubusercontent.com/566463/182169177-732ec442-780b-419c-996f-458a65151b78.png">

**Comment by rwojsznis** [comment]
Well, that's embarrassing; thank you for reporting this @warpech <3 we have replaced babel compiler recently at it seems previous version used slightly different set of plugins that required react - in order not to break anything we adjusted recently rolled out changes - could you give it a go now please?

**Comment by warpech** [comment]
Yes, it works now. Thanks for being so awesomely quick!
