### ISSUE TITLE
Solved: Server timeout

### ISSUE THREAD

**Issue by slingtruchoice** [jsfiddle/jsfiddle-issues#1791]
I believe the whole site is down currently. Sorry if this is not a good place for this notification. 

Server timeout, on Firefox, Chrome and Safari. ~1:40pm EST. 

![Screen Shot 2022-10-25 at 1 42 40 PM](https://user-images.githubusercontent.com/112584707/197844830-f666d9cc-1618-4bb6-9974-5eb07e98073a.png)
![Screen Shot 2022-10-25 at 1 42 45 PM](https://user-images.githubusercontent.com/112584707/197844834-4a3dda3f-f411-4365-9138-ba43f522d705.png)

**Comment by coder0107git** [comment]
I'm having this problem too.

**Comment by slingtruchoice** [comment]
issue has resolved for me.

**Comment by coder0107git** [comment]
Okay. I just checked and confirmed it does work for me now.
