### ISSUE TITLE
the jsfiddle base URL is showing the oldest version, instead of base version

### ISSUE THREAD

**Issue by marcoyfkwok** [jsfiddle/jsfiddle-issues#1814]
version 1:
https://jsfiddle.net/marcoyfkwok/zd385L6k/1
![image](https://github.com/jsfiddle/jsfiddle-issues/assets/8841524/64b16046-d8f9-475d-9242-5fd7c8f0afe8)

version 4: (set as base)
https://jsfiddle.net/marcoyfkwok/zd385L6k/4
![image](https://github.com/jsfiddle/jsfiddle-issues/assets/8841524/888b7739-a142-43e9-9092-c269e1f72b03)

base version URL:
https://jsfiddle.net/marcoyfkwok/zd385L6k/
![image](https://github.com/jsfiddle/jsfiddle-issues/assets/8841524/8838e2ec-06a3-4ed8-8f80-be2022b99559)

**Comment by rwojsznis** [comment]
Sorry for the hiccups folks and thank you for reporting this; over the weekend we were running massive data migrations and seems like a regression made it's way into the codebase; please take a look now 🙏

**Comment by artf** [comment]
Thanks @rwojsznis looks to be fixed ❤️
