### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by vsvetoslavov** [jsfiddle/jsfiddle-issues#1815]
Hello

Going to _Your fiddles_ (https://jsfiddle.net/user/fiddles/all/) produces error 500

> 500
> 
> Oops. This shouldn't have happened.

Same for _Settings_ https://jsfiddle.net/user/settings/profile/

Here is my most recent fiddle, which produces the same error. Since I am unable to browse my fiddles I can't check if any other is working:
https://jsfiddle.net/nupkc/w46eutnc/

**Comment by rwojsznis** [comment]
We're having a global outage 😬  will keep you posted!

**Comment by ElMoonLite** [comment]
Yup same here. Also can't see my overview of fiddles.
However I seem to be able to open some of my fiddles but not all of them. If I click a few bookmarked fiddles I get the same 500 error for some but others work.

Also, when I try to save a new fiddle a little blue loading bar shows up at the top of the page, takes about a minute to complete, and then nothing happens.

**Comment by rwojsznis** [comment]
Issue resolved ☺️

**Comment by vsvetoslavov** [comment]
Thanks @rwojsznis for the update! I suspected something like that was going on, actually I meant this issue more like a report for the outage. Great news that all has been resolved and thanks for the hard work! :)

**Comment by ElMoonLite** [comment]
Huzzah! Everything seems to work again. :)

Hmm if you need to do massive migrations, perhaps next time set up a static maintenance.html and point all traffic there for the duration. That is more clear for users and prevents messing up resources and possibly data while users make request attempts.

Things like this make me scared. I should probably export and backup all my jsfiddles... about 140 by now... 
Some quite monolithic and some I still use quite often. Is there a way to export all fiddles at once?
The API only seems to show a list of fiddles, not fiddle content.

Is there a jsfiddle discord? forum? irc? Anything where jsfiddle users can talk to the community and solve problems between users? Somehow I completely fail to find any way to communicate with other jsfiddle users...

Also... I probably shouldn't put 4 different topics in one post, some of which are hardly relevant to the thread :'D
If only I knew where to talk about stuff.

**Comment by ElMoonLite** [comment]
Ah one of those migrations... I feel your pain. Or at least mild anxiety.

Yay backups! Though that might not secure recent data, as active data being saved etc. is still somewhat in jeopardy, being in limbo between client and server. e.g. My recent near data loss was mostly user error; making too much at once in one jsfiddle window, trying to save, and almost closing the window before realizing the save never worked :'D

Ooh, I would love a download all. I'm a sucker for always making my own "local" backups of everything.
That seems more fun than clicking all 100 fiddles and hitting ctrl-c ctrl-v about 500 times for all fiddles with all fields.

Aww I remember small teams... When business is doing good and it grows that is all good and well but the added bureaucracy is a major pain. Then again, if stuff is on fire, I'm no longer the person they call in the middle of the night :D 
I see how managing and moderating community posts could be painful. Even though you learn to understand that is just what happens, it still surprises me if so much spam profanity trolling and outright evil creeps into positive creative spaces. sad.

I used to say "anything I can do to help?" but work and being a dad these days hardly leaves me room to make promises like that. Still, happy to help and give back, from a happy jsfiddle user for many years.

I can give you all a big thank you for all the good work you do and have done. It's mostly been stable, and it always just works without needing to figure a ton of stuff out (from my perspective anyway). I love how jsfiddle is one of the few gems that still holds on to a more simple ui and not falling for the 'it has to do everything' hype that swallows up almost everything these days. And though the front end might look simple, I bet a lot of work is going on in the backend to keep everything running smoothly. Kudos to the entire team... which looking at https://jsfiddle.net/about seems like only two. Yikes. Even more respect keeping it running all this time :D
