### ISSUE TITLE
So slow to save action

### ISSUE THREAD

**Issue by nightow** [jsfiddle/jsfiddle-issues#1839]
![캡처nn](https://github.com/jsfiddle/jsfiddle-issues/assets/26591435/064c489c-199d-4645-9e0b-05c752a7c891)

**Comment by AMBudnik** [comment]
I don't work for me at all :/ no save no fork

**Comment by adrianszymanski89** [comment]
I can confirm this issue. Saving sometimes works, but I can't fork any of the projects.

**Comment by rwojsznis** [comment]
Note to self: features work better when they do not crash.

Please do take another try, issue should be solved now, sorry for the hiccups!

**Comment by AMBudnik** [comment]
It's confirmed, works well now. Thanks @rwojsznis :)
