### ISSUE TITLE
Add support to TypeScript

### ISSUE THREAD

**Issue by jWorker** [jsfiddle/jsfiddle-issues#227]
Is it possible to add support to TypeScript? Or is it already being done?

**Comment by baloodevil** [comment]
Why was this issue closed?  As far as I can tell, jsfiddle doesn't support TypeScript yet.  +1 vote.

**Comment by oskarkrawczyk** [comment]
No plans on supporting TypeScript in this version of JSFiddle. We'll have it in the future version - complete rewrite. Sorry.

**Comment by baloodevil** [comment]
Thanks for quick response.  I'll look forward to v next!  CodePen has
TypeScript support, but jsfiddle is preferred by many, including me.  Good
luck with the rewrite.

**Comment by oskarkrawczyk** [comment]
Thanks!

**Comment by kaatula** [comment]
Do you guys have any time estimations on mentioned rewrite?
I'm asking because I really prefer JSFiddle but - from time to time - really suffer from lack of TypeScript, as that is my production language...

**Comment by oskarkrawczyk** [comment]
@kaatula Q1 2016

**Comment by kirjs** [comment]
Let me know if you need any help with adding typescript.
