### ISSUE TITLE
Not possible to delete my account fully

### ISSUE THREAD

**Issue by skotchio** [jsfiddle/jsfiddle-issues#237]
I have a right for full deleting my account with all my feeds (include public). Please provide that feature in your service.

**Comment by sebastianbauer** [comment]
Would be great if it just would work. Two mails. Zero replies.

**Comment by alex-jitbit** [comment]
This screams for GDPR lawsuit

**Comment by oskarkrawczyk** [comment]
Instead of pulling the GDPR scare tactic like a little internet troll simply log in and delete your profiles from settings - it's right there to be used.

Also, all deletion requests coming via email are granted, might take 30 days though.

I consider this topic closed, and so is the issue.
