### ISSUE TITLE
Keyboard shortcut to comment line

### ISSUE THREAD

**Issue by AgDude** [jsfiddle/jsfiddle-issues#248]
A keyboard shortcut to 'comment' selected lines would be a very useful feature.  My suggestion is cntrl+/.

**Comment by thetroublemaker** [comment]
This is great however the shortcut creates an HTML comment, any chance of doing the same of the JS block?

**Comment by altrae** [comment]
Any update on this? This seems to have been an issue now for over three years.

**Comment by kmohanraj** [comment]
fdxgdf

**Comment by ukallika** [comment]
asd
