### ISSUE TITLE
HTML code auto-complete produces invalid closing tags

### ISSUE THREAD

**Issue by ghost** [jsfiddle/jsfiddle-issues#266]
Apologies if this tracker should be used for issues about the documentation and not jsfiddle itself, it seemed ok.

The new HTML code auto-complete produces end tags that don't make sense and are invalid:

```
<input></input>
<img></img>
<br></br>
<link></link>
 <!-- etc. -->
```

Using XHTML self-closing syntax such as `<input />` or `<img />` works fine and doesn't produce the unnecessary closing tag.

I personally don't think the end tags should appear automagically even when they are valid (maybe I will change my mind later), but at least the obvious self-closing tags should be ignored. I realize there may be differences with different doctypes, so maybe that should be considered?

**Comment by humbleRumble** [comment]
When using the HTML4/HTML5 doctype and not using self closing flags the automatic indentation does not function correctly. As well it will highlight the not matching end tag in red. Perhaps a filter for area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track and wbr ([HTML5 specification](http://www.w3.org/TR/html-markup/syntax.html#syntax-elements)) would help solve the issue?
