### ISSUE TITLE
,{ sequence causes line wrapping/cursor positioning glitch

### ISSUE THREAD

**Issue by grahamsnyder** [jsfiddle/jsfiddle-issues#274]
#### Steps to reproduce
1. Type a long line of code including the sequence `,{` in the js pane (see [here](http://jsfiddle.net/grahams/Pnu3U/)).
2. Click somewhere in the line after the wrap to position the cursor, and start typing.

#### Expected behaviour
1. Line wraps.
2. Cursor is positioned at the point in the text that was clicked.
3. Typed text appears at the cursor.

#### Result
1. Line wraps before `{`.
2. Cursor appears at the point clicked, even if this is in empty space after the wrap.
2. Typed text appears in a different position - the place in the line that would have been at the cursor if the line had wrapped at full width.

**Comment by lankymart** [comment]
Why do you keep closing this issue with no explanation, is it fixed? Find it really poor just closing it without explaining why.

**Comment by oskarkrawczyk** [comment]
Archiving this task for now since there are not plans on fixing this in the current version of JSFiddle.
