### ISSUE TITLE
Where are the jsHint hints now?

### ISSUE THREAD

**Issue by sparky672** [jsfiddle/jsfiddle-issues#300]
When the JS is invalid, I can see the red dots to the left, but hovering, clicking, on them does absolutely nothing.  Prior to maybe a week ago, I used to be able to see a hint by hovering them.

Seeing this issue in Firefox, Chrome, Safari.

**Comment by mwils-bp** [comment]
I have this problem across all browsers too (Firefox, Chrome, Safari).

**Comment by oskarkrawczyk** [comment]
The issue is not browser related.

**Comment by mwils-bp** [comment]
I see, so this has been an issue for quite a while then? Any idea when it could be likely fixed?

I've had this issue continuously for the past couple days...

**Comment by holroy** [comment]
I get the dot, but no explanation. Is this normal behaviour, or is it broken again?

**Comment by MarkSchultheiss** [comment]
I see this has been closed but the public site still has this issue.  Is this no longer being supported or is the issue still in need of repair? (used chrome 46)  It was a nice feature :)

**Comment by aindriu80** [comment]
where is jshint ?
