### ISSUE TITLE
2 space indentation

### ISSUE THREAD

**Issue by darthdeus** [jsfiddle/jsfiddle-issues#314]
It would be awesome if we could chose if we want 4 or 2 character indentation, since a lot of people (especially those coming from Ruby) are in favor of using 2 spaces.

**Comment by robhawkes** [comment]
+1

This is a major reason why I tend to use JSBin over JSFiddle at the moment. It's such a faff having to manually change to 2-space indentation.

**Comment by ryanpcmcquen** [comment]
Sign me up for this too.  :+1:

**Comment by dbackeus** [comment]
+1

**Comment by redconfetti** [comment]
![image](https://cloud.githubusercontent.com/assets/746759/8136966/e218f35c-10f4-11e5-81fb-d3ee946a5ce4.png)

**Comment by redconfetti** [comment]
![image](https://cloud.githubusercontent.com/assets/746759/8137019/36fa84d0-10f5-11e5-8a04-f75e36563849.png)

**Comment by boeserwolf** [comment]
+1

**Comment by redconfetti** [comment]
Just a note, I just realized that this functionality could be enforced by [editorconfig](http://editorconfig.org/) although not validated and raising an error during a build / continuous integration process.

**Comment by alexserver** [comment]
+1

**Comment by ryanpcmcquen** [comment]
It has arrived!!!!! :tada:

**Comment by wizzwizz4** [comment]
How do you change back to 4 space?
