### ISSUE TITLE
vertical panes stuck overlapping, Chrome only

### ISSUE THREAD

**Issue by albell** [jsfiddle/jsfiddle-issues#349]
A couple days ago, (Chrome on Mac) I accidentally moused on the vertical divider, and dragged it over to the left. I discovered this when the js and results rendered superimposed. Baffled, I switched to Canary, and moved on. But now I want to fix this, because it's hobbling, and I don't want to always be switching over to Canary or FF. I've dumped the cache and restarted a few times, and I simply can't move the divider back. Is it possible there's some internal setting that's gotten either stuck or corrupted?

![Screen Shot 2013-03-19 at 3 34 22 PM](https://f.cloud.github.com/assets/1142025/278464/81bb50f8-90e6-11e2-9d7a-5d2c2c12d97a.png)

**Comment by maxsilbert805** [comment]
I registered just to say thank you so much. I dislike having to open up firefox just so I can use jsfiddle and I had no idea how to fix it. Thanks!

**Comment by tkrotoff** [comment]
This problem just happened to me, don't know what causes it (was working in incognito mode)

**Comment by littlej247** [comment]
Thank you!
