### ISSUE TITLE
Warning tooltips obscure code

### ISSUE THREAD

**Issue by mkantor** [jsfiddle/jsfiddle-issues#373]
Warning tooltips (for things like *"No need for the HTML tag, it's already in the output."*) stack on top of the code, making it difficult to correct the problems the tooltips are warning you about. This is especially true of the HTML tag warning, since `</html>` will almost always be hidden underneath it.

![Warning tooltip example](http://i.imgur.com/GXMNB5B.png)

Having the warnings appear outside of the scrollable code area could be a nice alternative:

![Mockup of non-obscuring tooltips](http://i.imgur.com/bgjGQS0.png)

**Comment by Davidj361** [comment]
+1

**Comment by xDarkShadowKnightx** [comment]
+1 :)

**Comment by JasonHine** [comment]
+1

**Comment by oskarkrawczyk** [comment]
Messed something up during the code mirror update. Will fix.

**Comment by fipp** [comment]
Has this been looked into any more?

**Comment by lf94** [comment]
+1, 2 years since issue was filed, please implement this! :)

**Comment by oskarkrawczyk** [comment]
`+1` doesn't change a thing. This isn't going to be changed in this version of JSFiddle.
