### ISSUE TITLE
Add allowfullscreen attributes to iframe

### ISSUE THREAD

**Issue by yeldarby** [jsfiddle/jsfiddle-issues#374]
I'd like to request that the `allowfullscreen`, `mozallowfullscreen`, and `webkitallowfullsreen` attributes be added to the jsfiddle result iframe.

This will allow using the html5 fullscreen api within the iframe.

I'm trying to test cross browser support for the apis and the iframe doesn't have permission to request their use.

Edit: here's a fiddle that only works if you manually append those attributes to the iframe using the web inspector. http://jsfiddle.net/yeldarb/2cjSa/

**Comment by epelland** [comment]
Please re-open this issue.
