### ISSUE TITLE
keyboad update(Control + s) doesn't work

### ISSUE THREAD

**Issue by anilkk** [jsfiddle/jsfiddle-issues#384]
When I press Control + s, Browser save event is triggered. It doesn't  trigger save to my jsfiddle profile. Instead it asks for save this html page popup.

But If I press save or update button, it saves in my jsfiddle profile. Tooltip also shows keyboard short cut.

Run short cut works as expected (Control + return).

**Comment by rbford** [comment]
Problem still exists on Chrome Version 39.0.2171.99 m. 
Given that the UI command is 'Update', perhaps consider supporting Ctrl+U as an additional shortcut?

**Comment by JemiloII** [comment]
so i wonder if we can just make a Tamper Monkey Script for chrome. This way when we hit control s it'll just disable the default save and click the save button. Actually yeah, sounds like a simple eventListener. Maybe we can use mousetrap.js and create other hotkeys.

**Comment by pquerner** [comment]
@JemiloII Sure. That might work. See this post: http://stackoverflow.com/questions/21658829/jquery-capture-ctrl-s-and-command-s-mac

**Comment by JemiloII** [comment]
we don't need jquery, mousetrap.js is 4kb and can do ctrl-s and  command-s-mac, to write some eventListeners is a no brainer. :) We should be avoiding jquery, it's bulky and a clutch.

**Comment by pquerner** [comment]
@JemiloII Something like that? 
https://github.com/pquerner/jsfiddle_save_shortcut
(Works on save for new script, but fails when trying to update a script (instead it creates a new script))

**Comment by JemiloII** [comment]
i made a pull request. you just needed to create an if/else vs the two ifs and change undefined comparison to a null comparison.

**Comment by JemiloII** [comment]
im surprised it took so long for us devs to do something about the jsfiddle problem haha. Such an easy fix with tamper monkey + mousetrap.

**Comment by JemiloII** [comment]
if we want, we can now make an entire onslaught of commands. Like emmet commands for html.

**Comment by rbford** [comment]
Thanks guys! Since I'm already using Shortcut Manager
https://chrome.google.com/webstore/detail/shortcut-manager/mgjjeipcdnnjhgodgjpfkffcejoljijf
I just mapped Ctrl+U to this:
var button = document.getElementById('update') || document.getElementById('savenew');
if (button) { 
  button.click();
} else {
  alert('Update failed!'); 
}

**Comment by rbford** [comment]
@JemiloII Would you please elaborate on your 'we can now make an onslaught of commands' comment?

**Comment by pquerner** [comment]
@rbford He's talking about something like
http://docs.emmet.io/

Where you can add shortcuts like in an IDE. (If you type the beginning of a word and "tab" it, it'll auto-complete it.)


(I think ?)

**Comment by rbford** [comment]
@pquerner Interesting idea. Thanks for the explanation.

**Comment by JemiloII** [comment]
@rbford @pquerner that was what i was talking about

**Comment by anon01924** [comment]
This is still an issue (Chrome)
