### ISSUE TITLE
Feature Request: Search for Fiddles

### ISSUE THREAD

**Issue by atomdmac** [jsfiddle/jsfiddle-issues#385]
I've generated quite a few fiddles and, even though I've been careful to name each of them descriptively, it's getting hard to find stuff when I need it.

Would it be possible to make fiddles searchable? It would be a bonus if you could search based on comments but just being able to search based on title/description would be great.

**Comment by KyleMit** [comment]
:+1: This would be a much welcome addition to the Public Dashboard page
