### ISSUE TITLE
Rename D3 to version 3.x?

### ISSUE THREAD

**Issue by mbostock** [jsfiddle/jsfiddle-issues#403]
I noticed that in the frameworks & extensions drop-down menu, it lists D3 at version 3.0.4. However, it loads the official d3.v3.min.js from d3js.org (which is good!) so you’re actually getting the latest official 3.x including patch and minor releases.

Would you please change the menu to show "D3 3.x (edge)" or something similar?

**Comment by mbostock** [comment]
This bug was closed a couple years ago, but it still shows 3.0.4. Could you please fix?

**Comment by oskarkrawczyk** [comment]
@mbostock Done

**Comment by mbostock** [comment]
:+1: Thank you!
