### ISSUE TITLE
When loading external resources from a manifest file in gist, order is not respected.

### ISSUE THREAD

**Issue by jayarjo** [jsfiddle/jsfiddle-issues#416]
Scripts that I'm trying to load depend on each other and should be loaded in a particular order, but this doesn't happen. Sometimes the script that is referenced first in manifest file would come as second one in an actual jsfiddle, or third.

**Comment by dcleao** [comment]
Happy new year!
Any news on this?

**Comment by dcleao** [comment]
Hi zalun, do you expect to fix this any time soon?

**Comment by dcleao** [comment]
Hi zalun, sorry for insisting. Can I provide help, in some way, to fix this? Thanks.

**Comment by crissdev** [comment]
I'm having the same issue. Before getting here I posted on their Twitter page. This issue is already 1 year and 6 months old. Can someone take a look at this and fix it?

**Comment by dcleao** [comment]
Hi, is the jsFiddle project alive? Any news on this? I really like jsFiddle, but if it doesn't move, I'll need to move away...

**Comment by zalun** [comment]
argh - somehow I just seen this. I will take a look today/tomorrow

**Comment by crissdev** [comment]
It looks this has been fixed.
