### ISSUE TITLE
Safari Mac does not show actions toolbar

### ISSUE THREAD

**Issue by arnekolja** [jsfiddle/jsfiddle-issues#445]
On Safari for Mac (6.0.5 here, seen it for a while, multiple devices too) the actions toolbar ("Run", "Save", …) is not visible. It seems like it is out of the viewport, pulled out from the top. Tried to debug it via inspector, but I can't find the rules affecting it. I only see that I can pull it back in by adding a top margin of 40 px to either #header or the form.
![bildschirmfoto 2013-09-16 um 12 36 28](https://f.cloud.github.com/assets/178206/1148375/adb73010-1ec0-11e3-8449-f8e142a3c65c.png)

**Comment by goesredy** [comment]
Same to me
