### ISSUE TITLE
Running a JSFiddle opens a new empty window.

### ISSUE THREAD

**Issue by TWiStErRob** [jsfiddle/jsfiddle-issues#448]
Open http://jsfiddle.net/TWiStErRob/g4FV8/
Click run: empty page: http://fiddle.jshell.net/_display/ opens (which actually contains my code)

Expected: just works, it was working until around 18:50 BST, but fails to "Run" after it.

I'm using Chrome.
And some other fiddles from net seem to work fine.

**Comment by losnir** [comment]
I encountered the same problem too, when forgetting to invoke a constructor function (that has a `name` property) with the `new` keyword, thus invoking it in the global namespace (`this` equals to `window`).

**Comment by jdmagic21** [comment]
I started to get an issue with mine. I am trying to access cookies and it opens in a new window. http://jsfiddle.net/codedcontainer/xkb0m66d/13/

**Comment by TWiStErRob** [comment]
@jdmagic21 Like we stated above if you overwrite `window.name` you get in trouble :)
I did a binary-search for the problematic line (remove half, check, remove other half, check, repeat with problematic half) and I found the one that's causing the problem:
```javascript
 $('body').find([name="'"+subname[0]+"'"]).val(subname[1]);
```
Compare the above to the correct code:
```javascript
 $('body').find('[name="'+subname[0]+'"]').val(subname[1]);
```
Orignally you were esentially doing the following operations:
```javascript
window.name = "'" + subname[0] + "'";
var array = new Array();
array.push(window.name);
$('body').find(array).val(subname[1]);
```

**Comment by jdmagic21** [comment]
@TWiStErRob  Thanks for that. This fixed the issue!
