### ISSUE TITLE
Allow echo requests to return custom HTTP headers and HTTP status codes

### ISSUE THREAD

**Issue by gitgrimbo** [jsfiddle/jsfiddle-issues#449]
Hi,

I've checked the documentation and the issues here and not seen this capability.

Primarily, I'd like to be able to test error scenarios with my fiddles, so I'd like the capability to return HTTP 404, 500 etc response codes.

An extension of this would be to allow for setting certain response headers from the echo request.

Thanks.

**Comment by steveoh** [comment]
so the answer is no?

**Comment by oskarkrawczyk** [comment]
@steveoh I've marked it as Archived for now, we'll get back to it at some point but not anytime soon.
