### ISSUE TITLE
Embedded JSFiddle: Tab changing is broken in Firefox and Safari (Chrome works fine) 

### ISSUE THREAD

**Issue by evanmoran** [jsfiddle/jsfiddle-issues#453]
To repro load this fiddle in the most recent versions of Safari or Firefox:
http://jsfiddle.net/evanmoran/qbZWQ/

Choose a tab to select Javascript/Result/HTML/CSS etc. 

**Expected:** The tab changes

**Actual:** The content disappears forever =(

The console outputs the error: 

    TypeError: this.sections[index] is undefined

At this location:

    this.switchTab = function(action, index, trigger){
      var actionParent = this.actions.getParent();
      this.sections.removeClass('active');
      this.sections[index].addClass('active');    <------ ERROR HERE
      if (actionParent){
        actionParent.removeClass('active');
        actionParent[index].addClass('active');
      }
      if (trigger.get('data-trigger-type') === 'result'){
        loadResult();
      }
    } 

It appears it is indexing incorrectly into an array. Should be an easy fix!

**Comment by arniekoz** [comment]
@zalun It still doesn't work. The error is due to an un-closed else block, so both the click and change events were triggered at the same time. In the embeddable.js file line 44-49, you can see the following:

```
click: function(event){
	if (event){
		event.stop();
	}
	self.switchTab(action, index, this);
},
```
changing the above to this:

```
click: function(event){
	if (event){
		event.stop();
	} else {
		self.switchTab(action, index, this);	
	}					
},
```

Solves the issue. Can @oskarkrawczyk check this bug fix?

**Comment by oskarkrawczyk** [comment]
Fixed. Will be deployed tomorrow.
