### ISSUE TITLE
Add Kendo UI to the libraries list

### ISSUE THREAD

**Issue by derickbailey** [jsfiddle/jsfiddle-issues#459]
Hello,

I'm a huge fan of JSFiddle (I use it constantly for demos and blog posts) and am also a Developer Advocate for Kendo UI and related tools. We would love to see Kendo UI added to the list of libraries, along side the other great tools you have listed in there.

To start, we'd like to have the last two major releases listed. This would include a few CSS files as well as a JavaScript file for each release. Kendo UI also has a direct dependency on jQuery, and we would need to include that reference.

Thanks,

  -Derick

---

Kendo UI can be referenced from the following CDN locations:

### Kendo UI Q2 2013 (2013.2.716)

jQuery dependency: v1.9.1

http://cdn.kendostatic.com/2013.2.716/styles/kendo.common.min.css
http://cdn.kendostatic.com/2013.2.716/styles/kendo.rtl.min.css
http://cdn.kendostatic.com/2013.2.716/styles/kendo.default.min.css
http://cdn.kendostatic.com/2013.2.716/styles/kendo.dataviz.min.css
http://cdn.kendostatic.com/2013.2.716/styles/kendo.dataviz.default.min.css
http://cdn.kendostatic.com/2013.2.716/styles/kendo.mobile.all.min.css

http://cdn.kendostatic.com/2013.2.716/js/kendo.all.min.js

### Kendo UI Q1 2013 (2013.1.319)

jQuery dependency: v1.9.1

http://cdn.kendostatic.com/2013.1.319/styles/kendo.common.min.css
http://cdn.kendostatic.com/2013.1.319/styles/kendo.rtl.min.css
http://cdn.kendostatic.com/2013.1.319/styles/kendo.default.min.css
http://cdn.kendostatic.com/2013.1.319/styles/kendo.dataviz.min.css
http://cdn.kendostatic.com/2013.1.319/styles/kendo.dataviz.default.min.css
http://cdn.kendostatic.com/2013.1.319/styles/kendo.mobile.all.min.css

http://cdn.kendostatic.com/2013.1.319/js/kendo.all.min.js

**Comment by codylindley** [comment]
Was this ever sorted out? Can we add Kendo UI now?
