### ISSUE TITLE
[REPRODUCE] set as base doesn't work

### ISSUE THREAD

**Issue by teo1978** [jsfiddle/jsfiddle-issues#47]
<b>Please write a comment after trying to reproduce</b>

It seems that sometimes cache key is not deleted after [Set as base].
Editor panels have old data and Result the right (new) one.
Excessive logging of the issue is on - please provide the url in your reproducing comments.
_WORK AROUND_ - wait until cache is cleared (up to 15 minutes)

---

<hr/>

original bug request
set as base simply doesn't work. Try to set as base and everything gets messed up.

Steps to reproduce:

1) log in
2) go to a fiddle of yours
3) modify it
4) click update
5) click set as base

Expected result: the modified fiddle should now be the base

Observed result: randomly, any of the following:
A) works fine
B) it reverts to an older version of the fiddle
C) it shows an inconsistent fiddle where the RESULT is the updated one while the source code is of an older version of the fiddle.

This makes jsFiddle virtually unusable, I wonder how people work around this.

I usually log out, restart the browser, log in again, try in another browser, and after trying several times it gets fixed and the fiddle gets updated and set as base, but I haven't found a reliable workaround. Sometimes I waste several minutes trying to set an updated fiddle as base and cannot.

Happens with ALL browsers, almost 100% of the time - almost but not quite 100%.

**Comment by adamvleggett** [comment]
This issue is occurring for me again in fiddle https://jsfiddle.net/adamvleggett/b84nxcjt/
