### ISSUE TITLE
Unable to Drag Collab Bar

### ISSUE THREAD

**Issue by sturdy5** [jsfiddle/jsfiddle-issues#473]
When using the collaboration feature I am unable to move the collaboration bar that appears on the right side. I am using Google Chrome 31.0.1650.63 m. I also tried with Firefox 26.0 and was unable to move the collab bar.

When I attempt to drag the bar someplace else, it just highlights content on the page.

**Comment by JasonHine** [comment]
+1

**Comment by oskarkrawczyk** [comment]
The collaboration bar is not dragable, it look like it is but it's not.

**Comment by FelixDombek** [comment]
Do what @jsturdevant proposed. Just do it already, the totally wrong anchor & tooltip text has been there for 5 years now.
