### ISSUE TITLE
Feature Request: Add CSS frameworks

### ISSUE THREAD

**Issue by tsch1** [jsfiddle/jsfiddle-issues#475]
Please add feature in "Frameworks & Extensions" section, to select common CSS libraries, like eg. Bootstrap.

**Comment by weitzhandler** [comment]
Yes. I second this request! Twitter Bootstrap is really important.
It's been now over a year since issue was opened. Any progress?

**Comment by gereltod-g** [comment]
+1. I don't see related schedule in roadmap. Are you developing it?

**Comment by oskarkrawczyk** [comment]
Not at the moment.
