### ISSUE TITLE
Reset panel layout

### ISSUE THREAD

**Issue by dadaphl** [jsfiddle/jsfiddle-issues#493]
I accidentally moved the panels out of the screen. Reload doesn't bring them back. The only way i can use jsfiddle now is to open every fiddle in a incognito window.  

Browser: Chrome 33.0.1750.152

![screen shot 2014-03-25 at 07 51 32](https://f.cloud.github.com/assets/415536/2509095/3c40b450-b3ea-11e3-8bb3-91bb08ed757a.png)

**Comment by ziaprog** [comment]
Where is the console?

**Comment by baconface** [comment]
On most browsers you can access developer tools with a console window/tab by pressing F12.

**Comment by llamerr** [comment]
I'm seeing this and solution from this story no longer working. Any other workarounds?
![selection_076](https://cloud.githubusercontent.com/assets/1281970/16953798/0f7b0b4e-4dd7-11e6-8e5c-5784ea4f2434.png)

**Comment by oskarkrawczyk** [comment]
It does work, but you're trying to run the code in context of `Adblock Plus` instead of `top` – just switch that in devtools and it'll work.

**Comment by llamerr** [comment]
@oskarkrawczyk I just reloaded page few times - few times I got same error, but after that it started working for some reason. I'm not sure I understand what you mean by context of `Adblock Plus`, could you clarify please? You mean that error from that extension switched context of console or something like that? (That error not from `Adblock Plus` but from `Diigo toolbar` - was seeing it on a couple of pages before but haven't noticed that it affects something)

**Comment by oskarkrawczyk** [comment]
@llamerr Notice in your screenshot, below the Console, Animations tabs is a dropdown, it's selected to `Adblock Plus`, and should be selected to `top` (which is jsfiddle.net).

**Comment by llamerr** [comment]
@oskarkrawczyk I see now, thanks! Seems I accidentally swithed it at some moment.

**Comment by caub** [comment]
I guess the layout settings are saved serverside

**Comment by Grusteam** [comment]
still same problem

**Comment by tommai78101** [comment]
For anyone who is reading this Github issue, coming from Google search and from Bing search,

As of December 6, 2018, the current method to reset JsFiddle layout is:

1. Press F12 to open DevTools (Chrome) or Debugger (Firefox, Edge).
2. Navigate to "Application" in Chrome DevTools, or "Storage in Firefox/Edge Debugger.
3. Find "Local Storage".
4. Find www.jsfiddle.net.
5. Delete any entries/keys labeled as `grid_*-split-sizes` (eg. `grid_1-split-sizes`)
6. Refresh jsfiddle.net webpage.

Source: https://github.com/jsfiddle/jsfiddle-issues/issues/1151
