### ISSUE TITLE
PrototypeJS version update --> 1.7.2

### ISSUE THREAD

**Issue by jwestbrook** [jsfiddle/jsfiddle-issues#506]
A bugfix version of Prototype was recently released (1.7.2). Can it be added to the Library dropdown?

http://prototypejs.org/2014/04/18/prototype-1-7-2/

**Comment by jwestbrook** [comment]
Will this version not be added to jsfiddle? The latest version has be released for over a year and has not shown up in the interface.

Thanks!

**Comment by oskarkrawczyk** [comment]
@jwestbrook Added.
