### ISSUE TITLE
syntax check is completely wrong for html

### ISSUE THREAD

**Issue by matteosistisette** [jsfiddle/jsfiddle-issues#515]
Syntax check for non-XHTML kinds of HTML in jsfiddle is completely wrong, it checks it as XML regardless of the actual document declaration.

Examples:
  `<br>`
will always be marked as invalid if you don't add the trailing / as in `<br/>`
  `<div></DIV>`
will always be marked as invalid because case doesn't match.

This is expected behavior for XHTML-type documents, but NOT for HTML-type documents, where the above examples are all valid.

Syntax check should be done in accordance with the actual document declaration that is selected. 

Regarding HTML5, 
HTML5 admits two "flavours": XHTML-like (to be parsed by an XML parser according to a DTD) and HTML-like (to be parsed by an html parser). The document declaration determines which syntax is used.

Jsfiddle doesn't let you choose, it only has one option for HTML5 and it's the html-flavoured one (which is fine in my opinion as it's the most widely used); however the syntax check is done as if it was it was an XHTML document. 

Issue #514 is just one example of this wider issue

**Comment by teo1978** [comment]
What does "archived suppose to mean? Is it fixed?

**Comment by teo1978** [comment]
No, actually it's not fixed. Why have you closed this??

**Comment by oskarkrawczyk** [comment]
@teo1978 Archiving this for now since there are not plans on fixing this in the current version of JSFiddle.

**Comment by teo1978** [comment]
Funny way of managing bugs.
Just out of curiosity: are you going to reopen archived bugs when a new version of JSFiddle is going to be released, or do you expect people to figure out when the time comes to report them again?

**Comment by constructit** [comment]
What is the 3rd party plugin used?
Has the plugin been discontinued?
Is there an alternative plugin?
Is JSFiddle still actively developed? It's looking a bit stagnant on the update front. https://github.com/jsfiddle
