### ISSUE TITLE
Request: Allow Jade language input in addition to HTML

### ISSUE THREAD

**Issue by plato-cambrian** [jsfiddle/jsfiddle-issues#522]
As a web developer, I prefer writing [Jade](https://github.com/visionmedia/jade) syntax to render into HTML, thus avoiding errors and saving keystrokes.

I see that you have a Languages tab with e.g. SCSS and Coffeescript. I would like to be able to select Jade here. 

Other thoughts:
* Jade's a full templating language, with access to `locals.*`, but that's not something I care about as a jsfiddle user. I care about typing easy syntax that turns into static HTML content. [See and try a live Jade demo.](http://www.learnjade.com/)
* If you want to be able to see both Jade and HTML:
  * A toggle switch in the top left window to switch between HTML and Jade. 
  * A dropdown in each of the three windows (other than Result), so I can select e.g Jade/HTML/CSS, Jade/CSS/JS
* Changes made to the Jade code either:
  * automatically are rendered and propagated to any visible HTML window; OR
  * are rendered upon clicking a Render button

**Comment by avalanche1** [comment]
+1

**Comment by avalanche1** [comment]
closing just so? no feedback, no nothing? so sweet

**Comment by oskarkrawczyk** [comment]
@avalanche1 Archiving this for now since there are not plans on adding JADE in this version of JSFiddle. We might come back to it in the future – hence the tag on this issue.

**Comment by nmaxcom** [comment]
+100 to this. Also, we should now start calling it Pug.
