### ISSUE TITLE
No option to save or update a new fiddle

### ISSUE THREAD

**Issue by mm-gmbd** [jsfiddle/jsfiddle-issues#529]
I'm logged in and trying to save a jsfiddle I've just created, but there is no save/update/fork option at the top of the page (and the url is just a bare www.jsfiddle.net/, with no typical randomized jsfiddle name).

It's been a while since I've used jsfiddle, so I thought something must be different, but the documentation (http://doc.jsfiddle.net/basic/introduction.html#saving) clearly states "Buttons Save or Fork are always present in the UI. First one appears if no fiddle was loaded, the latter is used to create a new fiddle from the existing one." This is _not_ the case (image of UI below).

So... what's the deal?

![jsfiddle_problem](https://cloud.githubusercontent.com/assets/3329824/3833355/9cd0747e-1da6-11e4-99b9-e5ddbb7bf1c6.png)

**Comment by lhale** [comment]
I'm logged in to JSFiddle, made a new fiddle but there's no Save button - what's going on ?
