### ISSUE TITLE
no reason scroll in iframe/embeded results

### ISSUE THREAD

**Issue by codylindley** [jsfiddle/jsfiddle-issues#534]
The iframe embed results view scrolls for no reason.

In chrome latest go http://doc.jsfiddle.net/use/embedding.html and notice that there is an unnecessary scroll bar in the results view.

e.g. http://recordit.co/GQMkwB5Ww7

**Comment by baivong** [comment]
Why this issue is not fixed?

**Comment by ryanpcmcquen** [comment]
I would still love to see a fix for this. :+1:

**Comment by oskarkrawczyk** [comment]
Closing, I'm going to completely refactor this part of the app.
