### ISSUE TITLE
Cursor doesn't appear where types

### ISSUE THREAD

**Issue by skartknet** [jsfiddle/jsfiddle-issues#538]
Having some text on any on the windows, the letters don't appear where the cursor is. If for instance you click at the end of one line, the cursor appears over the last letter, literally on top of it but the text appears where expected. I attach an animated gif. In the image I always click at the end of the line before typing and you can see the cursor is not there.

I have tried IE, Firefox and Chrome and it only happens on Chrome (Version 38.0.2125.66 beta-m (64-bit))

![jsfiddle](https://cloud.githubusercontent.com/assets/1685262/4346728/94bca98c-4110-11e4-92bd-a4e93779eb09.gif)

**Comment by oskarkrawczyk** [comment]
Updated CodeMirror to the latest version, everything should be ok now.
