### ISSUE TITLE
external resource CSS not loaded by URL

### ISSUE THREAD

**Issue by webOS101** [jsfiddle/jsfiddle-issues#549]
Navigating to the following URL:

http://jsfiddle.net/gh/gist/enyo/nightly/4f55c778aee7c7bf4ddc/

does not load the external CSS library in Chrome or Safari.  If you hit the 'run' button, the CSS file will load correctly.  In Firefox, the CSS appears to load correctly.

**Comment by alcalyn** [comment]
I have the same problem.

Moreother, when I press Save, and I open the new url in a new tab, it works perfectly.

It seems to be broken only with a github example.
