### ISSUE TITLE
New Dojo releases

### ISSUE THREAD

**Issue by csnover** [jsfiddle/jsfiddle-issues#551]
1.10.4 //ajax.googleapis.com/ajax/libs/dojo/1.10.4/dojo/dojo.js
1.9.7 //ajax.googleapis.com/ajax/libs/dojo/1.9.7/dojo/dojo.js
1.8.10 //ajax.googleapis.com/ajax/libs/dojo/1.8.10/dojo/dojo.js
1.7.8 //ajax.googleapis.com/ajax/libs/dojo/1.7.8/dojo/dojo.js

Thanks!

**Comment by csnover** [comment]
@zalun still waiting to get these updated!

**Comment by zalun** [comment]
no way - will do it today

**Comment by zalun** [comment]
Fixed

**Comment by csnover** [comment]
Thanks! :kissing_heart:

**Comment by pdfernhout** [comment]
Three of the four CDN links produce 404 not found errors:
http://ajax.googleapis.com/ajax/libs/dojo/1.10.4/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.7/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.10/dojo/dojo.js

Is there some sort of lag for when Google's CDN picks these up after an update?

**Comment by csnover** [comment]
This is my fault. I thought I had gotten those sent to the CDN but didn’t. They should be up soon. So sorry for the trouble.

**Comment by pdfernhout** [comment]
Those URLs are still producing 404s. Also, and as one might expect, when I try to write a JSFiddle when choosing any of those versions (such as with the JavaScript "document.write('Hello');", I get an error message with "ReferenceError: dojo is not defined _display:21" when I try to "Run". However, the fiddle works OK when choosing other versions of Dojo, like 1.5.3 or "nightly". An example failing fiddle:
http://jsfiddle.net/gsqoos5m/

**Comment by pdfernhout** [comment]
Those URLs are all returning content now. Thanks!
