### ISSUE TITLE
Single closing quote character dropped in embedded iFrame

### ISSUE THREAD

**Issue by dbmikus** [jsfiddle/jsfiddle-issues#556]
I have the following jsfiddle: http://jsfiddle.net/OnSIP/wh0k8jvx/

When I embed the snippet using an iFrame,

```html
<iframe
    style="width: 100%; height: 800px;"
    src="http://jsfiddle.net/OnSIP/wh0k8jvx/embedded/js,html,css,result/"
    allowfullscreen="allowfullscreen" frameborder="0">
</iframe>
```

the closing quote (of the `'\s*\=\s*([^;]*).*$)|^.*'` part) does not render. It is not in the DOM, either.

**Comment by oskarkrawczyk** [comment]
Doesn't look like a JSFiddle issue. There have been thousands of fiddles embedded without this issue.

**Comment by dbmikus** [comment]
Hm... I'm not so sure. If I copy the embed link and paste it into a new JS Fiddle, I now lose both the `$` and the `'` (single quote) characters.

http://jsfiddle.net/ja4fqu1b/

That string section is rendered as

```
<span class="string">'\s*\=\s*([^;]*).*$)|^.*</span>
```

Sorry, don't have more time to look into it now, but I believe this at least shows it isn't related to the specifics of where I was embedding the fiddle.
