### ISSUE TITLE
Don't see all fiddles I created/forked/updated, the list is same for weeks in my profile

### ISSUE THREAD

**Issue by nitinsurana** [jsfiddle/jsfiddle-issues#564]
On my dashboard, I have only 2 pages, all recent fiddles created originally, updated from an existing one, forked... none are visible. Infact, the list never changes, it has been the same for months.

Probably, the steps to reproduce, would be to have an account and google any fiddle, update it or fork it. Go to your profile and it's not there.

My jsFiddle Username - nitincool4urchat

**Comment by oskarkrawczyk** [comment]
Weird, I'm seeing fiddles updates on the dashboard all the time. The public profile shows only fiddles with a title and description.
