### ISSUE TITLE
Override default dependencies from fiddles displayed from POST

### ISSUE THREAD

**Issue by ryanjduffy** [jsfiddle/jsfiddle-issues#573]
We extensively use the ability to display a fiddle from a POST on the [Enyo sampler](http://enyojs.com/sampler) and would like the ability to override the default dependencies using the `/dependencies/` URL param so we can exclude libraries that aren't relevant for a particular sample.

/cc: @webos101

**Comment by oskarkrawczyk** [comment]
Closing. We won't be touching this until a complete rewrite of JSFiddle. Sorry.
