### ISSUE TITLE
Unable to access fiddle

### ISSUE THREAD

**Issue by pilch74** [jsfiddle/jsfiddle-issues#575]
Hi there and thanks for pointing me in the right direction Oskar - love what you provide and it's been a godsend for me!!

My username is pilch and within page two of my fiddles http://jsfiddle.net/user/dashboard/fiddles/2/ there is a fiddle titled 'Weather Underground' and it's latest version is #6.  When clicking on either the title OR the revision, the url just points back to http://jsfiddle.net/user/dashboard/fiddles/2/.

This fiddle has been a long-standing labour of love and it would be a real shame if I couldn't ever use it again.

Thanks in advance,
Pilch

**Comment by zalun** [comment]
Thanks, a nice find

**Comment by zalun** [comment]
Checked it as it is the same on http://jsfiddle.net/user/pilch/fiddles/2/

**Comment by zalun** [comment]
OK - it is marked as spam - I will wait until our new spam prevention system will come to live and will unlock it

**Comment by acapellas4u** [comment]
Hi Zalun, any updates on this please?

Thanks.

**Comment by oskarkrawczyk** [comment]
We'll be unlocking fiddles per request only. Closing.
