### ISSUE TITLE
JS Code Container - Annoying Bug

### ISSUE THREAD

**Issue by jmusicc** [jsfiddle/jsfiddle-issues#577]
So there's this really annoying thing that happens where if you adjust the middle divider, the JS code container gets really messed up. I think it's either an issue with wordwrap or indentation. I found the only solution is to scroll up and down and the alignment gets fixed. Maybe you could add a mouseup trigger to the divider that recorrects this?

Ex: If you click on a line of code, it will go to a completely different line. Sometimes it will even select the correct line, but when you type a character it will jump to the wrong line.

Screenshot (ex. click on highlighted area but actually jumps to where the cursor is): 

![Screenshot](https://cloud.githubusercontent.com/assets/2212812/5892399/94c86120-a482-11e4-9616-9359bfa76ca8.PNG)

**Comment by oskarkrawczyk** [comment]
Closing. We won't be touching this until a complete rewrite of JSFiddle. Sorry.
