### ISSUE TITLE
Fiddle marked as spam?

### ISSUE THREAD

**Issue by sbehrends** [jsfiddle/jsfiddle-issues#578]
i didnt find anywhere for jsfiddle support, but maybe here I get some feedback.
Long time ago a created a fiddle and publish it, the username is Blunk, the fiddle ID is x8dSP, today I discovered it was renamed as "spam_x8dSP". Is there any way to get the code back?

Thanks :)

**Comment by zalun** [comment]
Yes, I will check the code and bring it back for you

W dniu 27/01/2015 o 23:18, sbehrends pisze:
> i didnt find anywhere for jsfiddle support, but maybe here I get some
> feedback.
> Long time ago a created a fiddle and publish it, the username is Blunk,
> the fiddle ID is x8dSP, today I discovered it was renamed as
> "spam_x8dSP". Is there any way to get the code back?
>
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsfiddle/jsfiddle-issues/issues/578>.
>

-- 
Piotr (zalun) Zalewa
JSFiddle

**Comment by sbehrends** [comment]
That would be awesome!
Any idea what happend?

**Comment by sbehrends** [comment]
Still marked as spam :(
@zalun

**Comment by oskarkrawczyk** [comment]
We're bringing back marked fiddles be request over support@jsfiddle.net only. Sorry.
