### ISSUE TITLE
could  add search form in add-library that make the add-library easier?

### ISSUE THREAD

**Issue by suhaotian** [jsfiddle/jsfiddle-issues#579]
Because there're so many librarys  ,
could  add search form in add-library that make the add-library easier ?

thks :+1:

**Comment by chrisjohnson** [comment]
Not sure if it solves your issue but when you open a select box you can usually start typing the name of the element and it will select that one for you, in modern browsers.

**Comment by suhaotian** [comment]
@chrisjohnson  tks
