### ISSUE TITLE
Any way to auto run?

### ISSUE THREAD

**Issue by AbeAlpha** [jsfiddle/jsfiddle-issues#580]
Is there ay way to make auto run on every keystore?
Like liveweave.com or kodtest.com

Will be nice too add a dark theme and add auto complete (if u write p auto writes /p)
A downloable .html file will be nice too :)

Thanks for all ur work

**Comment by baconface** [comment]
There would be reasons you would not want this. Such as Javascript would be constantly breaking since you would be continuously be submitting incomplete code. Also, I believe jsFiddle does a POST to PHP to organize and render the results. This would really hit the service hard with the increase of process requests.

**Comment by oskarkrawczyk** [comment]
We won't be fixing this issue in this version of JSFiddle.

And as @baconface mentioned, autorun doesn't make sense for JS.

**Comment by alkapwn3d** [comment]
I do understand the javascript issue but could you atleast give people the choice to autorun if they wanted? I use codepen but I like jsfiddle better except for the lack of autorun.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by drylib** [comment]
jsbin.com already does that and is very convenient for me. So "autorun doesn't make sense for JS" is not true.

**Comment by oskarkrawczyk** [comment]
@drylib See my comment above.

**Comment by drylib** [comment]
Is it "Live code evaluation" ?

**Comment by mechanicious** [comment]
You can hack your way to it, make sure your fiddle is saved.
```js
document.addEventListener("keydown", function(e) {
    if(typeof keydownCount === "undefined") keydownCount = 0; else keydownCount++;
        // run on keydown
	document.getElementById("run").click();
        // update every 25 keystrokes
	window.keydownCount % 25 === 0 && document.getElementById("update").click();
})
```

**Comment by oskarkrawczyk** [comment]
@mechanicious That's not going to work, you can't leave the `iframe` context to get to JSFiddle's UI actions.

**Comment by mechanicious** [comment]
@oskarkrawczyk It works pretty well for me.
![autosavenautoupdate](https://cloud.githubusercontent.com/assets/8450319/21505551/a2781bac-cc68-11e6-9a71-b23ad5a062fb.gif)

**Comment by kongyuyu** [comment]
@mechanicious Thank you for your inspiration, I have implemented this logic into a chrome extension. I am currently working on making it fully customizable. My extension currently could auto run with 1.5 sec debounce, auto save with 25 key counts, and also able to hide panels other than JS panel with a button click. Please suggest more functionalities. [https://github.com/kongyuyu/jsfiddle-chrome-extension](url)

**Comment by oskarkrawczyk** [comment]
I've added auto-running. Auto-save to follow!

Reopening this ticket for now. 

![2018-02-13 18 22 09](https://user-images.githubusercontent.com/34213/36164456-ac3e2a36-10ec-11e8-8373-4347b1e9a4f2.gif)

**Comment by oskarkrawczyk** [comment]
Auto saving also added.

Both available from the editor settings.
