### ISSUE TITLE
Saved fiddle doesn't show up on my dashboard

### ISSUE THREAD

**Issue by Puigcerber** [jsfiddle/jsfiddle-issues#582]
Hi! 

I have a saved fiddle that I can access [by url](http://jsfiddle.net/Puigcerber/a65tgufL/2/) but it doesn't show up on my dashboard. It's the first time this happens to me, really weird.

Cheers.

**Comment by zalun** [comment]
If you haven't created being logged in it will remain anonymous.
Please fork the fiddle while logged in and fork it.

**Comment by Puigcerber** [comment]
Well, I think it's not anonymous because it's shown under my username in the url.

**Comment by zalun** [comment]
In second vesion - you've updated being logged in

**Comment by Puigcerber** [comment]
Ok, I see it now, so forking is the way then :smile: 

Dziekuje!

**Comment by zalun** [comment]
Prosze bardzo :)

**Comment by smohadjer** [comment]
This is overly complicated and hard to figure out. I have found myself often starting a fiddle while not being logged in. Most of the times I just want to test an idea fast, but then as I work more and the fiddle becomes more complex I decide to save it as it's now something useful that I want to be able to refer to later. I keep myself searching for a "Save as..." button!

**Comment by souviiik** [comment]
I got a easier way to do this. Go to "All your fiddles" section, on an existing fiddle you will get a delete icon, with a hard coded link to delete it. The link is like [https://jsfiddle.net/_confirm_delete/<fiddle_id>/](https://jsfiddle.net/_confirm_delete/<fiddle_id>/). Just do a inspect element and change the fiddle_id with your desired one and click the delete icon.

This will delete the fiddle with new id and also remove the fiddle block, the one you have edited. Do not worry, on refresh of the page it will reveal the fiddle that was removed on the previous step.
