### ISSUE TITLE
Weinre link doesn't work (Could not resolve host: debug.phonegap.com)

### ISSUE THREAD

**Issue by javajosh** [jsfiddle/jsfiddle-issues#583]
Attempted to try out this functionality, but the link provided points to a host that doesn't exist.

http://debug.phonegap.com/client/#jsf_fwr

$ curl http://debug.phonegap.com/client/\#jsf_fwr
curl: (6) Could not resolve host: debug.phonegap.com

**Comment by zalun** [comment]
Thanks - will keep an eye on this

**Comment by oskarkrawczyk** [comment]
Closing, http://debug.phonegap.com/ is pretty much dead.
