### ISSUE TITLE
TidyUp doesn't work with coffeescript

### ISSUE THREAD

**Issue by 10by10pixel** [jsfiddle/jsfiddle-issues#584]
Using TidyUp ruins indenting which Coffeescript requires stays in tact. Here is an example:

**BEFORE**  
    if 1 is 1
        alert("Success")
    else
        alert("Failure")

**AFTER**  
    if 1 is 1 alert("Success")
    else alert("Failure")

The after version does not successfully compile and is therefore broken by the TidyUp button.

**Comment by oskarkrawczyk** [comment]
Yes, TidyUp doesn't work for CofeeScript. Will be fixed in the future.

**Comment by oskarkrawczyk** [comment]
Closing. We won't be touching this until a complete rewrite of JSFiddle. Sorry.
