### ISSUE TITLE
Print not working on /show because of jsfiddle header.

### ISSUE THREAD

**Issue by GeorgeBailey** [jsfiddle/jsfiddle-issues#586]
I hope I'm posting to the right place.

I was getting ready to test some printing concepts, but found that jsfiddle would no longer work for this. It used to.

Try Print Preview this page: http://jsfiddle.net/6Lnu2079/show/. It should be many pages long, but gets cut off instead.

**Comment by oskarkrawczyk** [comment]
No idea why, and to be perfectly honest I'd much rather not fix this and waste paper on pages long code printouts.

**Comment by GeorgeBailey** [comment]
@oskarkrawczyk,

> No idea why,

Because the `/show` page now forces the results into an iframe. (I assume this is to make the jsfiddle header work properly)

If my test page wasn't in an iframe it would provide the desired test results.

I'm not asking to remove the header+iframe, just give a workaround that allows it to be disabled when it gets in the way.

> and to be perfectly honest I'd much rather not fix this

That's your decision - doesn't bother me.

> and waste paper on pages long code printouts.

Did you read my post?

1. I'm not using any paper, I'm using Print Preview to see the test results.
2. This is not a code printout, this is /show which is the resulting page generated from the code.
3. If my result page is long, it is because that is my intent. If someone person wants to print the long page, that is their intent.

I am using jsfiddle for testing across browsers. I understand that you may not want to fix this, but 'no reason' is better than an 'inaccurate reason'

**Comment by GeorgeBailey** [comment]
I did find a workaround - in Firefox I can Right-Click->This Frame->Show Only This Frame.

I am guessing this works because Firefox sets the HTTP Referer?

Unfortunately this option is not available in Chrome or Internet Explorer so I have to use a different method for those browsers when I'm testing printing.

Still enjoy jsfiddle for non-print testing purposes. :smile:

**Comment by GeorgeBailey** [comment]
The example I gave wasn't the best. I usually am testing out CSS rules - especially when page counters are involved.
