### ISSUE TITLE
Debug not working in Firefox

### ISSUE THREAD

**Issue by tingtron** [jsfiddle/jsfiddle-issues#587]
Last test Firefox version 36.0.1 under Windows 7 64-bit.

In any JavaScript containing Fiddle, when attempting to debug, the Firefox debugger cannot access the Result source of the page. Instead the error below is shown, besides otherwise generic page `<user>/<fiddleid>/show` with `loadResult();` event handler. So it is not possible to set breakpoints, or step through the code.

When "debugger;" statement is used in the code, the landing source in the Firefox Debugger is `_display/`, which shows a single line:
```{"error": "Please use POST request"}```

Alternatively, it may land on the generic `.../show` page with `loadResult()` and "pretend" to step through the code, while the source of the generic page is completely unrelated to the actual resulting HTML/JavaScript.

Note: in Internet Explorer 11, debugging works fine in both scenarios: in list of sources, the `.../show` page actually contains the Result; and using `debugger;` statement also lands within actual Result source.

A possible issue with Firefox could be not being able to process the generic `show` page to load the Result adequately or fast enough. So it would be good to see if the Load Result mechanism could be more flexible to support Firefox behavior.

**Comment by zalun** [comment]
[Run] sends a POST request to JSFiddle. Apparently for debugging Firefox is trying to reload the page. It's not using the POST request hence the error. It should work with updating a version, but it's not a good solution.

**Comment by 42degrees** [comment]
Firefox changed a while back to reloading the page for a bunch of reasons (like inspect).  I've been using a "debugging;" statement executed before the JavaScript you care about (I usually just it at the bottom of the JavaScript panel) to force the browser to figure out where the source is.  From there I can set other breakpoints and it works fine.  I've had to do this in Chrome occasionally as well as it sometimes get's confused as to which tab (source) I'm editing.

**Comment by oskarkrawczyk** [comment]
We can't change Firefox's behavior so closing this ticket.
