### ISSUE TITLE
Please update CoffeeScript to 1.9.1

### ISSUE THREAD

**Issue by datagrok** [jsfiddle/jsfiddle-issues#589]
Selecting "CoffeeScript" from the Languages drop-down causes JSFiddle to include http://jsfiddle.net/js/coffeescript/coffeescript.js, which is currently CoffeeScript 1.6.2.

Please add support for a more recent version of CoffeeScript, like 1.9.1, to the Languages drop-down as well.

**Comment by oskarkrawczyk** [comment]
Closing. We won't be touching this until a complete rewrite of JSFiddle. Sorry.
