### ISSUE TITLE
JQuery edge -> QUnit script link is broken

### ISSUE THREAD

**Issue by dfoverdx** [jsfiddle/jsfiddle-issues#590]
Including the QUnit framework is broken because the URL is incorrect.

![image](https://cloud.githubusercontent.com/assets/3087358/6690901/72fcc7a4-cc80-11e4-954c-bd31ee6fb58e.png)

![screenshot 2015-03-17 08 32 00](https://cloud.githubusercontent.com/assets/3087358/6690892/66b3ad32-cc80-11e4-8e39-a93b5be729dd.png)

The URL currently used is https://github.com/jquery/qunit/raw/master/qunit/qunit.js.  It should be using the QUnit CDN http://code.jquery.com/qunit/qunit-1.17.1.js.

**Comment by oskarkrawczyk** [comment]
Fixed
