### ISSUE TITLE
http hosted predefined frameworks do not work on httpS://jsfiddle.net in Firefox

### ISSUE THREAD

**Issue by bneijt** [jsfiddle/jsfiddle-issues#591]
All predefined frameworks and extensions that are served via "http" will not work when jsfiddle is loaded as https in Firefox (version 36)

For examples, you can not use "D3" from the framework&extensions menu when you have loaded jsfiddle via https but it does work when loading jsfiddle over http.

The related Firefox error is: `Blocked loading mixed active content "http://d3js.org/d3.v3.min.js"` [Learn More](https://developer.mozilla.org/en-US/docs/Security/MixedContent)

Work arounds:
- Use jsfiddle over http instead of https.
- Add the framework using external resources and the cdnjs.com hosted version of the framework.

**Comment by mbostock** [comment]
I recommend that JSFiddle use CDNJS:

https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js

**Comment by oskarkrawczyk** [comment]
Most of the old frameworks have been switched to no-protocol

**Comment by mbostock** [comment]
FYI, I’ve enabled HTTPS support for <https://d3js.org>, so no-protocol URLs should work now.
