### ISSUE TITLE
Please update rainbow.js and data-language name for javascript on embeds

### ISSUE THREAD

**Issue by ccampbell** [jsfiddle/jsfiddle-issues#592]
I was looking at a react example with an embedded jsfiddle:
https://jsfiddle.net/reactjs/yun1vgqb/embedded/

I noticed that about 3/4 of the way down the page the highlighting breaks.  I patched it in rainbow https://github.com/ccampbell/rainbow/commit/34b9c622b34654f390a45eba5e09905e09fd1b5a

Also I noticed you are using data-language="js" for javascript embeds which as of right now is not supported in rainbow (just defaults to generic language rules).  If you change it to data-language="javascript" then all of the embedded javascript highlighting should look a bit better.

Thanks!

**Comment by oskarkrawczyk** [comment]
Closing, I'm going to completely refactor this part of the app.
