### ISSUE TITLE
Support for other libraries -- how is it done/requested?

### ISSUE THREAD

**Issue by JMerrill** [jsfiddle/jsfiddle-issues#596]
I'm interested in the not-yet-at-1.0 Aurelia framework. How would this become one of the library options in JSFiddle? The code is multiple projects under https://github.com/aurelia -- what do I (or the Aurelia developers) have to do to get it to be in the list?

Thank you.

**Comment by oskarkrawczyk** [comment]
@JMerrill if Aurelia is available on a CDN and can be added with a script include (not npm or anything like this), then I can add it straight away.

Just create a new ticket with the URLs to the script.
