### ISSUE TITLE
Broken jQuery edge URLs

### ISSUE THREAD

**Issue by mzgol** [jsfiddle/jsfiddle-issues#600]
jQuery (edge) should point to code.jquery.com/jquery-git.js, while jQuery Compat (edge) - to http://code.jquery.com/jquery-compat-git.js; see #555.

It seems those files have been erroneously swapped recently on jsFiddle... :/ I'm verifying by console.logging `$.ajaxSettings.xhr` on IE; in jQuery Compat (edge) the implementation should be larger and should include ActiveX options.

This will make a lot of people think a bug is in a wrong jQuery version so please fix it.

**Comment by oskarkrawczyk** [comment]
Fixed, thanks for the heads up

**Comment by mzgol** [comment]
Thanks for a quick reaction!
