### ISSUE TITLE
HTML4/5 self ending flag omitted improper automatic indentation and syntax error highlighting

### ISSUE THREAD

**Issue by humbleRumble** [jsfiddle/jsfiddle-issues#601]
When using the HTML4 or HTML5 doctype and omitting the self ending flag on void elements the automatic indentation and syntax error highlighting do not recognize the void element. Maybe a filter for area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track and wbr ([HTML5 Specification](http://www.w3.org/TR/html-markup/syntax.html#syntax-elements)) and defining those tags as automatically self ending (only in HTML4/5) would help.

**Comment by oskarkrawczyk** [comment]
There are no plans on fixing this in the current version of JSFiddle. Sorry.

This will be working in the future rewritten version of JSFiddle.
