### ISSUE TITLE
Enhancement: javascript line numbering

### ISSUE THREAD

**Issue by Mottie** [jsfiddle/jsfiddle-issues#605]
Thanks for an awesome resource!

The issue I run into is that debugging code in jsFiddle is difficult. When the console reports an error, the line number never matches the location of the code. Yes, I know you can click on the link provided with the error to look at the source, but then I still need to search for the matching code in the frame.

I think it would be **awesome** if the line numbering within the javascript frame would *start* at the same line number as it is in the document. 

It *should* be relatively simple. Javascript is added to the bottom of the page. So, jsfiddle can sum the line counts of the HTML & CSS by using the CodeMIrror API `doc.lineCount()` which returns the number of lines in those frames. Then the number of lines in the thead needs to be determined based on the number of resources. And lastly, CodeMirror has an option `firstLineNumber` which would allow setting the value of the first line number in the javascript frame... I don't know if CodeMirror allows dynamic changing of line numbers, but personally it would be good enough to set the javascript line numbering on page load since the HTML and css don't change that much.

**Comment by oskarkrawczyk** [comment]
There are no plans on adding this to the current version of JSFiddle. Sorry.

This will be present in the future rewritten version.

**Comment by Pamblam** [comment]
this really needs to get done. this and remove that obnoxious fucking blue banner you guys just added. if you did that i'll stop using plunkr.
