### ISSUE TITLE
Don't use $(window).load

### ISSUE THREAD

**Issue by mzgol** [jsfiddle/jsfiddle-issues#606]
The [`.load()` event shortcut](api.jquery.com/load-event/ ) was removed in https://github.com/jquery/jquery/commit/0705be475092aede1eddae01319ec931fb9c65fc. jsFiddle uses it when you choose to load jQuery `onLoad` which is now, as an effect, broken with `jQuery (edge)` and `jQuery Compat (edge)`.

You should change `$(window).load(fn)` to `$(window).on('load', fn)`.

Originally reported on Twitter at https://twitter.com/bedziejutro/status/602364273780793344.

**Comment by mzgol** [comment]
Ping?

**Comment by zalun** [comment]
Please check

**Comment by mzgol** [comment]
Works fine now, thanks.
