### ISSUE TITLE
Javascript panel resizing and mis-alligning issue

### ISSUE THREAD

**Issue by kshkrao3** [jsfiddle/jsfiddle-issues#608]
Hey all, 

A couple of days back I just resized the javascript panel in jsfiddle and now in my browser whenever I open jsfiddle I see the same broken panel which is shown in the below Image. Haven't tested in other browsers! This issue is in Google Chrome. What could be the reason? It looks really whole mess out here. Its not resizable now.
![untitled](https://cloud.githubusercontent.com/assets/11007754/8124648/81d30e90-10fb-11e5-9046-f2b98a229c62.png)

**Comment by oskarkrawczyk** [comment]
See here for solution: https://github.com/jsfiddle/jsfiddle-issues/issues/349

**Comment by kshkrao3** [comment]
Thank you so much.. :+1:  :)
