### ISSUE TITLE
Broken link on http://doc.jsfiddle.net/tutorial.html

### ISSUE THREAD

**Issue by paulbuis** [jsfiddle/jsfiddle-issues#609]
Link on bottom of page to "Andrew Wooldridge’s List of Stunning examples" appears to be broken (does not point to desired content) because "andrewwooldridge.com expired on 05/18/2015 and is pending renewal or deletion"

**Comment by oskarkrawczyk** [comment]
Will leave it in, in case Andrew brings the blog back to life.

**Comment by ToddBleeker** [comment]
Use the Wayback Machine
https://web.archive.org/web/20150622011826/http://andrewwooldridge.com/blog/2011/03/16/stunning-examples-of-using-jsfiddle

<Todd />
