### ISSUE TITLE
rename fiddle

### ISSUE THREAD

**Issue by nyothecat** [jsfiddle/jsfiddle-issues#61]
Hello,

I would greatly appreciate to be able to set the name of my choice for a fiddle. I have seen we can give a title in the Info menu, but it seems to be only for the current version; once updated, it disappears. Plus, it would be better to use this name as the id of the fiddle (in the url).

Right now I need to insert a comment at the beginning of my js to recognize my fiddles from the dashboard.

Thanks!

**Comment by alkopop79** [comment]
Again, why is this issue closed when it still persists?
