### ISSUE TITLE
Ctrl+S show "Save page" dialog first in Firefox

### ISSUE THREAD

**Issue by yar3333** [jsfiddle/jsfiddle-issues#610]
I use a Firefox and like Ctrl+S shortcut, but when I press it, Firefox show "Save page" dialog. After I press "Cancel" jsfiddle save the code.

**Comment by oskarkrawczyk** [comment]
We won't be changing keyboard shortcuts to new ones in this version of JSFiddle.

Shortcuts will be remapped in the completely rewritten version.
