### ISSUE TITLE
Please add new version of svg.js

### ISSUE THREAD

**Issue by Fuzzyma** [jsfiddle/jsfiddle-issues#612]
The title says it all.
The current svg.js - lib you can select in jsfiddle is around v0.8.
However svg.js v2 was released lately. It would be cool if you could add it to the selection.

**Comment by Fuzzyma** [comment]
\*knock knock\* - is this still working? hello?

**Comment by zalun** [comment]
I see it now - please provide us with the link to CDN
Thanks you

**Comment by Fuzzyma** [comment]
https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.0.5/svg.min.js

All version-urls can be optained here: https://cdnjs.com/libraries/svg.js
or just with an api call: https://api.cdnjs.com/libraries?search=svg.js&fields=assets

Thank you very much :)

**Comment by Fuzzyma** [comment]
Btw: Is there any chance, that you will also display always the latest version in the fiddle? Because new releases are coming very quickly

**Comment by oskarkrawczyk** [comment]
Added the latest version.
