### ISSUE TITLE
Ajax json echo fails because of access control policy

### ISSUE THREAD

**Issue by Naddiseo** [jsfiddle/jsfiddle-issues#613]
Posting to the '/echo/json/' no longer works in recent browsers. The error given is:
> XMLHttpRequest cannot load http://jsfiddle.net/echo/json/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://fiddle.jshell.net' is therefore not allowed access.

Example: http://jsfiddle.net/yVbYQ/7016/ 

Using Chromium 41.

**Comment by zalun** [comment]
This is the example from docs - http://jsfiddle.net/zalun/QsHw4/ - working fine. Best is to use URL withou a domain it will always be in the right one.
