### ISSUE TITLE
echo api endpoint requires the ending slash '/'

### ISSUE THREAD

**Issue by huochunpeng** [jsfiddle/jsfiddle-issues#616]
I was struggling again to get /echo/json to work this morning. I hit the same issue years ago but totally forgot again about the endpoint requires ending '/'.

So "/echo/json" doesn't work, it has to be "/echo/json/".

This is really really annoying. Even worse, the wrong endpoint "/echo/json" still gives me a "200" response with one empty json.

Could you please fix all the echo APIs to allow the ending slash to be optional?

Best Regards,
Chunpeng

**Comment by oskarkrawczyk** [comment]
Sorry, no plans on changing this behavior in the current version of JSFiddle. Will be sorted in the future version. Closing.
