### ISSUE TITLE
login loop

### ISSUE THREAD

**Issue by victornpb** [jsfiddle/jsfiddle-issues#618]
I'm trying to log in to my account, and I'm stuck in a login loop

I click on "login" button and it lands on http://jsfiddle.net/user/login/

type my credentials, click Login

it redirect me to: http://jsfiddle.net/user/login/?next=/user/dashboard/ 
and it's the same page.

No error, or bad username or password.

Safari 7.1.7 OS X 10.9.5

**Comment by oskarkrawczyk** [comment]
@victornpb works fine on my end.

Have you tried a different browser?

**Comment by oskarkrawczyk** [comment]
Can't replicate, closing.
