### ISSUE TITLE
Quick-add support for CSS frameworks

### ISSUE THREAD

**Issue by anndresorozco** [jsfiddle/jsfiddle-issues#619]
It would be nice to have a "Quick-add" feature for some famous CSS frameworks like [Bootstrap](http://getbootstrap.com/), [Foundation](http://foundation.zurb.com/), [Pure.css](http://purecss.io/), etc. It could be helpful to add some css to the fiddles more easily.

**Comment by oskarkrawczyk** [comment]
No plans of adding this to the current JSFiddle version. Sorry.
