### ISSUE TITLE
Example on page "Echo Javascript file and XHR requests" are not HTTPS friendly

### ISSUE THREAD

**Issue by alaycock** [jsfiddle/jsfiddle-issues#621]
The example for JSONP on the documentation page [Echo Javascript file and XHR requests](http://doc.jsfiddle.net/use/echo.html) is not HTTPS friendly. It links to [this non-HTTPS friendly](https://jsfiddle.net/zalun/yVbYQ/). Instead, [here is a HTTPS friendly fiddle](https://jsfiddle.net/5trxhxez/).

**Comment by oskarkrawczyk** [comment]
Those docs need to be retired since we're not updating them anymore.
