### ISSUE TITLE
Enyo major nightly update

### ISSUE THREAD

**Issue by JayCanuck** [jsfiddle/jsfiddle-issues#622]
Enyo is undergoing a massive shift is how code in it is organized and structured. For the nightly option of Enyo, could the js/css be updated to:

> Core:
> http://nightly.enyojs.com/latest/lib/enyo/dist/enyo.js
> http://nightly.enyojs.com/latest/lib/enyo/dist/enyo.css

> Checkbox for "Onyx":
> http://nightly.enyojs.com/latest/lib/onyx/dist/onyx.js
> http://nightly.enyojs.com/latest/lib/onyx/dist/onyx.css

> Checkbox for "Layout":
> http://nightly.enyojs.com/latest/lib/layout/dist/layout.js
> http://nightly.enyojs.com/latest/lib/layout/dist/layout.css

> Checkbox for "Canvas":
> http://nightly.enyojs.com/latest/lib/canvas/dist/canvas.js

> Checkbox for "Moonstone (dark)":
> http://nightly.enyojs.com/latest/lib/moonstone/dist/moonstone.js
> http://nightly.enyojs.com/latest/lib/moonstone/dist/moonstone.css

> Checkbox for "Moonstone (dark)":
> http://nightly.enyojs.com/latest/lib/moonstone/dist/moonstone.js
> http://nightly.enyojs.com/latest/lib/moonstone/dist/moonstone-light.css

> Checkbox for "Spotlight":
> http://nightly.enyojs.com/latest/lib/spotlight/dist/spotlight.js

> Checkbox for "iLib":
> http://nightly.enyojs.com/latest/lib/enyo-ilib/dist/enyo-ilib.js

And please remove g11n checkbox please. :)

Thanks!
cc: @zalun @oskarkrawczyk

**Comment by webOS101** [comment]
Any update on this issue?

**Comment by oskarkrawczyk** [comment]
@webOS101 @JayCanuck Done. Must have missed the notification about this.

**Comment by webOS101** [comment]
Thank you!
