### ISSUE TITLE
Ember JS

### ISSUE THREAD

**Issue by gitowiec** [jsfiddle/jsfiddle-issues#623]
Cześć
Najpierw chciałem podziękować za bardzo przydatne narzędzie. Bez Was byłoby trudniej!
Wielka prośba o dodanie wielu wersji Ember JS do bibliotek. Np od 0.9 wzwyż.
Nie ma tego dużo, ale między samymi wersjami potrafią być olbrzymie różnice (np 1.12 a 1.13!)
Serdeczne pozdrowienia!

**Comment by oskarkrawczyk** [comment]
Ember jest dostępne w wersji `latest` - zawsze najnowsza.
