### ISSUE TITLE
Invalid redirect for secure content

### ISSUE THREAD

**Issue by jugglinmike** [jsfiddle/jsfiddle-issues#624]
Although gh-524 was closed without comment, it looks as though JSFiddle currently supports HTTPS:

```
$ curl -i https://jsfiddle.net/cowboy/jNrVD/embedded/js,result/
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 19 Aug 2015 14:52:33 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
```

So thank you! The problem we've recently identified is that content requested over HTTPS but *without a trailing slash* is inappropriately redirected to an insecure transport:

```
$ curl -i https://jsfiddle.net/cowboy/jNrVD/embedded/js,result
HTTP/1.1 301 MOVED PERMANENTLY
Server: nginx
Date: Wed, 19 Aug 2015 14:28:24 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Location: http://jsfiddle.net/cowboy/jNrVD/embedded/js%2Cresult/
```

This causes mixed content warnings (and, in newer browsers, failure to load) when the latter URL pattern is used to embed examples in securely-served documents. We're updating our content to include the trailing slash, but this issue may be affecting others, and it seems like it may be an easy problem to correct.

Thanks for JSFiddle!

**Comment by telkomsel13** [comment]
#1

**Comment by oskarkrawczyk** [comment]
Looks like it's working correctly.
