### ISSUE TITLE
"latest" or "head" tag for sharing

### ISSUE THREAD

**Issue by brokkc1** [jsfiddle/jsfiddle-issues#626]
I request a **"latest"** or **"head"** URI added to the share feature.

The latest tag would simply point to the head of the fiddle revision stack.

ie **"/ufhd1s8g/latest/"** or **"/ufhd1s8g/head/"**  -> **"/ufhd1s8g/54/"** while 54 is the head revision.

**Comment by oskarkrawczyk** [comment]
For now we have the **Save as base** feature which removes the revision number and uses the head version.

No plans on having additional segments in the URL to get to the head.
