### ISSUE TITLE
Missing POST Fields

### ISSUE THREAD

**Issue by kitsonk** [jsfiddle/jsfiddle-issues#627]
I raised issues #220 and #229 and I believe they were closed without resolution.  I have started looking at this again.  The Dojo Toolkit team are considering providing links to code examples to generate JSFiddles.  There are two problems though with the POST API that are prohibiting a clean export.

The first we need to add an attribute to the body tag to get proper styling of the theme for Dojo.  Second we need to be able to add an attribute to the script tag to be able to properly configure the Dojo library.  Both of these are assessable via the user interface.

<img width="245" alt="create_a_new_fiddle_-_jsfiddle" src="https://cloud.githubusercontent.com/assets/1282577/9560800/fb171488-4e20-11e5-8a38-85660d3cb0c8.png">

But according to the [documentation](http://doc.jsfiddle.net/api/post.html) there are not appropriate POST fields to make this work.

**Comment by oskarkrawczyk** [comment]
There are no plans on fixing this in the current version of JSFiddle. Sorry.

This will be present in the future rewritten version.
