### ISSUE TITLE
iframe sandbox attribute allow-modals missing

### ISSUE THREAD

**Issue by Activee** [jsfiddle/jsfiddle-issues#628]
Chrome 46 blocks alert messages in iframe to resolve the issue, the value allow-modals has to be added to the sandbox attribute. Without that this simple code won't work on some version of chrome : https://jsfiddle.net/activee/f0zfw6y1/

**Comment by jmnote** [comment]
+1
version 46.0.2490.71 m

**Comment by oskarkrawczyk** [comment]
Done

**Comment by vinodc** [comment]
@oskarkrawczyk The embedded version continues to have issues: https://jsfiddle.net/activee/f0zfw6y1/embedded/result/ Could allow_modals be added to the sandbox attribute there?

**Comment by AStoker** [comment]
I think this is related. But on iOS and Safari, the page loads with this error: 
`gopxcmye:1173:178 Error while parsing the 'sandbox' attribute: 'allow-modals' is an invalid sandbox flag.`

**Comment by aegaas** [comment]
This seems to still be an issue on Safari in Mac OS X 10.11. Can we reopen?
