### ISSUE TITLE
New tag text color is a regression in usability

### ISSUE THREAD

**Issue by Tyler-H** [jsfiddle/jsfiddle-issues#629]
Long-time fan of JSFiddle here. Unfortunately, a few weeks ago I noticed a change that so far seems to be permanent: markup tags are now colored dark red-orange; #E65544 to be exact. The previous color/colors were much better in that they helped serve as a visual cue for writing correct or incorrect, or invalid, tags. 

With the new color, making an error is nearly indiscernible, due to #E65544 being so close to the "error" color of #F00. Please, *please* revert the normal tag colors back to what they used to be.

**Comment by oskarkrawczyk** [comment]
@Tyler-H I agree. Will try to bring back the previous colors.

**Comment by oskarkrawczyk** [comment]
Fixed. To be deployed soon.
