### ISSUE TITLE
Update available Underscore versions

### ISSUE THREAD

**Issue by reefdog** [jsfiddle/jsfiddle-issues#630]
The latest version of Underscore available on JSFiddle is 1.4.4, but the actual latest version is [1.8.3](https://cdnjs.com/libraries/underscore.js) ([CDN link](https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js)). Can you add 1.8.3?

(If this isn't the proper outlet for requesting version bumps, let me know where to go! I looked through the docs and these issues and this seems to be the correct way.)

**Comment by oskarkrawczyk** [comment]
Done
