### ISSUE TITLE
JSFiddle is not working through the McAfee proxy as progress script is recognized as downloadable file

### ISSUE THREAD

**Issue by DoKZ** [jsfiddle/jsfiddle-issues#633]
JSFiddle is not working through the McAfee enterprise proxy and freezes at this loading screen:
![jsfiddle1](https://cloud.githubusercontent.com/assets/8306952/10387984/d00f0782-6e87-11e5-8125-51c15b905d3c.png)

It happens due to the following reasons:  
`/mwg-internal/de5fs23hu73ds/progress?id=Kr0jdk176A` file is recognized by McAfee as a downloadable file but not script. McAfee is displaying its downloading page instead of plain contents:
![jsfiddle4](https://cloud.githubusercontent.com/assets/8306952/10388039/5ac5c15e-6e88-11e5-956a-3634616e83bf.png)

That's what I see when I directly open `http://fiddle.jshell.net/mwg-internal/de5fs23hu73ds/progress?id=Kr0jdk176A`:
![jsfiddle3](https://cloud.githubusercontent.com/assets/8306952/10388045/71745244-6e88-11e5-8118-499c355b4f57.png)

As JSFiddle gets non-JS file, it, obviously, throws an error and everything goes wrong:
![jsfiddle2](https://cloud.githubusercontent.com/assets/8306952/10388186/95d1cef4-6e89-11e5-8056-d9937813af4c.png)

Probably, something's wrong with headers or some other settings, because all other scripts on JSFiddle and other sites always load properly.

Thank you.

**Comment by oskarkrawczyk** [comment]
Probably white-listing jsfiddle.net and jshell.net will solve the issue.

I have no way of fixing this anyway since looks like a McAfee issue.
