### ISSUE TITLE
Fiddles compiled with Babel throw a SecurityError

### ISSUE THREAD

**Issue by wehriam** [jsfiddle/jsfiddle-issues#634]
**Description:** Fiddles compiled with Babel throw a SecurityError.

```
Uncaught SecurityError: Failed to read the 'frame' property from 'Window': Blocked
a frame with origin "https://fiddle.jshell.net" from accessing a frame with origin
"https://jsfiddle.net". Protocols, domains, and ports must match.
```

**Browser and OS:** Chrome 46.0.2490.71, OSX 10.10.4

**Example:** https://jsfiddle.net/pushtell/1gzjgv2j/

<img width="1103" alt="screenshot 2015-10-16 16 08 06" src="https://cloud.githubusercontent.com/assets/81482/10552198/1ea48f50-7420-11e5-8657-09e87069c9e8.png">

**Comment by oskarkrawczyk** [comment]
The Chrome team has changed a few things with policy over iframes in 46 – probable reason.

Will investigate.

**Comment by oskarkrawczyk** [comment]
Ok, should be working as before.

**Comment by wehriam** [comment]
Great, thanks. I'm a huge fan of the service, let me know if there's anything I can do to help out in the future.

**Comment by oskarkrawczyk** [comment]
@wehriam Will do, thanks!
