### ISSUE TITLE
Edit Profile - "Use the form Luke"

### ISSUE THREAD

**Issue by bleesand** [jsfiddle/jsfiddle-issues#635]
Created a profile in JS fiddle, received the message "use the form Luke. Should default to user name. If this is not an option, then "Use the form is sufficient" 
![capture1](https://cloud.githubusercontent.com/assets/3442762/10615533/74fef0dc-772e-11e5-90a8-11d284c105fa.PNG)

**Comment by oskarkrawczyk** [comment]
It's a play on the classic phrase "Use the force, Luke".

Closing.
