### ISSUE TITLE
API calls not working when in Fullscreen Results view

### ISSUE THREAD

**Issue by iAmMortos** [jsfiddle/jsfiddle-issues#636]
I have a jsfiddle that does some basic API calls and populates DOM elements with the resulting data.
It works fine when I'm in the standard dashboard view, but when I try to view the "Full Screen Result", the API calls cease to work. Perhaps it's not the APIs, but this has never been an issue for any other jsfiddle I've created.

Essentially, the dashboard output view, and the full screen solution view are behaving differently, when I assume they're running the same code.

jsfiddle here: http://jsfiddle.net/iAmMortos/nxsmbwLq/

**Comment by zalun** [comment]
Working for me here - http://jsfiddle.net/iAmMortos/nxsmbwLq/show/

**Comment by oskarkrawczyk** [comment]
Here as well. Closing.

**Comment by iAmMortos** [comment]
Is there a way to reach that `/show/` view from the GUI? I was accessing "full screen mode" by copying and pasting the link from the "Share" dropdown, which comes in the form
> https://jsfiddle.net/iAmMortos/jfvdtd9c/embedded/result/
