### ISSUE TITLE
Update CodeMirror for source view!

### ISSUE THREAD

**Issue by caitp** [jsfiddle/jsfiddle-issues#637]
Here's a screenshot taken for a CL for Blink's devtools, about improving the rendering of newer script features.

<img width="686" alt="screen shot 2015-10-23 at 1 55 47 pm" src="https://cloud.githubusercontent.com/assets/2294695/10708705/48142a48-79df-11e5-8b8b-7bad5067f8bd.png">

As nice as it looks in the devtools with the patch (the patched version of the devtools visible in the bottom left corner), it still looks like horseshit on the jsfiddle website. Might be good to fix this up.

Pulling CodeMirror/mode/javascript from v5.8 should be good enough to make this look pretty and fix the weird template literal rendering bug.

**Comment by oskarkrawczyk** [comment]
Fixed. To be deployed soon.
