### ISSUE TITLE
Add PostCSS as styles pre/post-processor

### ISSUE THREAD

**Issue by MadLittleMods** [jsfiddle/jsfiddle-issues#639]
[PostCSS](https://github.com/postcss/postcss)

> PostCSS is a tool for transforming styles with [modular] JS plugins.

See [`postcss-use`](https://github.com/postcss/postcss-use) and [`postcss-plugin-context`](https://github.com/postcss/postcss-plugin-context) for sandboxing and having only certain plugins available.

PostCSS will run client-side or on the backend.

**Comment by oskarkrawczyk** [comment]
No plans on adding PostCSS in this version of JSFiddle.

Will have it in the future rewrite.

**Comment by MadLittleMods** [comment]
@oskarkrawczyk What is the reasoning behind closing issues that will come in the "future rewrite"? Could stash them in a [milestone](https://github.com/jsfiddle/jsfiddle-issues/milestones)

**Comment by oskarkrawczyk** [comment]
This repo will be disabled

**Comment by equinusocio** [comment]
Any update now? :)

**Comment by Tintress15** [comment]
z
