### ISSUE TITLE
Can not scroll page on safari

### ISSUE THREAD

**Issue by ajaxsys** [jsfiddle/jsfiddle-issues#641]
Hi, 
I can't scroll page on 'share full screen' result page.

reproduce step:
1) open this page use iPhone(8.4) or safari on Mac(10.9.5), 
https://jsfiddle.net/30v5kL6x/embedded/result/

2)  click search button to fill a long table.

3)  try scroll page, not working.

**Comment by oskarkrawczyk** [comment]
Unfortunately we have no plans on fixing this, since we're focusing on a new version of JSFiddle.
