### ISSUE TITLE
Enyo (nightly) missing css

### ISSUE THREAD

**Issue by JayCanuck** [jsfiddle/jsfiddle-issues#642]
Hi,

https://github.com/jsfiddle/jsfiddle-issues/issues/622 was implemented not too long ago, however the core Enyo (nightly) has the proper js but missing the css.

Could http://nightly.enyojs.com/latest/lib/enyo/dist/enyo.css please be added for Enyo (Nightly).

Thanks!

cc: @zalun @oskarkrawczyk

**Comment by oskarkrawczyk** [comment]
Done
