### ISSUE TITLE
Collaboration is broken

### ISSUE THREAD

**Issue by j-harding** [jsfiddle/jsfiddle-issues#645]
When going to a previously created jsfiddle, clicking "Collaboration" and sending the link to another person, we can't see each other.  It only works if the other person then sends ME the collaboration link after clicking "Collaboration" again.  It will also occasionally freeze for both users, which caused me to lose all of the progress on a jsfiddle during an interview I was conducting.

**Comment by oskarkrawczyk** [comment]
Can't really replicate this, works fine on my end. 

We're using TogetherJS which is maintained by @mozilla at https://github.com/mozilla/togetherjs – all issues regarding collaboration should be posted there.
