### ISSUE TITLE
Loading speed is really slow

### ISSUE THREAD

**Issue by paulirish** [jsfiddle/jsfiddle-issues#646]
I've never seen a load under 5s. Usually around 12 seconds.

I took a look and just concatenating the major JS and CSS into single files would probably make the load ~5x faster.

Plz?   :) :)

![image](https://cloud.githubusercontent.com/assets/39191/11173219/fd3e7672-8bc7-11e5-8a85-3756a04ed8fa.png)

**Comment by oskarkrawczyk** [comment]
Really depends on the location and ISP. In Europe the load time is never >5s.

<img width="384" alt="screen shot 2015-11-16 at 09 34 14" src="https://cloud.githubusercontent.com/assets/34213/11177344/39c8f414-8c45-11e5-8f6a-5ac663b8d7d0.png">

Nevertheless, I agree, it can't hurt to concat the files. I'm poking around with a Gulp flow to stitch them together. We'll see.

**Comment by oskarkrawczyk** [comment]
Fixed. Got down to 9 requests. To be deployed soon.

<img width="637" alt="screen shot 2015-11-17 at 14 01 46" src="https://cloud.githubusercontent.com/assets/34213/11253966/a9e541d0-8e3e-11e5-8ca4-cb1c2976f60a.png">

**Comment by gluons** [comment]
For now:

It takes 1.79 minutes to finish loading for me.  
Using on 100 mbps network.

![ภาพ](https://user-images.githubusercontent.com/4688092/82874503-3dc1a880-9f60-11ea-9afa-627d8dd2eb6e.png)

**Comment by oskarkrawczyk** [comment]
@gluons Load speed from shoutheast Asia is rellay low, and we're aware of that.

Improving this is on the todo.
