### ISSUE TITLE
Tidy Up breaks fat arrows

### ISSUE THREAD

**Issue by rtoal** [jsfiddle/jsfiddle-issues#648]
I can't believe this was not an existing open issue (I checked) but when I hit Tidy Up the fat arrows get split into `=` and `>` tokens with a space in between.

**Comment by rtoal** [comment]
@oskarkrawczyk This looks like you just fixed this today. :)

**Comment by oskarkrawczyk** [comment]
@rtoal it seems like updating the tidy library did the job :-)
