### ISSUE TITLE
Ctrl + S save shortcut doesn't work in Chrome

### ISSUE THREAD

**Issue by mjohnsonengr** [jsfiddle/jsfiddle-issues#649]
Windows 8.1 w/ Chrome 46.0.2490.86 m

When I hit Ctrl + S on a fiddle, instead of saving the fiddle, Chrome picks up the Ctrl+S shortcut and tries to save the page.

I saw a previous, related issue, #384 -- given it was closed a long time ago, and being ignorant of any policy here, I figured I'd create a new issue for this.

This seems to have happened in Chrome for a while for me.  If you need more info, let me know.  If Ctrl+S is infeasible due to technical restrictions, it'd be nice if you at least mapped a different save shortcut.

**Comment by unitycoder** [comment]
Same problem with Firefox, quite annoying..
 
btw. ctrl+s capture works fine in web2py [codemirror editor](https://github.com/web2py/web2py/blob/327c40cd1721025653504d8f49a8dd592a0e8438/applications/admin/static/codemirror/lib/codemirror.js)

**Comment by 42degrees** [comment]
Confirmed it does not work in either Chrome 51.0.2704.84 m or Firefox 47.0.  See [this answer on SO](http://stackoverflow.com/questions/93695/best-cross-browser-method-to-capture-ctrls-with-jquery).

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no features will be added. The new rewritten codebase will have this feature.
