### ISSUE TITLE
include Opal / Inline-reactive-ruby (Ruby => Javascript transpiler + React.js wrapper)

### ISSUE THREAD

**Issue by catmando** [jsfiddle/jsfiddle-issues#650]
Would be very great if you could add opal to your list of supported languages.

Its very straight forward to do. See  http://reactive-ruby.github.io/inline-reactive-ruby/ for a demo of a complete no-build, no server static site, that includes everything you would need.

The only thing you probably need to know is that to call the compilation from JS you would do:
`Opal.Opal.Compiler.$new(some_string).$compile()`
which will return a string of JS ready to eval.  If compilation fails it raises an error which you would catch.

That's it.

Any questions... I am always around at https://gitter.im/zetachang/react.rb ask for @catmando

**Comment by oskarkrawczyk** [comment]
Thanks fro the suggestion, but to be honest all Ruby-related things are just out of JSFiddle's scope.

**Comment by catmando** [comment]
At the risk of being very annoying, I want to make sure you understand the request, and what opal is:

It is just like coffeescript, or jsx, or babel all of which you do support.  It translates full ruby code into javascript.   Using it within your app requires no more support than you use for say coffeescript.  

Not sure in who's best interest it is to reject this issue... It would seem that you are a "for profit" app based on ad revenue.  Adding opal to your supported languages just gives you a wider audience base.

**Comment by oskarkrawczyk** [comment]
Revenue is not everything. For now Opal is not something we're interested in. Maybe in the future.
