### ISSUE TITLE
Mixed content warnings

### ISSUE THREAD

**Issue by Mottie** [jsfiddle/jsfiddle-issues#651]
If you open jsfiddle using `https` & set the framework to use jQuery v1.9.1 &amp; jQuery UI 1.9.2.

![2015-11-26 10_32_24-edit fiddle - jsfiddle](https://cloud.githubusercontent.com/assets/136959/11427520/0a9a904e-9429-11e5-94f3-606930fb3541.png)

jQuery UI gives a mixed content warning for both the css and js.

![2015-11-26 10_45_25-developer tools - https___jsfiddle net_mottie_2ytd8xf3_](https://cloud.githubusercontent.com/assets/136959/11427728/d9f8f550-942a-11e5-8ad7-e4c7264970d0.png)

This does not happen if you select jQuery 2.0.2 &amp; jQuery UI 1.10.3.

Those are the only two "recent" options to include jQuery UI. Would you consider adding the latest jQuery UI 1.11.4 along with the latest jQuery versions 2.1.4 and 1.11.3? Both of which have been available since March & April respectively.

**Comment by oskarkrawczyk** [comment]
Fixed mixed content warning and added jQ 2.1.4 + jQ UI 1.11.4.

Thanks for the heads up!
