### ISSUE TITLE
Page initialization fails on iOS

### ISSUE THREAD

**Issue by AStoker** [jsfiddle/jsfiddle-issues#653]
Loading up the page on an iPad with iOS 9, the page fails to load with these errors.
![screen shot 2015-11-30 at 4 34 41 pm](https://cloud.githubusercontent.com/assets/2907279/11485262/5ba64c44-9780-11e5-8e0c-03315f7e4e09.png)

Page is completely broken, can't run the page, javascript styling doesn't work, nor html or css styling. 
Tried loading up a working fiddle, as well as a new fiddle, on multiple devices, and none of it works.

**Comment by oskarkrawczyk** [comment]
Works fine on iOS9 without any content blockers, so I assume that's that.

**Comment by AStoker** [comment]
What kind of device are you running on? I have no content blockers active, and I cannot get it to load on either an iPad or iPhone, nor on the iOS Simulators for iPad or iPhone (both fresh, nothing installed).

**Comment by oskarkrawczyk** [comment]
Weird. Will try to check on a simulator
