### ISSUE TITLE
CSS field doesn't update in collaboration mode:

### ISSUE THREAD

**Issue by donnietron** [jsfiddle/jsfiddle-issues#654]
Steps to reproduce: 
- Open a new fiddle
- click the Collaborate tab
- select the invite a friend option that appears
- Copy and paste the given link into an incognito window (or send to someone on a different browser)
- modify the HTML and JAVASCRIPT fields in the initiating browser and see that they update in the remote browser
- modify the CSS field in the initiating browser and see that it **does not** update in the remote browser
- modify the CSS field in the remote browser and see that it **does not** update in the initiating browser

Tested in Chrome 46 and Firefox 42

**Comment by MattyDub** [comment]
+1 I'm seeing the same thing.

**Comment by MattyDub** [comment]
I see this in my Chrome console when I type in the CSS pane. No other panes have this.
<pre>
Object.extend.forEach	@	_dist-editor.js?update_02122015:1

Class.validateEditorInput	@	_dist-editor.js?update_02122015:29

i.extend.$owner	@	_dist-editor.js?update_02122015:1

(anonymous function)	@	_dist-editor.js?update_02122015:29

(anonymous function)	@	_dist-editor.js?update_02122015:1

(anonymous function)	@	_dist-editor.js?update_02122015:1

(anonymous function)	@	_dist-editor.js?update_02122015:8

xt	@	_dist-editor.js?update_02122015:6

wt	@	_dist-editor.js?update_02122015:6

Mt	@	_dist-editor.js?update_02122015:6

Ir.poll	@	_dist-editor.js?update_02122015:8

(anonymous function)	@	_dist-editor.js?update_02122015:8
session
</pre>

**Comment by oskarkrawczyk** [comment]
Fixed
