### ISSUE TITLE
Remove "jQuery Compat (edge)"

### ISSUE THREAD

**Issue by mzgol** [jsfiddle/jsfiddle-issues#655]
The jQuery team decided not to release jQuery Compat; please remove that option from the JS dropdown. The URL at http://code.jquery.com/jquery-compat-git.js will soon start redirecting to http://code.jquery.com/jquery-git.js, i.e. the regular version.

**Comment by oskarkrawczyk** [comment]
@mzgol Thanks for the heads up!

`jQuery Compat (edge)` is now disabled, `jQuery (edge)` has been added.
