### ISSUE TITLE
Some design notes

### ISSUE THREAD

**Issue by jeremenichelli** [jsfiddle/jsfiddle-issues#657]
First of all, congrats for the big update, it looks **awesome**!

What I noticed was that even on big screens the icons and the bar don't have enough *air* and it all seems a little overcrowded. By adding a little padding on the header bar and the nav and some margin between buttons it looks great to me.

![captura de pantalla 2015-12-01 a las 5 41 28 p m](https://cloud.githubusercontent.com/assets/3856481/11513639/0f84ead6-9853-11e5-96e6-5387483c0dcd.png)

Just a suggestion.

**Comment by oskarkrawczyk** [comment]
@jeremenichelli thanks for the kind words and the suggestions – really appreciated!  

I went through maaaany iterations of the header and what you see now is a compromise between its whitespace and the area that take the editors – the latter is way more important than the header. I might poke around withe the height a bit more in the future but for now I'll just leave it as it is.

**Comment by jeremenichelli** [comment]
Totally understandable, just a suggestion from a user :smile: cheers!
