### ISSUE TITLE
Ctrl+/ shortcut creates HTML comments inside of JavaScript pane

### ISSUE THREAD

**Issue by nfriend** [jsfiddle/jsfiddle-issues#658]
Executing the "comment selection" shortcut, `Ctrl+/` (or `Cmd+/` on mac), in the JavaScript pane creates HTML comments (`<!-- -->`) instead of JavaScript comments (`//` or `/* */`).

**Comment by oskarkrawczyk** [comment]
Yeah, no idea why CodeMirror keeps doing this.

**Comment by oskarkrawczyk** [comment]
Tried figuring this out without success. I don't plan spending anymore time on this since we'll be replacing CodeMirror with Ace in the future.
