### ISSUE TITLE
Console crowded with events

### ISSUE THREAD

**Issue by Siphon880gh** [jsfiddle/jsfiddle-issues#659]
Love the face lift but the console is crowded by click, focus, and formupdate events. Please give us an option to turn that off since I use console for debugging and I'm sure a lot of people do because console.log(...) is the bread and butter. Thanks!

**Comment by oskarkrawczyk** [comment]
@Siphon880gh that's really odd, there are no console.logs in place for such events.

Can you post more details? A screencast would be helpful.

**Comment by Siphon880gh** [comment]
The problem seems to be gone now. Thanks! Chrome's console had been showing "SEND" : "form-update" every hundreds of milliseconds (from what I remember). Cheers.
