### ISSUE TITLE
CSS editor autocompletes 'width' to 'widows'

### ISSUE THREAD

**Issue by teetow** [jsfiddle/jsfiddle-issues#660]
1. In the CSS editor, type at least two characters of the word "width"
2. Hit Tab
3. Attribute autocompletes to "widows"

**Detailed information**
'w' becomes width
'wi' becomes widows
'wid' becomes widows
'widt' becomes widows
'width' becomes widows

**Comment by oskarkrawczyk** [comment]
Emmet seems to work this way. Don't know why. I'll report this to them.

**Comment by teetow** [comment]
Ah, so it's Emmet under the hood. This seems related; you can add custom snippets to work around the issue (solution is for Sublime Text 2 but the config file seems related to Emmet)

http://stackoverflow.com/questions/21048127/how-to-remove-some-specific-autocomplete-in-sublime-text-2
