### ISSUE TITLE
:w in vim mode should trigger Update

### ISSUE THREAD

**Issue by nfriend** [jsfiddle/jsfiddle-issues#664]
Currently, in vim mode, the `:w` shortcut triggers a `t.save is not a function` error:

![image](https://cloud.githubusercontent.com/assets/1638631/11596077/a00e2e7e-9a78-11e5-9a4a-f565d0798017.png)

In my opinion, it would make sense for this shortcut to instead trigger an `Update` on the current fiddle.

**Comment by oskarkrawczyk** [comment]
@nfriend I'm not a VIM user myself, but my understanding is that `:w` is just a command to the scope of the panel (for example JS), not the whole editor.

But maybe what you're saying does make sense for VIM users. I'm really unsure. Would probably need someone else to share his thoughts on this.

**Comment by elsehow** [comment]
I'm a vim user as well, and I would definitely expect :w to trigger an update. JSFiddle would be just about perfect for me if it did this.

**Comment by oskarkrawczyk** [comment]
I'll try to poke around with this and make `:w` save/update the fiddle.

**Comment by oskarkrawczyk** [comment]
Unfortunately I couldn't find an easy way to add this.

We're all hands on the rewrite and in order to get it out sooner rather than later, we can't spend time on getting new features into the legacy codebase.

As per our rules, closing.
