### ISSUE TITLE
Indent size gives unpredictable indenting after Enter

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#667]
Congrats on the new, cleaner UX!

Steps for reproduction: 
1. Open http://jsfiddle.net/highcharts/LLExL/
2. Set the indent size to 4
3. Place the cursor behind line 3 in the JavaScript frame and hit Enter

**Comment by oskarkrawczyk** [comment]
@TorsteinHonsi thanks!

As to the indenting, it's just adapting to the line indent from the previous line, this is normal. Same is happening in Atom, Sublime Text. To me it would be unpredictable if I had 3 spaces and Return would jump to the new line with 4 or 2 (depending on the indent level set).

**Comment by TorsteinHonsi** [comment]
> Same is happening in Atom, Sublime Text.
Sounds like we're not seeing the same thing.

Here's a video showing what I see in both Chrome and Firefox on latest OS X: http://screencast.com/t/QZ4UDcv1F.

**Comment by oskarkrawczyk** [comment]
Weird. Can you share that fiddle with me?

**Comment by TorsteinHonsi** [comment]
It's in the first post, "steps for reproduction"...

**Comment by oskarkrawczyk** [comment]
I have no issues with that fiddle. Indenting works as expected.

**Comment by TorsteinHonsi** [comment]
I see the same thing across Chrome, Firefox and Safari. 

If I am not logged in, starting with the default settings, I get correct indenting with 2 spaces. When I change it to 4, it becomes like I showed you in the video. Now when I set it back to 2, it is still broken and behaves like the video.

**Comment by oskarkrawczyk** [comment]
Will have a look again

**Comment by TorsteinHonsi** [comment]
For your information, it it _not_ reproduceable on a clean installation with CodeMirror 5.9.0 and JavaScript parsing. [View on jsFiddle](http://jsfiddle.net/highcharts/m0upjrsg/1/).

**Comment by oysteinmoseng** [comment]
I can also reproduce this using the steps in the original post.

**Comment by jon-a-nygaard** [comment]
Same here, but I have not been able to reproduce this using a new fiddle.

**Comment by TorsteinHonsi** [comment]
I can see it in new fiddles as well. If I write the contents of the OP fiddle into the JS window, it goes bananas after the second line `$('#container').highcharts({`.

**Comment by oskarkrawczyk** [comment]
Sorry it's taking so long guys, the issue is a weird one. 

From the logic perspective it should work fine, but it doesn't.

Still investigating.

**Comment by TorsteinHonsi** [comment]
No prob Oskar. Did you manage to reproduce it?

**Comment by oskarkrawczyk** [comment]
Yes, it's a very weird issue that I believe is rooted somewhere deep within CodeMirror – I generally had many issues with CM lately when trying to do a more advanced setup. I'm seriously thinking about migrating to Ace at this point.

**Comment by oskarkrawczyk** [comment]
Did some alterations in the way the indent is applied to CM, seems like it helped a bit.

But the truth is that CM gets super confused about the indent level once the provided code is inconsistent with the indentation depth. So while it should work with clean code, it'll probably fail otherwise.

I'll be keeping an eye on this, and look for a better fix.
