### ISSUE TITLE
Feature Request - be able reorder external resources

### ISSUE THREAD

**Issue by mickeyvip** [jsfiddle/jsfiddle-issues#668]
Hello.

The _External Resources_ feature is very nice, but it is not convenient if one needs to reorder the resources - the whole process of adding needs to be restarted by removing and adding them in the correct load order.

Please make the reordering easier.

Thank you.

**Comment by oskarkrawczyk** [comment]
There are not plans on adding this until the complete rewrite of JSFiddle.

**Comment by Jaded-Design** [comment]
Seriously? This seems like such a minor function, just a simple ability to click an arrow and move a resource up or down... Honestly it doesn't make sense to not include this in whatever the next release is.

**Comment by mickeyvip** [comment]
Also it looks like this functionality was requested several times:

#599  - 16 October 2015(!), a year ago, and was closed with similar note - future version
#819

**Comment by oskarkrawczyk** [comment]
Added resources reordering.

**Comment by Jaded-Design** [comment]
@oskarkrawczyk That's Great! The community thanks you!

**Comment by mickeyvip** [comment]
Thank you!
