### ISSUE TITLE
onXXX event handler error

### ISSUE THREAD

**Issue by zanetu** [jsfiddle/jsfiddle-issues#669]
http://jsfiddle.net/13d9wzns/  (tested in Chrome 47.0.2526.73 and Firefox 38.4.0 on 64-bit Debian sid)

Expected: Counter increments upon click. 
Actual: "ReferenceError: handleClick is not defined" in console. 

Working example: http://liveweave.com/jwYX8g

**Comment by oskarkrawczyk** [comment]
Not a JSFiddle bug.

The load type is set to `onLoad` which as expected generates:

```
window.onload=function(){
  var i = 0;

  function handleClick() {
    document.getElementById('counter').textContent = ++i;
  }
}
```

You're defining your `handleClick` inside of an anonymous function, so the handle would not be available on the outside.
