### ISSUE TITLE
changes in current update get permanent

### ISSUE THREAD

**Issue by SergioCrisostomo** [jsfiddle/jsfiddle-issues#671]
Steps:

 - made a fiddle (jsfiddle.net/Sergio_fiddle/m2f64ez4/)
 - made some changes (added `<div>Morning!</div>`)
 - pressed _Run_
 - want to regreat and did a refresh in browser (reload saved url from above)
 - __problem:__ the new code (not saved) is permanent

If I get the url and open in another browser I get the correct code that was saved with that version, but in original browser where I made the fiddle changes don't disapear. Even after refresh.

**Comment by oskarkrawczyk** [comment]
@SergioCrisostomo It's a feature. It's called a local draft so you never loose the code you were working on.

I can see your confusion if you want to reset the fiddle by simply refreshing the page – I might add a button to reset the local draft to the original version (#672).

**Comment by SergioCrisostomo** [comment]
:+1: thanks for fast answer
