### ISSUE TITLE
Gist integration broken after new version of Fiddle came out

### ISSUE THREAD

**Issue by RyanVice** [jsfiddle/jsfiddle-issues#674]
I'm very close to finishing a book on React that uses JSFiddle's integration with GitHub Gists for a lot of samples and it appears the integration isn't working with the new version of JSFiddle and all my samples are now broken. We are supposed to be publishing in a few days so any help would be greatly appreciated.

**Comment by RyanVice** [comment]
![image](https://cloud.githubusercontent.com/assets/1588377/11689952/d0a34062-9e59-11e5-8572-42dfb70dc77f.png)

The image below shows the issue. You can see that the hash and URL in Fiddle are correctly configured according to the documentation but the source that is displayed is different.

**Comment by oskarkrawczyk** [comment]
@RyanVice did this started happening today or before today?

**Comment by RyanAtViceSoftware** [comment]
@oskarkrawczyk Today was the first day I noticed it.

**Comment by oskarkrawczyk** [comment]
Can you up JSFiddle on the link from the screenshot, open up Developer Tools, switch to Resources tab,  expand the Local Storage tree, highlight jsfiddle.net, see if an item with the key `draft[]` appears, if so, delete it, refresh the page, and tell me if that sorted the issue?

**Comment by oskarkrawczyk** [comment]
Actually, I'm pretty sure that's the issue.

I've changed some things so the draft doesn't get applied on the api pages.

That said you still need to remove all `draft[]` items from your Local Storage.

**Comment by RyanAtViceSoftware** [comment]
Seems to be working now. Thanks for the tip for deleting the local storage.
