### ISSUE TITLE
Panel-level editor options aren't saved in Chrome or IE

### ISSUE THREAD

**Issue by nfriend** [jsfiddle/jsfiddle-issues#675]
To reproduce:

1. Begin a new, empty fiddle in Chrome or IE
1. Change any of the JavaScript editor options (for example: language to TypeScript, framework to jQuery)
1. Refresh the page

All dropdowns will be reset to their default values.

It seems that Firefox is persisting these values correctly.

**Comment by oskarkrawczyk** [comment]
Only the code itself is stored as a local draft. The UI is not, until you actually save the fiddle.
