### ISSUE TITLE
Make HTML autocomplete disablable

### ISSUE THREAD

**Issue by rudiedirkx** [jsfiddle/jsfiddle-issues#677]
Can I disable these HTML autocompletions? (`|` is the cursor)

* `<p|` + `>` will add 2 lines and a `</p>`
* `<p>Text: <textarea name="text"| /></p>` + ENTER makes `<p>Text: <textarea name="text"></textarea> /></p>` which is wrong and not at all what I wanted.

I'm not asking you to fix these. It's impossible. Online editors just aren't good enough. I am asking you to make it disablable. The previous version was great: no automagic.

Thanks

**Comment by oskarkrawczyk** [comment]
<img width="471" alt="screen shot 2015-12-11 at 19 55 39" src="https://cloud.githubusercontent.com/assets/34213/11752701/48b2cbfc-a041-11e5-90fd-47f8d53e70c0.png">

**Comment by rudiedirkx** [comment]
Ooooh the HTML options aren't in the HTML options dropdown! Got it. Thanks.
