### ISSUE TITLE
With the redesign, 'fi' text looks weird

### ISSUE THREAD

**Issue by lorenmh** [jsfiddle/jsfiddle-issues#678]
This may have been intentional but with the font you are using, characters f and i, when together, becomes a new 'fi' character.  It looks really weird guys:

![screen shot 2015-12-11 at 10 39 31 am](https://cloud.githubusercontent.com/assets/5161502/11752280/875577ae-9ff3-11e5-87cf-1579a3b4b88d.png)

If you remove the style 'text-rendering: optimizeLegibility;' then it goes away.

Again, this may have been intentional but it looks weird.

**Comment by oskarkrawczyk** [comment]
What browser and OS are you using?

This doesn't happen on any of the machines I've tested with.

<img width="257" alt="screen shot 2015-12-11 at 19 53 35" src="https://cloud.githubusercontent.com/assets/34213/11752619/e4f11ec0-a040-11e5-97bd-2ad02673679f.png">

**Comment by oskarkrawczyk** [comment]
Tested a bit more, looks like specific versions of Chrome/Firefox on Yosemite and Windows 8 have this issue.

**Comment by lorenmh** [comment]
Yeah, I'm using Yosemite OS X 10.10.5 with Chrome 45.0.2454.85 (64-bit)

**Comment by oskarkrawczyk** [comment]
@lorenmh Should be fixed. Thanks for the heads-up!
