### ISSUE TITLE
Left column greater than 100% width; Right column inaccessible

### ISSUE THREAD

**Issue by skibulk** [jsfiddle/jsfiddle-issues#680]
While using both the old version and the redesigned version of JSFiddle, there is an error that occurs while using a right-docked Chrome Inspector Panel. If the site's column resizer is dragged behind the Inspector in this case, the left column is assigned a width greater than 100%. The worst part is that this setting is saved to local preferences. Refreshing the page won't recover access to the right column either.

**Comment by oskarkrawczyk** [comment]
#493
