### ISSUE TITLE
upgrade reactjs

### ISSUE THREAD

**Issue by flyher** [jsfiddle/jsfiddle-issues#681]
hi,
1.i mix the Babel  and Javascript in one file,it show the error.
only one select can choice, but i need use Babel and Javascript code in different file with one html. 
![_2015-12-15_14-02-25](https://cloud.githubusercontent.com/assets/5570324/11803381/5d9fea4e-a335-11e5-9656-27096846a808.png)

2.the latest react on jsfiddle is 0.14.3. Can you update it to the latest version.

3.the error message can cover the code.
![2](https://cloud.githubusercontent.com/assets/5570324/11803607/5f10f402-a337-11e5-81ee-7bdd8f465ead.png)

thank you.

**Comment by oskarkrawczyk** [comment]
1. You can pick only one
2. Updated
3. Don't use <script> tags inside of the JS panel and the warning will disappear

**Comment by flyher** [comment]
@oskarkrawczyk 
thank you very much.
