### ISSUE TITLE
Type in Local Drafts help text

### ISSUE THREAD

**Issue by rtoal** [jsfiddle/jsfiddle-issues#682]
Sorry to be pedantic but

    so you don't lose a thing (even if your offline).

should be changed to

    so you don't lose a thing (even if you're offline).

in the info text for Local Drafts (which is an awesome feature BTW).

Heh - the title of this issue should be "Typo in...." not "Type in..." See, we've all been there....

**Comment by oskarkrawczyk** [comment]
Whoops, my bad. Fixed.
