### ISSUE TITLE
Drafts don't save external resources

### ISSUE THREAD

**Issue by amk221** [jsfiddle/jsfiddle-issues#683]
Resuming a draft is a great feature, but they won't work without their external resources.

**Comment by jensenak** [comment]
This bug bit me when I tried to click on the annoying "alert" icon in the top left and accidentally clicked the  jsfiddle icon and navigated to a new fiddle. I restored my draft and found all external resources were gone.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
