### ISSUE TITLE
Code boxes are gray

### ISSUE THREAD

**Issue by jancoow** [jsfiddle/jsfiddle-issues#686]
For some reason all code boxes are gray: I can't see any code in it. Also the output isn't showing.
This happens in Chromium on Linux.

![schermafdruk van 2015-12-17 12-51-30](https://cloud.githubusercontent.com/assets/9000749/11869087/f2deb7f6-a4bc-11e5-9409-d46d2e81d5c2.png)

**Comment by oskarkrawczyk** [comment]
What's the fiddle URL?

**Comment by jancoow** [comment]
It's with all fiddles. Also when creating a new fiddle. I noticed that i've the same issue in firefox.

**Comment by oskarkrawczyk** [comment]
Are there there any console errors?

Maybe it has something to do with the Fira font.

If you find the `.CodeMirror` element for one of the code panels, and uncheck the `font-family` declaration, will the text appear?

<img width="1129" alt="screen shot 2015-12-17 at 19 44 38" src="https://cloud.githubusercontent.com/assets/34213/11878583/fe4f5e94-a4f6-11e5-9ca4-396a451381e6.png">

**Comment by jancoow** [comment]
Mm. The font was the problem. When changing it to Arial everything appears again. Am i missing this font?

**Comment by oskarkrawczyk** [comment]
Very interesting, you shouldn't be missing anything since there are two fonts from Google Fonts used on JSFiddle and I can see one of them renders, but Fira for some reason does not.

In Dev Tools -> Network, are there any requests that fail, especially for fonts?

**Comment by jancoow** [comment]
Nope, there are no errors or requests that fail. 

![schermafdruk van 2015-12-17 20-04-58](https://cloud.githubusercontent.com/assets/9000749/11879101/9a03d7f0-a4f9-11e5-9fdc-f5fab09ef550.png)

If install fira-mono on my system i can see the text, and after removing the font on my system the text disappears again.

**Comment by oskarkrawczyk** [comment]
Yep. https://github.com/google/fonts/issues/10

Tried a different version of Fira Mono, try now (refresh your cache just in case).

**Comment by jancoow** [comment]
Nope, still not working.

**Comment by oskarkrawczyk** [comment]
Well in that case not much I can do about it at this time. I'll leave font on the Mozilla's CDN so that once they fix it, JSFiddle will have the fix asap.

**Comment by kylekatarnls** [comment]
Hi, IMHO, no matter what font CDN you use, you should have a fallback with a standard font type:
```css
font-family: 'Fira', monospace;
```

**Comment by oskarkrawczyk** [comment]
Obviously

**Comment by kylekatarnls** [comment]
I say that because I have jsffidle embeded that display with a sans-serif font and it seems to be a random Mozilla CDN bug too.

**Comment by oskarkrawczyk** [comment]
We're not using Mozilla's CDN anymore, it was unreliable. Font stack fallback's to at least 7 monospaced fonts.

**Comment by kylekatarnls** [comment]
Strange, I clicked today on Embed, paste the stript tag and I can see https://code.cdn.mozilla.net/fonts/fira.css in the Network console. Normal?

**Comment by oskarkrawczyk** [comment]
Flushed the cache, should be ok now.

**Comment by kylekatarnls** [comment]
Thanks. Great! Never see a so fast support!
