### ISSUE TITLE
Broken html header

### ISSUE THREAD

**Issue by littleguga** [jsfiddle/jsfiddle-issues#687]
Here some screenshots:
![image](https://cloud.githubusercontent.com/assets/12018713/11912214/6e7e736e-a644-11e5-8e57-9cef9fc6c90c.png)
![image](https://cloud.githubusercontent.com/assets/12018713/11912219/8f211ac2-a644-11e5-9768-3b51c5501ede.png)

I have last Chrome, win7 64x.

**Comment by oskarkrawczyk** [comment]
It'll happen everywhere when the window is that small.

I won't be fixing this in this version of JSFiddle since it's impossible to use it anyway in a window this small.
