### ISSUE TITLE
Ractivejs external framework cdn inaccessible due to jsfiddle security policy

### ISSUE THREAD

**Issue by lazylester** [jsfiddle/jsfiddle-issues#689]
Selecting ractivejs as a framework appears to attempt to load from http://cdn.ractivejs.org/latest/ractive.js.

However this is now inadmissible in jsfiddle as the security policy requires https access to frameworks.

I imagine you need the ractive devs to make this available over https and then modify the access url in jsfiddle, so I'll prompt the ractive devs to add a comment to this issue with the correct url to use.

**Comment by oskarkrawczyk** [comment]
Switched to use the stable versions of Ractive. 0.7.3 has been added and works over SSL.

If the guys from Ractive enable SSL on their domain, the (now hidden) EDGE and LATEST versions will start working.

**Comment by Rich-Harris** [comment]
We've been meaning to enable SSL – this might be the kick in the pants we need. In the meantime though, [this template fiddle](http://jsfiddle.net/rich_harris/va6jU/) continues to work with the edge version, and you can happily fork it (just make sure you stay on HTTP!)
