### ISSUE TITLE
Display a warning on over SSL fiddles with unsecure resources 

### ISSUE THREAD

**Issue by oskarkrawczyk** [jsfiddle/jsfiddle-issues#690]
We're now defaulting to SSL - all new fiddles are created over SSL. 

While existing fiddles can be accessed over SSL or non-SSL, it would be good to display a warning that the fiddle is probably broken if he has added unsecure resources in a secure fiddle.

**Comment by MichaelErmer** [comment]
+1

**Comment by alcoheca** [comment]
Please for the sake of humanity get this fixed for all old fiddles.

It's insanely annoying

**Comment by alcoheca** [comment]
..you can't even edit the existing resources..

**Comment by oskarkrawczyk** [comment]
Warning added.

<img width="687" alt="screen shot 2016-11-20 at 10 44 58" src="https://cloud.githubusercontent.com/assets/34213/20461947/69ae084e-af0e-11e6-9f2e-5695d093d8e5.png">
