### ISSUE TITLE
Not seeing microphone for Collaborate

### ISSUE THREAD

**Issue by jaminroe** [jsfiddle/jsfiddle-issues#691]
Was trying to use the microphone feature for collaboration, but there is no mic prompt showing up in Chrome. I'm on the latest version:

![image](https://cloud.githubusercontent.com/assets/1559447/11947107/5753a54a-a830-11e5-9dee-45318fcb5abe.png)

**Comment by oskarkrawczyk** [comment]
Works fine here.

<img width="1231" alt="screen shot 2015-12-22 at 08 24 02" src="https://cloud.githubusercontent.com/assets/34213/11950085/72b46702-a885-11e5-9507-262dcceeb4e3.png">

Collaboration is done with TogetherJS, if you feel  there's an issue with it, you can report issues here: https://github.com/mozilla/togetherjs/issues

**Comment by jaminroe** [comment]
Don't see that when I click the lock

**Comment by jaminroe** [comment]
Yes, for some reason the mic isn't working on this fiddle of mine: http://jsfiddle.net/jaminroe/3q8kuL0c/. Please don't edit the fiddle though, using it for a presentation.

**Comment by oskarkrawczyk** [comment]
@jaminroe You've probably dismissed it for the jsfiddle.net domain. I'd suggest looking for a setting in your browser

**Comment by jaminroe** [comment]
I already had accepted: 

<img width="525" alt="screen shot 2015-12-22 at 11 00 01 am" src="https://cloud.githubusercontent.com/assets/1559447/11959419/2cb725bc-a89b-11e5-8fa3-42a69f1496b9.png">

**Comment by oskarkrawczyk** [comment]
@jaminroe Maaaaybe togetherjs has stored something weird for that fiddle – see devtools Resources and Local Storage. I believe this is where they keep their config.

**Comment by jaminroe** [comment]
Yeah probably. Thanks again though!

**Comment by jaminroe** [comment]
Happening again :( http://jsfiddle.net/jaminroe/q9jLd1j4/

**Comment by jaminroe** [comment]
Yup, I just confirmed that https://github.com/jsfiddle/jsfiddle-issues/issues/691#issuecomment-167138219 is the issue :)
