### ISSUE TITLE
Change title on save 

### ISSUE THREAD

**Issue by zalun** [jsfiddle/jsfiddle-issues#694]
Haven't checked it - just reporting

18:04 < amanaaxe> or anyone know how to get a fiddle that was not saved in my chrome history? apparently clicking fork>save>update just changes window.location and chrome sweetly didnt save the URL
18:10 < amanaaxe> nvm just the title wasnt there *PHEW*

**Comment by oskarkrawczyk** [comment]
No point of fixing this in the current version, too much work. Will be working in the next.
