### ISSUE TITLE
Editor settings buttons have outline

### ISSUE THREAD

**Issue by totalamd** [jsfiddle/jsfiddle-issues#696]
Editor settings buttons (HTML, CSS, JS) have standard dotted active link outline while clicking on it.

**Comment by oskarkrawczyk** [comment]
You mean checkboxes in the Embed settings?

**Comment by totalamd** [comment]
Not really, I mean HTML / CSS / JS settings buttons turn outline when clicked:
![screenshot@imgur](http://i.imgur.com/NB52ocD.png)

**Comment by oskarkrawczyk** [comment]
I'll look into that.
