### ISSUE TITLE
Embedded iframe content is too tall (100vh + 50px)

### ISSUE THREAD

**Issue by laukstein** [jsfiddle/jsfiddle-issues#697]
Embedded iframe content always has scrollbar since `#tabs #result` has `height: 100vh` and above tab has 50px... In order to fix change to `height: calc(100vh - 50px);`.
See issue in example http://jsfiddle.net/laukstein/VNsdy/embedded/result/

**Comment by oskarkrawczyk** [comment]
@laukstein Thanks, was just about to release a hotfix
