### ISSUE TITLE
Edit in JSFiddle link not working

### ISSUE THREAD

**Issue by xameeramir** [jsfiddle/jsfiddle-issues#698]
Look at the fiddle embedded [here](http://xameeramir.github.io/seo-cheat-sheet/). The visitors of the site are not be able to edit the fiddle. 

>Error 404
>We're truly sorry, but there is no such page.

The link returns 404.

**Comment by oskarkrawczyk** [comment]
Will have a look

**Comment by oskarkrawczyk** [comment]
Fixed. Thanks for brining this to my attention!
