### ISSUE TITLE
Headway notifications seems to be too much

### ISSUE THREAD

**Issue by xameeramir** [jsfiddle/jsfiddle-issues#699]
These notifications are repeatedly shown:

 - Local drafts
 - TypeScript support
 - Changes to how local drafts work
 - New embeds and Embed Creator

Out of these, *Local drafts* is the oldest one. Now whenever a new notification comes, **this** oldest item also gets added in `total notifications count`.

That top left red pop up, annoys end users because it distracts them from the main editor.

**Comment by oskarkrawczyk** [comment]
Headway probably needs to readjust some stuff. Closing as it's not a JSFiddle issue.

**Comment by xameeramir** [comment]
@oskarkrawczyk maybe, you can share this with Headway. I do not know anyone there.

**Comment by oskarkrawczyk** [comment]
I will
