### ISSUE TITLE
jsfiddle frameworks and extension options not showing 

### ISSUE THREAD

**Issue by swydell** [jsfiddle/jsfiddle-issues#700]
I can't access the frameworks or extension options on my jsfiddle page. This is what my page looks like. Is there a way for me to open my frameworks and extension options.
![my jsfiddle](https://cloud.githubusercontent.com/assets/10273250/12077381/4f37401a-b195-11e5-821d-9f5d1f4b6b73.png)

**Comment by oskarkrawczyk** [comment]
<img width="514" alt="screen shot 2016-01-03 at 11 09 34" src="https://cloud.githubusercontent.com/assets/34213/12078252/7dc3f85e-b20a-11e5-968b-2349995c595a.png">
