### ISSUE TITLE
Embed dropdown goes off the left of the screen when browser window is wide

### ISSUE THREAD

**Issue by LB--** [jsfiddle/jsfiddle-issues#701]
When I click Embed, some of the dropdown goes off the left of the screen and I can't access it.
![image](https://cloud.githubusercontent.com/assets/1296838/12082193/12c3404c-b254-11e5-9002-cf27bf6ca990.png)
Google Chrome Version 47.0.2526.106 m (64-bit), with a 1080p monitor - I only cropped the screenshot on the right and bottom, the top left corner is the top left corner of the page.

Strangely, if I make my browser window _smaller_, the issue goes away upon reopening the dropdown - it seems only very wide browser windows cause this to happen. Seems like the dropdown width is calculated based on the width of the viewport and there's no limit to stop it from going off the edge of the screen.

**Comment by Tyler-H** [comment]
Reproduced in Firefox  43.0.3 as well.

**Comment by oskarkrawczyk** [comment]
Fixed
