### ISSUE TITLE
Tutorial needs an update

### ISSUE THREAD

**Issue by stelovsky** [jsfiddle/jsfiddle-issues#703]
In http://doc.jsfiddle.net/tutorial.html:
1) In "Activate MooTools" it reads:
  On the left-hand side of the page, click “Frameworks and Extensions”
![image](https://cloud.githubusercontent.com/assets/1028809/12109748/e4d00cf6-b339-11e5-9906-4ff61e9825f3.png)
There are no “Frameworks and Extensions” there anymore, to activate MooTools, click "JavaScript" in bottom-right pane then click “Frameworks and Extensions”
Also, the title "Activate MooTools" should be aligned right underneath the screenshot.
2) the link to "Andrew Wooldridge’s List of Stunning examples" on the bottom of the page is broken:
![image](https://cloud.githubusercontent.com/assets/1028809/12109729/b3720bc8-b339-11e5-9f90-602271128788.png)

**Comment by oskarkrawczyk** [comment]
Yes, all of this needs to be scrapped and re-done. Already working on it, but it takes time.
