### ISSUE TITLE
Inspect element in Chrome 47 not working as expected

### ISSUE THREAD

**Issue by alvarotrigo** [jsfiddle/jsfiddle-issues#705]
The CSS panel still showing old CSS code even it has been changed in jsfiddle.

A way to reproduce it:
- Open https://jsfiddle.net/
- Type `<span>aaaaa</span>` in the HTML panel
- Type `span{  background:yellow; }` in the CSS panel
- Click Run (or save)
- Right click over the span in the result panel > inspect element
- You will see the `span{  background:yellow; }` in the Chrome inspector's CSS panel
- Change the style in jsfiddle CSS panel to `span{  background:red; }`
- Click Run (or save)
- Right click over the span in the result panel > inspect element
- You will see the `span{  background:yellow; }` in the Chrome inspector's CSS panel instead of the expected `span{  background:red; }`

You can either close or keep the Chrome inspector open, the result will be the same. 

I've tested it in Browserstack to make sure it was not a problem of my Chrome installation. Same result.
Using the latest stable version: Chrome 47.0.2526.106 m

**Comment by oskarkrawczyk** [comment]
Closing and reopening inspector shows `red` for me. 

Seems like that's how inspector works. Definitely not a JSFiddle issue.

**Comment by alvarotrigo** [comment]
> Closing and reopening inspector shows red for me.

Right, my mistake.

It seems to be a Chrome issue then: https://code.google.com/p/chromium/issues/detail?id=530799&q=inspector%20css&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified
