### ISSUE TITLE
Embedded JSFiddle in React.js Docs not scrolling on iPad

### ISSUE THREAD

**Issue by muhammad-saleh** [jsfiddle/jsfiddle-issues#706]
Dears,
I was reading React.js documentation and they use your embedded version
I was using my iPad Mini
They have a long snippets that needs to be scrolled down to view it all
So the issue is that I wasn't able to scroll the embedded iframe at all which made it unusable

When I tried to scroll it down the whole page scrolled down and not your iFrame

**Update:**
After a further investigation this issue happens on both Chrome and Safari on iPad
But the weird thing I found is that I was able to scroll normally ONLY in the first snippet but not in the latter

Try it here please:
[Thinking in React](https://facebook.github.io/react/docs/thinking-in-react.html)
Thanks.

**Comment by NFCorp2016** [comment]
OK

**Comment by oskarkrawczyk** [comment]
Closing since React docs are no longer using JSFiddle.
