### ISSUE TITLE
Confirm "Leave Page" upon clicking the top-left logo

### ISSUE THREAD

**Issue by whitneywooyy** [jsfiddle/jsfiddle-issues#707]
Hi there, I've now one too many times accidentally hit the JSFiddle logo in the top-left corner when I was actually trying to click "Run"...and have consequently lost all my work, therefore I'm making a suggestion to enable an alert to allow the user to confirm that they want to leave the current fiddle and begin a new one. Other options would be to open a new fiddle in a new tab, or move the "Run" button to another location in the menu. Please consider making this change.

**Comment by oskarkrawczyk** [comment]
@whitneywooyy All unsaved work is stored locally as a draft. Simply bring back the stored version.

<img width="295" alt="screen shot 2016-01-07 at 22 04 13" src="https://cloud.githubusercontent.com/assets/34213/12182777/a00825ce-b58a-11e5-9ad8-c1e09793b5d7.png">

**Comment by whitneywooyy** [comment]
I see, thank you. Although, perhaps it would be best to consider something along those lines for user experience-sake? Thanks.

**Comment by oskarkrawczyk** [comment]
Nope, we've replaced the on-leave-alert with local drafts.
