### ISSUE TITLE
No Frameworks and Extensions showing on sidebar

### ISSUE THREAD

**Issue by JESii** [jsfiddle/jsfiddle-issues#708]
I am not seeing the "frameworks and extensions" link which the documentation says is on the side bar. Thus, no obvious way to specify which JS framework I want to use. Tried on both Firefox/Chrome and same result. This is all described in the docs at 
![image](https://cloud.githubusercontent.com/assets/486/12197335/03c8700c-b5bb-11e5-9e80-37929bc39359.png).

**Comment by oskarkrawczyk** [comment]
Docs are out of date.

<img width="809" alt="screen shot 2016-01-08 at 13 56 04" src="https://cloud.githubusercontent.com/assets/34213/12198367/9537ffea-b60f-11e5-8aa1-89c425469da4.png">

**Comment by JESii** [comment]
Got it; thanks!
