### ISSUE TITLE
font not always loading properly

### ISSUE THREAD

**Issue by zalun** [jsfiddle/jsfiddle-issues#709]
hellyeah> sometimes i got this error from jsfiddle Font from origin 'http://code.cdn.mozilla.net'
                  has been blocked from loading by Cross-Origin Resource Sharing policy: No
                  'Access-Control-Allow-Origin' header is present on the requested resource. Origin
                  'http://jsfiddle.net' is therefore not allowed access.

**Comment by oskarkrawczyk** [comment]
Moved away from Mozilla's CDN
