### ISSUE TITLE
NS_ERROR_STORAGE_CONSTRAINT error in Firefox

### ISSUE THREAD

**Issue by xraphael75** [jsfiddle/jsfiddle-issues#710]
I can't get this site to work at all in Firefox. I get these errors:

NS_ERROR_STORAGE_CONSTRAINT in togetherjs.js line 85
NS_ERROR_STORAGE_CONSTRAINT in _dist-editor.js?update_05_01_2016_1 line 32
NS_ERROR_STORAGE_CONSTRAINT in app.js line 1

and nothing in the code-entry area loads. Using FF 43.0.4.

**Comment by oskarkrawczyk** [comment]
Can't replicate. No similar reports have been issued. Closing.
