### ISSUE TITLE
Can't run any fiddle due to mozilla cdn

### ISSUE THREAD

**Issue by eko24** [jsfiddle/jsfiddle-issues#711]
Hello,
When I simply vistit https://jsfiddle.net/ or any other fiddle I see this error in my console:  
![image](https://cloud.githubusercontent.com/assets/758017/12369628/da8a16f6-bc03-11e5-8ef9-77dd13ffb67f.png)
(Font from origin 'https://code.cdn.mozilla.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://jsfiddle.net' is therefore not allowed access.)

FYI: I'm using Chrome 47.0.2526.106 on Windows 8
Let me know if I can provide you any additional info

**Comment by eko24** [comment]
**UPDATE: I'm able to run fiddles**
Sorry, it seems I've tryed to run broken fiddle.
But mentioned error in console still presents

**Comment by eko24** [comment]
#709

**Comment by oskarkrawczyk** [comment]
I see no such error.

Have you tried incognito mode (without any extensions)?

**Comment by eko24** [comment]
@oskarkrawczyk yep, still able to reproduce:
![image](https://cloud.githubusercontent.com/assets/758017/12388693/1104d146-bddd-11e5-9c03-3b714f94f717.png)

**Comment by oskarkrawczyk** [comment]
Can you access https://code.cdn.mozilla.net/fonts/fira.css without any issues?

**Comment by oskarkrawczyk** [comment]
Switched CDN to a different one. Should work.

**Comment by eko24** [comment]
@oskarkrawczyk I'm able to see https://code.cdn.mozilla.net/fonts/fira.css
Now I don't see mentioned error, so I close the issue.
Thank you for fixing it :+1:
