### ISSUE TITLE
Tidy removes whitespace before pseudo-classes

### ISSUE THREAD

**Issue by mgiuffrida** [jsfiddle/jsfiddle-issues#712]
`div :first-child` becomes `div:first-child`, changing the meaning from "the first child of every div" to "every div that is a first child".

Using a pseudo-class without a subject is acceptable; for example, [`:link { color: red }`](https://www.w3.org/TR/REC-CSS2/selector.html#link-pseudo-classes).

Repro case: https://jsfiddle.net/mgiuffrida/w0qbwref/

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
