### ISSUE TITLE
Raphael 2.1.0 not working

### ISSUE THREAD

**Issue by JohnReeves** [jsfiddle/jsfiddle-issues#715]
After choosing the javascript library Raphael 2.1.0, the simple line drawing doesn't work in jsfiddle:

var paper = Raphael(10, 50, 600, 300);
paper.path("M 10 0 10 125 z").attr({stroke: 'black', 'stroke-width': 5});

copied to jsbin.com, renders a vertical line, as expected.

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by JohnReeves** [comment]
Thank you! The AI Emojis worksheets I use to teach kids the beauty of coding work again https://jsfiddle.net/mf32mwgo/
