### ISSUE TITLE
"Save"/"Update" doesn't reload the "Result"-pane

### ISSUE THREAD

**Issue by hurda** [jsfiddle/jsfiddle-issues#716]
When adding code and saving it as a new fiddle or updating an existing fiddle, the result-pane is not (re)loaded to represent the code.

The user has to execute "Run" or refresh the page to see the changes in the "Result"-pane too.

Tested in IE, Chrome and Firefox.

**Comment by oskarkrawczyk** [comment]
Can't replicate.

Are you getting errors in devtools?

**Comment by oskarkrawczyk** [comment]
This is by design.
