### ISSUE TITLE
Run ► Button too close to JS Fiddle Logo

### ISSUE THREAD

**Issue by dconsta3** [jsfiddle/jsfiddle-issues#718]
Ever since the new redesign of the JSFiddle site, I have found that the Run button is way too close to the JSFiddle logo image. 

Too many times I have clicked the Logo instead of the Run button as it is extremely close together. (View the page source and highlight over the code to see how close it is.) 
Clicking the logo, clears the page and starts a-fresh (annoying for new coders). The older version had things much more spaced. This would be a simple fix.

PS: Even though I save my work often, sometimes I rely on CTRL+Z to undo what I've done in to quickly revert my changes.

**Comment by oskarkrawczyk** [comment]
All unsaved fiddle's are stored as a local draft which can be brought back with two clicks.

**Comment by baconface** [comment]
Hopefully the devs are cool with this. But if it really plagues you get Greasemonkey, Tampermonkey, or some other scripting browser extension. Then make a script that hides or deletes the ```#branding``` element on jsfiddle.net to delete the logo. If you want to keep the logo just change the href attribute in the hyperlink to ```javascript:void(0);``` to prevent the default behavior.
