### ISSUE TITLE
login to hide sponsors after being logged in?

### ISSUE THREAD

**Issue by xameeramir** [jsfiddle/jsfiddle-issues#719]
Although the user is already logged in, jsFiddle is showing ads:

![login to hide sponsors after being logged in](http://i.stack.imgur.com/tnvp3.png)

Refreshed the page twice.

**Comment by oskarkrawczyk** [comment]
Will fix next week.

**Comment by jayh99** [comment]
![image](https://cloud.githubusercontent.com/assets/281493/13054552/107fcbe6-d3d0-11e5-9b61-05a753d1374f.png)

Still seeing this issue.

**Comment by oskarkrawczyk** [comment]
Haven't got around to sort this

**Comment by jayh99** [comment]
No problem, thanks for the update.

**Comment by borilla** [comment]
This is still happening.Can we re-open if it's not getting fixed?

**Comment by oskarkrawczyk** [comment]
I'll get around and fix it soon.

**Comment by koertvankleef** [comment]
Shouldn't it be reopened until fixed? It shows as closed on my end. Otherwise we'd have to open a duplicate, and that'd just cause clutter.

**Comment by oskarkrawczyk** [comment]
Removed info about logging in order to hide Carbon ads.
