### ISSUE TITLE
Some variants of the font Fira Mono don't show & and | properly

### ISSUE THREAD

**Issue by kbadk** [jsfiddle/jsfiddle-issues#720]
Some variants of the font _Fira Mono_ don't show `&` and `|` properly. 

While the [Fira Mono from Fontsquirrel](http://www.fontsquirrel.com/fonts/fira-mono) seems to support the characters, [the version downloaded from Google Fonts](https://www.google.com/fonts/specimen/Fira+Mono) does not.

If you're using the Fira Mono from Google fonts, [this fiddle should demonstrate the bug](https://jsfiddle.net/eg92ftf0/).

I suggest removing Fira Mono from the `font-family`, making the second in line (Monaco) the default.

**Comment by sentabi** [comment]
![screenshot_2016-02-02_16-33-02](https://cloud.githubusercontent.com/assets/203196/12745190/a8ae1770-c9ca-11e5-8294-70ee55f2a2a8.png)

I notice this bug too. 
Character `^` `@ ` don't rendered properly.

**Comment by kbadk** [comment]
This issue has not been fixed.

**Comment by hvanmegen** [comment]
Firefox 47.x here on Ubuntu 12.04 seems to be rendering just fine

![firefox_font_rendering](https://cloud.githubusercontent.com/assets/5887986/16583217/64af94dc-42b4-11e6-956e-0216d23aa848.png)
