### ISSUE TITLE
react

### ISSUE THREAD

**Issue by js08** [jsfiddle/jsfiddle-issues#722]
hey,

the same react code is working in codepen but its not working in fiddle why
working
http://codepen.io/tasssik/pen/yeGozR

not working
https://jsfiddle.net/n5Luz6ym/74/

**Comment by oskarkrawczyk** [comment]
I have no idea why it's not working. There's no point on figuring out what's wrong since the rendering process in the new JSFiddle rewrite will be completely different.

**Comment by js08** [comment]
@oskarkrawczyk  so when you are planning to launch :)
