### ISSUE TITLE
Tutorial not compatible with site

### ISSUE THREAD

**Issue by ppKrauss** [jsfiddle/jsfiddle-issues#724]
http://doc.jsfiddle.net/tutorial.html is for "old jsfiddle", see for instance "how to select AngularJS framework" in this case, http://jsfiddle.net/eu81273/8LWUc/

**Comment by pdehaye** [comment]
indeed, the main page refers to MooTools and how to activate it in the wrong place

**Comment by ppKrauss** [comment]
The  tutorial **is wrong**, I am talking about a page (the tutorial) that is not updated... What you talking about?

**Comment by oskarkrawczyk** [comment]
Indeed. I have no time to update it. It'll have to stay this way for the foreseeable future.
