### ISSUE TITLE
Enyo Version Update

### ISSUE THREAD

**Issue by webOS101** [jsfiddle/jsfiddle-issues#725]
Hello,

Would you please add a new Enyo version, as follows:

Enyo 2.7.0:

Core:
https://enyojs.com/enyo-2.7.0/lib/enyo/dist/enyo.js
https://enyojs.com/enyo-2.7.0/lib/enyo/dist/enyo.css

Checkbox for "Onyx":
https://enyojs.com/enyo-2.7.0/lib/onyx/dist/onyx.js
https://enyojs.com/enyo-2.7.0/lib/onyx/dist/onyx.css

Checkbox for "Layout":
https://enyojs.com/enyo-2.7.0/lib/layout/dist/layout.js
https://enyojs.com/enyo-2.7.0/lib/layout/dist/layout.css

Checkbox for "Canvas":
https://enyojs.com/enyo-2.7.0/lib/canvas/dist/canvas.js

Checkbox for "Moonstone (dark)":
https://enyojs.com/enyo-2.7.0/lib/moonstone/dist/moonstone.js
https://enyojs.com/enyo-2.7.0/lib/moonstone/dist/moonstone.css

Checkbox for "Moonstone (dark)":
https://enyojs.com/enyo-2.7.0/lib/moonstone/dist/moonstone.js
https://enyojs.com/enyo-2.7.0/lib/moonstone/dist/moonstone-light.css

Checkbox for "Spotlight":
https://enyojs.com/enyo-2.7.0/lib/spotlight/dist/spotlight.js

Checkbox for "iLib":
https://enyojs.com/enyo-2.7.0/lib/enyo-ilib/dist/enyo-ilib.js

Checkbox for "svg":
https://enyojs.com/enyo-2.7.0/lib/svg/dist/svg.js

---
While you're in there, it appears we forgot to add svg to the nightly build of Enyo on jsFiddle.  Can you add a svg checkbox to nightly with the following:

Checkbox for "svg":
http://nightly.enyojs.com/latest/lib/svg/dist/svg.js

---
Thanks!
cc: @zalun @oskarkrawczyk

P.S.  Hopefully in the new jsFiddle you'll have library config files stored in a repo that can have pull requests issued against them!

**Comment by webOS101** [comment]
Hi @oskarkrawczyk .  Any news on when this may be updated?  We would like to plan for our public release and this is a blocker.

**Comment by oskarkrawczyk** [comment]
@webOS101 Sorry for the delay. It's done now. Don't hesitate to ping me about such things next time – if I miss it here, ping me [on twitter](https://twitter.com/oskar).

> P.S. Hopefully in the new jsFiddle you'll have library config files 
> stored in a repo that can have pull requests issued against them!

That's one of the options, other is just fetch libs from NPM

**Comment by webOS101** [comment]
Excellent news, thanks!
