### ISSUE TITLE
Order of external resources if jsFiddle is run from GitHub

### ISSUE THREAD

**Issue by GoshaFighten** [jsfiddle/jsfiddle-issues#726]
It looks like jsFiddle loads external resources defined in the demo.details file on GitHub in a random way. Sometimes, the order is important. As a result, a jsFiddle does not work. See, for example, [http://jsfiddle.net/gh/get/library/pure/GoshaFighten/Test/tree/master/WebApplication/Home](http://jsfiddle.net/gh/get/library/pure/GoshaFighten/Test/tree/master/WebApplication/Home). Try to reload the jsFiddle several times and press Run.

**Comment by oskarkrawczyk** [comment]
Can't argue, it is broken. Unfortunately the current codebase is frozen. We're not changing anything and focusing on the complete rewrite (which will not have this issue). Closing.

**Comment by NicolasRannou** [comment]
Any time line for this issue?

**Comment by oskarkrawczyk** [comment]
As mentioned, the current codebase is frozen and it won't be fixed.

**Comment by NicolasRannou** [comment]
Yes but you also said "focusing on the complete rewrite (which will not have this issue)", do you still plan to support this feature somehow though?

**Comment by oskarkrawczyk** [comment]
Yes, the feature will be available. The rewrite will be available this year.

**Comment by NicolasRannou** [comment]
Thanks

**Comment by alcalyn** [comment]
Still having the problem

**Comment by oskarkrawczyk** [comment]
It was never fixed.
