### ISSUE TITLE
Highlight modified panels

### ISSUE THREAD

**Issue by yckart** [jsfiddle/jsfiddle-issues#728]
Much of us have opened often more than one fiddle at once, changing something here and there, read a book, take a cup of coffee and come back later, and have no clue of the current state (Is there anything to save, or not? Ok, better hit "Update" and "Set as base", just to be sure...).

Would nice to have another little "bulb" (or those buttons disabled), to see if some code was changed.

**Comment by oskarkrawczyk** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rvHtHUWr&#x2F;63-highlight-modified-panels"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Highlight modified panels</a>

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
