### ISSUE TITLE
Use default (subpixel) font smoothing in Firefox

### ISSUE THREAD

**Issue by websash** [jsfiddle/jsfiddle-issues#729]
This CSS property

``` css
-moz-osx-font-smoothing: grayscale;
```

in https://jsfiddle.net/css/_dist-editor.css?update_02_02_2016_2 makes source code font very thin and unreadable in Firefox (OS X). Font rendering without this property is much much better.  
For webkit it's  `-webkit-font-smoothing: subpixel-antialiased;` that is correct

**Comment by oskarkrawczyk** [comment]
@websash Can you provide a screenshot of what you're seeing?

**Comment by websash** [comment]
Sure, here is font smoothing with `-moz-osx-font-smoothing: grayscale;`

![screen shot 2016-02-24 at 8 17 47 pm](https://cloud.githubusercontent.com/assets/679341/13296057/51109cc4-db34-11e5-8c77-2121b82369ce.png)

and here's without one

![screen shot 2016-02-24 at 8 18 47 pm](https://cloud.githubusercontent.com/assets/679341/13296103/7c0e08f8-db34-11e5-8e79-af1ae5aad223.png)

**Comment by oskarkrawczyk** [comment]
Fixed.
