### ISSUE TITLE
login username maxlength is set to 30 but an email can be 75 characters

### ISSUE THREAD

**Issue by pawelkuras** [jsfiddle/jsfiddle-issues#731]
You can log in using either your username or email, but while you can save a 75 character email in your profile (not sure why, but if you enter more than 75 characters it saves without error, but selecting the text shows only the first 75 characters) you can only enter 30 characters in the username and this is enforced by maxlength as well as serverside validation, since if I use developer tools to bypass the maxlength field I still get an error reading:

&nbsp;&nbsp;&nbsp;&nbsp;Ensure this value has at most 30 characters (it has 39).

I encountered the issue, because I logged in using my email rather than the username.

**Comment by oskarkrawczyk** [comment]
The current codebase is frozen, in favor of us working on the new JSFiddle.

We won't be fixing this in the current version.
