### ISSUE TITLE
[Suggestion] "Are you sure?" popup when navigating away, or accidental refresh via F5, or clicking Logo.

### ISSUE THREAD

**Issue by Krummelz** [jsfiddle/jsfiddle-issues#735]
So I started a fiddle and before I bothered to save anything, I accidentally clicked on the JSFiddle logo image in the top-left corner, instead of clicking on the Run button, which reloaded the fiddle editor, and thus threw away my work. 

So I tried again, this time around I was careful to not click the logo by accident, however, I accidentally pushed F5 instead of 5 on my keyboard. Work lost again, before I got very far. 

Yes, I have butter-fingers tonight. No this does not happen often, but it's one of those things where when it happens you bend your head down in frustration and walk away from the computer for a while.

Could there please be a handler for `window.onbeforeunload`?
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by oskarkrawczyk** [comment]
All unsaved work is saved in local storage, and can be brought back with 2 clicks.
