### ISSUE TITLE
Order of script tags does not reflect order of `resources` key in POST

### ISSUE THREAD

**Issue by jesstelford** [jsfiddle/jsfiddle-issues#736]
For example, if I POST with the following data:

```
{
          html: '<div></div>',
          css: '',
          js: '/* Some react code */',
          resources: 'https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.24/browser.js,https://cdnjs.cloudflare.com/ajax/libs/react/0.14.6/react.min.js,https://cdnjs.cloudflare.com/ajax/libs/react/0.14.6/react-dom.min.js',
          wrap: 'h',// No wrap, in the head
          panel_js: 2 // version 1.7
}
```

The actual order of script tags in the page is:

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.6/react-dom.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.6/react.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.24/browser.js"></script>
```

Reverse alphabetic maybe? Or just random?

I've tried different permutations of the order in POST, ~~but it always results in the same order in the rendered page~~. Hmm, this doesn't seem to happen every time. Occasionally, it will be in the correct order.

Since `react-dom.min.js` relies on `react.min.js` having been loaded already, this breaks my ability to create new fiddles via a POST.

Note: The order of the resources listed in the "External Resources" section of the UI is also incorrect in the same way.

**Comment by jesstelford** [comment]
Hmm, this doesn't seem to happen every time. Occasionally, it will be in the correct order.

Note: The order of the resources listed in the "External Resources" section of the UI is also incorrect in the same way.

**Comment by jesstelford** [comment]
I see #399 was reported 2.5yrs ago, and recently `archived` - was this meant to be fixed? Or is it a `wontfix`?

**Comment by oskarkrawczyk** [comment]
It's random and it's a bug.

The current codebase is frozen. We're focusing on the complete rewrite.

Unfortunately even if we'd decide to fix this, the frozen codebase is written in Django and we have no one who knows Django on the team anymore.

Sorry to say but this is a `wontfix`.

**Comment by jesstelford** [comment]
Oh well, thanks for responding really quickly all the same :)

Any eta on the new codebase?

**Comment by oskarkrawczyk** [comment]
Q3 2016

**Comment by hirokiosame** [comment]
Any updates on this? It still seems to be an issue

**Comment by oskarkrawczyk** [comment]
@majkelcc Any chance you've addressed this in `next` branch?
