### ISSUE TITLE
Javascript Warning Tooltip

### ISSUE THREAD

**Issue by enki-code** [jsfiddle/jsfiddle-issues#739]
Not sure what exactly I'm doing [here](https://jsfiddle.net/enkicode/v352nc31/) that jsFiddle doesn't seem to approve of.

I keep getting this extremely annoying tooltip that I cannot close. The tooltip says 'Input plain JavaScript code, no HTML'.

I load the fiddle, it's fine, no warning, I start typing *anything* and the tooltip pops up. 

Not really sure how this is being interpreted as HTML.....

![jsfiddle-annoying](https://cloud.githubusercontent.com/assets/12533449/13906977/cdb99940-eea0-11e5-8f2c-0be4e8dee97d.png)

**Comment by enki-code** [comment]
It appears as though jsFiddle does not like the creation of the script element with jQuery. 

```
var $intercept = $('<script/>', {
    type: 'text/javascript',
    text: func
});
```
As soon as I remove that line the notification goes away.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no features/minor issues will be addressed. The new rewritten codebase will not have this issue.

**Comment by enki-code** [comment]
@oskarkrawczyk Thanks for letting me know.
