### ISSUE TITLE
Right side sections (CSS and Result) pushed very far to right side of my screen and no way to drag them back

### ISSUE THREAD

**Issue by edulis8** [jsfiddle/jsfiddle-issues#740]
This keeps occurring no matter how many times I sign out, or create new profiles. I would really appreciate some help here as I am intensively learning to code and no being able to view fiddles is starting to hamper my progress!! Thanks!

![screen shot 2016-03-21 at 10 19 05 pm](https://cloud.githubusercontent.com/assets/13525195/13942773/032b90ac-efb3-11e5-9e1f-b2e47dd39b92.png)

**Comment by oskarkrawczyk** [comment]
https://github.com/jsfiddle/jsfiddle-issues/issues/493
