### ISSUE TITLE
Scroll Jumping Issues

### ISSUE THREAD

**Issue by poofichu** [jsfiddle/jsfiddle-issues#742]
In collaboration mode, the boxes will jump to the top when the other person is editing them.

See animated gif below:  I'm looking at the bottom of the HTML box, but as soon as the other user types, it send me right back to the top.  I can't see what new code is being created.

![jsfiddle_jump](https://cloud.githubusercontent.com/assets/6757613/14030399/5f5fcc98-f1d5-11e5-8fbf-d083c601f060.gif)

I'm using Chrome Version 49.0.2623.87 (64-bit) on 15" Macbook Pro Retina / OSX Yosemite 10.10.5

**Comment by oskarkrawczyk** [comment]
Collab is done using TogetherJS from Mozilla, the behavior you're seeing is out of our control.

You can report this issue directly on their GH Issues – https://github.com/mozilla/togetherjs/issues
