### ISSUE TITLE
Changing title of fiddle not reflected in dashboard

### ISSUE THREAD

**Issue by glenpike** [jsfiddle/jsfiddle-issues#744]
If I fork a fiddle which is already public and edit the title.  The title of the original root is still displayed in the dashboard.
Possibly the reason for #564 - hence the confusion around this?

**Comment by oskarkrawczyk** [comment]
Current codebase is frozen. This will work as expected in the rewrite of JSFiddle.

**Comment by damianc** [comment]
@oskarkrawczyk - it still remains not fixed.

**Comment by oskarkrawczyk** [comment]
Works as I expected
