### ISSUE TITLE
Add option to run autoprefixer

### ISSUE THREAD

**Issue by demrks** [jsfiddle/jsfiddle-issues#745]
Currently, if you click on the little gear icon inside the CSS panel, you only have the option to normalize the CSS. I think it'll be great if you could add a second option to run [autoprefixer](https://github.com/postcss/autoprefixer). Similar to what codepen is doing:

<img width="339" alt="screen shot 2016-04-03 at 17 00 31" src="https://cloud.githubusercontent.com/assets/5760429/14233053/ad36bb76-f9bd-11e5-8332-3b316157a0a1.png">

**Comment by oskarkrawczyk** [comment]
Current codebase is frozen. No new features will be added. This is planned for the rewrite.
