### ISSUE TITLE
Fiddle name is not applied in page title when loading from GitHub

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#748]
Example: http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/legend/align/

This fiddle is loaded from GitHub and its name set in `demo.details`. If you save and reload the new URL so that it does not load from GitHub, the name is also present in the page `<title>`.

I would expect this to happen also when loading from GitHub. It would be great for SEO if we could name our fiddles after the feature they are showcasing.

**Comment by hawk-ip** [comment]
I agree, the title is generic, even when specified in `demo.details`.

**Comment by oskarkrawczyk** [comment]
@majkelcc has fixed the issue.
