### ISSUE TITLE
Dashboard inadequate with many jsfiddles

### ISSUE THREAD

**Issue by dlaliberte** [jsfiddle/jsfiddle-issues#750]
I have 19 pages of jsfiddles in my dashboard, accumulated over the years, and tediously scrolling through list, or randomly clicking on page numbers is the only way to view them.  I would suggest making the dashboard searchable.  Or better, add support for tags on the dashboards, or add a dashboard viewing option with one line per fiddle, all in one page.

**Comment by oskarkrawczyk** [comment]
New Dashboard in in the works in the JSFiddle rewrite.
