### ISSUE TITLE
Result and CSS window is not shown.

### ISSUE THREAD

**Issue by dtes** [jsfiddle/jsfiddle-issues#751]
My screen resolution 1920x1080. Chrome 50.0.2661.75 m.
![20 04](https://cloud.githubusercontent.com/assets/15036576/14663181/8d07be2a-06df-11e6-906a-29ad5846952a.png)

after changing style of windows result and css window shown properly.
![20 04-2](https://cloud.githubusercontent.com/assets/15036576/14663182/8d07bc9a-06df-11e6-9338-427266d9ee20.png)

**Comment by oskarkrawczyk** [comment]
Run command from the first comment of #493
