### ISSUE TITLE
Can't register with e-mail (which contain dot)

### ISSUE THREAD

**Issue by dariuszsikorski** [jsfiddle/jsfiddle-issues#752]
Hello I'm using e-mail with dots in the name, like this:

my.name@gmail.com but jsfiddle rejects this pattern during sign-up process because of dot in the name (it is correct to have dots in e-mail login).

Regards

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no features/minor issues will be addressed. The new rewritten codebase will not have this issue.
