### ISSUE TITLE
Ctrl + / in JS section uses HTML-style comment instead of JS

### ISSUE THREAD

**Issue by dariuszsikorski** [jsfiddle/jsfiddle-issues#753]
Selecting a line on Html section, then commenting with ctrl + / results in:
`<!-- commented code -->`

Css section results in:
`/* commented code */`

Js section results in:
`<!-- commented code -->`
instead of:
`/* commented code */`

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no features/minor issues will be addressed. The new rewritten codebase will not have this issue.
