### ISSUE TITLE
Uncaught Security Error

### ISSUE THREAD

**Issue by enki-code** [jsfiddle/jsfiddle-issues#754]
Keep getting the following error in Chrome

> app-938859d308.js:1 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

![jsfiddle-err](https://cloud.githubusercontent.com/assets/12533449/14769488/5708d41c-0a0e-11e6-99cd-1deda533d158.png)

It seems to be pointing to this line `return t=window.localStorage[this.getStorageKey()]`.

**Comment by oskarkrawczyk** [comment]
Looks like you have custom security settings in Chrome, preventing x-domain cookie/storage access.
