### ISSUE TITLE
Search Fiddles in your Dashboard

### ISSUE THREAD

**Issue by kthornbloom** [jsfiddle/jsfiddle-issues#755]
Currently, the only way to find a fiddle you made awhile back is to go through the pagination, one page at a time (and hope you gave it a good name). Could we please have a simple search bar in the dashboard area that would search titles & descriptions?

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no features/minor issues will be addressed. The new rewritten codebase will have this feature.
