### ISSUE TITLE
ClojureScript integration

### ISSUE THREAD

**Issue by martinklepsch** [jsfiddle/jsfiddle-issues#756]
I'm not sure what's necessary to make this a reality but it would be amazing to have ClojureScript available on JSFiddle. Any pointers in how the ClojureScript community could help make this happen are appreciated :)

**Comment by arichiardi** [comment]
:+1: on this, the community is very active in the bootstrapped/self-hosting area (see [ttp://www.clojurescript.io and other) and it would be great to share this knowledge in order to enhance jsfiddle.

**Comment by oskarkrawczyk** [comment]
We have this on the roadmap (https://trello.com/b/LakLkQBW/jsfiddle-roadmap), just cast a vote there so it's clear what to focus next.

Thanks!
