### ISSUE TITLE
Keyboard shortcut to comment out JavaScript

### ISSUE THREAD

**Issue by JamieRuderman** [jsfiddle/jsfiddle-issues#758]
https://github.com/jsfiddle/jsfiddle-issues/issues/248 partially addressed the request, but didn't add the functionality to the panel I would actually use it in...  ;)

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
