### ISSUE TITLE
Export JSFiddle as a Gist

### ISSUE THREAD

**Issue by codynguyen1116** [jsfiddle/jsfiddle-issues#760]
There should be an ability to export a JSFiddle as a Github Gist

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

**Comment by oskarkrawczyk** [comment]
https://twitter.com/jsfiddle/status/979802736664379393?s=21
