### ISSUE TITLE
Setting the value of 'draft[]' exceeded the quota.

### ISSUE THREAD

**Issue by yckart** [jsfiddle/jsfiddle-issues#762]
Every time the editor is updated, I get a _quota exceeded error_ from `dist-editor.js`.

Clearing the `localStorage` and `sessionStorage` has no effect.

``` js
_dist-editor.js?update_25_04_2016_1:32
  Uncaught QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'draft[]' exceeded the quota.
```
- OS X 10.11.4
- Chrome 50.0.2661.86 (64-bit)

**Comment by bradley** [comment]
👍

**Comment by oskarkrawczyk** [comment]
Clearing local storage solves the issue.

**Comment by gordonwoodhull** [comment]
Specifically, you can go to

```
chrome://settings/content/cookies
```

and delete the cookies for jsfiddle, and the error will stop.
