### ISSUE TITLE
Close unwanted panels

### ISSUE THREAD

**Issue by javisperez** [jsfiddle/jsfiddle-issues#763]
Hello, i have a feature request. 

It would be nice to close unwanted panels that you're not using, for example, some times i just use the script panel and i would like to have a bigger script panel by closing the html and css panel as i'm not using them. Or maybe just toggle them.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

**Comment by javisperez** [comment]
Thanks to you :)
