### ISSUE TITLE
Import from other fiddles

### ISSUE THREAD

**Issue by javisperez** [jsfiddle/jsfiddle-issues#764]
Hello, i would like to include scripts from other fiddles to have a better organized large fiddles, sometimes scripts get larges and i could maybe split it into multiple fiddles and then import them as i need it.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by javisperez** [comment]
Oh thank you for the info. Sorry i was looking for it on the road map but couldnt find it. My bad.
