### ISSUE TITLE
Feature request: protocol-less library links

### ISSUE THREAD

**Issue by MrCsabaToth** [jsfiddle/jsfiddle-issues#767]
Being able to specify library links without protocol, in a "//dsn.global.net/bootastrap.js". This way the http/https protocl would be determined to he situation.

If that's not doable, then gracefully substitute http library links with https to avoid client side browser rejection of non secure library loads. Time to time I run into this, especially with old fiddles. It's browser dependent how hard they act.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
