### ISSUE TITLE
Loading php page & mysql database

### ISSUE THREAD

**Issue by prakash741** [jsfiddle/jsfiddle-issues#768]
If you provide the facility to load and link a php page & mysql database to js fiddle then it would be very helpful.
Or
If it gives 2 more blocks for php coding & mysql, it will be a hit !!
Thousands of more users will use this service.
It will help to replicate the whole coding in an easy way.

**Comment by oskarkrawczyk** [comment]
PHP, SQL, and any other backend thing is completely out of **JS**Fiddle's scope.
