### ISSUE TITLE
Block comments in JavaScript via hotkeys.

### ISSUE THREAD

**Issue by ifeature** [jsfiddle/jsfiddle-issues#770]
**Feature request**
According to this [thread](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), I have suggestion about adding feature to [JSFiddle](https://jsfiddle.net/) which will allow to create block sections of comments using hotkeys, e.g.
**Cmd + /** - `//Line comment`
**Cmd + Opt + /** - `/*Block comment*/` 
  
---
Regards,
Artem.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
