### ISSUE TITLE
SCSS engine is old, doesn't support things like map-get

### ISSUE THREAD

**Issue by setek** [jsfiddle/jsfiddle-issues#771]
It seems that the SCSS rendering engine is old, it doesn't support things like map-get :)

**Comment by setek** [comment]
.. or maybe it does, there's some other error going on, it seems to break on:

`@media only screen and (min-width: map-get($cellSizes, $cellSize)) {`

Outputting in the source: 

`/* There where errors in SCSS */`

but it seems to work fine on:

`$tester: map-get($fonts, 'test');`

Even though SCSS will actually render fine without errors with either bits of code (Sass 3.4.22 (Selective Steve))

**Comment by oskarkrawczyk** [comment]
It's very old indeed.

Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
