### ISSUE TITLE
Idea: Selective commenting

### ISSUE THREAD

**Issue by Fleuv** [jsfiddle/jsfiddle-issues#772]
Like google drive has in docs, slides and sheets. Select a piece of code and hit a specific button to add a comment for the specific line of code selected. Just like google has, others can reply on your comment and maybe some other extra features.

**Comment by oskarkrawczyk** [comment]
We had this feature a long time ago and very few people were actually using it. I'll add this to the roadmap though, maybe the community will vote it up.
