### ISSUE TITLE
Export Fiddle to Stack Snippet

### ISSUE THREAD

**Issue by enki-code** [jsfiddle/jsfiddle-issues#773]
It would be nice if we could export fiddles as [Stack Snippets](https://blog.stackoverflow.com/2014/09/introducing-runnable-javascript-css-and-html-code-snippets/), I've already done this with a userscript, but, it's hacky and having it as a native feature would be much nicer.

**Comment by oskarkrawczyk** [comment]
We have no plans on doing this.
