### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by Mach12** [jsfiddle/jsfiddle-issues#774]
I'd like to suggest code folding: the ability to visually shrink blocks of code to one line, a la Notepad++ or Visual Studio.

If a fiddle goes a bit longer than expected, it would be nice to be able to compress it that way.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
