### ISSUE TITLE
Auto Run as an Option.

### ISSUE THREAD

**Issue by dotku** [jsfiddle/jsfiddle-issues#776]
The fiddle view could display (run) automatically during the edit. It would reflect the action instantly.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by antoniomcdesousa** [comment]
I would like to vote for this feature, but it is not listed in roadmap link provided, or at least I couldn't find it... what is the title and/or please provide a direct link to the original submitted request... thanks...
