### ISSUE TITLE
Ugly font rendering on Win10 (FF, Chrome, Edge)

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [jsfiddle/jsfiddle-issues#779]
The new font looks extremely ugly in every browser I have installed on my laptop :c 

# Firefox dev 48.0a2
Weird sub-pixel rendering and eaten tops (which turn into pixel-font) make the font completely unreadable. It's a PNG, but looks like JPG :|
![ugly](https://cloud.githubusercontent.com/assets/3174357/15091801/5d9febcc-14a8-11e6-806e-4af5b5b9a297.PNG)

# Chrome 48.0.2564.116 m
Not so bad, but hard to read because of blurred horizontal lines and fading tops. Also it looks too light. 
![ugly2](https://cloud.githubusercontent.com/assets/3174357/15091802/7e84cb46-14a8-11e6-8382-6bd5a620027e.PNG)

# Microsoft Edge
Same as Firefox. 
![ugly3](https://cloud.githubusercontent.com/assets/3174357/15091807/a0567fb2-14a8-11e6-88f2-75e9cacc0e9a.PNG)

**Comment by oskarkrawczyk** [comment]
Tested via Browser stack:

<img width="1093" alt="screen shot 2016-06-19 at 09 29 51" src="https://cloud.githubusercontent.com/assets/34213/16175948/69de7182-3600-11e6-8b56-17c0f1d19108.png">

<img width="1084" alt="screen shot 2016-06-19 at 09 29 42" src="https://cloud.githubusercontent.com/assets/34213/16175949/69dfee86-3600-11e6-94ff-7d5a935f2f50.png">

Looks ok to me.

Perhaps it's something wrong with your windows installation. Nobody else has mentioned this problem.

Closing, will reopen if we get more issues regarding this.
