### ISSUE TITLE
Mobile simulation

### ISSUE THREAD

**Issue by Link2Twenty** [jsfiddle/jsfiddle-issues#780]
Simulate touch input and mobile screen resolutions in results tab.

**Comment by oskarkrawczyk** [comment]
@Link2Twenty How would you go about and do that? Just curious.

**Comment by Link2Twenty** [comment]
Honestly I'm not really sure,

I'd probably looks to see if these were actually effective and try and implement them where I could.

http://azoff.github.io/overscroll/
https://www.npmjs.com/package/simulate-touch

Though that being said it was just an idea I had with no real thought of implementation difficulty.

**Comment by oskarkrawczyk** [comment]
Since this can be done with devtools, we won't be doing this ourselves.
