### ISSUE TITLE
HMTL imports option

### ISSUE THREAD

**Issue by Link2Twenty** [jsfiddle/jsfiddle-issues#781]
Option to add HTML imports for polymer and web components.

Needs to be placed into the header.
`<link rel="import" href="/path/to/imports/stuff.html">`

**Comment by GGG-KILLER** [comment]
This may help you: http://doc.jsfiddle.net/use/hacks.html

**Comment by oskarkrawczyk** [comment]
We're evaluating the possibility of adding full HTML to fiddle – so that everything inside of HEAD can be edited. That said, it's very distant future, not worth of a ticket at the present.
