### ISSUE TITLE
Powerpoint Integration

### ISSUE THREAD

**Issue by msumaverick16** [jsfiddle/jsfiddle-issues#783]
I know what you are thinking, but this application is such a integral part of the workforce that it would be nice to have something like this to revitalize the data visualization usage in Powerpoint. Something that will be user friendly, efficient and dependable, and last but not least... **easy to make changes.

I have already looked at Plotly and Fiddle for Powerpoint, but they're very sluggish and cannot be depended on. 

Thanks and keep up the innovation! 

-Mel

**Comment by oskarkrawczyk** [comment]
I think we'll have to wait for someone independent to create such an integration based on our API. 

This is completely out of the scope of our roadmap for the foreseeable future.
