### ISSUE TITLE
Idea: Latest Fiddle

### ISSUE THREAD

**Issue by taplar** [jsfiddle/jsfiddle-issues#784]
For those of us who dislike being in collaboration mode, but would like to easily get to the latest revision, along with /# to get to a specific revision a new "/latest" which would show the current last revision would be nice.

Hanging out in a support chatroom and people throwing around random jsfiddle links, they don't always remember to share their links, or they share an old one mistakenly.  It'd be nice to get one, change (or append) /latest to the end of the url and then just be able to refresh to see if/what they've changed.

**Comment by oskarkrawczyk** [comment]
So this hasn't landed on our Roadmap because it'll be baked in the rewrite. Absolutely agree, this would be a very helpful feature.
