### ISSUE TITLE
Embedded nested JSFiddle

### ISSUE THREAD

**Issue by Mottie** [jsfiddle/jsfiddle-issues#786]
Sometimes I need to create a JSFiddle that will become an iframe inside of another JSFiddle.

It used to be possible, a loooong time ago, to link directly to the result page - a page which didn't include a "Edit is JSFiddle" header.

I am *not* asking to allow embedding only the result frame from *outside* of the JSFiddle domain.

But now there is another issue with cross-domain interactions:

> VM1179:46 Uncaught SecurityError: Blocked a frame with origin "https://fiddle.jshell.net" from accessing a frame with origin "https://jsfiddle.net". Protocols, domains, and ports must match.

Would it be possible to get this working again?

**Comment by oskarkrawczyk** [comment]
We'll get embedding within JSFiddle domains working, but in the 2.0 rewrite (already on our roadmap). The current codebase is frozen.
