### ISSUE TITLE
Some versions of Mootools not loading

### ISSUE THREAD

**Issue by GGG-KILLER** [jsfiddle/jsfiddle-issues#787]
Some versions of Mootoools still use the http:// protocol, and as jsFiddle has enforced a https everywhere policy, Chrome and other browsers don't allow the framework to be loaded as it's using http and not https.

Link to fiddle showing problem: [`https://jsfiddle.net/gh/gist/mootools/1.2/606699/`](https://jsfiddle.net/gh/gist/mootools/1.2/606699/)

> Mixed Content: The page at 'https://jsfiddle.net/gh/gist/mootools/1.2/606699/' was loaded over HTTPS, but requested an insecure script 'http://mootools.net/download/get/mootools-1.2.6-core-nc.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by oskarkrawczyk** [comment]
We're aware of the issue. We're fixing this on per request basis, since it needs to be fixed manually. Unfortunately version 1.2.6 doesn't seem to be available on any CDN anymore.
