### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by sufianShafiq** [jsfiddle/jsfiddle-issues#788]
Your site is very Good and i appreciate. Thanks for provide us this site :) . 
            I think here must be debugger option , by which we can easily understand the code and go ahead step by step,

Thanks :)
sufian

**Comment by GGG-KILLER** [comment]
This isn't possible unless they wrote a javascript parser or whatever language you expect to be "debugged" to go "step by step".

**Comment by oskarkrawczyk** [comment]
Indeed, makes no sense since every browser already has an awesome debugger available natively.
