### ISSUE TITLE
Feature Request: Make the jsFiddle Editor mobile-friendly

### ISSUE THREAD

**Issue by ramtob** [jsfiddle/jsfiddle-issues#789]
Hello. I find that I am accessing jsFiddle quite a bit on my mobile phone. And, while editing and running jsFiddle on mobile is in principle possible, it is not actually responsive, and is consequently quite awkward. I would therefore request, if possible, to make the jsFiddle editor responsive, mobile-friendly. Such as Codepen has recently become. TIA

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
