### ISSUE TITLE
Hide the left bar with ctrl+shift+↑

### ISSUE THREAD

**Issue by mendeleev** [jsfiddle/jsfiddle-issues#791]
Very often, especially on a laptop screen it's vital to hide the left bar to increase a work-space. It was possible to do it using the **ctrl+shift+↑** shortcut, but currently that function isn't working. Also it prints an error to the console when I try to use that combination.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
