### ISSUE TITLE
Fix Collaboration

### ISSUE THREAD

**Issue by IPWright83** [jsfiddle/jsfiddle-issues#794]
Collaboration is incredibly useful. I've tried it 3 way today because nothing else seems to provide similar capabilities.

Unfortunately though we've found it's got a few issues:

- External Resources don't seem to sync properly
- I kept hitting update to save changes (but I don't actually know where they went, I couldn't find them later).
- If someone is typing, it resets your scroll position in the code editor
- It'd be incredibly handy to have a shared console!
- We couldn't get the mic's working at all.
- We seemed to struggle syncing up which session we were in - it had duplicates of me at one point.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed.

We'll have  look into this at some point in the future, after a complete JSFiddle rewrite.
