### ISSUE TITLE
New button

### ISSUE THREAD

**Issue by jamr-ron** [jsfiddle/jsfiddle-issues#797]
I'm pretty new to JsFiddle, so perhaps there is a way to do this, but I would like a 'new' button on the top nav, so that if I want to create a new fiddle I don't have to copy and paste https://jsfiddle.net in a new tab, or fork it and then overwrite old content.

Screenshot attached with example button.

![button](https://cloud.githubusercontent.com/assets/5273970/15448863/cb41eb1c-1f2a-11e6-9e60-fb1bf20d7c6f.png)

Thanks.

**Comment by oskarkrawczyk** [comment]
Thanks for the suggestions.

We had a NEW button long time ago, statistics had shown nobody was clicking it.
