### ISSUE TITLE
[Live Reloading] Use service worker to cache changes to re-run immediately

### ISSUE THREAD

**Issue by amio** [jsfiddle/jsfiddle-issues#798]
Then we got live reloading (without a roundtrip to server).
What do you think?

**Comment by oskarkrawczyk** [comment]
While this would make some sense in the current JSFiddle (frozen codebase) where language translation for Babel or CoffeeScript is being done client-side, the new JSFiddle will have preprocessing done on the backend side so there's always going to be a roundtrip – well unless there were no changes to the input, but then why would someone re-run a fiddle.

I'm tempted to use Service Worker + caching in the new JSFiddle, but the new flow would make it pretty hard.

**Comment by amio** [comment]
Nice to hear a new JSFiddle is on the way 👍 

For new JSFiddle, I think we can make "live-reloading" a checkbox, when user check it, load the transpiler and register the service worker. The transpiler could be shared by frontend and backend to keep the consistency.

BTW, where can I find a detail plan for the new JSFiddle? The trello boards seems mostly user's advice, not a full plan. IMHO, keep transpiling on client-side seems OK by me, I'm wondering what's the consideration of the change.

**Comment by oskarkrawczyk** [comment]
There's no public detailed roadmap. If we end up transpiling on the client-side again, it'll be progressive enhancement to the backend traspilation. One significant reasoning behind ditching client-side transpilation is that some transpilers are 3-4 megabytes in size.

**Comment by amio** [comment]
A progressive enhancement would be great!

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
