### ISSUE TITLE
Use Gists or Git files as require/import

### ISSUE THREAD

**Issue by pankajpatel** [jsfiddle/jsfiddle-issues#799]
It would be to have require/import feature form gists or a particular file from github repo.

This would make experimenting with the code quick and easy.

For example same gist can be used to experiment with different types jQuery plugins. Like sample table is in a gist and importing/requiring the plugin file from github will save time and speed up the minor code experimenting.

**Comment by oskarkrawczyk** [comment]
You can include gist through External Resources, just be sure to use https://rawgit.com/ so it's the right mime type.
