### ISSUE TITLE
Tidy JSX breaks JSX

### ISSUE THREAD

**Issue by Chipairon** [jsfiddle/jsfiddle-issues#805]
Taking the react jsfiddle suggested here [https://facebook.github.io/react/blog/2013/06/02/jsfiddle-integration.html](https://facebook.github.io/react/blog/2013/06/02/jsfiddle-integration.html)
Leads to this fiddle [http://jsfiddle.net/vjeux/kb3gN/](http://jsfiddle.net/vjeux/kb3gN/) with the following javascript:

```
var Hello = React.createClass({
    render: function() {
        return <div>Hello {this.props.name}</div>;
    }
});
 
React.render(<Hello name="World" />, document.body);
```

If tidied, the closing JSX brackets `/>` are being separated causing invalid code:

```
var Hello = React.createClass({
  render: function() {
    return <div > Hello {
      this.props.name
    } < /div>;
  }
});

React.render( < Hello name = "World" / > , document.body);
```

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
