### ISSUE TITLE
Code Reviews

### ISSUE THREAD

**Issue by danielminnaar** [jsfiddle/jsfiddle-issues#807]
Allow your code to be reviewed by public or private peers, to suggest edits and improvements. Perhaps a feature to 'Accept Suggestion' which updates your code to the suggested edit?

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

**Comment by oskarkrawczyk** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XxblGlOX&#x2F;54-code-reviews"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Code Reviews</a>
