### ISSUE TITLE
Support for Pug (formerly Jade) instead of HTML

### ISSUE THREAD

**Issue by imaustink** [jsfiddle/jsfiddle-issues#808]
[Jade](http://jade-lang.com/) is a really great language/transpiler for rapid development and it really shines when prototyping or testing.

Since it's all based on JavaScript it works great on the client, no need to compile Jade server side.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
