### ISSUE TITLE
Add Aurelia to JavaScript Frameworks & Extensions 

### ISSUE THREAD

**Issue by Spontifixus** [jsfiddle/jsfiddle-issues#809]
I really would love to see Aurelia (http://aurelia.io) being added to the Frameworks and Extensions. This framework is a rising star among the web application frameworks and it would be great if one could test some features out by using JSFiddle!

**Comment by oskarkrawczyk** [comment]
@Spontifixus unfortunately it doesn't look like it's available via a CDN anywhere.

**Comment by oskarkrawczyk** [comment]
We can add it if it's available as a single file on a CDN, until then closing the ticket.

**Comment by YardGnomeNinja** [comment]
This has recently changed! [Is this sufficient?](https://cdnjs.com/libraries/aurelia)
