### ISSUE TITLE
Make external sources urls editable

### ISSUE THREAD

**Issue by Narretz** [jsfiddle/jsfiddle-issues#810]
I would really like to have the option to edit external sources. I mostly use jsfiddles from people that want to show me bugs in AngularJS, which means I test many different versions of AngularJs against the fiddle. Right now I have to replace the whole external source, and it would make my life much easier if I could simply edit the url.

**Comment by oskarkrawczyk** [comment]
External resources will be completely overhauled in the 2.0 rewrite. Closing as this is already on our roadmap.
