### ISSUE TITLE
Can't Update or Fork with certain JavaScript code?

### ISSUE THREAD

**Issue by sparky672** [jsfiddle/jsfiddle-issues#812]
I've been using jsFiddle for a long time, but today I'm seeing a new issue.  I cannot "Fork" or "Update" any jsFiddle.  After editing a jsFiddle, I click on "Update" and the URL simply displays `jsfiddle.net`.  I get the same result after clicking "Fork".  I've tried in several browsers with the same result.

Then I discovered the whole problem was being caused by a chunk of code within the JavaScript pane.  I cannot show you the jsFiddle in question, since the bug is not giving me a URL.

Start with this jsFiddle:  https://jsfiddle.net/m0q031hh/

Insert the following code block exactly as indicated by "insert code here" comment and then click "Fork" or "Update" button.  Then look for jsFiddle URL... refuses to create a new URL and existing URL is gone.

```
        if (response == "ok") {
             showMyMessage('You have successfully been logged in! Redirecting in 2 seconds...', 'success');
             setTimeout('window.location.href = "home.php"; ', 2000);
             alert('ok tu');
         } else {
             showMyMessage('Something wrong! ' + response, 'error');
             alert('jsu tu');
         }
         return false;
```

**Comment by oskarkrawczyk** [comment]
Cannot replicate this behavior. It forks the fiddle as usual.

**Comment by sparky672** [comment]
I just replicated the issue in Safari, FireFox, and Chrome.  It's 100% repeatable for me in any browser.

In fact, here's a simpler method:  just open a new jsFiddle window and paste that code block from my OP into JavaScript pane.  Click save and nothing happens.

**Comment by oskarkrawczyk** [comment]
Cannot replicate. https://v.usetapes.com/3KAh3SyfQD

**Comment by sparky672** [comment]
I'm on a Mac too BTW.  Here is Firefox.

http://sendvid.com/w5oyr88p

**Comment by oskarkrawczyk** [comment]
Changing frame's `window.location.href` you're altering internal paths that need to stay unaltered for the editor to work.

Fix would require refactoring, and the codebase for this version of JSFiddle is frozen. Rewrite will not have this issue.

**Comment by sparky672** [comment]
Ok... at least this is explainable behavior.  It's not my code... just something somebody posted on a StackOverflow question I was working on.  When I tried to save fiddle, I couldn't.  Figured it best to just report this to you.
