### ISSUE TITLE
Can't edit or reorder external resources

### ISSUE THREAD

**Issue by teo1978** [jsfiddle/jsfiddle-issues#819]
The interface for managing external resources (i.e. linked css and js files) is a ridiculous pain in the ass.

If you have included a bunch of js and css file urls, and the order matters, and you have a typo in one of them, you can't either:
- f***ing edit it, which would be the OBVIOUS requirement
- as a workaround, delete it and readd it (with the typo fixed). You can't do that either because it will be added at the end and you can't reorder them. You have to delete and readd ALL of them.

How can someone have designed such a stupid interface??

If at least you allowed to edit the whole HTML (as opposed to only the body), like jsbin does, one could edit the links to external resources in the `<head>` directly.

It's pathetic.

**Comment by oskarkrawczyk** [comment]
User has been blocked for obnoxious and insulting tone.

Nobody in our organization wants to deal with that kind of people.
