### ISSUE TITLE
CSS frameworks Dropdown

### ISSUE THREAD

**Issue by forabetterjob** [jsfiddle/jsfiddle-issues#821]
can we have popular css frameworks listed in the CSS section. Similar to javascript.

Wonder why you haven't done that yet..!

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

As to why hasn't this been added yet, the answers is simple: current JSFiddle codebase is frozen and no new features are added. New stuff will be added in the rewritten version.
