### ISSUE TITLE
To be able to add files, also upload files from system.

### ISSUE THREAD

**Issue by gokhaled89** [jsfiddle/jsfiddle-issues#822]
I've been using jsFiddle for a long time and I think this important functionality is missing.
It doesn't allow us to create a local JavaScript file or a JSON file which can be used in the fiddle.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by gokhaled89** [comment]
Thanks for the update.

**Comment by gokhaled89** [comment]
Can you please tell me by when can we expect the new features to be added?

**Comment by oskarkrawczyk** [comment]
Not ETA
