### ISSUE TITLE
YUI library from JS lib picker dropdown has erroneous links

### ISSUE THREAD

**Issue by bcmoney** [jsfiddle/jsfiddle-issues#823]
Any JSfiddles relying on the JavaScript library/framework picker dropdown will likely be broken as they point to the following (for example for the latest listed YUI version 3.17.2):
https://yui.yahooapis.com/3.17.2/build/yui/yui-min.js

It appears as though Yahoo! has updated that link to the following (without a redirect unfortunately):
https://yui-s.yahooapis.com/3.17.2/build/yui/yui-min.js

It also solves any "non-HTTPS" issues as JSfiddle seems to be moving away from HTTP resource links en masse. Oddly enough, the HTTP version of the first link would work but HTTPS does not. Here's a sample basic JSfiddle that should work, but does not: 
https://jsfiddle.net/bcmoney/cekzwn5v/

Please update the link to YUI library, in order to fix broken references. Thanks!

**Comment by oskarkrawczyk** [comment]
Done
