### ISSUE TITLE
Tidy moves separate selectors to individual lines

### ISSUE THREAD

**Issue by Tyler-H** [jsfiddle/jsfiddle-issues#824]
Recently-ish, the Tidy function of JSFiddle was edited to sort additional selectors before the braces onto individual lines. 

e.g. when Tidied,

    html, body {}

becomes

    html,
    body {}

This adds unnecessary lines and spacing to the code, and I'd love for that to either be reverted or made an option in the settings. 

(It would also be great if newlines weren't injected between each full selector on Tidy, either)

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed.

The current behavior of Tidy to us is the correct behavior so we're not going to change it, maybe in some distant future we'll add the ability to configure Tidy.
