### ISSUE TITLE
Custom shortcuts

### ISSUE THREAD

**Issue by PhanindraNath** [jsfiddle/jsfiddle-issues#826]
Can we have few custom shortcuts for the functionalities which are already in jsFiddler? Because diff people use diff frameworks, it could be easy, to have same shortcuts. Also, still "Ctrl+S" problem is there from a long time, which can be avoided for self and can have more ease.

**Comment by oskarkrawczyk** [comment]
Shortcut support will be expanded upon in the 2.0 rewrite.
