### ISSUE TITLE
Ability to close the sidebar panel

### ISSUE THREAD

**Issue by midasdas** [jsfiddle/jsfiddle-issues#827]
It would be helpful if the sidebar panel could be closed, because right now it is taking up too much space on my small monitor (1024x768).

It used to be possible, apparently:

![Image][1]

Thanks :)

  [1]: http://extern.pascal-martin.fr/so/so-6833741.png

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
