### ISSUE TITLE
Feature idea: Ability to view history as a tree and diff between revisions

### ISSUE THREAD

**Issue by 42degrees** [jsfiddle/jsfiddle-issues#828]
I've been using jsFiddle for some relatively complex concepts recently and I ended up with quite a number of revisions of the fiddle.  There was some collaboration with others (not using the new collaboration feature, which I haven't had time to try yet) and that created other revisions and forks.  

So, what I really wanted to do was see the tree (revisions as well as forks) and compare one revision/fork to another to see what was changed.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
