### ISSUE TITLE
Ability to download a given revision as a stand-alone web page

### ISSUE THREAD

**Issue by 42degrees** [jsfiddle/jsfiddle-issues#829]
I would like to be able to take a given fiddle version and export it as a stand-alone HTML file that I can store off as documentation for the feature I proved/tested in jsFiddle and then moved into my own application.

As an aside, it would be nice if I could then turn around later and import that file (so the export could include markers showing which parts of the HTML file shouldn't be touched as auto-generated and which can be freely edited).  This would also give me a way to edit the fiddle in an external editor (for more complex editing) and then have that re-imported into jsFiddle as a new revision.  CodinGame does this with a browser plug-in that reloads the file every time you return to the browser (if I remember correctly) which allows me to do my primary edits in SlickEdit where I have tons of editing power, while still benefiting from the fiddle for sharing, demonstration, and debugging.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by 42degrees** [comment]
Thanks, but I had been through the backlog and didn't find it.  I looked again and still don't see it.  Could you please point it out to me so that I can vote for it?

**Comment by oskarkrawczyk** [comment]
https://trello.com/c/FsHI02RT/43-download-a-zipped-fiddle

**Comment by mplungjan** [comment]
> https://trello.com/c/FsHI02RT/43-download-a-zipped-fiddle

<img width="646" height="202" alt="Image" src="https://github.com/user-attachments/assets/2c3e0e00-0ed8-4a75-863c-dd8bf2de2c96" />

**Comment by oskarkrawczyk** [comment]
You can download fiddles for years now
