### ISSUE TITLE
Ability to have panel "layouts" and to swap between them

### ISSUE THREAD

**Issue by 42degrees** [jsfiddle/jsfiddle-issues#830]
It would be great if jsFiddle allowed us to save off the organization of the panels on the page differently for different types of fiddle.  If I'm mostly playing with CSS then I would have that panel primary with the others minimized (or even not shown), or if I'm mostly testing JavaScript, then it could be primary. Another use case would be initial development of a fiddle vs debugging, where in development I would probably want to see all panels, but while debugging I may only need to see the JavaScript and result panels.

I would save the current layout with a name, then I could switch back and forth between them by choosing them from a menu.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by 42degrees** [comment]
It would be helpful, when you are responding with "it's on the roadmap" to point the person to the actual item, rather than just liking to the roadmap.  I can't find this one on the roadmap either.  I do see one about enabling and disabling panels, but nothing about saving layouts.

I'm sorry, I know that I'm asking you to do more work, but my feeling is that if I can't find it on the roadmap, then maybe the actual problem is that I didn't do a very good job of explaining my idea here.

**Comment by oskarkrawczyk** [comment]
https://trello.com/c/kFH1FNYD/18-alternative-editor-grid-arrangements
