### ISSUE TITLE
suggestion: Improved AJAX imitation/handling

### ISSUE THREAD

**Issue by gibberishbc** [jsfiddle/jsfiddle-issues#833]
Current system does not really imitate AJAX. You created a workaround of workarounds, not a useful imitation for the purposes of demonstration or teaching. You guys are AMAZING coders - you can do better than that.

Perhaps you do not realize how much this would be used. Please look into it - I believe it would be a hugely popular improvement. Hotjar the question? For my part, probably 30% of the answers I provide on SO are related to AJAX. (1000+ answers, 15k rep)

It would be great to have a pseudo-AJAX system that allows the user to enter a standard AJAX code block (perhaps using one specific PHP filename "ajaxexample.php" or some such) and somehow define what the output should be. For example, create a pop-up panel (or some such) where user creates the output that will be injected into the success (or .done, .complete, .error) functions of the AJAX routine.

This will help place you firmly back on top at StackOverflow again...

**Comment by oskarkrawczyk** [comment]
@gibberishbc Out out curiosity, what in your opinion is wrong with the current `/echo` functionality?

You can:

- define the output
- define JSONP wrapper
- degine delay

http://doc.jsfiddle.net/use/echo.html

**Comment by gibberishbc** [comment]
It works, but it is nothing like a normal AJAX code block. I am speaking on behalf of beginners. As you know, the typical AJAX code block looks like this:

 

$.ajax({

                type: 'post',

                url: 'myajax.php',

                data: 'varName='+varvalue+ ‘nutherVar=’+nutherval,

                success: function(recd){

                                alert(recd);

                }

});

 

Or

 

$.post({"myajax.php", { name: "John", time: "2pm" }, function(recd){

                alert(recd);

});

 

The beginners and intermediate-level coders are looking for that structure. The echo system works, but it is like learning to drive by sitting in an armchair with a joystick for a steering wheel. It’s not a terribly great learning/teaching environment for AJAX. Yes, it echoes back the data, but the code is all wrong. Unrecognizable.

 

Believe me, I love jsFiddle – I am a huge armchair supporter. This is just my $0.02 as a relatively new coder.

**Comment by oskarkrawczyk** [comment]
I see, so the only issue is that the additional syntax it requires to define the output.

I'll add it to the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap) and it'll be up to the community to decide.
