### ISSUE TITLE
Link Libraries from Bower.io

### ISSUE THREAD

**Issue by captainkirk128** [jsfiddle/jsfiddle-issues#837]
Similar to linking libraries from NPM within a fiddle, it would be useful to link libraries from bower as well.

**Comment by yckart** [comment]
I would suggest to use [npmcdn.com](https://npmcdn.com)

> **We do NOT recommend JavaScript libraries use Bower.** Bower places additional burdens on JavaScript package authors for little to no gain. npmcdn is intended to make it easier to publish code, not harder, so Bower support will be removed in January 2017. Please move to npm for installing packages and stop using Bower before that time. See here for our rationale.
https://github.com/mjackson/npm-http-server#bower-support

**Comment by captainkirk128** [comment]
Awesome - thanks for the recommendation!
