### ISSUE TITLE
Persist credentials 

### ISSUE THREAD

**Issue by koenpunt** [jsfiddle/jsfiddle-issues#839]
Whenever I come back on jsfiddle.net, I almost always have to sign in again. Even when my last visit was only a day ago. 

Most annoying part about having to sign in again, is that after signing in, it doesn't redirect me back from where I came from, but to my user dashboard.

**Comment by oskarkrawczyk** [comment]
@koenpunt Care to elaborate?

**Comment by koenpunt** [comment]
@oskarkrawczyk accidental premature submit, comment updated :)

**Comment by oskarkrawczyk** [comment]
I have a feeling there's something wrong with your browser (perhaps an extension or something), the login cookie is set to expire after ~25 days.

**Comment by koenpunt** [comment]
I'm pretty my browser is doing fine, I don't have troubles with any other site.

Also, I just signed in, and the cookie is only set for about 14 days:
![image](https://cloud.githubusercontent.com/assets/351038/16457872/616b0676-3e1d-11e6-8970-9fc81934a5f7.png)

At least the redirect part is a valid point :)

**Comment by oskarkrawczyk** [comment]
Ah, sorry 14 days not 25 :-)
