### ISSUE TITLE
Download Fiddle as a Zip Package

### ISSUE THREAD

**Issue by arbelh** [jsfiddle/jsfiddle-issues#841]
Ability to download the HTML, CSS and the JS as a zip file in structured directories like:

HTML
  |-CSS
  |-JS

And the references to external resources in the HTML Header.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by mplungjan** [comment]
<img width="679" height="264" alt="Image" src="https://github.com/user-attachments/assets/f941caa6-c335-43c6-8bfe-5595eda39d2c" />
