### ISSUE TITLE
Ability to manipulate the `<head>` or otherwise do HTML Imports

### ISSUE THREAD

**Issue by tigerhawkvok** [jsfiddle/jsfiddle-issues#844]
For example, to test the Polymer library right now, we can't do that in JSFiddle. We'd need to add to the `<head>`

``` html
<base href="http://polymer-magic-server.appspot.com/components/">

  <script src="webcomponentsjs/webcomponents-lite.min.js"></script>

  <link href="polymer/polymer.html" rel="import"/>
  <link rel="import" href="google-map/google-map.html"/>
```

to test the [Google Map element](https://github.com/GoogleWebComponents/google-map/issues/308). It has a big warning that never goes away.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
