### ISSUE TITLE
After initial save, fiddles do not save.

### ISSUE THREAD

**Issue by ajfick** [jsfiddle/jsfiddle-issues#845]
Created a Test Fiddle... 
![created test](https://cloud.githubusercontent.com/assets/19314419/16591803/a243a01c-42ab-11e6-8203-6cb68b2ae762.png)

Save "Test" fiddle successfully... 
![immediately after init](https://cloud.githubusercontent.com/assets/19314419/16591818/b9ed60cc-42ab-11e6-8055-4893dde0ef18.png)

Edit "Test" Fiddle ... (just added more text)
![edited test](https://cloud.githubusercontent.com/assets/19314419/16591827/c30fd2c0-42ab-11e6-9ab3-aec6713d54e8.png)

Update "Test" fiddle, and clicked update button at top left. NOTE: the dashboard shows "#1 is the latest revision" which indicates a save after the initial save. 
![shows 1 revision](https://cloud.githubusercontent.com/assets/19314419/16591836/cafdf7fa-42ab-11e6-95b5-b90232798b0a.png)

Open fiddle again, "Updated" data is lost, back to initial save.
![reopened test](https://cloud.githubusercontent.com/assets/19314419/16591886/0b1aae3c-42ac-11e6-90a4-8f3e32849334.png)

I've had this issue for a few months. Tested on Firefox 47.0.1, Chrome Version 51.0.2704.103 (64-bit), and also Safari Version 9.1.1 (11601.6.17) all with the same issue. 

Hope I'm not just missing something!

**Comment by oskarkrawczyk** [comment]
@ajfick Unless you set the fiddle as the base version, the "Test fiddle" will point to the `/0` revision – the red link on the other hand will point the the newest available revision.

This behavior never changed :-)

**Comment by ajfick** [comment]
Got it! Thanks for correcting me! I had a feeling I might be doing something wrong but couldn't seem to find an answer.. I guess i never provided enough detail so I assumed it wasn't just me. Thanks again @oskarkrawczyk !

**Comment by oskarkrawczyk** [comment]
@ajfick No problem!
