### ISSUE TITLE
Alow `full screen` View

### ISSUE THREAD

**Issue by arbelh** [jsfiddle/jsfiddle-issues#846]
Allow a true **_full screen_** mode, where the result is directly loaded and is not inside an `iframe`.

E.g. via a url like `[fiddle url]/show/fullscreen/`

**Comment by oskarkrawczyk** [comment]
This feature was abused by spammers and scammers. Unfortunately we can't have nice things because of these people.

**Comment by arbelh** [comment]
How about having this option available only to fiddles created by registered users?

(You can also make it tighter by a light verification like asking the registered user to verify and link their github account to their jsfiddle account.)

For me as a developer a full screen mode is a huge advantage.

**Comment by oskarkrawczyk** [comment]
Scammers also register and validate emails.

We've been there, and it was something that can be done relatively easily with the current codebase, we'd never remove fullscreen in the first place.

That said, we're currently in the middle of rewriting JSFiddle into a 2.0 version, we'll have better ways of detecting scammers/spammers, perhaps then we'll be in a better position to bring back full screen view.

**Comment by ttocsmij** [comment]
Feel free to code it to execute scammers/spammers upon identification of same.
