### ISSUE TITLE
Allow `<META>` Tags

### ISSUE THREAD

**Issue by arbelh** [jsfiddle/jsfiddle-issues#847]
Allow UI related `<META>` tags.

Or at least and especially the `viewport` meta tag, `<meta name="viewport">`

A new input field labeled **_viewport meta_** can be added to the `HTML` settings drop-down in the `HTML` pane for the value of the tag.

(Will be very useful in combination with a **_`full screen`_** mode requested in another issue, specifically making the platform very potent for _**mobile/responsive**_ developments/reviews).

**Comment by oskarkrawczyk** [comment]
The new rewritten codebase will have this feature.
