### ISSUE TITLE
Font loading

### ISSUE THREAD

**Issue by Mottie** [jsfiddle/jsfiddle-issues#848]
If I want to add Material design icons, I need to load in an external font. If I add the font url to the external resources, it adds the url to a `<script>` tag by default, I guess since it doesn't end in `.css`, and the font doesn't load.

If I add a link to the HTML panel:

```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```
I get a warning - "For external CSS files use the Resources panel on the left".

Is there a method to add a url to the external resources to force it to load as a link? Or at least let us close the warning.

**Comment by oskarkrawczyk** [comment]
Add `@import 'https://fonts.googleapis.com/css?family= Material+Icons';` in the CSS panel.

**Comment by Mottie** [comment]
It doesn't work... See https://jsfiddle.net/Mottie/99zmedy3/

**Comment by oskarkrawczyk** [comment]
It does. You have a space after `=` in `@import 'https://fonts.googleapis.com/css?family= Material+Icons';`.
