### ISSUE TITLE
External Resources Plus Sign

### ISSUE THREAD

**Issue by Mottie** [jsfiddle/jsfiddle-issues#849]
The plus sign inside the external resources input makes it very difficult to edit URLs.

![2016-07-06 12_32_59-tablesorter demo - jsfiddle](https://cloud.githubusercontent.com/assets/136959/16628166/1d88c8a4-4376-11e6-9b67-19c5fe206998.png)

Sometimes I want to modify the url by simply changing a `.js` to a `.css`. Adding some padding to the input would solve this problem.

``` css
#external_resource {
  padding-right: 22px;
}
```

![2016-07-06 12_33_45-tablesorter demo - jsfiddle](https://cloud.githubusercontent.com/assets/136959/16628193/457fd37a-4376-11e6-807e-e12f631f6e77.png)

**Comment by oskarkrawczyk** [comment]
Fixed.
