### ISSUE TITLE
Bug: Warning for HTML, META, and HEAD tags, as well as CSS warning, triggered incorrectly

### ISSUE THREAD

**Issue by knod** [jsfiddle/jsfiddle-issues#851]
If you cut the HTML and paste it back in, you'll see that you get four warnings:
```
No need for the HTML tag, it's already in the output.
No need for the META tags.
No need for the HEAD tag, it's already in the output.
For CSS use the panel on the right.
```

The HTML doesn't have any of those tags, it just has those strings as values in the code (you'll see it has `data-output="macro:<!DOCTYPE html>..."`, etc).

Edge case, I know, but still a bug, and one that makes it very hard to edit that HTML.

**Comment by oskarkrawczyk** [comment]
Too much of an edge case to spent time creating a workaround. JSFiddle 2.0 won't have this issue since it won't have these warnings.
