### ISSUE TITLE
While editing JavaScript 'Command (⌘) + /' is adding a HTML comment instead of commenting out the current line

### ISSUE THREAD

**Issue by vivek241** [jsfiddle/jsfiddle-issues#853]
In Mac, 'Command (⌘) + /' is a common shortcut in most editors to comment out the current line.
While editing JS code if I try this shortcut, it adds a HTML comment i.e .

Is this expected?

**Comment by oskarkrawczyk** [comment]
This is how Emmet works, didn't find a way to change/fix it.

**Comment by RDardelet** [comment]
The same happens on windows with **Ctrl + /**
I beleive it shouldn't be so hard to force the behavior to change since the CSS section includes the usual /* */ comments that will also work in Javascript

**Comment by oskarkrawczyk** [comment]
If it wasn't hard it would be done by now.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
