### ISSUE TITLE
Zero Width Spaces in content

### ISSUE THREAD

**Issue by Kyle-Falconer** [jsfiddle/jsfiddle-issues#855]
I've noticed this for some time, that when I copy the code from the JavaScript panel into my code file, I'll sometimes get a [ZWP](https://en.wikipedia.org/wiki/Zero-width_space) character which will result in a syntax error on execution.

It would be nice if the ZWP characters were either not used at all or removed on copying.

**Comment by oskarkrawczyk** [comment]
It must be CodeMirror. I've updated to the newest version. If the issue persist, we'll just have to live with it until CodeMirror folks fix it.
