### ISSUE TITLE
JSON Schema builder

### ISSUE THREAD

**Issue by timberzen** [jsfiddle/jsfiddle-issues#856]
It would be nice to have a schema builder that creates the objects in C# & JS so that you can quickly get the JS to API up and running. having the same class lib would be good for the unit testing as well. Bit like http://json2csharp.com/

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
