### ISSUE TITLE
Scope is not working as expected

### ISSUE THREAD

**Issue by tahmina8765** [jsfiddle/jsfiddle-issues#857]
When I run the following code in JSFiddle, it alerts '1'. but if I run the same code in chrome console, it alerts correct result '2'

```
var a = 1;
function display(a) {
  this.a = a;
}
display(2);
alert(a);
```

**Comment by oskarkrawczyk** [comment]
Run the code outside of onload/domready.

<img width="695" alt="screen shot 2016-07-21 at 11 36 28" src="https://cloud.githubusercontent.com/assets/34213/17018273/6a842078-4f37-11e6-90fc-6f8ae7c73fd5.png">
