### ISSUE TITLE
Fiddles history and dates

### ISSUE THREAD

**Issue by roselan** [jsfiddle/jsfiddle-issues#858]
Some fiddles are now quite old and used to demonstrate ancient bugs/features.

It would be helpful to find the date of the "last edit" or even "created on" somewhere (in the Fiddle Meta, or Legal sections)

**Comment by codex73** [comment]
This is a good idea, maybe on dashboard next to the fiddle title.... something like this

Last Update: 09/02/16

or even a timestamp

10:15pm 09/02/16

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no features will be added. The new rewritten codebase will have this.
