### ISSUE TITLE
Add a const providing JSFiddle ID/"slug" for fiddles

### ISSUE THREAD

**Issue by MegaScience** [jsfiddle/jsfiddle-issues#859]
I was working with localStorage and wanted to make sure my localStorage entry was unique. I had the thought that if I could consistently obtain my JSFiddle ID code-wise, I could use it as part of my localStorage entry to assure it was unique. However, the only references made it the DOM are outside the scope (slug and fiddleOptions > slug). It would be helpful if the ID was defined where fiddles could access for such purposes.

This could also be used for protection against users who fork code and try to hide other code users might not notice, by making sure a Fiddle is running by the same ID. Similar to that, the ID of the creating user (anonymous where applicable) would help in that respect.

There could be issues with such an idea, so I'm open to hearing justified opposition.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no features will be added. The new rewritten codebase will have this feature.
