### ISSUE TITLE
High latency between Gist update and JsFiddle preview (due to caching?)

### ISSUE THREAD

**Issue by shazmoh** [jsfiddle/jsfiddle-issues#86]
JSFiddle/Gist integration: The latency between Gist update and JsFiddle preview is somewhere around 1 - 2 minutes. I was told its due to the caching of Gist. A push notification from GitHub for any Gist update could be used to evict/flush the gist from cache.

Based on:
http://twitter.com/#!/shazmoh/status/65212879489597441
http://twitter.com/#!/js_fiddle/status/65397591919181824
http://twitter.com/#!/shazmoh/status/65402560000962560

**Comment by RyanAtViceSoftware** [comment]
Hi @zalun I need this feature too. Any updates?
