### ISSUE TITLE
Folders or tags to maintain fiddles

### ISSUE THREAD

**Issue by anandrikka** [jsfiddle/jsfiddle-issues#860]
Hello,

It's an awesome experience using Jsfiddle to quickly write some examples or reproduce an issue while working. However there is a suggestion, if we can organize our fiddles it would be awesome.

**Comment by puffstream** [comment]
I agree, I use jsfiddle a lot to build app prototypes, test theories and so on, but I get lost in trying to find the useful applications I made. Might be a good idea to group similar features together so we can see how they might work with each other to resolve a common goal.

For example: you have vanity URLS, private fiddles, grouping fiddles.. in summary, the organisation of your jsfiddles.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
