### ISSUE TITLE
Settings do not allow email addresses with newer TLD domains

### ISSUE THREAD

**Issue by sheriffderek** [jsfiddle/jsfiddle-issues#861]
Settings do not allow email addresses with newer TLD domains.

For example, my email address is _derek@sheriffderek.consulting_ and it doesn't validate.

I can't offer any help with this, but just wanted to make a note of it - since these are becoming standards. : )

<img width="556" alt="screen shot 2016-07-26 at 2 41 25 pm" src="https://cloud.githubusercontent.com/assets/2066617/17156525/2757faca-533f-11e6-8cdc-fb7baabe9798.png">

**Comment by oskarkrawczyk** [comment]
Fixed
