### ISSUE TITLE
Changing an external resource letter

### ISSUE THREAD

**Issue by varguitas** [jsfiddle/jsfiddle-issues#862]
I deleted and re added an external resource with an upper-case difference, but the resource manager keeps using the old URL for some strange reason. I even try creating a new fiddle but when I type the new URL and save it the manager adds the old URL.

[Fiddle Link](https://jsfiddle.net/vvargas/a0tqkf4e/5/)

Old Resource:
http://tecdigital.tec.ac.cr/resources/tds-lib/lib/**D**atatables/js/jquery.dataTables.min.js

New Resource
http://tecdigital.tec.ac.cr/resources/tds-lib/lib/**d**atatables/js/jquery.dataTables.min.js

Thank's

**Comment by oskarkrawczyk** [comment]
Unfortunately it's case insensitive, just add `?2` at the end for the new resource to be picked up.

This will be fixed in the rewrite.
