### ISSUE TITLE
double result header, no content

### ISSUE THREAD

**Issue by dividinglimits** [jsfiddle/jsfiddle-issues#863]
Windows 8.1 
Firefox latest (currently 47.0.1)

![result_bug](https://cloud.githubusercontent.com/assets/3688829/17279976/b89df276-5751-11e6-96d4-a63391dc74e9.png)

**Comment by oskarkrawczyk** [comment]
- is the same happening on chrome?
- are there any errors in the console?
- when you hit RUN, will the problem disappear?
- when you load the URL again, is the problem still present?

**Comment by dividinglimits** [comment]
No to 1,2,3
Yes to 4

**Comment by dividinglimits** [comment]
This is still occurring on Windows 8.1 Firefox 48.0.2.The attached screenshot depicts a contrived example, with the web development tools open. Clicking "Run" or reloading the page has no positive impact on the error. Does not occur with Chrome Canary, have not checked the MS nor Opera flavors.
![bad_result](https://cloud.githubusercontent.com/assets/3688829/17944895/949a23ce-6a0f-11e6-89bb-43c36f04e0fa.png)

**Comment by oskarkrawczyk** [comment]
Tested on a bunch of operating systems in different browsers, not getting this. Also this is the first time someone mentions this issue, which kind of makes me believe this might be some issue on your end (?). Maybe an extension, some weird custom browser setting, hard to say.

I cannot replicate this issue. Unless somebody else confirms this issue exists, I'll have to close it. For now leaving it open.

**Comment by oskarkrawczyk** [comment]
We haven't receive any reports on this in a month. Also, can't replicate it on our end. Closing.
