### ISSUE TITLE
POST API displays base64 encoded code on Chrome for Android

### ISSUE THREAD

**Issue by miz884** [jsfiddle/jsfiddle-issues#864]
A code will be displayed in base64 encoded format if it is posted via POST API from Chrome for Android. It won't work if "Run" button is clicked.

It can be reproduced on this sample code.
http://jsfiddle.net/zalun/sthmj/embedded/result/

I tested it on Android 6.0 and Chrome 52.

Reproducing steps:
01. Open the link above on Chrome for Android.
02. Click "Submit".
03. Then, you'll see the following text in HTML pane:
PHAgY2xhc3M9InJlZCI+SXQncyBtYWdpYyE8L3A+CjxwPjxhIGhyZWY9Imh0dHA6Ly9kb2MuanNmaWRkbGUubmV0L2FwaS9wb3N0Lmh0bWwiPkRvY3VtZW50YXRpb248L2E+PC9wPg==

It is the base64 representation of the posted HTML code:

<p class="red">It's magic!</p>

<p><a href="http://doc.jsfiddle.net/api/post.html">Documentation</a></p>

There are same issues on JS and CSS panes as well.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed (minor because we have less 1% mobile users). The new rewritten codebase will not have this issue.
