### ISSUE TITLE
Add ability to reference/import other fiddles

### ISSUE THREAD

**Issue by Spoonunit** [jsfiddle/jsfiddle-issues#866]
Would be great to be able to use other fiddles as either CSS or JS external resources.
Alternatively/additionally, provide a mechanism to include content from other fiddles within HTML, CSS, and JS sections.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
