### ISSUE TITLE
position:fixed (should not be able to scroll the entire window, just the js/css/html/result)

### ISSUE THREAD

**Issue by gaby-de-wilde** [jsfiddle/jsfiddle-issues#867]
the whole entire jsfiddle thingy should be {position:fixed} to prevent accidental scrolling.

One can for example press page-down while not focusing any of the textareas or use grab and scroll on the side or top menu.

(i've only tried firefox)

**Comment by oskarkrawczyk** [comment]
Thanks for the suggestion but we'll leave it as it is.
