### ISSUE TITLE
result iframe not scrollable on touch devices + fix?

### ISSUE THREAD

**Issue by izar89** [jsfiddle/jsfiddle-issues#868]
When testing some cross-browser things I noticed that the result iframe is not scrollable on my ipad and android phone which is apparently a common problem with iframes. The following css on a parent container/div should fix the problem:

-webkit-overflow-scrolling: touch;
overflow-y: scroll;

Take a look at the following blogpost: https://davidwalsh.name/scroll-iframes-ios

<3 jsfiddle ;)

**Comment by oskarkrawczyk** [comment]
Merged into #706.

Hopefully I'll fix this today.
