### ISSUE TITLE
Displaying console.log() in result 

### ISSUE THREAD

**Issue by alirokni** [jsfiddle/jsfiddle-issues#869]
Currently, Result is the window to show javascript execution and to view console.log(), browser's devTool should be opened. It will be much easier if console.log() can be displayed in the Result (e.g. enabled in setting or appending the expected result)

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
