### ISSUE TITLE
Add two-factor authentication

### ISSUE THREAD

**Issue by davorb** [jsfiddle/jsfiddle-issues#870]
It would be nice if we could add [FIDO U2F](https://en.wikipedia.org/wiki/Universal_2nd_Factor) support to our accounts (like Github has). Otherwise, something like [RFC 6238](https://tools.ietf.org/html/rfc6238), which is what Google Auth and Authy uses, would be nice.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

**Comment by oskarkrawczyk** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rGnhSf5I&#x2F;58-two-factor-authentication"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Two factor authentication</a>
