### ISSUE TITLE
autocomplete external resources

### ISSUE THREAD

**Issue by mikebotazzo** [jsfiddle/jsfiddle-issues#871]
I would like to have an autocomplete mode when choosing the external resources.
For example, when typing `React` I lovely to have a list suggesting a default URI or a list of choices that I could move between using some keyboards shortcuts like <kbd> Ctrl</kbd> + <kbd> n</kbd> or <kbd> Ctrl</kbd> + <kbd> p</kbd>

**Comment by oskarkrawczyk** [comment]
We've got plans to have that. Already on our roadmap.
