### ISSUE TITLE
add to the Help menu links to the approved resources

### ISSUE THREAD

**Issue by andzi** [jsfiddle/jsfiddle-issues#874]
add to the Help menu links to the approved resources: firefox / chrome addons, code libraries, books, etc...

**Comment by oskarkrawczyk** [comment]
Not sure I follow what would this do.

**Comment by anzi** [comment]
menu [Legal, Credits and Links] is expected to be on bottom (but it will
take precious space), so on top right [Login/Signin | Settings | Help /
About] or at least to be divided from functional menu [Meta; Resources;
Ajax] with some line or color background.

maybe you decided, that Your target audience are geeks, hackers and
similars (those ones who blindly type on keyboard and operates from command
line ;) and they are born with knowledge, but for me it took about half
year to discover, that there is hidden submenu [Docs] and usefull addons
(for chrome and ff ) exists.

at present moment minimalistic design is clean and nice and understandable
from the point of developers to do only MVP (i.e. main functions)

but from the user side, especially newcomers it would be generous to lower
barriers for onboarding by putting links to essential info:

- http://doc.jsfiddle.net/
- http://doc.jsfiddle.net/meta/channels.html
- report bug / suggest feature
- firefox / chrome addons,
- code libraries,

good UI fuctionality samples (when logged in):
- http://dashboard.genmymodel.com (not the best)
- http://codebeautify.org/jsonviewer (all menu on the top)
- http://cssdeck.com/labs/wyshtc2a (probably the best)


***

**Comment by oskarkrawczyk** [comment]
Added some links
