### ISSUE TITLE
make Dashboard more compact, sortable, filtrable

### ISSUE THREAD

**Issue by anzi** [jsfiddle/jsfiddle-issues#875]
make Dashboard for better UI & UX:  more compact (as list), sortable, filtrable...

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the roadmap.

**Comment by greggman** [comment]
I didn't see this on the roadmap. I saw this https://trello.com/c/YPx1uTZe/20-fiddles-gallery-most-rated-viewed-forked

But that's not really what's being asked for here I think or rather there are several ideas here

1. sortable
2. filterable
3. compact (as list)

I find that I often want to reference an old fiddle. I don't know the name so I can't really search but if I was able to quickly see all the titles I'd know which ones to check. It seems like a list or columns of titles would be useful?

     +----------------------+----------------------+----------------------+
     | Testing console.log  | Rotating a cube      | Image Historgram     |
     | Trying out audio     | Drawing Stars        | Regex for quotes     |
     | Trying Symbols       | Proxy test           | WebGL Multisample    |
     | Testing console.log  | Geometry Generation  | Patterns in 2d       |
     | Pref of funcs vs ... | Textured Cube        |                      |
     +----------------------+----------------------+----------------------+
