### ISSUE TITLE
Loading CDN from listed instead of searching cdn links

### ISSUE THREAD

**Issue by shahilmhd** [jsfiddle/jsfiddle-issues#876]

**Comment by oskarkrawczyk** [comment]
Not sure what you mean, please elaborate.

**Comment by shahilmhd** [comment]
I was thinking it would be easy to pick cdn from the list so that we need not specify the link insted just select the cdn names EX: bootstrap, foundation etc

**Comment by shahilmhd** [comment]
This would be for external resource

**Comment by oskarkrawczyk** [comment]
We'll be integrating with a CDN soon.
