### ISSUE TITLE
Html gadget getting in the way on scrollbar

### ISSUE THREAD

**Issue by GearTheWorld** [jsfiddle/jsfiddle-issues#879]
An image worth a thousand words :

![image](https://cloud.githubusercontent.com/assets/8614008/17852685/7a97bfac-6836-11e6-9872-010a979394db.png)

**Comment by GearTheWorld** [comment]
Looks like it's all right in IE 11 but all other browser fails.  The worst is Chrome!

**Comment by oskarkrawczyk** [comment]
It's been like that for years, nobody ever had an issue with it, so we'll just leave it as it is until JSFiddle 2.0 is out and the UI gets some refinement.
