### ISSUE TITLE
Feature request: fiddle with service workers

### ISSUE THREAD

**Issue by jimmywarting** [jsfiddle/jsfiddle-issues#880]
Sometimes i want to play around with service workers but they are annoying to update and setting up cuz they need to run on localhost or https

Being able to run a new service worker every time you update the script would help tremendous
This would be something uniq that no other playground has

**Comment by oskarkrawczyk** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Xs3blZFe&#x2F;62-ability-to-attach-a-customizable-service-worker-to-a-fiddle"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ability to attach a customizable Service Worker to a fiddle</a>

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!
