### ISSUE TITLE
Safari error: Error while parsing the 'sandbox' attribute

### ISSUE THREAD

**Issue by aegaas** [jsfiddle/jsfiddle-issues#882]
http://jsfiddle.net/Wk7VF/71/

[Error] Error while parsing the 'sandbox' attribute: 'allow-modals' is an invalid sandbox flag. (71, line 610)

**Comment by oskarkrawczyk** [comment]
http://stackoverflow.com/a/33542435:

> This error can be safely ignored, the script will continue to run fine. These are two new flags which have been implemented in Chrome 46 (the current stable release). If you're testing in a browser that doesn't support them, you'll see that error (which is really just a warning).

> The allow-modals flag is required because Chrome will, by default, block modal dialogs within a sandboxed iframe. Adding this flag allows modals to work in your apps scripts.
