### ISSUE TITLE
Javascript obfuscated on iphone

### ISSUE THREAD

**Issue by rubberony** [jsfiddle/jsfiddle-issues#883]
I think the title says it best.  I was browsing some examples coming out of highcharts.com on my iphone.  The javascript and the html appeared to be either compressed & or obfuscated - unreadable at least.  It looks like I was using the chrome browser on my phone.

**Comment by oskarkrawczyk** [comment]
Cannot replicate. Also, this version of JSFiddle doesn't support rendering on mobile.
