### ISSUE TITLE
Error HTTP Status code for /echo/json/

### ISSUE THREAD

**Issue by buksy90** [jsfiddle/jsfiddle-issues#884]
Could you change response from server so that when there is an error in input of the AJAX request the HTTP code will be **400 Bad Request** ?

It would be handy so we could use/test jQuery's `.fail()` method in our Fiddles :)

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

**Comment by oskarkrawczyk** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pzOXJw71&#x2F;61-error-http-status-code-for-echo-json"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Error HTTP Status code for &#x60;&#x2F;echo&#x2F;json&#x2F;&#x60;</a>
