### ISSUE TITLE
Hide-Show Left Sidebar

### ISSUE THREAD

**Issue by codex73** [jsfiddle/jsfiddle-issues#885]
Maybe having an icon somewhere along the left sidebar allowing users to hide/show column as needed.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by andymule** [comment]
hows it goin?

**Comment by zedred46** [comment]
I had this issue, and decided to code this functionality in javascriptand load it every time in the chrome extension [Custom JavaScript for websites](https://chrome.google.com/webstore/detail/custom-javascript-for-web/poakhlngfciodnhlhhgnaaelnpjljija).

Just visit [jsfiddle.com](https://jsfiddle.net/) and past the [javascript code](http://ge.tt/2DN8vFu2) into the chrome extension. The code adds two items in settings, one to hide the sidebar and the other to some of the top buttons (it only leaves Run, Save and Tidy visible). Both options will load as on by default but can be changed in the settings menu. The state of the options will not be saved when you leave the page, but the default could be changed by editing the javascript code.

**Comment by takeru** [comment]
`document.getElementById("sidebar").hide(); document.getElementById("layout-container").setAttribute("style", "grid-template-columns: 0px 1fr;");`
<img width="1029" alt="スクリーンショット 2020-03-11 10 38 45" src="https://user-images.githubusercontent.com/82017/76373749-9e3f4180-6384-11ea-914a-3913dfdf85a5.png">
