### ISSUE TITLE
jQuery UI?

### ISSUE THREAD

**Issue by 017Bluefield** [jsfiddle/jsfiddle-issues#886]
As far as jsfiddle.net goes, I've been using jQuery **2.0.2** because it allows me to use with it jQuery UI. However, between then and now, the only jQuery version that _has_ jQ UI is version **1.9.1**--the earliest iteration. What's happened? What's going on?

**Comment by oskarkrawczyk** [comment]
Added jQuery UI to jQuery (slim) 3.1.0

**Comment by 017Bluefield** [comment]
Ah, okay. Thanks.
