### ISSUE TITLE
Use github issues instead of trello

### ISSUE THREAD

**Issue by jimmywarting** [jsfiddle/jsfiddle-issues#887]
Organize github issues with Milestones & Labels can make this good to. 
 - Easier for people to report bugs/ideas
 - Don't have to be switched over to trello. 
 - Can have a nice discussion over them. 
 - Has 👍  👎  voting to and can be sorted as well

**Comment by oskarkrawczyk** [comment]
1. Trello is not for reporting issues, this is the place
2. We need the Roadmap to be in a Kanban board
3. Discussions on ideas on the Roadmap are not our priority
4. You can indeed vote for ideas on Trello (no need for downvotes)

**Comment by jimmywarting** [comment]
I hate when owner closes others reported issues directly before other people can see this and say "yea that's a good idea, why don't we do that?" 😞 
If it would have been a duplicated then fine...

Github has milestones too which kind of is like roadmap
How many have a trello account and where do most developer hang out? On GitHub!
I just like to keep everything gather on the same place. Don't understand why some use basecamp github and jira while github has everything that is needed
---

If someone would say something like this in my repo "Hey, can you turn your ES6 javascript code in to TypeScript?". That would turn my stomach around I would at least wait 24-48 hours until they can convince me why or the other way around and be sure that that is what other people also want. or that the majority of people also disagree...

I know of one repo who rushed into using [feathub](http://feathub.com/) over one day cuz it was so well pressented while i was inactive for a moment and just a day after that I convinced them that it was a bad idea and they regretted there decision - and they even said a day after that: "why didn't you say so before"- my point here is don't rush in to conclusion/decision 

---

But fine have it your way. I don't care so much since i don't work for jsfiddle or contributing to it so.
