### ISSUE TITLE
Unable to alter Fiddle Meta after initial save

### ISSUE THREAD

**Issue by codex73** [jsfiddle/jsfiddle-issues#889]
After a fiddle is initially saved, "Fiddle Meta" title or description cannot be set or updated, it won't retain new values.

How to replicate: 

** Save a new fiddle, leave "Fiddle Meta" title empty or enter something.
** Enter something on "Fiddle Meta" title or description, click UPDATE.
** Go to Dashboard, check if Title or Description was changed for that fiddle.

**Comment by oskarkrawczyk** [comment]
The dashboard displays meta info of the Base version. Be sure to set the fiddle as base.

**Comment by alkopop79** [comment]
Why is this issue closed when it still happens? I cannot change the meta of my fiddles with default name. What's the workaround?

**Comment by codex73** [comment]
@alkopop79 It appears that is the intended behavior. See previous message by @oskarkrawczyk. In order to alter the default name, after editing, you'll need to click "Set as Base". The dashboard always shows the base meta data. Hope this helps.

**Comment by alexramsey92** [comment]
I disagree with the intended behavior.
