### ISSUE TITLE
1 space indentation

### ISSUE THREAD

**Issue by MrSwed** [jsfiddle/jsfiddle-issues#891]
subj. Why not ?

**Comment by oskarkrawczyk** [comment]
We've got 2/3/4 which are the most popular. No plans to add 1 space indentation.

**Comment by MrSwed** [comment]
>most popular
any statistic ?

and why it bad user experience ?

**Comment by oskarkrawczyk** [comment]
> any statistic ?

Common knowledge, 2 and 4 are the most used in frontend development.

> and why it bad user experience ?

Code is less readable.

**Comment by MrSwed** [comment]
an imposed opinion..  
but I will not argue..
