### ISSUE TITLE
Deleted External Resources come back after forking or updating

### ISSUE THREAD

**Issue by sparky672** [jsfiddle/jsfiddle-issues#892]
It seems that External Resources, once added, can never again be removed.

Steps to reproduce:
1.  Create/Save a jsFiddle with at least one External Resource.
2.  Delete this External Resource and Fork or Update the jsFiddle.  The URL has been updated and the resource "appears" to be gone.
3.  Load the newly forked or updated jsFiddle into a new browser window and observe that this External Resource has come back!

Tested in Firefox, Chrome, and Safari.

**Comment by oskarkrawczyk** [comment]
Seems like a regression after introducing resource reordering. Will have a look into it.

**Comment by sparky672** [comment]
Problem still happening... very frustrating condition, especially when trying to replace resources with more up to date versions.

**Comment by oskarkrawczyk** [comment]
No point in mentioning it over and over, you'll get a notification once it's fixed

**Comment by ghybs** [comment]
Hi,

From what I have seen, only the last "removed" external resource is kept.
If you remove several external resources in a row, all but the last one are correctly removed.

Therefore an awful workaround for now could be to add a dummy external resource, remove whatever resource we need, and lastly "remove" the dummy resource.

**Comment by sparky672** [comment]
> Therefore an awful workaround for now could be to add a dummy external resource, remove whatever resource we need, and lastly "remove" the dummy resource.

Oh yes, that is a very ugly workaround.  Maybe the root problem will get fixed someday.

**Comment by oskarkrawczyk** [comment]
Fixed.
