### ISSUE TITLE
Find other than browser's ctrl+F

### ISSUE THREAD

**Issue by bowTiesAreCool** [jsfiddle/jsfiddle-issues#893]
Basically, this is important because the browser's ctrl+F only looks at code currently bieng viewed, and thus is useless for finding specific parts of a long code

**Comment by oskarkrawczyk** [comment]
CMD+F will find and highlight code in all panels even if it's out of the viewport.

![dsa](https://cloud.githubusercontent.com/assets/34213/18766243/9561f540-8119-11e6-8d26-f8a89e3142af.gif)
