### ISSUE TITLE
Resources not loaded when reading from GitHub

### ISSUE THREAD

**Issue by hawk-ip** [jsfiddle/jsfiddle-issues#895]
When a `http://jsfiddle.net/gh/get/` page is loaded, resources specified in `demo.details` don't get put into the iFrame `<head>`, until you click Run. Once you click Run, they are in there and the fiddle works properly.

Example [here](http://jsfiddle.net/gh/get/jquery/1.11/hawk-ip/jquery.tabSlideOut.js/tree/4b098187012cd518432dc8b8a6826a3ea69b9b41/demo).

Expected behaviour is that `<head>` should be populated with the resources the first time the fiddle page loads.

Current workaround is to 
1. Put `<script>` tags in the HTML [as suggested on SO](http://stackoverflow.com/questions/8790943).
2. Put `<link>` tags in the CSS using the [JSFiddle CSS hack](http://doc.jsfiddle.net/use/hacks.html).

**Comment by TorsteinHonsi** [comment]
+1

**Comment by oskarkrawczyk** [comment]
I'll have a look into this, but if the fix requires backend alterations we won't do it since the backend codebase is frozen and cannot be modified even if we wanted to.

**Comment by oskarkrawczyk** [comment]
Should be fixed.
