### ISSUE TITLE
Idea: Option to collapse functions 

### ISSUE THREAD

**Issue by joostblok** [jsfiddle/jsfiddle-issues#896]
Hello,

I'd like to add my own idea to the idea list.
The ability to collapse functions/loops just like visio or notepad++ can.
Because when you have a function or loop which keeps going for 1km and you have to go around it all the time its super annoying.

Greetings,
Joost

**Comment by joostblok** [comment]
**Update this was already added as code folding I think. Do not know for sure though.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
