### ISSUE TITLE
Commenting a selected region in JavaScript window

### ISSUE THREAD

**Issue by ni8mr** [jsfiddle/jsfiddle-issues#897]
Now an user can comment by selecting a porting of the codes of HTML and CSS with ctrl + '/' button. But in case of JavaScript, when an user try to to do this, it shows a SyntaxError in the log. It will be helpful, if comment option on a selected portion of the codes in JS window, is added in jsFiddle.

**Comment by oskarkrawczyk** [comment]
Duplicate #483
