### ISSUE TITLE
Add referrers in dashboard

### ISSUE THREAD

**Issue by KeesCBakker** [jsfiddle/jsfiddle-issues#90]
I would like to see that sites that link to my fiddles. This make management a lot bit easier, because sometimes I would like to delete scripts that are no longer needed. I also would like to see how many times they are visited and how many forks there are made.

Is it possible to implement these features?

**Comment by KeesCBakker** [comment]
Any news?

**Comment by oskarkrawczyk** [comment]
Sorry, not going to happen anytime soon. I'll leave it open for the future.

**Comment by KeesCBakker** [comment]
Any news?

**Comment by oskarkrawczyk** [comment]
Added to our roadmap - https://trello.com/b/LakLkQBW/jsfiddle-roadmap
