### ISSUE TITLE
JSX highlighting is incorrect

### ISSUE THREAD

**Issue by gaearon** [jsfiddle/jsfiddle-issues#900]
With Babel, I see weird coloring when I use JSX:

<img width="459" alt="screen shot 2016-10-05 at 13 37 53" src="https://cloud.githubusercontent.com/assets/810438/19113325/fafd56a6-8b00-11e6-9049-6dac9aabd725.png">

GitHub doesn’t have this problem:

```jsx
let element = <h1><span>Hello</span>, world!</h1>;

ReactDOM.render(
  element,
  document.getElementById("root")
);
```

**Comment by oskarkrawczyk** [comment]
We have no coloring mode for JSX at the moment.

**Comment by oskarkrawczyk** [comment]
Added JSX mode for Babel.
