### ISSUE TITLE
Is there an way to add a new library as an item of supported library list?

### ISSUE THREAD

**Issue by fernandosouza** [jsfiddle/jsfiddle-issues#901]
I would like to know the process. Should I submit a request to a specific team? Can I implement it and send a PR?

**Comment by oskarkrawczyk** [comment]
You can request an addition here

--

**Comment by fernandosouza** [comment]
Thank you for answer @oskarkrawczyk. The tool is http://metaljs.com.

Liferay's engineering team is developing an open source tool to build components. Other teams began to use it and we believe that jsFiddle is a perfect way to share code examples and discuss about.

It will be great to have MetalJS in jsFiddle supported tool list. :)

**Comment by oskarkrawczyk** [comment]
Unfortunately it doesn't seem like metaljs is available on cdnjs and we
require it to be there.

--
