### ISSUE TITLE
Quickly generate a Preview URL

### ISSUE THREAD

**Issue by PDegenPortnoy** [jsfiddle/jsfiddle-issues#904]
My team uses JSFiddle to create code mockups that are higher fidelity than what the graphic artists produce.  Being able to quickly generate a Preview URL that shows only the Preview pane and does not allow editing and share that with team members, key stakeholders, and capture in documentation would be a boon to the work flow. 

It would be most ideal if that Preview URL was constant so that it always showed the latest saved version, e.g.: http://jsfiddle.net/MyUserName/afiddleid/latest/embedded/result/

**Comment by oskarkrawczyk** [comment]
@PDegenPortnoy Just create an embed, for example: 

- Result panel only: http://jsfiddle.net/oskar/7960xwsj/embedded/result/
- all panels with Results being the first one: http://jsfiddle.net/oskar/7960xwsj/embedded/result,css,html,js

You can generate embed from any fiddle:

<img width="577" alt="screen shot 2016-10-14 at 17 06 23" src="https://cloud.githubusercontent.com/assets/34213/19392343/b600db04-9230-11e6-96da-b112f646170e.png">

<img width="529" alt="screen shot 2016-10-14 at 17 06 39" src="https://cloud.githubusercontent.com/assets/34213/19392345/b8ffd0e4-9230-11e6-806b-57a9b25790c9.png">

**Comment by PDegenPortnoy** [comment]
Thanks, @oskarkrawczyk!
