### ISSUE TITLE
SSL certificate for code.jquery.com is invalid

### ISSUE THREAD

**Issue by koenpunt** [jsfiddle/jsfiddle-issues#905]
jQuery is no longer working on jsfiddle.net because the SSL certificate of the domain serving the file has expired:
https://code.jquery.com/jquery-2.2.4.js

Workaround: use a different jquery source: https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js

**Comment by oskarkrawczyk** [comment]
The SSL cert looks a-ok as far as I can see:

<img width="401" alt="screen shot 2016-10-14 at 22 11 50" src="https://cloud.githubusercontent.com/assets/34213/19401359/4402942c-925b-11e6-9b68-db73d085c0c7.png">

**Comment by koenpunt** [comment]
Mine is telling me different:

![image](https://cloud.githubusercontent.com/assets/351038/19401390/6d175d84-925b-11e6-8036-af71e762b626.png)

![image](https://cloud.githubusercontent.com/assets/351038/19401389/6b60d8e4-925b-11e6-82af-46b7be491fe0.png)

**Comment by koenpunt** [comment]
Found this related article: https://support.globalsign.com/customer/portal/articles/2599710-ocsp-revocation-errors---troubleshooting-guide

**Comment by oskarkrawczyk** [comment]
That's because of GlobalSign has bunch of issues at the moment: http://www.zdnet.com/article/globalsign-security-certificate-foul-up-knocks-out-secure-websites/
