### ISSUE TITLE
Use target: 1 (ES5) for TypeScript to support decorators

### ISSUE THREAD

**Issue by PFight** [jsfiddle/jsfiddle-issues#906]
JSFiddle now compiles TypeScript calling ts.transpile like this:

    var params = [sourceScript, { filename: "embeded" }];
    var transpiled = ts.transpile.apply(ts, params);
    new Function(traspiled)();

Problem, is that you pass second parameter `compilerOptions` object to `transpile`, without `target` property. That's why, target by default is 0 (ES3).  Due to [bug in TypeScript compiler](https://github.com/Microsoft/TypeScript/issues/11658), decorators for ES3 works, but not correctly. Documentation for TypeScript says, that decorators supported only for target: ES5. So, I suggest modify your code like this:

    var params = [sourceScript, { filename: "embeded", target: 1 }];
    var transpiled = ts.transpile.apply(ts, params);
    new Function(traspiled)();

Then, [this code](https://jsfiddle.net/PFight/3cmnctz2/) will work fine in JSFiddle, as it [works in Plunker](https://plnkr.co/edit/fcjDyqdK6kG9yPWlTsNB?p=preview).

**Comment by oskarkrawczyk** [comment]
@PFight `target: 1` wasn't really working so did a `target: "es6"` instead. Looks like it's ok.

**Comment by PFight** [comment]
It looks [not working](https://jsfiddle.net/PFight/3cmnctz2/) now. If you look at [implementation](https://raw.githubusercontent.com/Microsoft/TypeScript/v1.7.3/lib/typescript.js), there target can be 0 (ES3), 1 (ES5) or 2 (ES6). It must work.

See [this example](https://jsfiddle.net/PFight/qxgqy0a3/). When I pass target: 1, decorator called like this:

    __decorate([
        TestDecorator
    ], MyClass.prototype, "foo", null);

But, when I pass nothing, or target: 0, code is like this:

    __decorate([
        TestDecorator
    ], MyClass.prototype, "foo");

That last `null` parameter is the reason of invalid behaviour of decorators. You can try debug log in console output of transpile, and look, whether that `null` parameter exists or not. I tried change your "es6" in debugger in chrome, and [this fiddle](https://jsfiddle.net/PFight/3cmnctz2/) become working.
