### ISSUE TITLE
Log TypeScript compilation errors

### ISSUE THREAD

**Issue by PFight** [jsfiddle/jsfiddle-issues#907]
JSFiddle now compiles TypeScript calling ts.transpile like this:

    var params = [sourceScript, { filename: "embeded" }];
    var transpiled = ts.transpile.apply(ts, params);
    new Function(traspiled)();

To log TypeScript compilation errors in console, you should change it like this:

    var diagnostics = [];
    var params = [sourceScript, { target: 1 }, "embeded", diagnostics];
    var transpiled = ts.transpile.apply(ts, params);
    new Function(traspiled)();
    for (var i = 0; i < diagnostics.length; i++) {
        console.error(diagnostics[i]);
    }

See this [JSFiddle example](https://jsfiddle.net/PFight/qxgqy0a3/) in action. It would be great also implement some GUI, that will show compilation errors in special window.

p.s.  See [another issue](https://github.com/jsfiddle/jsfiddle-issues/issues/906) for explanation, why I use `target: 1` there.

**Comment by oskarkrawczyk** [comment]
@PFight Added console logging. Having a GUI won't be possible for now, since we'll rather spent the time on the complete rewrite of JSFiddle which is ongoing.
