### ISSUE TITLE
* { ... } in CSS breaks jsfiddles

### ISSUE THREAD

**Issue by caub** [jsfiddle/jsfiddle-issues#908]
example: https://jsfiddle.net/crl/s0xbrwv5/

![image](https://cloud.githubusercontent.com/assets/3134574/19409528/9b859670-92d5-11e6-9a77-3c130c373d80.png)

`body * { ... }` would work though

**Comment by oskarkrawczyk** [comment]
It's a combination of `* {}` and `display` that breaks rendering.

No idea why, there's nothing from what I see in the source that would cause this issue.

**Comment by oskarkrawczyk** [comment]
Closing. 2.0 rewrite will not have this issue.
