### ISSUE TITLE
Allow change/removal of avatar

### ISSUE THREAD

**Issue by GoOtterGo** [jsfiddle/jsfiddle-issues#909]

**Comment by oskarkrawczyk** [comment]
Avatar is connected to your gravatar.

**Comment by llccing** [comment]
@oskarkrawczyk ,should show modify info on jsfiddle.com somewhere?

**Comment by oskarkrawczyk** [comment]
@llccing see my comment above.

**Comment by llccing** [comment]
@oskarkrawczyk ,i know,  i mean if you can show info in the website (jsfiddle.com)
