### ISSUE TITLE
Add API to get js-fiddle in JSON format

### ISSUE THREAD

**Issue by monkeypunch3** [jsfiddle/jsfiddle-issues#911]
I'm working on tools for web developers and I would like users to be able to import JSFiddles, edit them in the application and then submit them back. I've found the API to submit a new jsfiddle [here](http://doc.jsfiddle.net/api/post.html) but not a way to read that back or modify it later.

**Comment by oskarkrawczyk** [comment]
Added to [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap). Thanks!

**Comment by monkeypunch3** [comment]
Great! I only seem to be able to see about 20 ideas. Do you have a link to the issue?

**Comment by oskarkrawczyk** [comment]
Just do a search for "API"

**Comment by monkeypunch3** [comment]
Thanks! Found it. I was looking in the ideas column not the accepted column.
