### ISSUE TITLE
Add support for live editing

### ISSUE THREAD

**Issue by monkeypunch3** [jsfiddle/jsfiddle-issues#912]
If possible, enable support for live editing. For example, as you type in markup, or CSS update the preview live.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by monkeypunch3** [comment]
Great. I could not find it. Do you have a link to the specific issue?

**Comment by oskarkrawczyk** [comment]
https://trello.com/c/Sm7Or8Bj/13-live-code-evaluation

**Comment by monkeypunch3** [comment]
Thanks! I was looking in the ideas column not the accepted column.
