### ISSUE TITLE
Show visits/views

### ISSUE THREAD

**Issue by imacange** [jsfiddle/jsfiddle-issues#915]
It would be good to show how many people viewed a fiddle.
On that [link](https://www.quora.com/What-are-some-of-the-best-known-JSfiddles) you gave examples of some of the most viewed fiddles but your website should have a homepage that shows the most viewed fiddles or/and have a voting system.
Then one can search and see all the fiddles related to the subject he is looking for without having to go via google or some other search engine.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
