### ISSUE TITLE
Fat arrow syntax not working in TypeScript

### ISSUE THREAD

**Issue by Crevil** [jsfiddle/jsfiddle-issues#917]
I've had some snippets on JSFiddle for some blog posts using TypeScript, but some of them have stopped working.

Specifically it's when I use the fat arrow notation for function definitions. It have been working before, but something have changed.

Here is a simple example: https://jsfiddle.net/CaveOfCode/3wdme693/1/ 

With the following snippet:

```
const fatArrow = () => console.log("fatArrow");
fatArrow();
const functionKeyword = function() { console.log("functionKeyword"); };
functionKeyword();
```

The fatArrow throws the error.

```
VM111:2 Uncaught SyntaxError: Unexpected identifier
```

**Comment by oskarkrawczyk** [comment]
TypeScript transpiler in JSFiddle only allows you to use:

`const fatArrow = () => { console.log("fatArrow") }`
