### ISSUE TITLE
Don't Bug for CORS or HTTPS

### ISSUE THREAD

**Issue by technbuzz** [jsfiddle/jsfiddle-issues#918]
If I am a tester and want to test certain api. Other coding playground would stop me, because I am not following Same origin policy or the I am requesting a non secure or **http** resource from **https**.

I wish if there is a solution along with honoring the security.

**Comment by oskarkrawczyk** [comment]
@technbuzz JSFiddle works over HTTP and HTTPS, just change the protocol for an existing fiddle.

**Comment by dizel3d** [comment]
I cannot use it without creating a new fiddle, because **http**://jsfiddle.net/ automatically redirects me to **https**

**Comment by oskarkrawczyk** [comment]
Existing fiddles can be used over HTTP.

**Comment by dizel3d** [comment]
Yes, there is no real problem to create a fiddle.
