### ISSUE TITLE
Diff history

### ISSUE THREAD

**Issue by kaihendry** [jsfiddle/jsfiddle-issues#919]
I have a bunch of WIPs public fiddles here: https://jsfiddle.net/user/kaihendry/fiddles/

https://twitter.com/kaihendry/status/791911842566148097

But it's too difficult for me to know what's working and to prune the ones that are not working without some sort of history.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
