### ISSUE TITLE
jsfiddle automatically closing tags when it shouldn't

### ISSUE THREAD

**Issue by cdilga** [jsfiddle/jsfiddle-issues#921]
The following fiddle shows a nested p tag being manipulated in an unexpected way. https://jsfiddle.net/cdilga/u73z4a4j/11

HTML generated by jsfiddle:
```
<p class="red">Foo</p>

<!--Erroneous tags are added in here -->
<p class="red"></p><p class="big">
Bar
</p><p></p>
```

Obviously, the styling doesn't seem to apply since the p tag that is red is going to have zero height.

**Comment by oskarkrawczyk** [comment]
Not sure I understand the request here.

The fiddle (http://jsfiddle.net/cdilga/u73z4a4j/11/) highlights the last `</p>` because it's nested which is not the right thing to do for `p` tags. So this is correct.
