### ISSUE TITLE
Attatching image files

### ISSUE THREAD

**Issue by bb986** [jsfiddle/jsfiddle-issues#924]
It would be incredibly useful if you were able to upload image files rather than having to give image URLs so that when jsfiddle is being used with stackoverflow or is being used by students then you would not have to find image URLs if you downloaded them some time ago.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
