### ISSUE TITLE
my new fiddle I have added external resource which I have taken from old fiddle

### ISSUE THREAD

**Issue by js08** [jsfiddle/jsfiddle-issues#925]
i am trying to create a new fiddle keeping my old fiddle as refrence.
in my new fiddle I have added external resource which I have taken from old fiddle.
but my new fiddle is not working like my old fiddle.
there is some problem in adding external resources.
cam you guys tell me how to fix It.
old fiddle https://jsfiddle.net/9e767txs/9/
new fiddle https://jsfiddle.net/uk9tembv/1/
-external resources https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xat1/t39.3284-6/12056998_1697020110531721_1758939694_n.js https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xtp1/t39.3284-6/12056967_908623935885795_236887341_n.js

**Comment by oskarkrawczyk** [comment]
One fiddle is using `JavaScript 1.7` the other is not.
