### ISSUE TITLE
Idea: Resizeable Description

### ISSUE THREAD

**Issue by cazzer** [jsfiddle/jsfiddle-issues#927]
## Idea
As a fiddler, I would like to be able to resize my fiddle's description's `textarea` so that I can ramble on and on and on and on and on and on without having to scroll constantly to double check that my nonsense makes sense.

#### Workarounds
1. Open up dev tools and remove `resize: none` from `#sidebar textarea`
2. Write shorter descriptions

## Use Case
Here is me experiencing the _pain_:
<img width="246" alt="edit_fiddle_-_jsfiddle" src="https://cloud.githubusercontent.com/assets/2466842/20245839/9a3c3bda-a95e-11e6-9690-06e927dc8208.png"><img width="253" alt="edit_fiddle_-_jsfiddle" src="https://cloud.githubusercontent.com/assets/2466842/20245860/3daa1d82-a95f-11e6-98c7-4158503fb47e.png">

I'm happy to submit a PR for this if that's a thing that people can do.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
