### ISSUE TITLE
Using non-slim jQuery?

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#928]
We wanted to upgrade all our demos to use the latest jQuery version, but faced the problem that jsFiddle's API now auto-loads jQuery *Slim* instead of the full package. Our demos depend on the AJAX capabilities of the full package.

Demo: http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/basic-line/

I would expect either the full package to load, or an alternative way of specifying the non-slim version. Or, most logically, that the slim package would only be included explicitly, like `gh/get/jquery-slim/3.1.1/`.

**Comment by oskarkrawczyk** [comment]
@TorsteinHonsi We're looking into this

**Comment by majkelcc** [comment]
Hi @TorsteinHonsi, we'll be probably moving jQuery Slim versions to a separate category. In the meantime I changed version `3.1.1` to point to the full jQuery version.

**Comment by oskarkrawczyk** [comment]
Fixed. `jQuery Slim` now also resides in its own group.

**Comment by TorsteinHonsi** [comment]
Thanks Oskar!
