### ISSUE TITLE
Be able to sync your fiddle with the most common online storage providers

### ISSUE THREAD

**Issue by rodude123** [jsfiddle/jsfiddle-issues#929]
At the moment the only way you can physically save your updates is through jsfiddle but you loose track of what updates you have made like I do regularly and this is why saving to google drive onedrive, dropbox or mega is crucial as you can see what version your on

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
