### ISSUE TITLE
Jsfiddle is more and more bogus

### ISSUE THREAD

**Issue by onigetoc** [jsfiddle/jsfiddle-issues#930]
I used to love jsfiddle. but there's more and more annoying things.
- the https http ajax request work and do not work.
- today, want i clicked run a new page opened.
-` {"error": "Please use POST request"}`  I do not want to use POST i want to us GET 
- sometime something work but it stop working minutes latter even if i return to old functional version.
- Can't delete external ressources anymore, it's always staying there's

Sorry but if all these bugs are not fixed i will soon leave for codepen.
I do not like the Codepen UI but it's 100% working and powerfull. Do pay service like Codepen to make it better if you need support.

Thank you

**Comment by oskarkrawczyk** [comment]
Everyone's free to use the service they like the most.

Nothing is bogus about JSFiddle, the old codebase is frozen and we're working on a rewrite. That's all.
