### ISSUE TITLE
Draft and Embed not working

### ISSUE THREAD

**Issue by aguiguy** [jsfiddle/jsfiddle-issues#931]
I noticed today that the "draft" and "embed" features are no longer working.
The embed preview works, but when you follow the embed URL, it returns the createEmbedFrame() function.call() source code.

The "draft" page does open but shows the wrong fiddle (one of my previous fiddles from within the last 3 weeks).  The same action happens with my other fiddles.

![jsfiddle-screenshot-embed](https://cloud.githubusercontent.com/assets/1181530/20459452/7399e58c-ae8f-11e6-9aac-f95f270169fc.png)

**Comment by oskarkrawczyk** [comment]
@aguiguy So you take the URL from a `script` tag and expect the content to be something other than JavaScript?

Not quite following what's supposed to be incorrect in this behavior.

As to draft, should be working again.

**Comment by aguiguy** [comment]
Dzieki.
ah, yes...  I meant to use "embedded".   I never used "embed" before, and assumed that call was the same as the "embedded" call.
