### ISSUE TITLE
Load external Resources auto list for easy access

### ISSUE THREAD

**Issue by sheetaldshivdas** [jsfiddle/jsfiddle-issues#932]
Appreciate if a list is provided to select amongst the available common and mostly used external resources like, jQuery, angular, angular2, ionic, etc... with the latest versions automatically updated while creating a new fiddle additional to user providing the link.

**Comment by oskarkrawczyk** [comment]
You can pick frameworks from the JS config panel:

<img width="461" alt="screen shot 2016-11-21 at 08 08 04" src="https://cloud.githubusercontent.com/assets/34213/20473539/a8ae9aa0-afc1-11e6-9246-a7d3c384cbcb.png">
