### ISSUE TITLE
Interfering Ad

### ISSUE THREAD

**Issue by Mottie** [jsfiddle/jsfiddle-issues#933]
At times I need to stack windows. When I do this, the contents of the side bar are inaccessible behind the ad. In this screen shot, I attempt to use the scroll wheel to scroll through the external resources.

![jsfiddle sidebar](https://cloud.githubusercontent.com/assets/136959/20640501/16698406-b3a5-11e6-867d-1e7ada220428.gif)

**Comment by oskarkrawczyk** [comment]
Fixed
