### ISSUE TITLE
suggestion for shortcut keys

### ISSUE THREAD

**Issue by zenithtekla** [jsfiddle/jsfiddle-issues#934]
It is good if JSFiddle integrates a few patterns of shortcut keys.
Sublime-Text 3 pattern: shortcut keys like CTRL+L, CTRL + D, CTRL+K, CTRL+SHIFT+D, CTRL+/, CTRL+SHIFT+/ (for comment  /* code commented out */), ...

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no features will be added. The new rewritten codebase will have this feature.
