### ISSUE TITLE
Bug: Valid HTML4.01 can get marked as red (<<< NOTE: HTML4.01)

### ISSUE THREAD

**Issue by chrisjj** [jsfiddle/jsfiddle-issues#936]
This is a repeat report augmented for the benefit of people who [previously mistook this issue](https://archive.is/HF3Gr) as being due to invalid HTML 5 (<<< 5 not 4).

Despite that this HTML4.01:
```

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>Title of the document</title>
</head>

<body>
<div>
<table>
<tr><td>kjasd kjasdh kajsdh alkjsdh lajksdhlas</td>
<tr><td>
  <ul class="container">
    <li class="left"><a href="#">ListItem1</a></li>
    <li class="right"><a href="#">ListItem2</a></li>
  </ul>
</table>
</div> 
```

http://pastebin.com/BipXrFFH

is valid http://i.imgur.com/3GmvAIa.png , JSFiddle marks two tags in read:

http://i.imgur.com/diMC4oO.png

![image](https://cloud.githubusercontent.com/assets/6157073/20674031/3c66f6c6-b57f-11e6-9747-6f48c19299bd.png)

https://jsfiddle.net/vhdz49jh/

**Comment by oskarkrawczyk** [comment]
Use HTML5 or XHTML.

**Comment by chrisjj** [comment]
Thanks for the suggestion. Here's mine: fix JSFiddle, or declare that it doesn't work properly on HTML4.01.
