### ISSUE TITLE
Long e-mail addresses cause sign up page to use 100% CPU and freeze up

### ISSUE THREAD

**Issue by jbchouinard** [jsfiddle/jsfiddle-issues#939]
I have found it impossible to sign up on fiddle.net with my business e-mail address since the page becomes unusably slow when entering a long (25+ characters) address. Eventually I have to kill the tab or browser since the page uses 100% CPU.

I have observed the same behaviour on Chrome Version 54.0.2840.100 (64-bit) and Firefox 47.0, running on Ubuntu 15.10.

How to reproduce:

Go to [https://jsfiddle.net/user/signup/](https://jsfiddle.net/user/signup/)
Keep typing characters in email address box - eventually the tab hangs up - at around 25-28 characters on my system.

**Comment by oskarkrawczyk** [comment]
I can confirm the problem, interesting issue. Will have a look soon.

**Comment by jbchouinard** [comment]
Checking the console, when the address is long, each call to Helpers.Helpers.isEmail takes over half a second. I don't have any more time to look into it but that seems to be the culprit.

**Comment by oskarkrawczyk** [comment]
Yep, I know exactly what the issue is, interestingly this is the first time anyone has reported this.

**Comment by oskarkrawczyk** [comment]
Fixed
