### ISSUE TITLE
Settings: Default Framework

### ISSUE THREAD

**Issue by b9chris** [jsfiddle/jsfiddle-issues#940]
It's super annoying to have to select jQuery every time I start a fiddle. It would help a lot if in Settings I could just set some defaults and never have to do those clumsy taps anymore.

A 2011 Issue's discussion implied this would be possible, but it never arrived:
https://github.com/jsfiddle/jsfiddle-issues/issues/73

**Comment by oskarkrawczyk** [comment]
2.0 rewrite will bring Templates where default frameworks can be set. We already have templates on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
