### ISSUE TITLE
Update fabricJS to 1.7.1

### ISSUE THREAD

**Issue by asturur** [jsfiddle/jsfiddle-issues#941]
Hello, i'm Andrea, mantainer of fabricJS.

On jsfiddle we have fabricJS up to 1.5.0 while the library is bumped to 1.7.1

Would be possible to have it upgrade to 1.7.1?

For what kind of version can be asked an upgrade? how often?

Thanks,
Andrea

**Comment by oskarkrawczyk** [comment]
Hi, please make sure the newest Fabric is available in CDNJS. Only then we
can update it in JSFiddle

--

**Comment by oskarkrawczyk** [comment]
1.7.1 added.

**Comment by oskarkrawczyk** [comment]
> For what kind of version can be asked an upgrade? how often?

You can requests updates as ofter as your release new versions.

**Comment by asturur** [comment]
thanks!
