### ISSUE TITLE
Shortcuts for comments and multiple selection

### ISSUE THREAD

**Issue by tranotheron** [jsfiddle/jsfiddle-issues#943]
It would be great to have shortcut, when highlighting excerpt of code and click "cmd/ctrl + /" to automatic comment this fragment (right now it's working only for html).

I love multiple selections from some IDE's: https://blog.jetbrains.com/phpstorm/2014/03/working-with-multiple-selection-in-phpstorm-8-eap/ too

**Comment by oskarkrawczyk** [comment]
Comments: https://github.com/jsfiddle/jsfiddle-issues/issues?utf8=%E2%9C%93&q=comment
Multi-cursor: Added to Roadmap.
