### ISSUE TITLE
Download all the fiddles as a static site with dashboard page being index

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [jsfiddle/jsfiddle-issues#944]
Whatever fiddles you have, you would be able to download all the fiddles as a static site with dashboard page being the landing page of the site.

External scripts and resources may not be included.

**Comment by oskarkrawczyk** [comment]
Downloading fiddles is on the roadmap, so are profiles with fiddle index, but downloading static indexes is not something we'd want to explore.
