### ISSUE TITLE
<html>, <head>, and <body> tags

### ISSUE THREAD

**Issue by TK0805** [jsfiddle/jsfiddle-issues#945]
I think you should add an option where which enables you to use the <html>, <head>, and <body> tags, because that would be nice, because I am kind of being thrown off by this way. It does simplify it, which I like, but I would enjoy this option. I have no comments on the CSS, JavaScript, or CoffeeScript options. I think you did a good job on JSFiddle.

**Comment by oskarkrawczyk** [comment]
We've debated this multiple times for a long time internally, and decided not have full HTML.
