### ISSUE TITLE
Mixed Content Enyo CDN and jsfidle secure connection

### ISSUE THREAD

**Issue by MAMISHO** [jsfiddle/jsfiddle-issues#946]
Hi, I was trying run Every enyo versions on jsfiddle but I couldn't it. the problem which show me in Chrome's console is like this.
VM164:1 Mixed Content: The page at 'https://jsfiddle.net/MAMISHO/r782a6yn/' was loaded over HTTPS, but requested an insecure script 'http://enyojs.com/enyo-2.5.1/enyo/enyo.js'. This request has been blocked; the content must be served over HTTPS.

So I tried to get https from Enyo cnd and its working. JsFiddle team, could you update secure connection to ENYO library please? Because I love JsFiddle and I use To try some enyo code in this tool.

**Comment by oskarkrawczyk** [comment]
Both, nightly and 2.7.0 will work just fine.

Switched rest of the versions to no-protocol so it works over HTTP and HTTPS.
