### ISSUE TITLE
JSFiddle collaboration no longer works in Firefox

### ISSUE THREAD

**Issue by isoft** [jsfiddle/jsfiddle-issues#948]
The JSFiddle collaboration feature no longer works in Firefox. If one of two people is using Firefox, he does not see the actions performed by the other user. This may be a problem with the together.js library.

**Comment by oskarkrawczyk** [comment]
Can't replicate, tested on the newest Firefox. Everything works as expected.

If you feel like this is a bug in together.js, drop a report on their GH Issues.

**Comment by isoft** [comment]
Looks like it was an obscure Privacy Badger issue. For those who might run into a similar problem, you may need to disable Privacy Badger for the whole browser. Disabling it only on a tab running JSFiddle (or any other site using together.js) may not work. If you would like to continue using Privacy Badger you may need to reinstall it.
