### ISSUE TITLE
Automatically loading js in body in generated fiddles

### ISSUE THREAD

**Issue by larsac07** [jsfiddle/jsfiddle-issues#949]
In a generated fiddle, it would be nice to be able to select where to load the JS.

Example: http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/maps/series/data-datalabels/

In our case, this would mean not having to use the JQuery `ready()` function every time, as we could for example simply load JS in the `<body>`. Perhaps this could be set in `demo.details`, something like:

```
---
 name: Example fiddle
 authors:
   - Lars Cabrera
 loadType: body
...
```

**Comment by oskarkrawczyk** [comment]
@majkelcc Do you think it's possible to get this working in the legacy codebase? 

Oddly I see some references in the code suggesting this might be supported in `api_github/views.py#59`

**Comment by majkelcc** [comment]
@oskarkrawczyk @larsac07 passing `js_wrap` key in manifest file with these values should do:

- __l__ - onLoad
- __d__ - onDomready
- __h__ - no wrap in head
- __b__ - no wrap in body

**Comment by larsac07** [comment]
Thank you!
