### ISSUE TITLE
Problems with including raw CSS files from GitHub

### ISSUE THREAD

**Issue by fnagel** [jsfiddle/jsfiddle-issues#95]
A few weeks ago GitHub changed its raw files path from:

<pre>
https://github.com/fnagel/jquery-ui/raw/selectmenu/themes/base/jquery.ui.selectmenu.css
</pre>

to this:

<pre>
https://raw.github.com/fnagel/jquery-ui/selectmenu/themes/base/jquery.ui.selectmenu.css
</pre>

The old URL is redirected to the new one but even when I change the path jsFiddle inlcudes to the new URI the stylesheets will not work (tested in FF4, FF5 and latest stable Chrome). JS files work as expected.

_DEMOS_
Old file path, worked perfectly a few weeks ago: http://jsfiddle.net/fnagel/hsn95/
Demo with new file path AND additional inline styles so its working: http://jsfiddle.net/fnagel/GXtpC/
Workaround is to add the needed stylesheets as inline styles within the CSS pane in jsFiddle, so please delete inline styles to reproduce the issue.

Problem has been verified by zalun (IRC #jsfiddle)

**Comment by spaeronz** [comment]
how do you add css
