### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Southernw2002** [jsfiddle/jsfiddle-issues#950]
Hi there .. first up apologies for the possible silly questions...

I have just found JSFiddle.. and it is fantastic... but I need some basic help.. and having trouble finding it.

I have a project to do a Google map of places to be visited on a holiday, and have (in JSfiddle) got basically things working

I did have troubles saving work .. I still cant find a save button as one of the help sheets I read suggested... and cant work out how to link directly to the resultant map.

The ultimate plan is to dynamically update the map (potentially from a excel sheet).

So .. can you point me towards a good reference/help document ?

Many thank

Andrew

**Comment by oskarkrawczyk** [comment]
There's a **Save** button in the action bar.

<img width="421" alt="screen shot 2016-12-31 at 14 35 02" src="https://cloud.githubusercontent.com/assets/34213/21577747/566328aa-cf66-11e6-976e-08977980c9ac.png">

You cannot link directly to the resulting frame, but you can embed the results within a website:

<img width="1003" alt="screen shot 2016-12-31 at 14 36 25" src="https://cloud.githubusercontent.com/assets/34213/21577751/940d3e98-cf66-11e6-8725-42bd2276f39c.png">

Alternatively you can append `/embedded/` at the end of the fiddle URL to see the embed without the need of actually embedding it somewhere.

**Comment by Southernw2002** [comment]
Hi Oskar.. thank you for the help... I am having a lot of fun ... but with the occasional frustrations.

I have a Update button ( Run, Update, Fork, Set as Base, Tidy, Collaborate and Embed).. but it doesn't seem to save.. so need to use the Set As Base option.....

I found a note on one of the many sheets I have read and added /show to the web address and its working wonderfully.

Have hit a wall with infowindows which I will post soon.. but (like I said ) I am having a lots (mainly) of fun.

Happy New Year and thanks again

Andrew

**Comment by Southernw2002** [comment]
OK .. thank you

A
