### ISSUE TITLE
Stop logging us out?

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#952]
jsfiddle is the only site that regularly logs me out. (the cookie expires)

Worse, the workflow in this case is no fun. It usually consists of

1. Go to jsfiddle.net
2. Type in some code
3. Realize I'm not logged in
4. Press Login
5. Cry because fiddle is now lost

OR

1. Go to jsfiddle.net
2. Type in some code
3. Realize I'm not logged in
4. Open a new tab
5. Go to jsfiddle.net
6. Login
7. Manually copy HTML pane from old tab to new
8. Manually copy JS pane from old tab to new
9. Manually copy CSS pane from old tab to new
10. Manually copy any other settings from old tab to new
11. Cry because this is so tedious

Maybe there is a good reason for the sessions or login cookies to expire? Assuming you can't just set the cookie not to expire for years maybe some other workflow? For example if clicking "login" didn't lose the current fiddle that might be enough. Another idea would be to have a cookie that doesn't expire that effectively says "this user was logged in before" and if that cookie exists and the user is not logged in prompt them to login? Just throwing out ideas.

**Comment by oskarkrawczyk** [comment]
If you're logged out and create an anonymous fiddle, you can open a new tab, log in, and press save in the previous tab. There's no need to copy code. Also, there's a local draft of unsaved fiddles stored so you don't lose fiddles that weren't saved.

That said, the codebase for the current JSFiddle version is frozen – no minor issues will be addressed. The new rewritten codebase will not have this issue.
