### ISSUE TITLE
No Library on saved projects

### ISSUE THREAD

**Issue by Southernw2002** [jsfiddle/jsfiddle-issues#953]
Not sure if this a FSFIDDLE question ... but I have a couple of projects I an learning and they show that they have NO LIBRARY... and don't load without a security message.
Projects that show a library are all fine.

What do I do to fix ?

Thanks

**Comment by oskarkrawczyk** [comment]
I'm not sure I understand.

Please provide fiddles as examples.

--

**Comment by oskarkrawczyk** [comment]
Load all external scripts via https.

--

**Comment by Southernw2002** [comment]
I am very sorry but I don't understand... I really cant see the difference between the project that run and this one.

**Comment by oskarkrawczyk** [comment]
Load the google library via https not http. You can't load JSFiddle via HTTPS and external resources via HTTP.
