### ISSUE TITLE
Ability to view "All Fiddles" page with preview thumbnails

### ISSUE THREAD

**Issue by su-narthur** [jsfiddle/jsfiddle-issues#954]
It's hard to find fiddles in my "All Fiddles" page since I can only see a small amount of the code and the titles are mostly random strings. Having an optional layout consisting of preview thumbnails (could be cached) would make it so much easier to find what I'm looking for.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.

**Comment by su-narthur** [comment]
@oskarkrawczyk Thanks for the link. Just read all the cards and don't see this idea. Do you remember the title of the card?

**Comment by oskarkrawczyk** [comment]
Agree, the title could be better, but the filleds thumbs and such are under https://trello.com/c/YPx1uTZe/20-fiddles-gallery-most-rated-viewed-forked
