### ISSUE TITLE
Allow type definitions in Babel mode

### ISSUE THREAD

**Issue by Aldredcz** [jsfiddle/jsfiddle-issues#955]
Hello!

My simple request is about adding [`babel-plugin-transform-flow-strip-types`](https://www.npmjs.com/package/babel-plugin-transform-flow-strip-types) into Babel transpiler settings. This would allow to simply copy-paste _flowtyped_ code (no expecting to be typechecked, just allowing the syntax). 

Thanks.

**Comment by oskarkrawczyk** [comment]
I couldn't get this to work with the client version of Babel, perhaps it can get enabled in JSFiddle 2.0 when the language parsing is being done on the backend
