### ISSUE TITLE
Content runs twice when loading from GitHub

### ISSUE THREAD

**Issue by TorsteinHonsi** [jsfiddle/jsfiddle-issues#956]
Live demo: http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/line-basic/

Observed in Chrome that the chart animates in, then flashes and animates once again. This only applies to content loaded from GitHub. It happens when the page is refreshed too.

Originally reported to Highcharts: https://github.com/highcharts/highcharts/issues/6237

**Comment by cs09g** [comment]
This happens me as well when the code try to load some code from <script href=""> tag in HTML section.
Any progress on this issue?

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by cs09g** [comment]
when was it fixed? now it works charm!

**Comment by oskarkrawczyk** [comment]
It was fixed when I wrote "Fixed".
