### ISSUE TITLE
Result tab failing on embeds.

### ISSUE THREAD

**Issue by codylindley** [jsfiddle/jsfiddle-issues#957]
The result tab is no longer working (or showing up) with embeds.

e.g. https://www.reactenlightenment.com/react-state/8.2.html

click on results tab. 

Do I need to update something?

**Comment by oskarkrawczyk** [comment]
The issue is that your rendering content after the iframe's contents sent info to the iframe about its height.

We'd need to check the size of the body on an interval and then update the iframe again.

I'll have a look into this first thing tomorrow morning.

**Comment by codylindley** [comment]
So, something change recently, because when I wrote the book this was working fine. Right?

**Comment by oskarkrawczyk** [comment]
Something did change

**Comment by codylindley** [comment]
Is there an ETA on this? Apologies, don't want to be pushy, just need to know if I need to find another solution. I'm curious, would not all embedded solutions be suffering this same issue? This can't be just my implementation. Or, is it?

**Comment by oskarkrawczyk** [comment]
I need a some time to figure out the best way to fix this with preferably not using `setInterval` to check if any element has changed its size. So far couldn't find a good cross-browser way.

In the mean time I'll add a minimum size for the results panel so in the worst case scenario user will have to scroll its content.

Btw. Is there a way you can use the `iframe`-based embed instead of the `<script>` one?

**Comment by oskarkrawczyk** [comment]
@codylindley Don't know why this didn't occur to me before but to bypass the current behavior just set a fixed height to the `body` element or any other in fiddle's CSS.

**Comment by codylindley** [comment]
You mean iframe. Right?

i.e. https://www.dropbox.com/s/b665v45520fwyx5/Screenshot%202017-01-23%2010.35.32.png?dl=0

**Comment by oskarkrawczyk** [comment]
@codylindley No, I mean the body. https://jsfiddle.net/1x4ngchs/ (inception alert: JSFiddle embed embedded in JSFiddle)

**Comment by oskarkrawczyk** [comment]
Since getting elements dimension inside of an `iframe` with `setInterval` is too expensive, a failsafe has been added when the height of the results tab is `0`.

Better solution will be provided once `ResizeObserver` is implemented by most browser vendors.
