### ISSUE TITLE
fiddle hashed content after saving

### ISSUE THREAD

**Issue by Zydnar** [jsfiddle/jsfiddle-issues#958]
![2017-01-19 12_46_49-edit fiddle - jsfiddle](https://cloud.githubusercontent.com/assets/20562545/22106015/10eb1c70-de47-11e6-9fe8-9886e7ceefc6.png)
Browser Chrome 55.0.2883.87 m (64-bit) windows
Mayby session restore or clearing cache caused the issue, nothing else came to my mind.

**Comment by oskarkrawczyk** [comment]
This sometimes happens, the reason is unclear.

Rewrite 2.0 will not have this issue as it'll work completely different and will not need a base64 encoded content.
