### ISSUE TITLE
Update Dojo versions

### ISSUE THREAD

**Issue by dylans** [jsfiddle/jsfiddle-issues#959]
We're like to have the Dojo versions updated on JS Fiddle please.

Here's the more recent versions:

http://archive.dojotoolkit.org/cdn/1.12.1-cdn/
http://archive.dojotoolkit.org/cdn/1.11.3-cdn/
http://archive.dojotoolkit.org/cdn/1.10.7-cdn/
http://archive.dojotoolkit.org/cdn/1.9.10-cdn/
http://archive.dojotoolkit.org/cdn/1.8.13-cdn/
http://archive.dojotoolkit.org/cdn/1.7.11-cdn/
http://archive.dojotoolkit.org/cdn/1.6.4-cdn/
http://archive.dojotoolkit.org/cdn/1.5.5-cdn/
http://archive.dojotoolkit.org/cdn/1.4.7-cdn/

Let me know if there's anything else you need from us. Thanks!

**Comment by oskarkrawczyk** [comment]
@dylans We can add versions of Dojo available at https://cdnjs.com/libraries/dojo, which means that nothing newer than 1.10.4, unless someone updates CDNJS with the newer versions.

**Comment by dylans** [comment]
Thanks @oskarkrawczyk ok, I've opened https://github.com/cdnjs/cdnjs/issues/10349to track that down. Previous request by users from back in July to add 1.11.x haven't been answered thus far, so hopefully we can streamline the process with them.

**Comment by oskarkrawczyk** [comment]
@dylans they have so many requests that it's better to just prepare a pull request so they can merge it in – from what I understand the team behind CDNJS is really small and they're having issues keeping up with demand.

**Comment by dylans** [comment]
I offered to do that, but I really need to know what they want/expect in the PR. I looked at the past PRs for Dojo versions and they vary substantially in how they were done. I don't think they really want all 27MB gzipped of Dojo though that's what Google does. Some versions just have dojo.js, which really won't help much at all, others include all of dojo/dojo, etc.

**Comment by oskarkrawczyk** [comment]
@dylans any word on this?

**Comment by dylans** [comment]
@oskarkrawczyk unfortunately nothing since they triaged the issue and marked it high priority back in January. I would be more than happy to do the work, but need someone from their team to spend a few minutes and explain how they want this done given the size of Dojo, etc.

**Comment by oskarkrawczyk** [comment]
@dylans So this is the deal, I can add Dojo from your CDN, the big downside is that when we release JSFiddle 2.0, and these versions of Dojo are still not on CDNJS, the fiddles using old CDN will stop working.

**Comment by dylans** [comment]
Ok, thanks, and I'll not forget about this. For what it's worth, since this original issue, there's been an additional point release, e.g. 1.12.2, 1.11.4, etc.

Also, exciting, when is JS Fiddle 2 being released?

**Comment by oskarkrawczyk** [comment]
@dylans 

> there's been an additional point release, e.g. 1.12.2, 1.11.4, etc.

Ok, I'll add the latest from each point-release, I'll do this later today or tomorrow morning.

> Also, exciting, when is JS Fiddle 2 being released?

Still pretty far away (takes a bit of time since we're learning Vue.js along the way), but the whole team is hands-on!

**Comment by oskarkrawczyk** [comment]
@dylans it has been done.

The issue you're having with getting CDNJS updated got us thinking if depending on them is the right way to go... We're now considering using NPM instead

**Comment by oskarkrawczyk** [comment]
@dylans We have a problem, a user has noticed in #984 that the resources are not available over SSL – I have to admit, I haven't checked the provided links, because I took for granted that they will work over HTTPS, but they don't.

Is there any chance you could enable SSL on the CDN?

**Comment by oskarkrawczyk** [comment]
@dylans ping

**Comment by dylans** [comment]
Sorry, I've been traveling and forgot to look into this, looking into it now, will post back asap (hopefully today)

**Comment by dylans** [comment]
@oskarkrawczyk this should be resolved now, thanks for bringing it to our attention.

**Comment by oskarkrawczyk** [comment]
@dylans Thanks a lot!
