### ISSUE TITLE
iframe sandbox "allow-popups" capability removed?

### ISSUE THREAD

**Issue by vinodc** [jsfiddle/jsfiddle-issues#961]
Our JSFiddles that launch pop-ups no longer work because "allow-popups" is not part of the sandbox attribute any longer. Could you confirm that if this will be added back? Or better yet, the "allow-popups-to-escape-sandbox" attribute? (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox)

Thanks!

**Comment by oskarkrawczyk** [comment]
@vinodc This has been removed due to it being abused by spammers and scammers. 

I'll give reverting the removal under consideration if you could provide a valid example of this being used in a non-shady way.

**Comment by vinodc** [comment]
@oskarkrawczyk Thanks for the quick response! Here is our JSFiddle example we link to from our production site, GitHub and documentation that is currently non-functional: https://jsfiddle.net/pseudonumos/PB565/embedded/ If you click on "Choose a file" and then click on "Google Drive", it should pop-up to allow the user to connect their Google Drive account and then close, postMessaging data back to the parent window.  You can view a working example [here](https://kloudless.com/file-explorer/) (by clicking "Demo the Chooser").

**Comment by perki** [comment]
Hello we have the same issue on our side. 

For our demo code, involving an oAuth process in a popup, the process is broken.

http://jsfiddle.net/pryv/kmtyxj37/

I would be pleased to have a workarround
Perki

**Comment by lolpack** [comment]
We're having the same issue for a fiddle that demonstrates our Oauth flow: https://jsfiddle.net/napstercat/zf0wjup7/

**Comment by oskarkrawczyk** [comment]
Re-added `allow-popups` for now.

**Comment by BreaGaudioso** [comment]
+1 Thanks for the re-add!

**Comment by alteredtastes** [comment]
+1 woop woop!
