### ISSUE TITLE
Weird stuff happens when using script tags within string

### ISSUE THREAD

**Issue by ferrx** [jsfiddle/jsfiddle-issues#963]
I was attempting to test out some XSS detection, but it seems like JSFiddle is getting in my way. Does JSFiddle have some web app firewall that prevents this? Or has my coffee not kicked in yet?

When using the following JS:
`var myScriptBlock = "<script>alert(1)</script>";`
`//ok..`
`//$('#select-test').append('<option value="' + 111 + '">' + myScriptBlock + '</option>')`

Results in:
`"; //ok.. //$('#select-test').append('' + myScriptBlock + '') });//]]>`

https://jsfiddle.net/ferr/pooue42y/5/

**Comment by oskarkrawczyk** [comment]
Do `"<script>alert(1)</"+"script>";` as a workaround. Other than that the codebase is frozen and no minor issues will be addressed.
