### ISSUE TITLE
Default arguments are not dealt properly

### ISSUE THREAD

**Issue by cawahara** [jsfiddle/jsfiddle-issues#966]
When I use "Try it out" in babel. It turns 2. But when I use jsfiddle, it turns 5. (I checked console.log in Chrome dev tool.)
```
let fn = (a, b, c = 0, d, e) => {}
console.log(fn.length)  // expected result: 2
```
In babel "Try it out"
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&experimental=true&loose=false&spec=false&code=let%20fn%20%3D%20(a%2C%20b%2C%20c%20%3D%200%2C%20d%2C%20e)%20%3D%3E%20%7B%7D%0Aconsole.log(fn.length)%3B

In jsfiddle
https://jsfiddle.net/cawa/7a6wkmt9/

I think it should turn 2 as well in jsfiddle.

**Comment by oskarkrawczyk** [comment]
@cawahara It's hard to say why is this happening – there's a chance we're running an older Babel version which causes this. I'm having issues compiling it for the browser and updating.

**Comment by oskarkrawczyk** [comment]
Updating Babel seems to have fixed the issue.
