### ISSUE TITLE
Add .sass support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [jsfiddle/jsfiddle-issues#968]
Since you closed the [last issue](https://github.com/jsfiddle/jsfiddle-issues/issues/967) and locked the comments, I've had to make a new one. That isn't a very nice thing to do.

> "Just use the tool that works for you best"
\- oskarkrawczyk

JSFiddle *is* the tool that works best for me, it is just an *incomplete* tool. It needs to have **true** Sass support implemented and it will be very close to being perfect.

If JSFiddle was open source I would have added Sass support to it years ago.

I'm not coming here to waste my time. I'm **forced** to use a different tool, that does not fulfill my needs, because it has **one** feature that this one lacks. But it's a significant enough feature that I'm forced to go elsewhere.

You closed the issue and locked the comments. Gave no explanation as why you won't actually support Sass, or if you intend to, what the timeline or level of priority is for it.

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no minor issues will be addressed.

**Comment by TheJaredWilcurt** [comment]
Does that mean the project is no longer being maintained, or that there is a future version in the works unrelated to the current site?

If it's no longer maintained, then that makes sense, but it would have been nice to just mention that in the original message to prevent all the follow ups.

If a new version is in the works,  so long as it still serves the same purpose of creating self-contained html/css/js pages, then the feature request for full Sass support would still be relevant. Which then leads back to the question of why won't you support it, or if you will, what is it's level of priority.

**Comment by oskarkrawczyk** [comment]
A 2.0 rewrite is in the works, with a new codebase that will have some features, new issue, potential bugs. Old codebase is frozen and no minor issues will be addressed.
