### ISSUE TITLE
dragleave doesn't fire when leaving the result/output pane

### ISSUE THREAD

**Issue by bryc** [jsfiddle/jsfiddle-issues#969]
I have a [fiddle ](http://jsfiddle.net/mhwzrLbc/) demonstrating file drag detection in drag and drop API with a responsive full-screen dropzone. It uses `dragleave` to hide the dropzone, however since JSFiddle's new version, the event no longer fires when leaving the output pane in the editor. Embeds aren't affected and `dragleave` fires properly.

To reproduce this, drag a file over to the output pane, and try dragging it past the browser window edge, and also over JSFiddle's pane edges. It doesn't fire consistently when exiting the output pane. This isn't a problem on codepen and liveweave.

**Comment by oskarkrawczyk** [comment]
Works as far as I can see – added a `console.log` which is being fired just fine on leaving the drop area. 

I agree that it doesn't fire 100% of the time, but ~95% which is good enough, considering the codebase has been frozen (with some minor glitches) and no minor issues will be addressed.

I'll put this on the list of things to keep an eye for in the 2.0 rewrite.

**Comment by bryc** [comment]
Probably should have mentioned I was using Chrome. Just tried Firefox and it behaves in that situation. Actually Firefox has a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=656164) regarding dragging _out of the window_, whereas Chrome is having trouble with `dragleave` _within the window_, at least with JSFiddle. Opposites.
