### ISSUE TITLE
Record creation / modification dates, show them in the metadata section

### ISSUE THREAD

**Issue by mjpieters** [jsfiddle/jsfiddle-issues#970]
When investigating allegations of plagiarism, I find myself hitting jsfiddle results from Google with matches. I can't assess when the code in a JSFiddle was added however, so I have to dismiss any such results as having been copied too.

Surely the creation date of a JSFiddle revision is already recorded, but if it isn't, please do. Add the date(s) to the metadata section.

**Comment by oskarkrawczyk** [comment]
@mjpieters Hover over the **Fiddle Meta** for the creation date to appear in the (system) tooltip.

**Comment by mjpieters** [comment]
Ah, thanks. I looked at the page source briefly but didn't find that info. Perhaps this should be easier to discover, but I'll have to remember this for now.

**Comment by oskarkrawczyk** [comment]
We'll find a better place for it in the 2.0 redesign/rewrite
