### ISSUE TITLE
jsFiddle - cannot see/restore JavaScript area anymore

### ISSUE THREAD

**Issue by Legends** [jsfiddle/jsfiddle-issues#971]
Somehow I achieved to hide the javascript section :-).
Cannot restore it again. Deleted localstorage, cookies, ...nothing.
How to restore the layout again?

![jdz0y 1](https://cloud.githubusercontent.com/assets/966368/22971709/e62c2304-f376-11e6-8ef3-da08311f5b85.png)

**Comment by oskarkrawczyk** [comment]
https://github.com/jsfiddle/jsfiddle-issues/issues/493#issuecomment-39214845

**Comment by Legends** [comment]
Thanks , this works. I wonder how it keeps the broken layout, even after I have reset/cleared all storage locally?
