### ISSUE TITLE
Add a keyboard handler for 'F5'

### ISSUE THREAD

**Issue by mkools-vg** [jsfiddle/jsfiddle-issues#972]
Pressing the F5 button will currently refresh the browser (Chrome), causing you to lose the entered code. 

Please add a handler for the F5 key (and make it run the fiddle), or at least a warning that unsaved code is being lost when leaving the page.

**Comment by oskarkrawczyk** [comment]
We won't be altering system function keys. If you accidentally reload/close the fiddle, use the draft feature to bring back unsaved changes.
