### ISSUE TITLE
Update fabric to v 1.7.7

### ISSUE THREAD

**Issue by asturur** [jsfiddle/jsfiddle-issues#977]
Hello, i'm Andrea, mantainer of fabricJS.

Would be possible to have it upgrade to 1.7.7?

I just released it, so maybe the the cdn will take some minute to grab it.

Can we delete all version before 1.5.0? does not make sense to leave them there since are unsupported. No idea what is the policy with broken fiddles resulting from deleting

Thanks,
Andrea

**Comment by oskarkrawczyk** [comment]
Added 1.7.7 and disabled versions all below 1.5.0
