### ISSUE TITLE
Running a JSFiddle opens a new empty window.

### ISSUE THREAD

**Issue by Clickys** [jsfiddle/jsfiddle-issues#979]
I dont know the reason but when i click run it opens a new tab https://fiddle.jshell.net/_display/ . I dont know how to fix it .

**Comment by oskarkrawczyk** [comment]
Hard to say, most likely an extension or adblocker is breaking out JS.

**Comment by Clickys** [comment]
yeah it seems that it was an extension problem , i remove the one that i assumed that it was causing the problem and now its ok . 

Ty
