### ISSUE TITLE
Last-child issue 

### ISSUE THREAD

**Issue by bogdanciocsan** [jsfiddle/jsfiddle-issues#980]
Hi guys.

There is a problem with rendering html / css when using the :last-child selector.

https://jsfiddle.net/seraphxb/go56hrxr/
vs
https://jsfiddle.net/seraphxb/go56hrxr/1/

I can see that the iframe you generate has a body tag, so the first example should work as well since body is a parent for the p tag, just as in https://www.w3schools.com/CSSref/tryit.asp?filename=trycss3_last-child

BR,
Bogdan

**Comment by oskarkrawczyk** [comment]
Use `p:last-of-type`. The `<body>` of the rendered fiddle contains additional elements a the very end, making `p` not the last element.

This is to be expected – you can test it out on w3schools or any other playground where you can modify the raw body contents.
