### ISSUE TITLE
Dynamically add/remove remote resources (JS, CSS) in JSFiddle widget

### ISSUE THREAD

**Issue by robsilva** [jsfiddle/jsfiddle-issues#981]
Does anyone know if there's a way to dynamically add or remove resources (JS and CSS files) into a JSFiddle via the widget?

I basically want to be able to control which version o my CSS and JS files get loaded into a fiddle:

I know I can do this:
```html
<script async src="//jsfiddle.net/username/{{fiddleID}}/embed/js,html,css,resources,result/dark/"></script>
````
but I am hoping for a way to do this:
```html
<script async src="//jsfiddle.net/username/{{fiddleID}}/embed/js,html,css,resources,result/file-{{version}}.css,file-{{version}}.js/dark/"></script>
```

**Comment by oskarkrawczyk** [comment]
No, embeddable is read-only.
