### ISSUE TITLE
After a POST, resources may not get listed in the same order

### ISSUE THREAD

**Issue by cristiscu** [jsfiddle/jsfiddle-issues#982]
To repro easily online, go to your [POST simulation page](http://jsfiddle.net/zalun/sthmj/embedded/result/) and replace the Resources field with:

http://abc.it/xyz.js,http://abc.it/xyz2.js,http://abc.it/xyz3.js,http://abc.it/xyz4.js,http://abc.it/xyz12.js,http://abc.it/xyz13.js,http://abc.it/xyz14.js,http://abc.it/xyz22.js,http://abc.it/xyz23.js,http://abc.it/xyz24.js

Submit and check External Resources list: most often they are not populated in the same order! 

This may cause a big problem with dependencies, while **both CSS and JS files may require a specific include order**.

[Original post here](http://stackoverflow.com/questions/41927911/wrong-order-of-external-resources-after-jsfiddle-post).

**Comment by cristiscu** [comment]
In jsFiddle's JavaScript code, you call submit_external_resource() for each item of the received preload_resources array of hyperlinks. Each call issues an asynchronous Request.JSON to add_external_resource_url, and adds a HTML list item resource entry on each onSuccess.

However, because of the asynchronous nature of an AJAX call, the responses are not guaranteed to come back in the same sequence order as the requests. And I suspect the order of populated LI items becomes unpredictable and sometimes messed up, especially for a large number of resources.

**Comment by oskarkrawczyk** [comment]
This is a known issue (nothing to do with how external resources are saved).

Codebase for the current JSFiddle version is frozen – no issues will be addressed. Our 100% focus is on the 2.0 rewrite.

**Comment by cristiscu** [comment]
"Known issue" is actually a BUG (a defect) when it prevents using parts of your app. Your POST is basically unusable for several resources with a dependency order. Have at least the decency of adding a note to that page, people waste their time to figure it out... 

And better document your feedback, it looks poor and arrogant. I.e. what's the problem then, if it's not about saving the resources. And when should we expect then the new version, with hopefully the fix.

**Comment by oskarkrawczyk** [comment]
> And when should we expect then the new version, with hopefully the fix.

We're not sharing the ETA. The codebase is rewritten to handle external resources in a completely different manner – it'll not have this issue, it might have other issues (as it happens in webdev).

**Comment by cristiscu** [comment]
I've been "in webdev" for longer than you've been on this earth, but never mind...

**Comment by oskarkrawczyk** [comment]
Gotcha.

Closing this topic as you seem to be a very frustrated and verbally-abusive person.
