### ISSUE TITLE
Update svg.js to 2.5

### ISSUE THREAD

**Issue by Fuzzyma** [jsfiddle/jsfiddle-issues#983]
Can you please update svg.js to version 2.5 which was released today?
If you could add all latest minor versions from 2 to 2.5 that would be great, too. (2.4, 2.3.7, 2.2.5, 2.1.1, 2.0.5)

**Comment by oskarkrawczyk** [comment]
Done

**Comment by Fuzzyma** [comment]
Wow that was fast. Thank you very much!
