### ISSUE TITLE
Add fiddle search (by user and/or keywords)

### ISSUE THREAD

**Issue by a2sheppy** [jsfiddle/jsfiddle-issues#985]
Add the ability to search by entering a username and/or a set of keywords. If I know that user Superman has written some great examples of Web Audio, it'd be very helpful to be able to search like:

User: Superman
Keywords: audio oscillatornode

Of course, being able to do it by URL parameters would be great, too, like https://jsfiddle.net/search?username=Superman&Keywords=audio+oscillatornode

This would save me so much time.

**Comment by oskarkrawczyk** [comment]
Thanks. We already have this on the [roadmap](https://trello.com/b/LakLkQBW/jsfiddle-roadmap), you can vote for the feature there.
