### ISSUE TITLE
GitHub mode with refs not working

### ISSUE THREAD

**Issue by pi0** [jsfiddle/jsfiddle-issues#987]
According to [jsfiddle docs](http://doc.jsfiddle.net/use/github_read.html) GitHub with refs URL should work like this: (here we want to point branch `examples`) : 

http://jsfiddle.net/gh/get/library/pure/bootstrap-vue/bootstrap-vue/tree/examples/examples/alerts

This throws this error:
```
GitHub responded with 404
https://api.github.com/repos/bootstrap-vue/bootstrap-vue/contents/examples/examples/alerts
Is your URL valid? Check documentation
```

This is because of invalid GitHub contents API usage. (see [here](https://developer.github.com/v3/repos/contents/#parameters)). We need to pass ref in a query parameter named `ref` : 
https://api.github.com/repos/bootstrap-vue/bootstrap-vue/contents/examples/alerts?ref=examples

And finally thanks for making awesome jsfiddle :)

**Comment by oskarkrawczyk** [comment]
Normally I'd say the codebase for this version of JSFiddle is frozen (because it is) and we don't address minor issues, but in this case we'll see what can be done :-)

**Comment by oskarkrawczyk** [comment]
@pi0 We've released support for `?ref=BRANCH` yesterday as a test, looks like everything is working as expected.
