### ISSUE TITLE
Cannot embedded gh fiddles 

### ISSUE THREAD

**Issue by pi0** [jsfiddle/jsfiddle-issues#988]
This is not a "bug" but it seems we just need minor changes in route definitions getting this work.
Real use-case example is with [bootstrap-vue](https://bootstrap-vue.github.io) docs. Without embedding gh slugs community cannot easily maintenance fiddles. (currently i am using private fiddles for that to work) And i think many many projects (including vuejs examples section) would highly like this feature. 

Again sorry for opening an issue here if it was wrong place. (May i open an trello card for that?)
If possible i would be happy to help implementing this feature and improving gh functionality.

Thanks :)

**Comment by oskarkrawczyk** [comment]
After doing some digging, turns out having support for this would be quite the refactoring.

We'll have this working in JSFiddle 2.0, but I cannot promise anything for 1.0 (current) – we'll dig a little deeper into this and see what can or cannot be done.

**Comment by oskarkrawczyk** [comment]
Not going to happen anytime soon. Closing, leaving this on the roadmap - https://trello.com/c/OAsuhpZF/71-ability-to-embed-fiddles-generated-from-a-gh-repo
