### ISSUE TITLE
jQuery 3.2.1

### ISSUE THREAD

**Issue by timmywil** [jsfiddle/jsfiddle-issues#989]
Sorry to bug you again so soon! We released 3.2.1 with some hotfixes. We introduced some regressions in 3.2.0 that we wanted to fix quickly.

http://blog.jquery.com/2017/03/20/jquery-3-2-1-now-available/

Thanks!

**Comment by oskarkrawczyk** [comment]
No problem, as long as it's available on CDNJS we can update

**Comment by oskarkrawczyk** [comment]
The thing is that 3.2.1 is not yet available, so we cannot update.

**Comment by timmywil** [comment]
I've emailed them. It should be available very soon.

**Comment by oskarkrawczyk** [comment]
3.2.1 added
