### ISSUE TITLE
Unsaved draft warning on anonymous Fiddle

### ISSUE THREAD

**Issue by jennifercampbell** [jsfiddle/jsfiddle-issues#997]
Steps to reproduce (Note: I'm not logged in):
1. Save a new Fiddle.
2. Make changes.
3. Save button no longer available, so click Update button.  (New version is created.)
4. Revisit original URL.  Warning 'Your Fiddle has an unsaved draft' is displayed.
5. Click on message, click on 'Apply local draft version'.  Changes are successfully applied.
6. Repeat steps 3 and 4. 'Unsaved draft' message still displayed.

How can I save the changes in such a way that I stop seeing the warning?

**Comment by oskarkrawczyk** [comment]
@jennifercampbell 

> Revisit original URL

You mean the one before the version number was applied to the URL?

**Comment by jennifercampbell** [comment]
Yes, that's right.

**Comment by oskarkrawczyk** [comment]
That's expected behavior. Normally users don't visit historical revisions.

Apart from this one we had zero complains about how saving drafts work, so we'll just leave it as it is, unless more requests pop up.
