### ISSUE TITLE
Asking to Disable Adblock even when it is Disabled

### ISSUE THREAD

**Issue by electron0zero** [jsfiddle/jsfiddle-issues#998]
I am running latest firefox with tracking protection on along with uBlock Origin (disabled on jsfiddle) and Privacy Badger (disabled on jsfiddle) but still getting this message asking to disable adblock

**See Screenshot**
![capture](https://cloud.githubusercontent.com/assets/9503187/24965048/85007fc8-1fc0-11e7-82fe-006090aa380e.PNG)

**Comment by oskarkrawczyk** [comment]
Looks like something else is blocking ad container from being created. Doesn't happen on clean Firefox installation, nor on Firefox with the two mentioned extensions installed but disabled.

Any other info would be appreciated.

Does running `document.getElementById("carbonads")` return something or `null`?

**Comment by electron0zero** [comment]
@oskarkrawczyk Yup it's `null`

**see screenshot**

![capture](https://cloud.githubusercontent.com/assets/9503187/24965918/1511ed8e-1fc3-11e7-92c7-71e46347b1dd.PNG)

**Comment by electron0zero** [comment]
@oskarkrawczyk it was [firefox tracking protection](https://support.mozilla.org/t5/Protect-your-privacy/Tracking-Protection-in-Firefox/ta-p/18255) that was blocking it.
As it can be seen in screenshot in above comment
Now it's all good
![capture](https://cloud.githubusercontent.com/assets/9503187/24966078/8ccddcca-1fc3-11e7-9092-08909cdf34e8.PNG)
